### ISSUE TITLE
Does snscrape mask ip

### ISSUE THREAD

**Issue by Loai-Hassan** [JustAnotherArchivist/snscrape#1000]
Does ssncrape musk our ips or use proxy 
And how is it considered legal or not
What is the legal consiquencnes

**Comment by JustAnotherArchivist** [comment]
snscrape supports proxies, but none are used by default.
The legality and potential consequences depend on your jurisdiction. Please consult a lawyer for legal advice.

**Comment by Loai-Hassan** [comment]
> 

So my IP is available?
