### ISSUE TITLE
Use screen_name to get tweets?

### ISSUE THREAD

**Issue by TianzhuQin** [JustAnotherArchivist/snscrape#1002]
May I please ask how we can have a specific user's tweets from the start time to the end time for now? Really in a hurry and currently have no clues....

And this one seems to have no params for screen name? Do we have other urls?
https://cdn.syndication.twimg.com/tweet-result

Thank you for all your help, and many great praise to the author @JustAnotherArchivist

**Comment by JustAnotherArchivist** [comment]
#996 mentions what's currently known to exist. Asking again isn't helpful.
