### ISSUE TITLE
Finding the Twitter UsersByRestIds GraphQL endpoint

### ISSUE THREAD

**Issue by chrisgoddard** [JustAnotherArchivist/snscrape#1012]
Hey there @JustAnotherArchivist - completely understand that you aren't going to be supporting authenticated scraping with your library - however for those of us who might want to build on your work, I was wondering whether you might be able to tell me where you found the `UsersByRestIds` endpoint?

I've been able to catalog every other GraphQL endpoint and its corresponding random ID (i.e. `graphql/***/TweetDetails` - but the only one I'm not able to find is `UsersByRestIds`. Now obviously with the amount of change on Twitter right now it might just not exist any more but I could just be looking in the wrong place. 

Thanks for all your work on this library - sorry it's no longer usable. Hopefully Twitter will change their non-authenticated behavior in the future.

**Comment by JustAnotherArchivist** [comment]
All endpoints are listed in their JS. You should be able to find it if you open your browser's dev tools and search all JS code through that ('Debugger' tab in Firefox).

**Comment by chrisgoddard** [comment]
Oh! Duh - haha - that's definitely easier than extracting out of the network requests. Thanks!
