### ISSUE TITLE
Does the Scrapper even work after Elon's API updates? Because I get `KeyError: 'name'`

### ISSUE THREAD

**Issue by kauuu** [JustAnotherArchivist/snscrape#1013]
I tried using it and I get `KeyError: 'name'`. On further analysis, I found I am getting error code 126, Logged Out as the content in the response. Why is this the case? Is it because of the Twitter API updates?

**Comment by ihabpalamino** [comment]
does snscrape work again??to scrap tweets by username?

**Comment by DanRev111212** [comment]
Same issue here. Not working.

**Comment by umairmayo80** [comment]
No, there is another [issue](https://github.com/JustAnotherArchivist/snscrape/issues/996) that states that all Twitter searches are blocked.
