### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by 24mic53** [JustAnotherArchivist/snscrape#1016]
Hey, im trying to download the snscrape development version in order to build a twitter web scraper.
As so, I wrote - pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git.
However I keep getting a syntax error - SyntaxError: invalid syntax.

Im using python 3.11

**Comment by JustAnotherArchivist** [comment]
Please provide the complete output of the `pip` command, and also the output of `pip --version`.

**Comment by ihabpalamino** [comment]
Use the command line, not the Python shell (DOS, PowerShell in Windows
