### ISSUE TITLE
import snscrape.modules.twitter could not be resolved

### ISSUE THREAD

**Issue by NoahLi06** [JustAnotherArchivist/snscrape#1017]
Hello, 
I am pretty new to coding with Python and trying to scrape Twitter. However, every time I try to import the module, it always says that it could not be resolved. I've already installed the library on my desktop. Is there a possible reason why this error keeps on popping up for me?

Thanks

**Comment by ihabpalamino** [comment]
the library is being updated due to the changes that elon musk has made twitter has stopped the ability of scraping without being logged so we are all waiting for the implementation of the solution. otherwise for now you will getiing blocked 404

**Comment by JustAnotherArchivist** [comment]
'Resolving' a module isn't an error that exists in Python as far as I know. Please share the complete actual error you get.

**Comment by ihabpalamino** [comment]
then pip install the module import it and make sure ur using the correct interpreter
