### ISSUE TITLE
Username scraping available for Twitter?

### ISSUE THREAD

**Issue by 4yR1l1k** [JustAnotherArchivist/snscrape#1023]
Hi, I'm trying twitter scraping via "username" but receiving 404 error. Also I've seen there is a post on May 14th about a similar issue (https://github.com/JustAnotherArchivist/snscrape/issues/895)

Username/user-id scraping still not available?

thanks

**Comment by AritzUMA** [comment]
same problem

**Comment by TheTechRobo** [comment]
No, it's still not fixed (which is why the issue is still open and it still doesn't work).

**Comment by rbrooks95** [comment]
Anyway I can set an alert for when the username scrape is working or just look out for it? @TheTechRobo

**Comment by TheTechRobo** [comment]
@rbrooks95 On the linked issue (#895) you can set up notifications for when someone comments or the issue is closed (meaning either solved or deemed unsolvable).
