### ISSUE TITLE
What is the specific date range of Instagram?

### ISSUE THREAD

**Issue by vicshi94** [JustAnotherArchivist/snscrape#1025]
I would like to inquire about the specific date range of Instagram posts that can be scraped. Additionally, I would appreciate guidance on how to retrieve data from a particular period, such as from 2019-12-01 to 2022-12-01. Is this accessible?

**Comment by vicshi94** [comment]
Sorry for asking a duplicate question (see #333, #390, and others). The biggest problem in tracing the previous data, I suppose, is the rate-limiting. Would it be better if I set a sleep time in each iterate?

**Comment by JustAnotherArchivist** [comment]
The Instagram scraper does not support filtering by date.

You can try to get around the rate limiting like that. My attempts a few years ago failed, so I effectively gave up trying to maintain the module. It currently doesn't work at all, I believe (#520).
