### ISSUE TITLE
Issue: snscrape.base.ScraperException: Unable to find guest token

### ISSUE THREAD

**Issue by Souvik2376** [JustAnotherArchivist/snscrape#1028]
What is the problem ? Can anyone help @JustAnotherArchivist 

![image](https://github.com/JustAnotherArchivist/snscrape/assets/100219950/328b6e86-1679-490d-b4a5-4a2ae32fbc6e)

**Comment by Souvik2376** [comment]
Right now updated to latest version and yet not resolved
![image](https://github.com/JustAnotherArchivist/snscrape/assets/100219950/dc8d650a-dd32-4dbd-b9bb-e179130dd324)

**Comment by FlyingWolFox** [comment]
#996
