### ISSUE TITLE
Informations about retweets and likes

### ISSUE THREAD

**Issue by CesarRoaldes** [JustAnotherArchivist/snscrape#103]
Hi JustAnotherArchivist,

First of all, thank you for this project with which I'm having a lot of fun.  
Beyond the number of retweets and likes, I was wondering if it was possible to retrieve information about the user accounts that retweeted or liked one of the tweet scrapped. If not, do you think that using selenium is necessary? What would be the difficulties and limitations?

Thank you in advance for your help,
César

**Comment by JustAnotherArchivist** [comment]
Hi César,

I'd love to add that. Unfortunately, I'm not aware of any way to get this information without logging in, and authentication is not something I intend to ever add for various reasons (see #23 and #50 for some details on that). Do you know of one?

**Comment by CesarRoaldes** [comment]
Hi JustAnotherArchivist, thank you for your fast answer, indeed by tracing the link on which the scratching was done i realized that when clicking on the retweets icon Twitter asks me to loggin. I've read the two issues that you shared with me but I don't get the what are the troubles of scraping with my signed Twitter account, would my activities get tracked by the plateform?

**Comment by JustAnotherArchivist** [comment]
Most certainly, and likely you would eventually get banned, although I don't know how aggressively Twitter handles that exactly.

**Comment by CesarRoaldes** [comment]
Thank you very much for this information !
