### ISSUE TITLE
Instagram change something! index Error.

### ISSUE THREAD

**Issue by erfan-sams** [JustAnotherArchivist/snscrape#1034]
### Describe the bug

IndexError: list index out of range

 jsonData = r.text.split('<script type="text/javascript">window._sharedData = ')[1].split(';</script>')[0] # May throw an IndexError if Instagram changes something again; we just let that bubble.

### How to reproduce

just get entity from any Instagram class

### Expected behaviour

Got error!

### Operating system

ubuntu 23.04

### Python version: output of `python3 --version`

3.11

### snscrape version: output of `snscrape --version`

for post in scraper.get_items(): 

### Scraper

InstagramUserScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
#520
