### ISSUE TITLE
always 429 rate limit error

### ISSUE THREAD

**Issue by mohammadali-seifkashani** [JustAnotherArchivist/snscrape#1039]
### Describe the bug

Hello and respect. This line in modules/twitter.py always causes 429 error. 
self._post('https://api.twitter.com/1.1/guest/activate.json', data = b'', headers = self._apiHeaders, responseOkCallback = self._check_guest_token_response)
Could you please check and correct this?

### How to reproduce

Example code:
```
from snscrape.modules import telegram, instagram, twitter

for i, t in enumerate(twitter.TwitterUserScraper('hamedkashani__').get_items()):
    print(t)
    if i == 3:
        break
```

### Expected behaviour

Some tweet objects :)

### Screenshots and recordings

![image](https://github.com/JustAnotherArchivist/snscrape/assets/45390101/084a7a9e-70eb-4a40-bcc0-79c72f1b57d1)

### Operating system

Windows 11

### Python version: output of `python3 --version`

3.10.11

### snscrape version: output of `snscrape --version`

snscrape 0.7.0.20230622

### Scraper

TwitterUserScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
#754
