### ISSUE TITLE
AttributeError: 'FileFinder' object has no attribute 'find_module

### ISSUE THREAD

**Issue by SureshS03** [JustAnotherArchivist/snscrape#1042]
Hey , when i try to use snscape i got this error message AttributeError: 'FileFinder' object has no attribute 'find_module

my code is 

import snscrape.modules.twitter as sn

q = "india"

for x in sn.TwitterSearchScraper(q).get_items():
    print(vars(x))
    break
    
please help me to resolve and i also search on reddit someone suggest me to use this "pip3 install snscape" but still i face same error

**Comment by TheTechRobo** [comment]
#782
