### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by KittGT42** [JustAnotherArchivist/snscrape#1047]
### Describe the bug

AttributeError: 'FileFinder' object has no attribute 'find_module'

### How to reproduce

AttributeError: 'FileFinder' object has no attribute 'find_module'

### Expected behaviour

AttributeError: 'FileFinder' object has no attribute 'find_module'

### Screenshots and recordings

AttributeError: 'FileFinder' object has no attribute 'find_module'

### Operating system

MacOS

### Python version: output of `python3 --version`

320

### snscrape version: output of `snscrape --version`

0.7

### Scraper

Facebook

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

### Backtrace

AttributeError: 'FileFinder' object has no attribute 'find_module'

### Log output

AttributeError: 'FileFinder' object has no attribute 'find_module'

### Dump of locals

AttributeError: 'FileFinder' object has no attribute 'find_module'

### Additional context

AttributeError: 'FileFinder' object has no attribute 'find_module'

**Comment by JustAnotherArchivist** [comment]
#782
