### ISSUE TITLE
output csv and  message of tweet

### ISSUE THREAD

**Issue by theOrange23** [JustAnotherArchivist/snscrape#105]
Hi, guys. I have a lot of difficulties in computer language. 

Could someone help me create a **CSV output**? And when I search for tweets, it returns link. How do I return the **text contained in the tweet**?

Congratulations on the project!

**Comment by JustAnotherArchivist** [comment]
You can get the tweet contents with `--format '{content}'`, but then multi-line tweets will also appear as such in the output, i.e. you can't tell which lines belonged together originally. Depending on what you're trying to do, that might be good enough though.

For actual CSV output (well, not comma-separated anymore if there's only one value per row), you'll have to use the API (example in #73) and [the `csv` module](https://docs.python.org/3/library/csv.html).

**Comment by theOrange23** [comment]
Thank you very much.

One more doubt:

I'm trying to fetch a user's tweets before 2017.

I'm using:

snscrape --jsonl --since 2013-01-31 - until 2017-01-31 twitter-user name> name.jsonl

For some reason it is giving error.

**Comment by JustAnotherArchivist** [comment]
There is no `--until` option. But for Twitter, you can use `snscrape --jsonl twitter-search 'from:name since:2013-01-01 until:2017-01-01'`. This would fetch `@name`'s tweets posted between 2013 and 2016.

**Comment by ihahawen** [comment]
Why i use this command ,it happen 
"usage: snscrape [-h] [--version] [-v] [--dump-locals] [--retry N] [-n N] [-f FORMAT] [--since DATETIME]
                {googleplus-user,telegram-channel,vkontakte-user,facebook-user,facebook-group,gab-user,gab-user-comments,gab-user-media,instagram-user,instagram-hashtag,instagram-location,twitter-search,twitter-thread,twitter-list-members,twitter-user,twitter-hashtag,twitter-list-posts}
                ...
snscrape: error: unrecognized arguments: --jsonl"

**Comment by ihahawen** [comment]
reinstall， i done it

**Comment by JustAnotherArchivist** [comment]
@ihahawen #77

**Comment by ihahawen** [comment]
> @ihahawen #77

Thank you! it works!

**Comment by smkngsqrl** [comment]
@JustAnotherArchivist Hi. Can you please let me know how to do a multi-keyword search?

snscrape --max-results 20000 twitter-search "#keyword1 since:2020-02-01 until:2020-08-01"

The above line of code works perfectly fine. If I try to add another keyword in the query using 'or' operator - ' | ', I get results that match both the criteria (similar to 'and'). Am I doing it right? Thanks for your help!

snscrape --max-results 20000 twitter-search "#keyword1 | #keyword2 since:2020-02-01 until:2020-08-01"

**Comment by callaaaa** [comment]
@theOrange23 Hello,can you show me an example about saving in csv? I use `snscrape --max-results 10 -f twitter-search trump > test.csv` ,but there is error: argument. I don't know how to use `-f` to do it.
