### ISSUE TITLE
Trying to understand module, trying to scrap twitter by query terms

### ISSUE THREAD

**Issue by sagefuentes** [JustAnotherArchivist/snscrape#106]
I'm still trying to understand some of the basis of this module, but if anyone can provide an example of just using this code in python script over console, it would really help. I am just trying to scrap a list of random works over random periods of time, so any example with a query term and dates would be really helpful.

Also, sorry this is not a technical issue, just having a bit of trouble understanding this library as I move over from GOT3

**Comment by JustAnotherArchivist** [comment]
Documentation on the API is currently inexistent, but you can find an example in #73. For time periods, you can use Twitter's search filters `since:2019-01-01 until:2019-02-01` to fetch tweets from January 2019, for example.

**Comment by sagefuentes** [comment]
Thank you! Seems I wasn't too far off in what I was trying to do.
