### ISSUE TITLE
facebook page

### ISSUE THREAD

**Issue by brunoec** [JustAnotherArchivist/snscrape#107]
Hello! How can I search a facebook page in a certain period of time? Ex: Trump's page since 2015 until 2016.

Congratulations for the code!

Yours sincerely,
B.E.C.

**Comment by JustAnotherArchivist** [comment]
You can use `--since` for the lower bound, but there is no `--until` (cf. #81), so you'll have to filter out the posts newer than an upper bound otherwise. There is no way to avoid having to fetch all the newer posts as well.
