### ISSUE TITLE
Support for top tweets on twitter-search

### ISSUE THREAD

**Issue by NowBothWhiteAndRed** [JustAnotherArchivist/snscrape#109]
Hi,

Is there any way to only get back top tweets from snscraper? Presently it looks like it's getting all of them.

Thanks!

**Comment by JustAnotherArchivist** [comment]
This isn't currently supported but probably shouldn't be too difficult to implement in principle. I'll have to see whether it will work well though. It will definitely break `--since` because the posts are returned in 'random' order (chronologically speaking).

**Comment by Fatima-Haouari** [comment]
> 
> 
> This isn't currently supported but probably shouldn't be too difficult to implement in principle. I'll have to see whether it will work well though. It will definitely break `--since` because the posts are returned in 'random' order (chronologically speaking).

Hi,
I am interested in getting the top tweets. I modified the code as follows:
1) Removed 'f':'live' in line 405: super().__init__(baseUrl = 'https://twitter.com/search?' + urllib.parse.urlencode({'lang': 'en', 'q': query, 'src': 'spelling_expansion_revert_click'}), **kwargs)
2) commented line 443 'tweet_search_mode': 'live'
I noticed that I am getting much more tweets than the original version of code.
Please advice if what I am doing it the right way. Am I really getting top tweets?

**Comment by Fatima-Haouari** [comment]
The issue with my updated code is that it keeps collecting tweets without an end. Any idea why is that?

**Comment by JustAnotherArchivist** [comment]
I have not looked yet into what changes are needed, and I can't provide support for modified versions of snscrape. I do intend to eventually implement this, but I'm currently busy with other things.
