### ISSUE TITLE
"Unable to find guest token" exception on Twitter scrapes from Google Collab

### ISSUE THREAD

**Issue by topliftarm** [JustAnotherArchivist/snscrape#110]
when search for tweets i give this error :
ScraperException: Unable to find guest token

in this line  ---> for i in tweets.get_items():

**Comment by ihahawen** [comment]
`for tweet in snscrape.modules.twitter.TwitterUserScraper(username='twitter').get_items():
     if tweet.content:
         print(tweet.content)`

**Comment by JustAnotherArchivist** [comment]
@topliftarm Are you using AWS (or something that runs on AWS like Heroku)?

**Comment by topliftarm** [comment]
> @topliftarm Are you using AWS (or something that runs on AWS like Heroku)?

u right! i used colab.....

**Comment by JustAnotherArchivist** [comment]
Sounds like Twitter is blocking Google Colab. @Hamma111 said the same thing in #79 recently.
If true, there's nothing snscrape or I can do about that. You will have to run snscrape somewhere else.

**Comment by JustAnotherArchivist** [comment]
@arranjdavis, does snscrape still work for you on Google Collab?

**Comment by arranjdavis** [comment]
> @arranjdavis, does snscrape still work for you on Google Collab?

Yeah, it is working for me, but its a roundabout way of getting it to work.

First, I needed to get Python 3.8 on the Colab. I do this by installing Anaconda (with Python 3.8) onto the Colab instance, and then launching a Jupyter Notebook via ngrok.

Then I run snsrape from the Jupyter Notebook. 

It is working as of now, and you can find the scripts I am using on my [github](https://github.com/arranjdavis/snscrape_google_colab).

**Comment by JustAnotherArchivist** [comment]
Thank you! I have no idea what's wrong then. In any case, it does not appear like a bug in snscrape or something I can change, so I'm closing this issue.

**Comment by tsangvin** [comment]
I have also encountered this issue, running snscrape on Jupyter. However, I am still grasping how often does it occur at the moment.

**Comment by numerosos** [comment]
Hi! Getting `ScraperException: Unable to find guest token` error for the first time. I always use Jupyter Notebook on my machine to run snscrape.

Anybody with the same issue? Last weekend I had no problem

**Comment by jrobi001** [comment]
@numerosos yup, issue started a few days ago for me running on my local machine. Been trying to run script all different ways, but seems it occurs after collecting over a certain amount. I can collect about 100,000 tweets before it kicks in.

**Comment by JustAnotherArchivist** [comment]
This issue is specifically about Google Collab, not residential connections or anything else.
