### ISSUE TITLE
Python 3.9 issues

### ISSUE THREAD

**Issue by iPadGuy** [JustAnotherArchivist/snscrape#111]
**Command:** `snscrape --since 20200923 --max-results 3 twitter-user realDonaldTrump`

**Output:**
```python
Traceback (most recent call last):
  File "/usr/local/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/snscrape/cli.py", line 251, in main
    args = parse_args()
  File "/usr/local/lib/python3.9/site-packages/snscrape/cli.py", line 160, in parse_args
    import snscrape.modules
  File "/usr/local/lib/python3.9/site-packages/snscrape/modules/__init__.py", line 15, in <module>
    _import_modules()
  File "/usr/local/lib/python3.9/site-packages/snscrape/modules/__init__.py", line 12, in _import_modules
    module = importlib.import_module(moduleName)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/snscrape/modules/vkontakte.py", line 14, in <module>
    class VKontaktePost(typing.NamedTuple, snscrape.base.Item):
  File "/usr/local/lib/python3.9/typing.py", line 1820, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported
```

**Comment by JustAnotherArchivist** [comment]
Ah yeah, I saw that change in NamedTuple behaviour somewhere else before. I intend to replace the named tuples with dataclasses anyway, which would also solve this of course.

Thanks for the report, I'll try to fix this soon. For the time being, please stick to Python 3.8.

**Comment by tirkarthi** [comment]
This is due to https://github.com/python/cpython/pull/19363

**Comment by vinliao** [comment]
Hi @JustAnotherArchivist, I'm still experiencing this problem on python 3.9 even though it seems like you have pushed a fixed on oct 16.

Any update on this?

**Comment by JustAnotherArchivist** [comment]
@vinliao There hasn't been a release in a while as I've been busy with other stuff and still want to implement some things before the next version. So yeah, dev version only for the time being.

**Comment by vasana12** [comment]
> Hi @JustAnotherArchivist, I'm still experiencing this problem on python 3.9 even though it seems like you have pushed a fixed on oct 16.
> 
> Any update on this?
> 
> Edit: using the development version works.

This change will work in version 3.9. The code below is the method I used.
I modified the snscrape library code a bit.

The code in the current library is:
``
class InstagramPost(typing.NamedTuple, snscrape.base.Item):
	cleanUrl: str
	dirtyUrl: str
	date: datetime.datetime
	content: str
	thumbnailUrl: str
	displayUrl: str
	username: str
	likes: int
	comments: int
	commentsDisabled: bool
	isVideo: bool

	def __str__(self):
		return self.cleanUrl
```
Replace that code with the code below

from dataclasses import dataclass
@dataclass
class InstagramPost(snscrape.base.Item):
	cleanUrl: str
	dirtyUrl: str
	date: datetime.datetime
	content: str
	thumbnailUrl: str
	displayUrl: str
	username: str
	likes: int
	comments: int
	commentsDisabled: bool
	isVideo: bool

	def __str__(self):
		return self.cleanUrl
```

**Comment by tcrgit** [comment]
Might I suggest you should update the readme.md in light of the fact that this (quite old) bug affects python 3.9+? It would help those who aren't clever enough to search closed issues, and in light of Twitter's recent rules change concerning provate media, you are likely to see an influx of new users

I suggest changing (bold mine, to be removed for readme.md):

snscrape requires **Python 3.8 or higher**. The Python package dependencies are installed automatically when you install snscrape.

to 

snscrape requires **Python 3.8. For Python 3.9 or higher, please install the development version.** The Python package dependencies are installed automatically when you install snscrape.

**Comment by JustAnotherArchivist** [comment]
@tcrgit Here's a better option: a new release is out.

**Comment by topekekere** [comment]
> > Hi @JustAnotherArchivist, I'm still experiencing this problem on python 3.9 even though it seems like you have pushed a fixed on oct 16.
> > Any update on this?
> > Edit: using the development version works.
> 
> This change will work in version 3.9. The code below is the method I used. I modified the snscrape library code a bit.
> 
> The code in the current library is:
> 
> ```
> class InstagramPost(typing.NamedTuple, snscrape.base.Item):
> 	cleanUrl: str
> 	dirtyUrl: str
> 	date: datetime.datetime
> 	content: str
> 	thumbnailUrl: str
> 	displayUrl: str
> 	username: str
> 	likes: int
> 	comments: int
> 	commentsDisabled: bool
> 	isVideo: bool
> 	def __str__(self):
> 		return self.cleanUrl
> ```
> 
> Replace that code with the code below
> 
> ```
> from dataclasses import dataclass
> @dataclass
> class InstagramPost(snscrape.base.Item):
> 	cleanUrl: str
> 	dirtyUrl: str
> 	date: datetime.datetime
> 	content: str
> 	thumbnailUrl: str
> 	displayUrl: str
> 	username: str
> 	likes: int
> 	comments: int
> 	commentsDisabled: bool
> 	isVideo: bool
> 	def __str__(self):
> 		return self.cleanUrl
> ```

where can I find the library?

**Comment by JustAnotherArchivist** [comment]
@topekekere Just use the latest version of snscrape if you have Python 3.9+. This was fixed a long time ago.

**Comment by crbunney** [comment]
This is the current top google result when looking for `Multiple inheritance with NamedTuple is not supported`. For the benefit of others like me, I just want to signpost the official python project issue that tracks why this changed and what's being done about it: https://github.com/python/cpython/issues/88089
