### ISSUE TITLE
Searching with date and user

### ISSUE THREAD

**Issue by el-grudge** [JustAnotherArchivist/snscrape#112]
1. I know I can search by user and date that using the command line like 

`snscrape --since 2020-10-06 twitter-user realDonaldTrump`

But, is it possible to do it using TwitterUserScraper? 

2. Also, is it possible to add an 'until' option?

I tried doing it this way 

`sntwitter.TwitterUserScraper('realDonaldTrump' + 'since:2020-10-05 until:2020-10-07').get_items()`

but that didn't work.

**Comment by JustAnotherArchivist** [comment]
The `twitter-user` scraper is just syntax sugar around `twitter-search` for simple user queries. For more complex queries, use the latter, i.e.

    TwitterSearchScraper('from:realDonaldTrump since:2020-10-05 until:2020-10-07')

**Comment by el-grudge** [comment]
works like a peach, thanks
