### ISSUE TITLE
search for username and specific word - Twitter

### ISSUE THREAD

**Issue by brunoec** [JustAnotherArchivist/snscrape#113]
Hello. Is it possible?

I tried: snscrape --jsonl twitter-search "from:username words since:date until:date" > name.json

But didn't work.

**Comment by JustAnotherArchivist** [comment]
I can't help you with 'didn't work'. Exactly that syntax works fine.

**Comment by Arf9999** [comment]
The `--jsonl` option isn't available in the standard pip3 install (version 0.3.4)

To use it you need to install the dev version:
`pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git`
