### ISSUE TITLE
Which are the available attributes of the Tweet object returned by TwitterSearchScraper?

### ISSUE THREAD

**Issue by FernandoDurier** [JustAnotherArchivist/snscrape#115]
Hello!!
How are you?
Which are the available features in tweet object in sntwitter.TwitterSearchScraper?
So far I got those here:
```
username = tweet.username
text = tweet.content
pubdate = tweet.date
permalink = tweet.url
```

Also, which are the query options available? I was trying to restrict it by the username, but, couldn't ...
query = keyword + ' since:2020-01-01 lang:pt' (I've tried username:UNAME, or twitter-user:UNAME, or user:UNAME, and nothing worked).
Here is how I'm doing it:

```
import snscrape.modules.twitter as sntwitter
keyword = '(COVID OR Corona Vírus)'
maxTweets = 3000
tweets = []
tdf = None
for i,tweet in enumerate(sntwitter.TwitterSearchScraper(keyword + ' since:2020-01-01 lang:pt').get_items()) :
        if i > maxTweets :
            break
        username = tweet.username
        text = tweet.content
        pubdate = tweet.date
        permalink = tweet.url
        tweets.append({
            "permalink":permalink,
            "pubdate":pubdate,
            "text":text,
            "username":username
        })
```

**Comment by JustAnotherArchivist** [comment]
Hi,

I hope to write some documentation for this soon. Until then, you can find the available fields in the code. As of the current dev version: https://github.com/JustAnotherArchivist/snscrape/blob/ffd9289edc5bab32e1e2314e7c04b4da9c933867/snscrape/modules/twitter.py#L20-L42

The 'query options' are actually Twitter's filters. snscrape doesn't know anything about them. Twitter no longer has them publicly documented either to my knowledge. To filter by a username (handle), use `from:username`.

**Comment by FernandoDurier** [comment]
Thank you for the fast answer and also for this project!!

**Comment by JSMboli** [comment]
Hi Guys,
 
I like this and I am trying to get likecount and retweet count but getting an error. for instance 
username = tweet.username
text = tweet.content
pubdate = tweet.date
permalink = tweet.url 
all works but
tweet.likecount or tweet.retweetcount did not work.

please help.

**Comment by mehrnooshazizi** [comment]
@JustAnotherArchivist, hello,

> 

Hello! I'm trying to use this package to scrape some tweets having multiple keywords. This is a sample of my code:

a = ['blue', 'green', 'sad old', 'yellow', 'red']
b = ['apple', 'orange']
c = ['mountain', 'forest']

products_list = list(itertools.product(a, b, c))
for i in products_list:
    keyword = i[0] + "  "+ i[1]+"  "+ i[2]
    data = sntwitter.TwitterSearchScraper(keyword +' since:2020-12-08 until:2020-12-18').get_items()                          

df = pd.DataFrame(data)

But I can't get any tweets. Can you help me? I want tweets that contain a combination of 3 keywords together. How should I iterate through my list to use multiple keywords?

**Comment by naufalscudetto** [comment]
For example I need a list of users that is mentioned.
After using mentionedUsers to get it, I notice that it is in the format [https://twitter.com/username].

May I ask how i could get only the username  without the https ? because I cant seem to preprocess it

**Comment by TheTechRobo** [comment]
That's if you print it out or convert it to a sstring. It's probably a User object

**Comment by JustAnotherArchivist** [comment]
As the code excerpt above shows, it is indeed a list of `snscrape.modules.twitter.User` objects. If you only want usernames, you'll have to get the `username` attribute of those.

**Comment by colina83** [comment]
Excellent post - Does anybody knows how can I get the total number of comments on each tweet, meaning who commented at an individual tweet level?
