### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MapperIT** [JustAnotherArchivist/snscrape#119]
` snscrape --jsonl twitter-search "#SherlockHolmes since:2015-01-01 until:2015-01-15" > sherlock_tweets.json` crashes with `SyntaxError: invalid syntax `  pointing a twitte**R**-search. I am runing code in command prompt using Python 3.6.8 and snscrape 0.3.4.

**Comment by MapperIT** [comment]
The same error occur when using Python 3.8.4

**Comment by JustAnotherArchivist** [comment]
Where does the crash occur? Full traceback please.

Also, `--jsonl` is only available on the dev version of snscrape, not on 0.3.4. The dev version requires Python 3.8.

**Comment by MapperIT** [comment]
It worked without --jsonl
`snscrape twitter-search "#SherlockHolmes since:2015-01-01 until:2015-01-15" > sherlock_tweets.json` 
Thank you!
