### ISSUE TITLE
Can't get tweets but only URL

### ISSUE THREAD

**Issue by shizia** [JustAnotherArchivist/snscrape#120]
I used the commend:
"snscrape twitter-user username"
but only get a URL list.
Is there any problems? How to get the tweets correctly?

**Comment by JustAnotherArchivist** [comment]
URLs are snscrape's default output. Look into the `--jsonl` (only on the dev version) and `--format` options or the API (#73) to access other information.

**Comment by shizia** [comment]
> URLs are snscrape's default output. Look into the `--jsonl` (only on the dev version) and `--format` options or the API (#73) to access other information.

I will try it. Thanks a lot!!!
