### ISSUE TITLE
No results since twitter outage

### ISSUE THREAD

**Issue by werderfan23** [JustAnotherArchivist/snscrape#123]
Hello together, 

is anyone else dealing with problems since the twitter outage?

I don't get any error messages, but I also don't get any results for the same query which worked fine yesterday. 

Thank you a lot in advance and thank you also for this great software. It helped me a lot for my master-thesis. 

Greetings
Tim

**Comment by Sailoriae** [comment]
Hello !
I have the same problem with `TwitterSearchScraper`. :(
Have a nice day !

**Comment by crearesearch** [comment]
I have the same issue, anyone found a way to solve it?

**Comment by ChaD202** [comment]
I am now getting results but I am not scraping all the tweets required. Seems like pagination is ending prematurely for some reason.

**Comment by werderfan23** [comment]
> I am now getting results but I am not scraping all the tweets required. Seems like pagination is ending prematurely for some reason.

True, I'm also now getting at least some results. Maybe it just takes some time.

**Comment by santoshbs** [comment]
So does this not work?

**Comment by JustAnotherArchivist** [comment]
Confirmed, reproducible in a browser, and people on Twitter are reporting it as well (e.g. [here](https://twitter.com/mwiik/status/1316949224177664001)). It seems that Twitter's search is a bit broken at the moment. Let's hope they fix it.

**Comment by Sailoriae** [comment]
And let's hope they won't limit this API to 7 days in order to force us to pay for their Enterprise API. 😅

**Comment by werderfan23** [comment]
Twitter Search is working again!
