### ISSUE TITLE
Getting less tweets than expected

### ISSUE THREAD

**Issue by darien-soung** [JustAnotherArchivist/snscrape#126]
Hi all, 

Anyone else notice they are getting less results from the TwitterSearchScraper function? 

Around a month ago I used GOT3 to scrape my tweets, and I got an average of 3000 tweets a day for a specific search query. I started using snscrape today (as GOT3 was disabled) to scrape my tweets on the same query and to my enlightenment, it worked flawlessly (thanks to JustAnotherArchivist).

However upon further inspection of my collected tweets, I found out that I was getting lesser tweets than I expected as I was only getting 50-200 tweets per day. (Note that the same search query is used).

Is there anybody that is facing the same problem?  

The search query is: "#protestlockdown OR #nolockdown OR #covidhoax OR #saynotomasks OR #virusscam OR #plandemic OR 
                                  #scamdemic OR #coronavirusus OR #reopenUS OR #ReOpenAmerica OR #scamdemic2020 OR 
                                  #covid19walkout OR #reopennc OR #CovidUS OR (#coronavirus AND protest)OR #covid1984 OR 
                                  #NOMASK OR #reopenschools"

Function: tweets = sntwitter.TwitterSearchScraper(search_hashtags + ' since:%s until:%s' %(since_date, until_date)).get_items()

**Comment by darien-soung** [comment]
UPDATE: Using the command-line module: snscrape --jsonl twitter-search seems to work fine and provides more results than TwitterSearchScraper

**Comment by JustAnotherArchivist** [comment]
`snscrape twitter-search` pretty much just iterates over `TwitterSearchScraper.get_items`, so that doesn't make sense. And indeed:

```
> snscrape --jsonl --progress twitter-search '#protestlockdown OR #nolockdown OR #covidhoax OR #saynotomasks OR #virusscam OR #plandemic OR #scamdemic OR #coronavirusus OR #reopenUS OR #ReOpenAmerica OR #scamdemic2020 OR #covid19walkout OR #reopennc OR #CovidUS OR (#coronavirus AND protest) OR #covid1984 OR #NOMASK OR #reopenschools since:2020-10-15 until:2020-10-16' >/dev/null
[...]
Finished, 1905 results
> python3 -c 'import snscrape.modules.twitter'$'\n''s = snscrape.modules.twitter.TwitterSearchScraper("#protestlockdown OR #nolockdown OR #covidhoax OR #saynotomasks OR #virusscam OR #plandemic OR #scamdemic OR #coronavirusus OR #reopenUS OR #ReOpenAmerica OR #scamdemic2020 OR #covid19walkout OR #reopennc OR #CovidUS OR (#coronavirus AND protest) OR #covid1984 OR #NOMASK OR #reopenschools since:2020-10-15 until:2020-10-16")'$'\n''print(len(list(s.get_items())))'
1905
```

(I fixed the missing space after `protest)`.)

**Comment by darien-soung** [comment]
I found a solution to my problem and I want to share with whoever who is facing the same problem. I run the cmd script with python code and converted `jsonl `format into `json` format. The code is as follows:

```
cmd = "snscrape --jsonl twitter-search \"#protestlockdown OR #nolockdown OR #covidhoax OR #saynotomasks OR #virusscam OR #plandemic OR #scamdemic OR #coronavirusus OR #reopenUS OR #ReOpenAmerica OR #scamdemic2020 OR #covid19walkout OR #reopennc OR #CovidUS OR #covid1984 OR #NOMASK OR #reopenschools since:%s until:%s\"" % (
    '2020-04-01', '2020-04-02')
proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, )

output = proc.communicate()[0]

tweets = [json.loads(jline) for jline in output.splitlines()]



for i in range(len(tweets)):
    print(tweets[i])
```
