### ISSUE TITLE
Is there any way of scraping tweets from historical time?

### ISSUE THREAD

**Issue by hakanalpp** [JustAnotherArchivist/snscrape#127]
I know there is an argument "--since"that takes tweets from that date to now but, I need tweets from for example 2018 august to 2019 august, is there a way of doing that?

**Comment by MdeH1997** [comment]
you can use since and until to mark your timeline, for instance "since:2018-01-06 until:2019-01-06"

**Comment by JustAnotherArchivist** [comment]
See also #81
