### ISSUE TITLE
Unrecognized arguments with single quotes on Windows cmd

### ISSUE THREAD

**Issue by shizia** [JustAnotherArchivist/snscrape#128]
Hello, I have some problem.
I used this command:
 `snscrape twitter-search 'foobar since:2019-01-01 until:2019-01-02'` 
but it return this error: `snscrape: error: unrecognized arguments: since:2019-01-01 until:2019-01-02'`.
How to solve it?

**Comment by JustAnotherArchivist** [comment]
This is an issue with your environment. The command works correctly on any standard shell. The error message, especially the single quote at the end, indicates that the quoting isn't preserved in whatever you are using to run snscrape.

**Comment by shizia** [comment]
> This is an issue with your environment. The command works correctly on any standard shell. The error message, especially the single quote at the end, indicates that the quoting isn't preserved in whatever you are using to run snscrape.

Well ,I am still a little bit confused. So I should change my environment? What should I change?

**Comment by JustAnotherArchivist** [comment]
I have no idea. What are you using?

**Comment by shizia** [comment]
I use cmd of  windows 10.

**Comment by JustAnotherArchivist** [comment]
I was suspecting that. I still have no idea since I haven't had to use Windows in a long time, but maybe try double quotes instead of single quotes.

**Comment by shizia** [comment]
It works!!Thank you very much!!!!
