### ISSUE TITLE
How to fetch information on a Twitter user given a screenname?

### ISSUE THREAD

**Issue by micaelamaria** [JustAnotherArchivist/snscrape#133]
Hi! Is it possible in Twitter to get all the user information from the screenname, using snscrape?

**Comment by JustAnotherArchivist** [comment]
Yes.
CLI: `snscrape --jsonl --with-entity --max-results 0 twitter-user screenname`
API: `snscrape.modules.twitter.TwitterUserScraper('screenname').entity`
You will get an object similar to the ones on each tweet's `user` key.
This is only available in the development version currently.
