### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Flashfire42** [JustAnotherArchivist/snscrape#14]
Any possible way for a GUI wrapper for the average noob who wants to scrape an account.

**Comment by peterk** [comment]
I have combined snscrape with Squidwarc into a tool called [Munin](https://github.com/peterk/munin-indexer/blob/master/README.md) for people who want to start archiving open posts.

**Comment by JustAnotherArchivist** [comment]
@peterk Sorry, I saw this a long time ago but never replied. Excellent work, thank you!

---

I'm going to close this issue as wontfix. As explained above, I won't spend any time on this. Non-intrusive PRs are still welcome in principle, although I think that it would be better to keep it separate as a frontend for the API or CLI, similar to the countless wget GUIs.

**Comment by upintheairsheep** [comment]
https://github.com/chriskiehl/Gooey

**Comment by upintheairsheep** [comment]
This tool allows just that easily.

**Comment by TheTechRobo** [comment]
> I'm going to close this issue as wontfix. As explained above, I won't spend any time on this. Non-intrusive PRs are still welcome in principle, although I think that it would be better to keep it separate as a frontend for the API or CLI, similar to the countless wget GUIs.

Also, BTW: Are you just asking this for every archival repo?
