### ISSUE TITLE
How to get video or photo of media in a tweet?

### ISSUE THREAD

**Issue by ihahawen** [JustAnotherArchivist/snscrape#143]
Hi，
I don't know how to use issue insert code，sorry！
If in json files,i can use this code output the fullUrl and store photo.

```python
table=[]
with open("trump.json",'r',encoding='utf-8') as load_f:
    n=0
    for line in load_f:
        n+=1
        print(n)
        data = json.loads(line)
        #table.append(data)
        #pd.DataFrame.from_records(table).to_csv('text_files_test_10.csv',encoding='utf-8')
        if data['media']:
            for medium in data['media']:
            	if medium['type'] == 'photo':
             		print(medium['fullUrl'])`
```

Use other ways：

```python
import snscrape
for tweet in snscrape.modules.twitter.TwitterUserScraper(username=name).get_items():
        media=tweet.media
```

print result

    [Photo(previewUrl='https://pbs.twimg.com/media/Ek_hodXVMAEo9pc?format=jpg&name=small', fullUrl='https://pbs.twimg.com/media/Ek_hodXVMAEo9pc?format=jpg&name=large', type='photo')]

or

    [Video(thumbnailUrl='https://pbs.twimg.com/ext_tw_video_thumb/1320348316639532008/pu/img/leM_UOyxiYELn-Nz.jpg', variants=[VideoVariant(contentType='application/x-mpegURL', url='https://video.twimg.com/ext_tw_video/1320348316639532008/pu/pl/_wvWUV5zYvh3ldaX.m3u8?tag=10', bitrate=None), VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1320348316639532008/pu/vid/1280x720/6CN65DiSr9JokWRg.mp4?tag=10', bitrate=2176000), VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1320348316639532008/pu/vid/480x270/gspLjGW5fYeYRWZG.mp4?tag=10', bitrate=256000), VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1320348316639532008/pu/vid/640x360/hvE-BMIGCjj5ZceS.mp4?tag=10', bitrate=832000)], duration=17.595, type='video')]

it seems not json format，I tried to get photourl or videourl，but I don't know how to get ，can you help me？

**Comment by JustAnotherArchivist** [comment]
(Formatting fixed)

These are Python objects in lists. Specifically, they're dataclasses, and you can access those things as attributes. For example:

```python
for medium in tweet.media:
	if medium.type == 'photo':
		# Do something with medium.fullUrl
	elif medium.type == 'video':
		# Do something with one of the URLs in medium.variants
```

**Comment by ihahawen** [comment]
I really appreciate your help.It helps me a lot!

**Comment by ihahawen** [comment]
There something mistake:    
for medium in tweet.media:
TypeError: 'NoneType' object is not iterable

**Comment by JustAnotherArchivist** [comment]
`tweet.media` is `None` if a tweet has no media. That's true whether you use it directly or after JSON conversion and the reason why you had to add the `if data['media']:` line in your initial code.

**Comment by ihahawen** [comment]
There something mistake:
for medium in tweet.media:
TypeError: 'NoneType' object is not iterable

**Comment by ihahawen** [comment]
I try again

**Comment by ihahawen** [comment]
Thanks you quickly answer my question，it works～

**Comment by ihahawen** [comment]
I hope to help others
`mediaurl=[]
        # media=tweet.media
        if tweet.media:
            for medium in tweet.media:
                if medium.type == 'photo':
                    mediaurl.append(medium.fullUrl)
                #Do something with medium.fullUrl
                elif medium.type == 'video':
                    # Do something with one of the URLs in medium.variants

                    for v in medium.variants:
                        mediaurl.append(v.url.replace("?tag=13", "").replace("?tag=10", ""))`

**Comment by sunyoid** [comment]
> Hi，
> I don't know how to use issue insert code，sorry！
> If in json files,i can use this code output the fullUrl and store photo.
> 
> ```python
> table=[]
> with open("trump.json",'r',encoding='utf-8') as load_f:
>     n=0
>     for line in load_f:
>         n+=1
>         print(n)
>         data = json.loads(line)
>         #table.append(data)
>         #pd.DataFrame.from_records(table).to_csv('text_files_test_10.csv',encoding='utf-8')
>         if data['media']:
>             for medium in data['media']:
>             	if medium['type'] == 'photo':
>              		print(medium['fullUrl'])`
> ```
> 
> Use other ways：
> 
> ```python
> import snscrape
> for tweet in snscrape.modules.twitter.TwitterUserScraper(username=name).get_items():
>         media=tweet.media
> ```
> 
> print result
> 
> ```
> [Photo(previewUrl='https://pbs.twimg.com/media/Ek_hodXVMAEo9pc?format=jpg&name=small', fullUrl='https://pbs.twimg.com/media/Ek_hodXVMAEo9pc?format=jpg&name=large', type='photo')]
> ```
> 
> or
> 
> ```
> [Video(thumbnailUrl='https://pbs.twimg.com/ext_tw_video_thumb/1320348316639532008/pu/img/leM_UOyxiYELn-Nz.jpg', variants=[VideoVariant(contentType='application/x-mpegURL', url='https://video.twimg.com/ext_tw_video/1320348316639532008/pu/pl/_wvWUV5zYvh3ldaX.m3u8?tag=10', bitrate=None), VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1320348316639532008/pu/vid/1280x720/6CN65DiSr9JokWRg.mp4?tag=10', bitrate=2176000), VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1320348316639532008/pu/vid/480x270/gspLjGW5fYeYRWZG.mp4?tag=10', bitrate=256000), VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1320348316639532008/pu/vid/640x360/hvE-BMIGCjj5ZceS.mp4?tag=10', bitrate=832000)], duration=17.595, type='video')]
> ```
> 
> it seems not json format，I tried to get photourl or videourl，but I don't know how to get ，can you help me？

i dont know anything about coding but do i just paste this in the python IDLE?

**Comment by sunyoid** [comment]
> Thanks you quickly answer my question，it works～

Can we get the full code? when i paste your python doesn't recognize 'media'.

**Comment by DaisyLLanxi** [comment]
Hi @gxwyz , I tried the codes that you provided and mine displayed an error:" AttributeError: 'Video' object has no attribute 'type'" in `"if medium.type == 'photo"`. Do you met this error before? Thanks.

**Comment by gxwyz** [comment]
> Hi @gxwyz , I tried the codes that you provided and mine displayed an error:" AttributeError: 'Video' object has no attribute 'type'" in `"if medium.type == 'video"`. Do you met this error before? Thanks.

for tweet in TwitterSearchScraper(keyword).get_items():

**Comment by DaisyLLanxi** [comment]
> > Hi @gxwyz , I tried the codes that you provided and mine displayed an error:" AttributeError: 'Video' object has no attribute 'type'" in `"if medium.type == 'video"`. Do you met this error before? Thanks.
> 
> for tweet in TwitterSearchScraper(keyword).get_items():

Yes I tried it and do the if statement inside the for loop, but it still have the error. This is my codes:
```
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('flood since:2022-02-28 until:2022-03-01').get_items()):
    if i>50:
        break
    tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.media])
    print(tweet.media)
    if tweet.media:
        for medium in tweet.media:
            if medium.type == 'video':
                for v in medium.variants:
                        mediaurl.append(v.url.replace("?tag=13", "").replace("?tag=10", ""))
                print(medium.fullUrl)
```

**Comment by TheTechRobo** [comment]
Please make sure you are on the latest version of snscrape. pip will silently downgrade your snscrape if you are on Python 3.7.

**Comment by DaisyLLanxi** [comment]
> Please make sure you are on the latest version of snscrape. pip will silently downgrade your snscrape if you are on Python 3.7.

Yeah I am using pip version 20.2.3 and dev version of snscrape.

**Comment by gxwyz** [comment]
> ```python
> snscrape.modules.twitter.
> ```



> > > 嗨@gxwyz，我尝试了您提供的代码，但我的代码显示错误："AttributeError: 'Video' object has no attribute 'type'" in `"if medium.type == 'video"`. 你以前遇到过这个错误吗？谢谢。
> > 
> > 
> > 对于 TwitterSearchScraper(keyword).get_items() 中的推文：
> 
> 是的，我尝试过并在 for 循环中执行 if 语句，但它仍然有错误。这是我的代码：
> 
> ```
> for i,tweet in enumerate(sntwitter.TwitterSearchScraper('flood since:2022-02-28 until:2022-03-01').get_items()):
>     if i>50:
>         break
>     tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.media])
>     print(tweet.media)
>     if tweet.media:
>         for medium in tweet.media:
>             if medium.type == 'video':
>                 for v in medium.variants:
>                         mediaurl.append(v.url.replace("?tag=13", "").replace("?tag=10", ""))
>                 print(medium.fullUrl)
> ```

i think “if tweet.media” is in front of “tweets_list.append” ，because some twitter is no video or photo,so tweets_list is None。

**Comment by JustAnotherArchivist** [comment]
Yeah, this changed since the original issue (specifically in commit 460be9d5), and there is no longer a `type` attribute. This is now the proper way to do it in Python:

```python3
if tweet.media:
	for medium in tweet.media:
		if isinstance(medium, snscrape.twitter.Photo):
			#...
		elif isinstance(medium, snscrape.twitter.Video):
			#...
```

If you're processing the JSONL data, you'll want to check the `_type` attribute instead.

**Comment by DaisyLLanxi** [comment]
> Yeah, this changed since the original issue (specifically in commit [460be9d](https://github.com/JustAnotherArchivist/snscrape/commit/460be9d5814de82a2c5a5abe772872baca192207)), and there is no longer a `type` attribute. This is now the proper way to do it in Python:
> 
> ```python
> if tweet.media:
> 	for medium in tweet.media:
> 		if isinstance(medium, snscrape.modules.twitter.Photo):
> 			#...
> 		elif isinstance(medium, snscrape.modules.twitter.Video):
> 			#...
> 		elif isinstance(medium, snscrape.modules.twitter.Gif):
> 			#...
> ```
> 
> If you're processing the JSONL data, you'll want to check the `_type` attribute instead.

Yes I tried the isinstance method and it works! I also use Issue #241 to help me deal with it. Then I use wget to download the images, I found the codes  
```
with open('filename.jpg', 'wb') as fp:
            fp.write(r.content)
```
will keep override the filename.jpg. Is there any way to transfer each fullUrl of Photo to .jpg format and store it? I know how to store the urls but I am confused how to transfer each url and don't let previous url be overridden.
