### ISSUE TITLE
How to scrape tweets from a certain country or location?

### ISSUE THREAD

**Issue by yueyuanlucy** [JustAnotherArchivist/snscrape#145]
Hi,

I am trying to scrape the tweets about covid-19 using Python but wanted to just focus on the tweets from the US. Could you kindly help me with the code? Thank you so much!

sntwitter.TwitterSearchScraper(keyword + ' since:2019-01-01').get_items())

**Comment by JustAnotherArchivist** [comment]
Twitter's documentation [suggests](https://help.twitter.com/en/using-twitter/twitter-advanced-search) that you can use operators such as `near:"San Francisco" within:15mi` to filter by location. There are also `geocode` and `place` operators, see details [here](https://github.com/igorbrigadir/twitter-advanced-search). However, this would only find geotagged tweets, and it appears that [Twitter removed that feature last year](https://twitter.com/TwitterSupport/status/1141039841993355264), so I'm not sure whether this is actually useful.

**Comment by yogesh-5-sharma** [comment]
Hi @JustAnotherArchivist , is there any way to scrape tweets based on users account home location??

**Comment by JustAnotherArchivist** [comment]
@yogesh-5-sharma I don't know of any way to do that.
