### ISSUE TITLE
Support for Reddit

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#15]
Should support users, subreddits, and maybe threads (i.e. discovering the post URLs for each post in a thread; maybe also only for those that aren't displayed on the normal thread page due to deep nesting or too many comments).

This would have to go through the Pushshift API since Reddit's own API is garbage.

**Comment by github-userx** [comment]
Maybeone of these could be implemented or used as help? 

* reddit-thread-ripper (2017)
program to download an entire Reddit thread's comment section. It can be used as a standalone script or as part of a python program
https://github.com/saucecode/reddit-thread-ripper

* https://notabug.org/odg/SnooScraper

* https://github.com/stebbins/strigil/

* https://github.com/aliparlakci/bulk-downloader-for-reddit/

* https://github.com/nramin/reddit-python-posts-downloader/

* https://github.com/shadowmoose/RedditDownloader/


(I'm a noob and don't know much about programming so apologies if this is a dumb idea)
