### ISSUE TITLE
Feature request: Twitter retweeters of a particular tweet

### ISSUE THREAD

**Issue by Arf9999** [JustAnotherArchivist/snscrape#153]
The twitter web search doesn't surface retweets. Is it possible to scrape the retweeters of a particular twitter status?
i.e. scrape this page:
![image](https://user-images.githubusercontent.com/36820513/98242045-80a69400-1f74-11eb-8a88-6e5ee3dd907e.png)

**Comment by JustAnotherArchivist** [comment]
Duplicate of #103
