### ISSUE TITLE
snscrape csv output

### ISSUE THREAD

**Issue by sunyoid** [JustAnotherArchivist/snscrape#154]
My knowledge on python inst that great but, can someone walk me through on how to create a **csv output** to a folder where I **can view the archived tweets at?**

Thanks!

**Comment by sunyoid** [comment]
Details:I tried looking at the old issues but I just dont seem to get it, especially in  [issue#105](https://github.com/JustAnotherArchivist/snscrape/issues/105).

**Comment by IceBerge421** [comment]
Hi @sunyoid, not sure if this is helpful, but I used some python scripts put together in the comments here and was able to get a CSV output: https://github.com/Mottl/GetOldTweets3/issues/98

Scroll down to the comments from a few days ago!

Using this, I was able to use snscrape to get tweets from a keyword search into a CSV. I hope that's helpful! (Note: GetOldTweets3 isn't working, so these comments are about using snscrape as an alternative!).

**Comment by JustAnotherArchivist** [comment]
#118 has some code for this as well.

**Comment by sunyoid** [comment]
> #118 has some code for this as well.

thats only part of the code and when i pasted that in jupyter it gives my a whole bunch of error, and I have no clue how to code in python.

**Comment by JustAnotherArchivist** [comment]
@sunyoid I recommend you to go through some basic Python tutorial(s) before trying to use snscrape's API. The [official one](https://docs.python.org/3/tutorial/index.html) is very thorough. Once you get a grasp of Python code structure, data types, modules, etc., it should hopefully be fairly obvious despite the lack of documentation.

**Comment by sunyoid** [comment]
> @sunyoid I recommend you to go through some basic Python tutorial(s) before trying to use snscrape's API. The [official one](https://docs.python.org/3/tutorial/index.html) is very thorough. Once you get a grasp of Python code structure, data types, modules, etc., it should hopefully be fairly obvious despite the lack of documentation.

alright i think ill do that and come back in 2 months and try this out. Thank you so much for your time!

**Comment by leoGCoelho** [comment]
@sunyoid i made a basic extension of snscrape that mades an CSV output with all tweets extracted [leoGCoelho/Snscrape-Dataframe-Builder](https://github.com/leoGCoelho/Snscrape-Dataframe-Builder)

**Comment by DiameterEffect** [comment]
> @sunyoid i made a basic extension of snscrape that mades an CSV output with all tweets extracted [leoGCoelho/Snscrape-Dataframe-Builder](https://github.com/leoGCoelho/Snscrape-Dataframe-Builder)

alright I will try this later on, thank you for this!
