### ISSUE TITLE
Can I use proxy in it?

### ISSUE THREAD

**Issue by HandsomeLuoyang** [JustAnotherArchivist/snscrape#157]
Because of some reason, I have to use proxy to visited twitter website. How can I add a proxy?

**Comment by HandsomeLuoyang** [comment]
I have already find a method, thanks! I changed the code of requests.Session. wuhu~~

**Comment by JustAnotherArchivist** [comment]
Duplicate of #74

**Comment by papaya-ais** [comment]
Thank you
I tried several time
But only that you said worked for me too

`def request(method, url, params=None, data=None, headers=None, timeout=10, responseOkCallback=None,
            allowRedirects=True):
    # proxy set
    global proxy_dict
    session.proxies = proxy_dict`
