### ISSUE TITLE
How to get the number of likes, retweets, and replies from Twitter?

### ISSUE THREAD

**Issue by sufyanhamid** [JustAnotherArchivist/snscrape#158]
I want to ask that how can we get the number of (likes, retweets, comments) using snstwitter.
Kindly write the example query to fetch these data as well. Thanks in advance.
The code I have:

```python
import snscrape.modules.twitter as sntwitter
maxTweets = 3000


for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:@AntonioNeri_HPE + since:2000-01-01 until:2020-11-17').get_items()):
    if i > maxTweets :
        break
    print(tweet.content)
    print(tweet.username)
    print(tweet.date)
    
        
csvFile.close()
```

**Comment by JustAnotherArchivist** [comment]
* Likes: `tweet.likeCount`
* Retweets: `tweet.retweetCount`
* Replies: `tweet.replyCount`
* Quotes: `tweet.quoteCount`

This requires the current dev version of snscrape.

**Comment by sufyanhamid** [comment]
> * Likes: `tweet.likeCount`
> * Retweets: `tweet.retweetCount`
> * Replies: `tweet.replyCount`
> * Quotes: `tweet.quoteCount`
> 
> This requires the current dev version of snscrape.

So kindly tell me which verision is that?

**Comment by sufyanhamid** [comment]
> * Likes: `tweet.likeCount`
> * Retweets: `tweet.retweetCount`
> * Replies: `tweet.replyCount`
> * Quotes: `tweet.quoteCount`
> 
> This requires the current dev version of snscrape.

when I run this version than it gives the error that [AttributeError: 'Tweet' object has no attribute 'replyCount'] also for all 4 counts.
Kindle guide me how to fix it?

**Comment by azadesel** [comment]
You can use "locat":status.user.location,   the word "status" instead of tweet.
                        "fav": status.favorite_count,
                         "rt":status.retweet_count,

**Comment by azadesel** [comment]
You can use the word status instead of tweet.

"locat":status.user.location,
 "fav": status.favorite_count,
 "rt":status.retweet_count,

**Comment by JustAnotherArchivist** [comment]
@sufyanhamid, the current development version in this repository. See [the installation section in the readme](https://github.com/JustAnotherArchivist/snscrape#installation) for details.

@azadesel, I don't know what you're doing, but a) the variable name assigned on iteration is irrelevant, and b) those fields do not exist on objects returned by snscrape.

**Comment by azadesel** [comment]
> @sufyanhamid, the current development version in this repository. See [the installation section in the readme](https://github.com/JustAnotherArchivist/snscrape#installation) for details.
> 
> @azadesel, I don't know what you're doing, but a) the variable name assigned on iteration is irrelevant, and b) those fields do not exist on objects returned by snscrape.

Well i worked with tweepy to get the likes and retweet numbers etc. after i got urls from snscrape and i got what i wanted. I thought she might be using the codes that are available online and changing the iteration makes difference in that case. ı thought you understand that, my bad.

**Comment by sufyanhamid** [comment]
> @sufyanhamid, the current development version in this repository. See [the installation section in the readme](https://github.com/JustAnotherArchivist/snscrape#installation) for details.
> 
> @azadesel, I don't know what you're doing, but a) the variable name assigned on iteration is irrelevant, and b) those fields do not exist on objects returned by snscrape.
@JustAnotherArchivist Thank you so much for your reply and sharing your experience finally its work.
Have a nice day :)

**Comment by sufyanhamid** [comment]
> @sufyanhamid, the current development version in this repository. See [the installation section in the readme](https://github.com/JustAnotherArchivist/snscrape#installation) for details.
> 
> @azadesel, I don't know what you're doing, but a) the variable name assigned on iteration is irrelevant, and b) those fields do not exist on objects returned by snscrape.

@JustAnotherArchivist Thanks for helping me and sharing your experience. Finally it works.
Have a nice day :)

**Comment by JSMboli** [comment]
I wanted to do same thing but struggled a lot even after using this 

!pip install git+https://github.com/JustAnotherArchivist/snscrape.git 

in Jupiter notebook. 
I had to install git first before running !pip install git+https://github.com/JustAnotherArchivist/snscrape.git
and it finally worked.

**Comment by furkanmertunal** [comment]
Hi, I have the same problem and when I tried to upgrade the package with the development version, it gives an error. Is there an updated one already for which there's no link?

**Comment by valalithak** [comment]
How can I filter replies and get only the original tweets? I'm currently using the dev version but did not find any attribute which lets me identify if a tweet is original or a reply to some other tweet
@JustAnotherArchivist any help would be appreciated.

**Comment by Mitthoon** [comment]
> > @sufyanhamid, the current development version in this repository. See [the installation section in the readme](https://github.com/JustAnotherArchivist/snscrape#installation) for details.
> > @azadesel, I don't know what you're doing, but a) the variable name assigned on iteration is irrelevant, and b) those fields do not exist on objects returned by snscrape.
> 
> @JustAnotherArchivist Thanks for helping me and sharing your experience. Finally it works. Have a nice day :)

**Comment by Mitthoon** [comment]
> > > @sufyanhamid, the current development version in this repository. See [the installation section in the readme](https://github.com/JustAnotherArchivist/snscrape#installation) for details.
> > > @azadesel, I don't know what you're doing, but a) the variable name assigned on iteration is irrelevant, and b) those fields do not exist on objects returned by snscrape.
> > 
> > 
> > @JustAnotherArchivist Thanks for helping me and sharing your experience. Finally it works. Have a nice day :)

I am facing the same issue. May I know how you solved it? It is really urgent for my final year project

**Comment by TheTechRobo** [comment]
@Mitthoon What issue are you having? Installing the latest version should give you those attributes.

If you're on Python 3.7, pip will silently install an older version of snscrape.
