### ISSUE TITLE
Not filtering retweets

### ISSUE THREAD

**Issue by ajc356** [JustAnotherArchivist/snscrape#163]
I have just run my snscrape query in two different iterations, one filtering retweets and one not. Yet I get the same number of results with each. 

` snscrape --jsonl --max-results 2000000 --since 2020-03-01 twitter-search '((CRB or #CRB) -clubes -coupe -SuperCoupe -SUPER_COUPE -football -belouizdad -chabab -USMA -brasileño -Brasileirão -Algérie -Railway -@IR_CRB -@RailMinIndia -@PiyushGoyal) OR CERB OR #CERB OR (#EI (Canada OR #onpoli OR #cdnpoli)) OR (Canada unemployment) OR ((#CRA or cra) (#covid19canada OR #covid19relief OR covid OR covid19 OR coronavirus or pandemic)) -filter:retweets' > cerb_no_retweets.json`
returns 255327 tweets 

`snscrape --jsonl --max-results 2000000 --since 2020-03-01 twitter-search '((CRB or #CRB) -clubes -coupe -SuperCoupe -SUPER_COUPE -football -belouizdad -chabab -USMA -brasileño -Brasileirão -Algérie -Railway -@IR_CRB -@RailMinIndia -@PiyushGoyal) OR CERB OR #CERB OR (#EI (Canada OR #onpoli OR #cdnpoli)) OR (Canada unemployment) OR ((#CRA or cra) (#covid19canada OR #covid19relief OR covid OR covid19 OR coronavirus or pandemic))' > cerb_with_retweets.json`
returns 255894 tweets 
- Surely there have not been only 567 retweets on these topics but rather is due to users creating new tweets in the time (maybe 2 hours) between my queries. Could there be an issue with the way I am calling `-filter:retweets` ?

**Comment by JustAnotherArchivist** [comment]
As explained in your previous issue (#162), Twitter never returns retweets unless you explicitly specify `include:nativeretweets` or `filter:nativeretweets`. `filter:retweets` is for old-style retweets (tweet text prefixed by `RT`), which are essentially irrelevant nowadays.
