### ISSUE TITLE
Scrape Tweets with multiple keywords

### ISSUE THREAD

**Issue by mahsaazizi** [JustAnotherArchivist/snscrape#168]
Hi there! I wonder if we can extract tweets from Twitter by more than one keyword. For example, I need all the tweets having the two words of 'COVID' and 'Cancer'. It is doable using snscrape?

**Comment by JustAnotherArchivist** [comment]
Yes, simply pass multiple keywords separated with a space in the argument to the `twitter-search` scraper. For example, in a POSIX shell: `snscrape twitter-search 'foo bar'`
