### ISSUE TITLE
Scraping facebook posts of public groups and pages using a keyword within a particular timeframe 

### ISSUE THREAD

**Issue by PriyankaPGowdaa** [JustAnotherArchivist/snscrape#169]
Is there a way I could extract facebook posts content using snscrape from public groups and pages for a particular keyword in a particular timeframe in python? It would be of great help. Thanks.

**Comment by PriyankaPGowdaa** [comment]
I know it is a very detailed request but any help would be greatly appreciated. Thank you

**Comment by JustAnotherArchivist** [comment]
Unfortunately, Facebook doesn't have a search system like Twitter's, so this is impossible directly. You will have to do that outside of snscrape, e.g. with the API to filter by `'keyword'` for posts in January of this year:

```python
sinceDate = datetime.date(2020, 1, 1)
untilDate = datetime.date(2020, 2, 1)
for post in snscrape.modules.facebook.FacebookGroupScraper('groupname').get_items():
	if post.date < sinceDate:
		# This should be safe, but I'm not 100 % sure whether Facebook always returns posts in reverse chronological order.
		break
	if post.date >= untilDate:
		continue
	if not post.content or 'keyword' not in post.content:
		continue
	# Do something with the posts of interest...
```

The first content condition catches text-less posts. You might want to use `'keyword' not in post.content.lower()` to match case-insensitively.

**Comment by kwekuobosu** [comment]
Hi @JustAnotherArchivist, similar question to what @PriyankaPGowdaa asked, I want to know if I could query all facebook posts in general, as in from any page at all just like how the TwitterSearchScraper works, with a search query. Thanks in advance!

**Comment by JustAnotherArchivist** [comment]
@kwekuobosu No, that's not possible for the same reason as the above is needed for filtering within a group: Facebook does not have such a search (at least not for non-logged-in users).

**Comment by Oluwaseun5** [comment]
@kwekuobosu What if I'm logged in as a user? Is it possible then?

**Comment by JustAnotherArchivist** [comment]
@Oluwaseun5 #270
