### ISSUE TITLE
Some Facebook pages return no results

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#17]
Because Facebook sucks, snscrape currently returns no results on some pages even though it follows the pagination correctly.

Examples:
* https://www.facebook.com/JBishopMP/
* https://www.facebook.com/MarcusJHutchins/
* https://www.facebook.com/marionsugeknight/
* https://www.facebook.com/familyorbit/
* https://www.facebook.com/andyroid.net/

**Comment by JustAnotherArchivist** [comment]
Yet another example: https://www.facebook.com/jairmessias.bolsonaro/

**Comment by kiska3** [comment]
I just pip3 installed the development version.
This profile: https://www.facebook.com/Calare-UAP-1139073959593025/
Has posts, but snscrape is unable to get them

**Comment by JustAnotherArchivist** [comment]
I can scrape that profile successfully with the latest master (64693f74b).
