### ISSUE TITLE
How can I get video or photo of media ?

### ISSUE THREAD

**Issue by HAKANMAZI** [JustAnotherArchivist/snscrape#173]
I am using this code to get media of tweet.

```python
import snscrape
for tweet in snscrape.modules.twitter.TwitterUserScraper(username=name).get_items():
        media=tweet.media
        print(media)
```

I am getting this error

> Traceback (most recent call last):
>   File "1.py", line 37, in <module>
>     media=tweet.media
> AttributeError: 'Tweet' object has no attribute 'media'

**Comment by JustAnotherArchivist** [comment]
The `media` attribute is only available in the current development version, so you'll need to install from this repository rather than from PyPI.

**Comment by HAKANMAZI** [comment]
Thank very fastly answer bro ; 
Then ı installed pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git this version problem is solved.
