### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by philose83** [JustAnotherArchivist/snscrape#179]
Hi! I am trying to install the development version but having an error below:

Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to /private/var/folders/qp/cht2sjw917b55xyn3mj0vvtw0000gp/T/pip-req-build-y_rju0mi
ERROR: Command errored out with exit status 1: git clone -q https://github.com/JustAnotherArchivist/snscrape.git /private/var/folders/qp/cht2sjw917b55xyn3mj0vvtw0000gp/T/pip-req-build-y_rju0mi Check the logs for full command output.

Thanks!

**Comment by JustAnotherArchivist** [comment]
> Check the logs for full command output.

Have you tried that? The part you posted doesn't provide any information why it failed, and it's working fine here.

**Comment by philose83** [comment]
Yes, I executed  "!pip install git+https://github.com/JustAnotherArchivist/snscrape.git" in Jupyter notebook and got the error (I  followed "https://github.com/MartinBeckUT/TwitterScraper/blob/master/snscrape/python-wrapper/snscrape-python-wrapper.ipynb"). Is there a way to get more detail about the error? 

The thing is I want to get "replycounts" but it seems it is only available for the development version. There was no problem with installing the basic version though.

**Comment by JustAnotherArchivist** [comment]
The path given in the error message (/private/var/folders/qp/cht2sjw917b55xyn3mj0vvtw0000gp/T/pip-req-build-y_rju0mi in your first message) should contain a log file, I believe.

**Comment by philose83** [comment]
I checked the path, but couldn't find anything starting with "pip-req ..." This is weird. Is there another way to install the development version?

**Comment by philose83** [comment]
Solved! I found that I need to install Git. After installing git, everything works great. Thanks!
