### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by ygoldfrid** [JustAnotherArchivist/snscrape#186]
Hi, I have been using the scraper through the Python library and it is wonderful! I have noticed though that the library is not updated with the latest changes in this repo. Could you please update it? In particular, I would like, if possible, to use the TwitterProfileScraper feature through the library.
Thank you so much for your great work!

**Comment by JustAnotherArchivist** [comment]
I'm not sure what you mean. Are you talking about the released version on PyPI?

**Comment by ygoldfrid** [comment]
Yes precisely!

**Comment by JustAnotherArchivist** [comment]
I see. I don't know yet when the next release will be ready. Hopefully in February. There are still several things I want to implement first though.

**Comment by ygoldfrid** [comment]
Ok thank you very much for your quick response! I'll keep an eye open for that library update :)

**Comment by edsu** [comment]
Why not leave this open until February?

**Comment by JustAnotherArchivist** [comment]
Because it's neither a bug nor an enhancement nor anything else that should be tracked in an issue. If you want to be notified of the release, please use GitHub's notifications (under the 'watch' settings, button at the top right of any repo page) or [PyPI's release RSS feed](https://pypi.org/rss/project/snscrape/releases.xml).

**Comment by edsu** [comment]
It would be an enhancement.

**Comment by JustAnotherArchivist** [comment]
Not in the sense of what enhancement *issues* are, i.e. feature requests.
Anyway, there are better ways to be notified about new releases. Please use them.
