### ISSUE TITLE
Is there any documantations or code blocks for Facebook, Instagram, Telegram?

### ISSUE THREAD

**Issue by HAKANMAZI** [JustAnotherArchivist/snscrape#188]
First of all, Really thanks for this great library.
I can use this library for Twitter easly. But I can't use it for other social medias. Can anyone share any code blocks or documantation?

**Comment by JustAnotherArchivist** [comment]
Apart from the `--help` output on the CLI, no documentation exists (#6). Try `snscrape --help` and the individual modules', e.g. `snscrape facebook-user --help`.

**Comment by HAKANMAZI** [comment]
Thanks Fastly repply
