### ISSUE TITLE
Tweets not scraped for 2021. Scraping stops at 31st of december 2020

### ISSUE THREAD

**Issue by E-STAT** [JustAnotherArchivist/snscrape#189]
Hi

Please, I used snscrape to fetch tweets and I am highly interested in 2021 tweets; I specified the date range I want but I am getting 404 for any 2021 date.

Please, help

**Comment by JustAnotherArchivist** [comment]
With this little information, I can't help you. Everything works fine here as far as I can tell. Please read the pinned issue and provide the details mentioned there.

**Comment by E-STAT** [comment]
Thanks for the response.

I was missing a space in the 'since: date until: date' section.

issues fixed now.
