### ISSUE TITLE
Tweets dating back to the start of twitter i.e.2006

### ISSUE THREAD

**Issue by akhilsriram786** [JustAnotherArchivist/snscrape#191]
I am working on my Masters project wherein which I have to collect tweets related to query IoT from many years ago. When I try to use if condition like in the code below it does not work. Is it possible to collect tweets dating back to 2006?

```python
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('iot since:2006-04-01 until:2020-12-31').get_items()):
    if i>1000000:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.username])
    
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])
print(tweets_df2)
```

**Comment by JustAnotherArchivist** [comment]
In principle, that code works. However, there are likely more than 1 million tweets mentioning 'iot' over that time period, so your `if i>1000000:` condition will stop the search too early, and results are always returned in reverse-chronological order (i.e. newest first). Also, it appears that the oldest matching tweet returned by the search is from [January 2007](https://twitter.com/tremotrav/status/4860603), so you won't get any results from 2006 anyway.

By the way, the `until` filter is exclusive. So your query would find tweets up to and including 2020-12-30 but *not* from the last day of 2020.
