### ISSUE TITLE
Is it possible to get retweeted tweet using TwitterSearchScraper Class? 

### ISSUE THREAD

**Issue by tasnimaziz** [JustAnotherArchivist/snscrape#199]
Can i get tweets which retweeted by someone else using TwitterSearchScraper class?

**Comment by JustAnotherArchivist** [comment]
No (#8). `TwitterProfileScraper` can but has other limitations (<https://github.com/JustAnotherArchivist/snscrape/issues/85#issuecomment-698998263>).
