### ISSUE TITLE
List of following/followers for a particular Twitter Profile

### ISSUE THREAD

**Issue by darrenlimweiyang** [JustAnotherArchivist/snscrape#200]
**Summary**
Is there a way of getting a list of following/followers for a profile? 

**Why**
Would be nice to track certain profiles, especially public figures

**Suggestion**
Using the current user object we have, would it be possible to extend the implementation?

Thank you for your work thus far.

**Comment by JustAnotherArchivist** [comment]
No, this is not possible because snscrape does not and will not support authentication.

#103
