### ISSUE TITLE
How to use datetime.date instance with Twitter's since/until filters?

### ISSUE THREAD

**Issue by kirti-garg** [JustAnotherArchivist/snscrape#203]
I'm interested in getting 50 tweets per day for 30 days. Kindly suggest how I can pass single_date which is a variable of datetime.date() object to the 'until' parameter. 

```
for single_date in daterange(start_date, end_date):
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper('keyword until:single_date lang:en').get_items()):
      if i>50:
          break
      tweets_list2.append([tweet.date, tweet.id, tweet.content,tweet.username])
```

**Comment by JustAnotherArchivist** [comment]
Like this, for example:

    TwitterSearchScraper(f'keyword until:{single_date:%Y-%m-%d} lang:en')

Keep in mind that Twitter's `until` filter is exclusive, i.e. `until:2021-01-14` will return tweets posted on or before ***13*** Jan.

**Comment by kirti-garg** [comment]
Oh, this is great! This solves the issue.
Thank you for such a prompt reply! Really appreciate your help!
