### ISSUE TITLE
Support for scraping list of trends on Twitter

### ISSUE THREAD

**Issue by HAKANMAZI** [JustAnotherArchivist/snscrape#206]
Hi @JustAnotherArchivist firstly thank you so much such a great library.
  I want to scrape Trending Topics names. Is there a way to scrape Trends names. I checked all issues but I didnt find.

**Comment by JustAnotherArchivist** [comment]
I assume you mean the entries on <https://twitter.com/i/trends>?

**Comment by HAKANMAZI** [comment]
Yes @JustAnotherArchivist definitally i need trends entries. İs there any way to get ?

**Comment by JustAnotherArchivist** [comment]
No, this is not supported currently.

**Comment by ThyagoRD** [comment]
Hello @JustAnotherArchivist!

I'm trying to extract Trend Topics from Twitter locally to Brazil, but I'm not succeeding. Is there any way to do this, using snscrape? I can extract world trends, those from Brazil I cannot.

**Comment by JustAnotherArchivist** [comment]
@ThyagoRD https://github.com/JustAnotherArchivist/snscrape/issues/308#issuecomment-969218445
