### ISSUE TITLE
Installed snscrape using pip3 but command snscrape is not recognized using cmd line on Windows

### ISSUE THREAD

**Issue by zz328** [JustAnotherArchivist/snscrape#210]
installed using pip3 install snscrape and tried running on windows powershell, command prompt, and git bash but unable to recognize snscrape. don't know why this is happening because tried on a mac using terminal with the same commands and it's fully functional.

**Comment by JustAnotherArchivist** [comment]
I'm afraid I can't help with issues with specific systems or environments (cf. pinned issue), especially as I haven't used Windows in a very long time. snscrape does nothing special here, so any other normal package installation should have the same issue, and the solution (whatever it is) should fix it for all. I'd suggest using your favourite search engine. My guess would be a path or Python 2 vs 3 issue.

**Comment by rrreese** [comment]
@zz328  I encountered the above problems and have a resolution

On my machine pip installs the executables to this location:

```
C:\Users\<MYUSERNAME>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts
```

I would suggest navigating to `C:\Users\<MYUSERNAME>\AppData` and doing a search for `snscrape.exe`

You will  then need to add that location to your PATH then restart your shell
