### ISSUE TITLE
Searching Twitter with many keywords and `OR` clauses fails

### ISSUE THREAD

**Issue by federicoscabbia** [JustAnotherArchivist/snscrape#211]
Hi, I'm trying to scrape tweets using snscrape by location. Since leaving the query empty does not produce useful results (seems that it scrapes only tweets coming from instagram), i dediced to insert in the query the 100 most common words in english language, however snscrape gives me the following error. I first attach my code:
snscrape --jsonl --progress --max-results 10000 --since 2019-01-01 twitter-search "you OR i OR the OR to OR a OR it OR and OR that OR of OR in OR what OR is OR me OR we OR he OR this OR for OR my OR on OR your OR have OR do OR no OR don OR are OR be OR not OR was OR can OR know OR with OR all OR but OR here OR there OR they OR so OR get OR just OR go OR like OR up OR come OR right OR she OR him OR out OR if OR at OR now OR one OR about OR how OR oh OR want OR got OR her OR will OR well OR see OR good OR let OR yes OR think OR as OR who OR why OR yeah OR did OR from OR his OR when OR going OR man OR take OR where OR time OR them OR back OR an OR us OR look OR or OR would OR say OR were OR been OR then OR had OR tell OR some OR our OR okay OR by OR too OR gonna OR down OR could OR hey OR didn geocode:40.77937310313686,-117.13671577518582,900km until:2019-01-02" > tweets_country_2019-01-01.json

And this is the error i get:
2021-04-06 07:22:17.423  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=you+OR+i+OR+the+OR+to+OR+a+OR+it+OR+and+OR+that+OR+of+OR+in+OR+what+OR+is+OR+me+OR+we+OR+he+OR+this+OR+for+OR+my+OR+on+OR+your+OR+have+OR+do+OR+no+OR+don+OR+are+OR+be+OR+not+OR+was+OR+can+OR+know+OR+with+OR+all+OR+but+OR+here+OR+there+OR+they+OR+so+OR+get+OR+just+OR+go+OR+like+OR+up+OR+come+OR+right+OR+she+OR+him+OR+out+OR+if+OR+at+OR+now+OR+one+OR+about+OR+how+OR+oh+OR+want+OR+got+OR+her+OR+will+OR+well+OR+see+OR+good+OR+let+OR+yes+OR+think+OR+as+OR+who+OR+why+OR+yeah+OR+did+OR+from+OR+his+OR+when+OR+going+OR+man+OR+take+OR+where+OR+time+OR+them+OR+back+OR+an+OR+us+OR+look+OR+or+OR+would+OR+say+OR+were+OR+been+OR+then+OR+had+OR+tell+OR+some+OR+our+OR+okay+OR+by+OR+too+OR+gonna+OR+down+OR+could+OR+hey+OR+didn+geocode%3A40.77937310313686%2C-117.13671577518582%2C900km+until%3A2019-01-02&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=ext%3DmediaStats%252ChighlightedLabel: non-200 status code

If I use 10 words the code works, so it must be something regarding the length of the code right?
Thanks in advance for the help!

**Comment by JustAnotherArchivist** [comment]
Your query is likely too long. According to [StackOverflow](https://stackoverflow.com/questions/4976547/twitter-api-search-too-complex), Twitter's limits are 50 `OR` clauses or 500 characters (after URL-encoding), but I haven't verified that.

However, as far as I can see, a simple query of 'geocode:40.77937310313686,-117.13671577518582,900km' works fine for me (and will also find non-English results, of course), and so does adding an `until` clause.

**Comment by federicoscabbia** [comment]
thanks for the answer! I was wondering why do I get so many tweets that are shared from instagram? Is there a way to scrape only tweets coming from a specific source? like android or iphone?

**Comment by JustAnotherArchivist** [comment]
Yes, `source:twitter_for_android` and `source:twitter_for_iphone`, respectively. The web interface is `twitter_web_client`. Must be combined with another filter.

**Comment by JustAnotherArchivist** [comment]
Closing as the original issue is answered and can't be worked around.

**Comment by federicoscabbia** [comment]
sorry if i bother you again.
What would be the right command to get only androids AND iphone tweets at the same time?
i found that this works but i cannot find the way to add twitter_for_iphone in the query
snscrape --jsonl --progress --max-results 10000 --since 2020-07-01 twitter-search "source:twitter_for_android geocode:37.7764685,-122.4172004,1000km  until:2020-07-31" > tweets_country.json

**Comment by JustAnotherArchivist** [comment]
`(source:twitter_for_android OR source:twitter_for_iphone) geocode:...` (untested)

**Comment by Ds27jara** [comment]
Hi, I have a similar problem but I don't know how to fix it. I get the same error code but my query is not that long, however, the links is.

This is the code:

import snscrape.modules.twitter as sntwitter
import pandas as pd
import time

# Define the search query, language, and date range
query = "chatgpt"
language = " (lang:en)"
since = "2022-12-1"
limit = 20000

# Define the number of tweets to sample
sample_size = 2500

# Define the search query with hashtag, language, and date range
tweets = []

for i, tweet in enumerate(sntwitter.TwitterSearchScraper(query + language + ' since:' + since).get_items()):
    if len(tweets) == sample_size:
        break
    else:
        if tweet.likeCount >= 5:
            tweets.append({'Date': tweet.date, 
                           'User': tweet.user.username, 
                           'Tweet': tweet.content, 
                           'Followers': tweet.user.followersCount, 
                           'Following': tweet.user.friendsCount, 
                           'Likes': tweet.likeCount, 
                           'Retweets': tweet.retweetCount, 
                           'Comments': tweet.replyCount})
            print(f"Scraped tweet {i+1}: {tweet.content}")
        time.sleep(0.1)

# Convert the list of tweets into a Pandas DataFrame
df = pd.DataFrame(tweets)

# Extract the numerical values from the 'Followers', 'Likes', 'Retweets', and 'Comments' columns
df['Followers'] = df['Followers'].astype(str).str.extract('(\d+)').astype(int)
df['Likes'] = df['Likes'].astype(str).str.extract('(\d+)').astype(int)
df['Retweets'] = df['Retweets'].astype(str).str.extract('(\d+)').astype(int)
df['Comments'] = df['Comments'].astype(str).str.extract('(\d+)').astype(int)

# Save the DataFrame as a CSV file
df.to_csv('chatgpt_tweets.csv', index=False)

# Print the total number of tweets and the number of sampled tweets
print(f"Total number of tweets: {len(df)+i}")
print(f"Sample size: {len(df)}")
