### ISSUE TITLE
ERROR: Package 'snscrape' requires a different Python: 3.7.4 not in '~=3.8'

### ISSUE THREAD

**Issue by AnsarKZ** [JustAnotherArchivist/snscrape#223]
Hi guys! Thank you for your work!

I have tried running the dev version both with Python 3.8 and the latest 3.9.4
this error comes up anyways, thank you

>>>>>>>>>>>
Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to c:\users\owner\appdata\local\temp\pip-req-build-dkipyk2s
Note: you may need to restart the kernel to use updated packages.
  Running command git clone -q https://github.com/JustAnotherArchivist/snscrape.git 'C:\Users\Owner\AppData\Local\Temp\pip-req-build-dkipyk2s'
ERROR: Package 'snscrape' requires a different Python: 3.7.4 not in '~=3.8'

**Comment by JustAnotherArchivist** [comment]
As mentioned in the README:

> snscrape requires Python 3.8 or higher.
