### ISSUE TITLE
Json file appears incorrect

### ISSUE THREAD

**Issue by x879q** [JustAnotherArchivist/snscrape#227]
hi,
When storing data in a file. json, it appears that there is an error reading the file
**"Multiple JSON root elements"**

**Comment by JustAnotherArchivist** [comment]
snscrape produces JSONL (JSON lines), not JSON. Each line in the output is a JSON object.

(For completeness: JSONL is also known as LDJSON (line-delimited JSON) or NDJSON (newline-delimited JSON).)
