### ISSUE TITLE
Searching for multiple hashtags on Instagram

### ISSUE THREAD

**Issue by linar7** [JustAnotherArchivist/snscrape#228]
Hello, I have a question about scraping specific hashtags (especially on Instgram). Is it possible to ask for multiple Hashtags, so that the results will only be posts that have all of those? Is it maybe even possible to look for one OR the other Hashtag? Maybe anyone has tried this before.

**Comment by JustAnotherArchivist** [comment]
That's not directly possible as Instagram doesn't have such a filter mechanism (at least not without authentication). So you'll have to emulate that on your side. For AND, run the scrape on one hashtag (preferably the one that is used most rarely), then filter out results that don't contain all other hashtags of interest. For OR, run one scrape on each hashtag and combine the results, deduplicating on the `cleanUrl`s.

**Comment by linar7** [comment]
Thanks for the quick response! I'll look into it.
