### ISSUE TITLE
Not able to install it on raspbian 

### ISSUE THREAD

**Issue by github-userx** [JustAnotherArchivist/snscrape#23]
Hi,

I compiled and installed python3.6 on raspbian (Debian stretch based distro) and try to install snscrape in via pip in a virtualenv:

$ virtualenv --python=python3.6 snscrape
$ cd snscrape 
$ . /bin/activate
$ pip install snscrape

But I'm always getting some compiling error. (?)

I already did:

$ sudo apt-get install python3-libxml2 python3-lxml python-libxml2 python-lxml

Do we have to install the libxml2 and lxml dependencies via pip? I assume if that would be the case, they would *automatically* be installed with the snscrape package.

I apologize, I am still a noob.

**Comment by JustAnotherArchivist** [comment]
If you get a compilation error, then that sounds like it's related to the installation of lxml (since that's the only of snscrape's dependencies which requires compilation). Whether you install it through pip or through apt shouldn't matter. If you `pip install snscrape`, that should install lxml as well, but libxml2 including its headers (e.g. the libxml2-dev package on Debian) would have to be installed already for that to work. If you `apt-get install python3-lxml`, that should install the required dependencies as well; at least [the Debian package](https://packages.debian.org/stretch/python3-lxml) has libxml2 as a dependency (the headers aren't needed in that case because they're only necessary for compiling; the python3-lxml package already contains the compiled Python package), so I assume the same is the case on Raspbian.

What happens if you execute python3 and then enter `import lxml`?

**Comment by github-userx** [comment]
Thanks for the response.

This was my complete log:

user@user:~/.bin $
user@user:~/.bin $ virtualenv --python=python3.6 snscrape-test
Running virtualenv with interpreter /usr/local/bin/python3.6
Using base prefix '/usr/local'
New python executable in /home/user/.bin/snscrape-test/bin/python3.6
Also creating executable in /home/user/.bin/snscrape-test/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
user@user:~/.bin $ cd snscrape-test
user@user:~/.bin/snscrape-test $ . bin/activate
(snscrape-test) user@user:~/.bin/snscrape-test $
(snscrape-test) user@user:~/.bin/snscrape-test $ pip install snscrape
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting snscrape
  Using cached https://www.piwheels.org/simple/snscrape/snscrape-0.1.3-py3-none-any.whl
Collecting lxml (from snscrape)
  Using cached https://files.pythonhosted.org/packages/4b/20/ddf5eb3bd5c57582d2b4652b4bbcf8da301bdfe5d
805cb94e805f4d7464d/lxml-4.2.5.tar.gz
Collecting beautifulsoup4 (from snscrape)
  Using cached https://files.pythonhosted.org/packages/21/0a/47fdf541c97fd9b6a610cb5fd518175308a7cc605
69962e776ac52420387/beautifulsoup4-4.6.3-py3-none-any.whl
Collecting requests (from snscrape)
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8
b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->snscrape)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5
cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->snscrape)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05
a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->snscrape)
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292
d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->snscrape)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510
b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /home/user/.bin/snscrape-test/bin/python3.6 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-install-vs5qls2r/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__
);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
/tmp/pip-wheel-btny_h2z --python-tag cp36:
  Building lxml version 4.2.5.
  Building without Cython.
  ERROR: b'/bin/sh: 1: xslt-config: not found\n'
  ** make sure the development packages of libxml2 and libxslt are installed **

  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.6
  creating build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/builder.py -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/sax.py -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/__init__.py -> build/lib.linux-armv7l-3.6/lxml
  creating build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-3.6/lxml/includes
  creating build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-3.6/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-3.6/lxml/html
  creating build/lib.linux-armv7l-3.6/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-3.6/lxml/isoschematron
  copying src/lxml/etree.h -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/etree_api.h -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-3.6/lxml
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-3.6/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-3.6/lxml/includes
  creating build/lib.linux-armv7l-3.6/lxml/isoschematron/resources
  creating build/lib.linux-armv7l-3.6/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-3.6/lxml/i
soschematron/resources/rng
  creating build/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-3.6/lxml/isosc
hematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-3.6/lxml/isosc
hematron/resources/xsl
  creating build/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.
linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.
xsl -> build/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/l
ib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> buil
d/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/li
b.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv
7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-armv7l-3.6
  creating build/temp.linux-armv7l-3.6/src
  creating build/temp.linux-armv7l-3.6/src/lxml
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DCYTHON_CLINE_IN
_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/local/include/python3.6m -c src/lxml/etree.c -o build/te
mp.linux-armv7l-3.6/src/lxml/etree.o -w
  In file included from src/lxml/etree.c:662:0:
  src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: file or directory not found
   #include "libxml/xmlversion.h"
                                 ^
  compilation terminated.
  Compile failed: command 'gcc' failed with exit status 1
  creating tmp
  cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitbv7zcsuu.c -o tmp/xmlXPathInitbv7zcsuu.o
  /tmp/xmlXPathInitbv7zcsuu.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   main (int argc, char **argv) {
   ^~~~
  cc tmp/xmlXPathInitbv7zcsuu.o -lxml2 -o a.out
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml, beautifulsoup4, urllib3, idna, certifi, chardet, requests, snscra
pe
  Running setup.py install for lxml ... error
    Complete output from command /home/user/.bin/snscrape-test/bin/python3.6 -u -c "import setuptools
, tokenize;__file__='/tmp/pip-install-vs5qls2r/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file
__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --rec
ord /tmp/pip-record-h9givn9p/install-record.txt --single-version-externally-managed --compile --instal
l-headers /home/user/.bin/snscrape-test/include/site/python3.6/lxml:
    Building lxml version 4.2.5.
    Building without Cython.
    ERROR: b'/bin/sh: 1: xslt-config: not found\n'
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.6
    creating build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/builder.py -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/sax.py -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/__init__.py -> build/lib.linux-armv7l-3.6/lxml
    creating build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-3.6/lxml/includes
    creating build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-3.6/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-3.6/lxml/html
    creating build/lib.linux-armv7l-3.6/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-3.6/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/etree_api.h -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-3.6/lxml
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-3.6/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-3.6/lxml/includes
    creating build/lib.linux-armv7l-3.6/lxml/isoschematron/resources
    creating build/lib.linux-armv7l-3.6/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-3.6/lxml
/isoschematron/resources/rng
    creating build/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-3.6/lxml/iso
schematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-3.6/lxml/iso
schematron/resources/xsl
    creating build/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/li
b.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt
1.xsl -> build/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build
/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> bu
ild/lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/
lib.linux-armv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-ar
mv7l-3.6/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/src
    creating build/temp.linux-armv7l-3.6/src/lxml
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DCYTHON_CLINE_
IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/local/include/python3.6m -c src/lxml/etree.c -o build/
temp.linux-armv7l-3.6/src/lxml/etree.o -w
    In file included from src/lxml/etree.c:662:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: file or directory not found
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    Compile failed: command 'gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit6qo7820e.c -o tmp/xmlXPathInit6qo7820e.o
    /tmp/xmlXPathInit6qo7820e.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    cc tmp/xmlXPathInit6qo7820e.o -lxml2 -o a.out
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/user/.bin/snscrape-test/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tm
p/pip-install-vs5qls2r/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replac
e('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-h9gi
vn9p/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.b
in/snscrape-test/include/site/python3.6/lxml" failed with error code 1 in /tmp/pip-install-vs5qls2r/lx
ml/
(snscrape-test) user@user:~/.bin/snscrape-test $


Then I installed *libxslt1-dev* from the Debian repositories and now it seems like it compiles correctly and it definitely hasn't given me any errors but the compiling doesn't finish, not even after around 15-20 minutes. is this a heavy compiling process? I did compile a few other thingson the raspberry pi before and it never took more than 10-20 minutes:



(snscrape-test) user@user:~/.bin/snscrape-test $ pip install snscrape
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting snscrape
  Using cached https://www.piwheels.org/simple/snscrape/snscrape-0.1.3-py3-none-any.whl
Collecting beautifulsoup4 (from snscrape)
  Using cached https://files.pythonhosted.org/packages/21/0a/47fdf541c97fd9b6a610cb5fd518175308a7cc60569962e776ac52420387/beautifulsoup4-4.6.3-py3-none-any.whl
Collecting lxml (from snscrape)
  Using cached https://files.pythonhosted.org/packages/4b/20/ddf5eb3bd5c57582d2b4652b4bbcf8da301bdfe5d805cb94e805f4d7464d/lxml-4.2.5.tar.gz
Collecting requests (from snscrape)
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->snscrape)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->snscrape)
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->snscrape)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->snscrape)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... /

**Comment by JustAnotherArchivist** [comment]
I don't have any experience with Raspberry Pis, but I've definitely never seen it take anywhere near that long on normal computers – more like a few seconds to *maybe* half a minute if the machine's busy during compilation... I found some reports that installations of certain packages can take quite a long time on RPi though, up to hours for heavy things like SciPy. I wouldn't except lxml to take that long since it's not as big and complex, but it could still take a while on a slow machine as the RPi. You could also try running the installation with the verbose flag, i.e. `pip install -v snscrape`, to get more output during the compilation.

**Comment by github-userx** [comment]
Thanks!

**Comment by github-userx** [comment]
I rebooted the machine and tried everything from the beginning again and now it finished the compiling successfully after around 15-20 minutes.

For the compiling to work I definitely needed the package **libxslt1-dev** installed.

snscrape works flawlessly now. thanks again!

May I ask why snscrape needs more dependencies than some other crawling apps who maybe only need requests, beautifulsoup etc.? (Maybe I understand it wrong)

I just tried snscrape. so it gives us the links to the tweets of a Twitter user. The Facebook module outputs a dozen links to photos and images. Does this only work for public profiles and content I assume? (There are many people with pprofiles set to private so that Google cant crawl their profile. You can change that in the Facebook account settings).

Do you have any ideas or planson supporting the downloading of facebook photos, e.g.someones profile pictures and all the photos someone is tagged in? 

For literally every single social media I have archiving tools and scripts but ever since DownThemAll!'s AntiContainer fly Facebook Photos stopped working (because Facebook changed their site), downloading photos from Facebook has been a PITA and it could only been done manually ever since.)
I've been thinking about if Facebooks mobile version that doesn't need JavaScript couldn't be used to crawl and download content more easily? (mbasic.facebook.com)
e.g. if we search for the photos someone is tagged in: *mbasic.facebook.com/search/UserID/photos-tagged* will give us a page with links to the photos. When we follow one of these photos we get to that photos single page where there exist the *"View Full Size"* Link that leads to the JPG Directlink.

I could imagine that this could be done with a script/crawler or a headless browser. Making the whole process automatic would be the important thing.

 What are you doing with the output snscrape's modules give you? Handing it to some other useful archiving tools like wget or WAIL? Like I am wondering how I could now further process the output of the Facebook module for example?

By the way, are you on reddit?

**Comment by JustAnotherArchivist** [comment]
Glad to hear you got it working. Yeah, I forgot to mention that the libxlst headers are needed as well.

> May I ask why snscrape needs more dependencies than some other crawling apps who maybe only need requests, beautifulsoup etc.? (Maybe I understand it wrong)

I intend to make the lxml dependency optional sometime in the future. That would make it possible to run snscrape in a pure-Python environment or on different Python implementations than CPython which don't support C extensions. There is no real reason why snscrape uses it now; it's just how it evolved from some previous scripts I had where I used lxml for performance reasons.

> The Facebook module outputs a dozen links to photos and images. Does this only work for public profiles and content I assume?

snscrape is supposed to work on any Facebook profile page which is publicly accessible, i.e. which doesn't require a login. In reality, some pages don't work though, cf. #17.

> Do you have any ideas or planson supporting the downloading of facebook photos, e.g.someones profile pictures and all the photos someone is tagged in?

If that information is accessible without logging in, that sounds like a nice addition, and I've filed #24 for it. (I'm hesitant to add any login functionality due to potential ToS issues.)

> I've been thinking about if Facebooks mobile version that doesn't need JavaScript couldn't be used to crawl and download content more easily?

I believe that mobile site doesn't provide the full functionality, at least not without login. But it's been a while since I looked at it. Regardless, JS isn't a big issue, just a PITA; all of the current modules emulate the JS behaviour to do the scraping.

> What are you doing with the output snscrape's modules give you? Handing it to some other useful archiving tools like wget or WAIL?

I usually throw the URL lists into [ArchiveBot](https://archiveteam.org/index.php?title=ArchiveBot), which produces WARC files and gets them integrated into the [Wayback Machine](https://web.archive.org/).
I do some post-processing on the snscrape output though to filter out all the crap that's included in the URLs, especially for Facebook. Cf. #10.

> By the way, are you on reddit?

Yes, I am, under the same username as here. Not very active though.

**Comment by github-userx** [comment]
Awesome!

Yeah, I guess some of the Facebook stuff U was referring to would need a login.
The fact that still no one has written any tools or scripts that can get photos of other people (that will require your login beforehand) also just shows how much of a PITA the fb site must be these days.

It was truly amazing and very easy to use when this anticontainer still worked two years ago:

https://github.com/downthemall/anticontainer/blob/master/plugins/facebook.com_photos.json

You could just go to soneones photo page — be it the profile pictures or even the Tagged-Photos page (which you had to load until all photos were loaded) — you only had to use downthemall within firefox.
(RIP DownThemAll / Still use it in firefox ESR sometimes)

The login could be implemented either through PW and username or a cookie file I guess. But I understand if this isn't on your map/plans right now and there are ToS concerns.

Until then we keep downloading photos manually on Facebook.

**Comment by JustAnotherArchivist** [comment]
I'm sure there are tools for it somewhere, although they may not be easy to find. But yes, the Facebook site (Facebook as a whole really) gives you cancer instantly. It causes headaches regularly in ArchiveBot due to *thousands* of JavaScript files referenced in the HTML... (Not to mention the privacy and social issues.)

FYI, Firefox ESR does not support legacy addons anymore either; 52 ESR reached EOL in early September, so there is now no supported Firefox version anymore which can run legacy addons. (Don't get me started on those shitty decisions by the Mozilla devs...) Continuing to use 52 ESR is probably not a good idea at this point due to possible security issues which would never get patched.

Closing since the original issue is resolved. Feel free to ask further questions or open a new issue for other problems though.
