### ISSUE TITLE
Get Tweet replies by tweet Ids?

### ISSUE THREAD

**Issue by mohammadibrahemmustafa** [JustAnotherArchivist/snscrape#230]
Is there any way to get the tweet replies by tweet ids? If this is not possible, How I can get the replies for a single tweet?

https://www.reddit.com/r/Python/comments/jqy73z/scraping_tweets_without_limits_using_snscrape_and/gpbptlh/
in this link there is a comment about using **collect_replies = True** parameter but it didn't work for me.

**Comment by JustAnotherArchivist** [comment]
This isn't supported by snscrape at the moment, neither getting tweets by ID (#137) nor getting replies (#51). `collect_replies` isn't and has never been a thing here.

**Comment by sorbitolbronson** [comment]
> This isn't supported by snscrape at the moment, neither getting tweets by ID (#137) nor getting replies (#51). `collect_replies` isn't and has never been a thing here.

isn't it possible to get replies using `conversation_id` ? That seems to return tweets that are made in reply to a given tweet (and their replies)

**Comment by JustAnotherArchivist** [comment]
You can't use `conversation_id` on its own, but yes, there is a half-working workaround with it. Cf. https://github.com/JustAnotherArchivist/snscrape/issues/176#issuecomment-752286398

**Comment by sorbitolbronson** [comment]
Nice! I've been using it with the `lang` parameter, but `filter:safe` is actually less constricting in my use case. Not exactly sure what it misses though... the scraper seems to return all replies to a tweet including replies to those replies (which is often more than is displayed by the webpage)

**Comment by JustAnotherArchivist** [comment]
You can't just retrieve part of a conversation. For example, if you want to get all replies (and replies to replies etc.) to a tweet that is itself a reply, that isn't possible with `conversation_id`. You have to start from the first tweet in the conversation and retrieve all of them. The new `twitter-tweet` scraper has the same limitation currently, but I intend to fix that.
