### ISSUE TITLE
Confusion of "near" method in snscrape in twitter?

### ISSUE THREAD

**Issue by Xiaoshu-Zhao** [JustAnotherArchivist/snscrape#231]
I heard Geolocation operators, including near:, aren't reliable anymore but I can still use "near" to search tweets, even though the number of tweets is limited. I am a little confused if I can continue to use "near". And what is the replacement of "near" if I would like to do some location-based search? 
Thanks!

**Comment by JustAnotherArchivist** [comment]
That's what I meant by 'not reliable': you can still use it, but it does not produce reliable results. As far as I can tell, location-based tweet searches are simply not really supported anymore. This isn't an snscrape thing. All filtering happens on Twitter's servers, and Twitter removed the ability to add location information to tweets in the first place.

→ #225 and #145
