### ISSUE TITLE
How to spread out Tweets

### ISSUE THREAD

**Issue by sonofsevenless** [JustAnotherArchivist/snscrape#232]
Hi, 

I want to scrape 10,000 for a certain hashtag over the course of a year. How can I stop pulling the 10,000 most frequent Tweets since the first date and spread out the scrape evenly across the whole year?

Thanks so much in advance.

**Comment by JustAnotherArchivist** [comment]
If the 'top' sorting is suitable, that's supported in the development version since a few days. Otherwise, it isn't possible directly, so you'd have to collect all results and then take a random sample from them locally. See #152 and #164.

**Comment by lolakhairy** [comment]
any update in this
