### ISSUE TITLE
Is it possible to scrape a user's favorited tweets?

### ISSUE THREAD

**Issue by youssefavx** [JustAnotherArchivist/snscrape#238]
If not, do you plan on adding this functionality? Obviously no pressure if not, this is an incredible package that is lightning fast, thank you so much for making our lives easier. It's the best social media scraping package I've used.

**Comment by JustAnotherArchivist** [comment]
Unfortunately, I don't believe this is possible because Twitter doesn't let unauthenticated users see others' likes. (See also: #83, #103, #174)

**Comment by youssefavx** [comment]
Ah I see, no problem. Thank you for the response and sorry I should've searched for "likes" and "twitter" I searched for "favorites" but didn't find anything initially so thought this was a new issue.
