### ISSUE TITLE
Unable to fetch user details from Twitter using TwitterSearchScraper?

### ISSUE THREAD

**Issue by parvathysarat** [JustAnotherArchivist/snscrape#239]
I am unable to fetch user details such as display name, location etc, which I see listed under TwitterSearchScraper profile details.

```
for i, tweet in enumerate(sntwitter.TwitterSearchScraper('from:USERNAME').get_items()):
    print(tweet.user)

```
The above code gives me the error "AttributeError: 'Tweet' object has no attribute 'user'". I have also tried this with TwitterUserScraper but get the same results. Is user detail not returned anymore? I do not see it listed when I check dir(tweet) either. (I have earlier used tweet.user.followersCount etc to fetch details, but I get the error now.)

Python Version : 3.7.10
snscrape : 0.3.4

**Comment by parvathysarat** [comment]
I see that I'm able to fetch details using snscrape 0.3.5, closing issue. Thanks.

**Comment by JustAnotherArchivist** [comment]
There is no snscrape 0.3.5, but yes, this is only available in the dev version currently.

**Comment by himani007** [comment]
@JustAnotherArchivist , I am facing the same error while running this code on colab.

**Comment by JustAnotherArchivist** [comment]
@himani007 See #463, you need Python 3.8 or higher.

**Comment by himani007** [comment]
Yes, checked that! Still didn't work. 
I am trying to fetch data from Twitter with a specific range of dates and keywords. Would love some help 😭
