### ISSUE TITLE
Download the Images in a local drive using snscrape twitter.

### ISSUE THREAD

**Issue by sufyanhamid** [JustAnotherArchivist/snscrape#241]
@JustAnotherArchivist how to get the images from the media of twitter's profile locally in to a drive. I used
"tweet.media" which give me the urls of all available media content but I want to download all the available media into my machine. How can I do that by using snscrape??

**Comment by JustAnotherArchivist** [comment]
snscrape doesn't support that. You will have to handle it externally. Poor example with Requests to get you started:

```python3
import requests
import snscrape.modules.twitter


for tweet in snscrape.modules.twitter.TwitterUserScraper('textfiles', False).get_items():
	if not tweet.media:
		continue
	for medium in tweet.media:
		if isinstance(medium, snscrape.modules.twitter.Photo):
			r = requests.get(medium.fullUrl)
			with open('filename.jpg', 'wb') as fp:
				fp.write(r.content)
```

**Comment by DaisyLLanxi** [comment]
Hi @sufyanhamid , may I ask how can you get the url of media? I tried to use tweet.media but it return none. My codes:
`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('flood since:2022-02-28 until:2022-03-01').get_items()):
    if i>500:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.media, tweet.lang, tweet.sourceUrl])
    #m = tweet.media.get('media', [])
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Media' 'Language', 'Source'])`

**Comment by TheTechRobo** [comment]
If `tweet.media` returns None, it probably means there's no media.

**Comment by DaisyLLanxi** [comment]
> 

Hi thanks! But when I check the tweets that during this period and the query, it shows about one thousands tweets.

**Comment by DaisyLLanxi** [comment]
> If `tweet.media` returns None, it probably means there's no media.

Hi thanks I just realised that I tried tweets_df.head() only provide first 5 tweets and they didn't have media.

**Comment by DaisyLLanxi** [comment]
> snscrape doesn't support that. You will have to handle it externally. Poor example with Requests (and current dev snscrape) to get you started:
> 
> ```python
> import requests
> import snscrape.modules.twitter
> 
> 
> for tweet in snscrape.modules.twitter.TwitterUserScraper('textfiles', False).get_items():
> 	if not tweet.media:
> 		continue
> 	for medium in tweet.media:
> 		if isinstance(medium, snscrape.modules.twitter.Photo):
> 			r = requests.get(medium.fullUrl)
> 			with open('filename.jpg', 'wb') as fp:
> 				fp.write(r.content)
> ```

Hi I have a error when I tried to download images to local drive by using wget. In my codes, I set the number of obtaining tweets i is 2000, but according to the images that downloaded is about 900. And I double check the twitter api request, it said the maximum is 3200. Do you know how to fix it? Thanks.
```
TypeError                                 Traceback (most recent call last)
TypeError: __init__() missing 1 required positional argument: 'title'
```

**Comment by TheTechRobo** [comment]
#407

**Comment by DaisyWatermelon** [comment]
> 

Thanks and sorry for late reply!
