### ISSUE TITLE
Facebook grabber: "Too many redirects"

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#243]
Trying to download XKCD's Facebook profile, doesn't work. I keep getting this: 

```
╰─$ snscrape -f "{id}" facebook-user TheXKCD > facebooklist.txt
2021-06-30 15:02:54.504  WARNING  snscrape.base  Error retrieving https://www.facebook.com/TheXKCD/: TooManyRedirects('Exceeded 30 redirects.'), retrying
```

After that, facebooklist.txt is empty, even though the account has hundreds of posts.

**Comment by JustAnotherArchivist** [comment]
Unable to reproduce, I'm getting #208 on the pagination instead. Any hints in the dump file?

**Comment by TheTechRobo** [comment]
I didn't get a dump file. I'll try again - may have just been a temporary issue with FB servers.

**Comment by JustAnotherArchivist** [comment]
It should produce one after the retries are exhausted. But it looks like you're using version 0.3.4, not the dev version (since that log message is an `INFO` now), and things have changed a fair bit in that area of the code. You can try adding `--dump-locals` to make it write a dump file on `WARNING`s, not only on crashes.

**Comment by TheTechRobo** [comment]
Here it is: http://paste.openstack.org/show/807088/

I'll try testing it on the dev version if it's still not reproducible.

**Comment by JustAnotherArchivist** [comment]
Hmm, yeah, nothing useful in there because the response object isn't created due to the exception. That's unfortunate. I'll add more dumping on requests exceptions.

**Comment by JustAnotherArchivist** [comment]
With 2bb706fe and `--dump-locals`, the details should get logged now.

**Comment by TheTechRobo** [comment]
The Python 3.8 bit of the development version is a bit unfortunate, but fortunately I installed it a few months ago.

Also, the FacebookPost doesn't seem ot have the "id" thing, so I just removed the format specifyer temporarily. 

And it seemed to work! I think you should get onto releasing the dev version as the main version soon. I didn't use it since I was worried it wouldn't be stable, turns out it was more stable than 0.3.4!

**Comment by JustAnotherArchivist** [comment]
Good to hear. Yes, there are a few things I still want to implement before releasing a new version, but that is the plan.
