### ISSUE TITLE
"Unable to find guest token"

### ISSUE THREAD

**Issue by RockinTheSuburbs** [JustAnotherArchivist/snscrape#252]
Hi, 

I've been getting this result repeatedly across two machines. It was working fine until it suddenly wasn't. I left it alone for a few days and then it started running perfectly again. Now nothing I can do will make it run. Is this similar to #64?

I am not using AWS or Google Collab or anything. Just trying to run the python file through Visual Studio Code on my Windows PC. 

```
Traceback (most recent call last):
  File "d:\\TwitterScraper\WrapperScraper3.py", line 29, in <module>
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('{} from:{} since:2020-05-25 until:2021-06-30'.format(keywords_list[m], users_list[n])).get_items()):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\snscrape\modules\twitter.py", line 512, in get_items     
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\snscrape\modules\twitter.py", line 231, in _iter_api_data    obj = self._get_api_data(endpoint, reqParams)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\snscrape\modules\twitter.py", line 201, in _get_api_data 
    self._ensure_guest_token()
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\snscrape\modules\twitter.py", line 182, in _ensure_guest_token
    raise snscrape.base.ScraperException('Unable to find guest token')    
snscrape.base.ScraperException: Unable to find guest token
```

Thanks in advance.

**Comment by JustAnotherArchivist** [comment]
No idea I'm afraid. It works fine for me from a couple test machines, so it's not like #64. But it's similar to #79 in the sense that it likely means Twitter banned you. I guess they just hate you in particular. :-(

Do searches in a browser (in a private window/without logging in) work from the same computer or IP address?

**Comment by RockinTheSuburbs** [comment]
> Do searches in a browser (in a private window/without logging in) work from the same computer or IP address?

Do you mean just generic searches on twitter.com in private web browser, without using the scraper? Yes. I don't have a server running, and I don't know how to run a Python file in private browser, if that's what you mean, so not sure how to answer your question otherwise. Sorry.

It worked one time this morning before it started throwing the exception again. I think it hates longer search word lists, possibly. I am going to leave it alone for a couple of days and then try running it on shorter search word lists. 

I'm curious what Twitter has banned, since this script didn't require me to go through a Developer account and get access tokens. I'm sensing it's my IP address, since once it fails on one machine it fails repeatedly on all machines on the same network for a period of time.

**Comment by JustAnotherArchivist** [comment]
> Do you mean just generic searches on twitter.com in private web browser, without using the scraper?

Yes, that's what I meant. snscrape emulates the interaction with that search interface to do its work. Weird that snscrape would be blocked but your browser not; I haven't seen that happen before. You checked in the browser at the same time as snscrape was failing, right?

> I think it hates longer search word lists, possibly.

There are limits for that, yes, but that gives a different error: #211

> I'm curious what Twitter has banned

In all the cases I've seen, yep, it was an IP ban.

**Comment by RockinTheSuburbs** [comment]
`Weird that snscrape would be blocked but your browser not; I haven't seen that happen before. You checked in the browser at the same time as snscrape was failing, right?`

Ok, I was mistaken. I am able to search if it is not failing, but once it is failing, you are correct that incognito browser searches don't work either.  When I searched in browser I got an error saying "rate limit exceeded."

So, I looked that up. Here's a blog post from 2018: https://blog.twitter.com/en_us/a/2008/what-does-rate-limit-exceeded-mean-updated

Basically, there are only a certain amount of API calls that Twitter can make per hour. I am using a list of almost 100 users, and searching an extensive list of keywords. This "unable to find guest token" issue arises when the number of API calls exceeds what Twitter allows in an hour. So the solution is to separate keywords into shorter list, and let the program rest for an hour once the "unable to find guest token" issue arises. Notably, I have been able to scrape 700+ tweets in one go, so I don't think the limit of 100 API calls mentioned in the blog post translates to 100 tweets, but I'm not sure how it does work.

Anyhow, I consider this one solved. Thanks for all your help!

**Comment by JustAnotherArchivist** [comment]
Thanks for confirming! That makes more sense.

snscrape does not use the official API, so those rate limits do not apply. (Also, that article is from 2008, not 2018, and I highly doubt it's still relevant.) It does however use the internal API that the Twitter website also calls, which has its own undocumented rate limits. However, snscrape handles and works around those, and I haven't seen any cases where that failed – not even on huge scrapes with millions of results and a dozen parallel snscrape processes. So something's strange there. But yeah, it doesn't sound like this is something that can be worked around from the snscrape side, unfortunately.
