### ISSUE TITLE
Twitter Place ID

### ISSUE THREAD

**Issue by mcjraquel** [JustAnotherArchivist/snscrape#253]
Hi. I tried to filter out tweets in my country using the near: place operator but the results include tweets from neighboring countries. I know that I could use the place: id operator but I don't know the Place ID of Philippines. Do you know how I could know or what it is? I tried looking it up everywhere but I don't think there's anyone who posted about it. Or is there another way to filter about tweets (like bounding box of coordinates)? Thanks a lot!

**Comment by JustAnotherArchivist** [comment]
Although not immediately obvious, this is the same as #235. I don't know of a way to query place IDs (or any other place properties, including the bounding box coordinates) without that Twitter API endpoint.

**Comment by JustAnotherArchivist** [comment]
Also, note that Twitter's geolocation searches are unreliable these days: #145

**Comment by mcjraquel** [comment]
I see. Thank you.
