### ISSUE TITLE
Twitter search_scrapper.get_items() returns links to statuses

### ISSUE THREAD

**Issue by kperveen** [JustAnotherArchivist/snscrape#255]
I wrote the following code to query data between the given dates and its working but the return of this call is links to statuses and not tweets.

`for tweet in sntwitter.TwitterSearchScraper('new since:2015-01-01 until:2019-07-01').get_items():
        print(tweet)`

Is that right? Or am I missing something?

I am using the dev version `snscrape 0.3.5.dev119+g0c22608`

This is what I get
`https://twitter.com/Eliedc00/status/1416291435972907009`

**Comment by JustAnotherArchivist** [comment]
This is right. An `snscrape.modules.twitter.Tweet`'s string representation is its URL, and `print` implicitly casts the argument to a string. `tweet` inside your loop is still a proper `Tweet` object with all its attributes. Try `print(repr(tweet))` or `print(tweet.json())`.

**Comment by JustAnotherArchivist** [comment]
This is also true for other scrapers, by the way. The string representation of an item is always its URL. The reason for that lies in how snscrape evolved. Originally, it could only output URLs, and the CLI uses `print(item)`. So when more attributes were added, that's how that behaviour was preserved for backwards compatibility.

**Comment by kperveen** [comment]
Thank you so much for the explanation.
