### ISSUE TITLE
Use time along with date to filter tweets

### ISSUE THREAD

**Issue by Sagar1094** [JustAnotherArchivist/snscrape#259]
Hi, 

Is there a way to apply time filter along with date. Like sntwitter.TwitterSearchScraper(' "Query" since:2021-07-29 22:00:00 until:2021-07-29 23:00:00').get_items().

Thanks

**Comment by JustAnotherArchivist** [comment]
I just found that there are `since_time` and `until_time` operators that take an epoch timestamp in seconds. So you can do that with `... since_time:1627596000 until_time:1627599600`.

Credit: https://github.com/igorbrigadir/twitter-advanced-search/issues/25

**Comment by Sagar1094** [comment]
This worked perfectly, thanks a lot. 👍

**Comment by King-Del-ErnestO** [comment]
> 

so when exactly does 1627596000 stand for please

**Comment by JustAnotherArchivist** [comment]
@King-Del-ErnestO https://en.wikipedia.org/wiki/Unix_time

**Comment by King-Del-ErnestO** [comment]
Thank you so much! Worked perfectly

**Comment by JustAnotherArchivist** [comment]
It appears that this can now also be done with `since` and `until`: `since:2022-10-27_12:00:00_UTC` selects tweets from the past half hour, and likewise `until:2022-10-27_12:00:00_UTC` selects tweets from before half an hour ago. Other timezones work as well, e.g. `until:2022-10-27_12:00:00_CEST`.
