### ISSUE TITLE
Find tweets from its ID

### ISSUE THREAD

**Issue by sufyanhamid** [JustAnotherArchivist/snscrape#264]
Hi @JustAnotherArchivist .
I want to get the tweet content using its ID and I'm using twitter search bar to get these details.

For example: From this link (https://twitter.com/PandeezBlack/status/1219771580919664640) I want to get the tweet content so I separate the tweet ID from the url and search the ID on twitter's search bar like this: (since_id:1219771580919664640 max_id:1219771580919664641 filter:safe) but I'm getting no results, I also use some other queries which is (conversation_id:1219771580919664640 lang:x) and (url:1219771580919664640 lang:x) but no results.

So kindly guide me to do this in a right way.

Thanks in advance :)

**Comment by JustAnotherArchivist** [comment]
`snscrape twitter-tweet 1219771580919664640`

If you really want to use the search, that works as well (unless the user is search-banned or similar), but you didn't use the right values. `since_id` is *not* inclusive, and `max_id` is. So this query works: [`since_id:1219771580919664639 max_id:1219771580919664640 (filter:safe OR -filter:safe)`](https://twitter.com/search?q=since_id%3A1219771580919664639%20max_id%3A1219771580919664640%20(filter%3Asafe%20OR%20-filter%3Asafe)&f=live). But yeah, use `twitter-tweet` instead.

**Comment by sufyanhamid** [comment]
Perfect. Thanks :)
