### ISSUE TITLE
Reply tweets count different from tweet.replyCount 

### ISSUE THREAD

**Issue by HAKANMAZI** [JustAnotherArchivist/snscrape#265]
Hi @JustAnotherArchivist , When I scrape this tweets https://twitter.com/evleaks/status/1033925199912214529 it gives me 31 reply tweets but tweet.replyCount gives me 28. 

Why the results are different?

**Comment by JustAnotherArchivist** [comment]
`replyCount` is the number of *direct* replies to a tweet; it does not include replies to replies or deeper levels. I've also noticed that it isn't always accurate though, and I suspect it has something to do with deleted or protected tweets.

**Comment by JustAnotherArchivist** [comment]
There's also a bug here: #266
