### ISSUE TITLE
What is the isUserId of TwitterUserScraper?

### ISSUE THREAD

**Issue by hiro-551010** [JustAnotherArchivist/snscrape#272]
First, I'd like to thank JustAnotherArchivist.
My problem is what isUserId in TwitterUserScraper.
The title says it all.

I'm sorry my English is not good enough.
thank you.

**Comment by JustAnotherArchivist** [comment]
`isUserId` is the clunky way how I implemented the `--user-id` option a while ago. When `isUserId` is `False`, `username` is the username of the user. When `isUserId` is `True`, `username` is the numeric user ID instead (but still as a string).

This is undocumented currently and will definitely change in the future when I clean up the API.

Also, your English's fine. :-)

**Comment by hiro-551010** [comment]
Thank you for quick reply.
For example, somethin like this?
```
for i,tweet in enumerate(sntwitter.TwitterUserScraper("matsu_bouze", False).get_items()):
```

Dear DeepL! (^^)b

**Comment by JustAnotherArchivist** [comment]
Yep, exactly! :-)

**Comment by hiro-551010** [comment]
Fundamental question, I want to get this person's tweets, I should use TweetUserScraper, right?
https://twitter.com/matsu_bouzu

This question is Should I build a new issue?

**Comment by JustAnotherArchivist** [comment]
Yes, or TwitterProfileScraper. See https://github.com/JustAnotherArchivist/snscrape/issues/85#issuecomment-698998263 for the differences.

**Comment by hiro-551010** [comment]
Thank you for answering all my questions!
