### ISSUE TITLE
ScraperException error (timeout error) in Twitter Search

### ISSUE THREAD

**Issue by Shiny-senni** [JustAnotherArchivist/snscrape#274]
Error retrieving https://twitter.com/search?f=live&lang=en&q=its+the+elephant+since%3A2020-06-01+until%3A2020-07-31&src=spelling_expansion_revert_click: ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=its+the+elephant+since%3A2020-06-01+until%3A2020-07-31&src=spelling_expansion_revert_click (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024FDB9A21F0>, 'Connection to twitter.com timed out. (connect timeout=10)'))"))
4 requests to https://twitter.com/search?f=live&lang=en&q=its+the+elephant+since%3A2020-06-01+until%3A2020-07-31&src=spelling_expansion_revert_click failed, giving up.

I am using Python 3.8.5 and snscrape snscrape-0.3.5.dev123+gc76f163 on Windows.

**Comment by JustAnotherArchivist** [comment]
Works fine for me. Can you access Twitter through a browser from the same machine?

**Comment by Shiny-senni** [comment]
Yes, I can

**Comment by JustAnotherArchivist** [comment]
Well, I have no idea then, but I see that this is the same as #197 (even the same query). Are you using a proxy? Do other (non-Twitter) scrapers work?

**Comment by Shiny-senni** [comment]
Yes, I am using a proxy as I need to use it to access Twitter. But Tweepy works (though only recent seven days). And I tried the Instagram scraper, same error happened. Is that the proxy's problem?

**Comment by JustAnotherArchivist** [comment]
If other scrapers fail in the same way, then yes, that indicates that something about your proxy setup isn't right. I just verified that snscrape works fine with a functional proxy (via the `HTTPS_PROXY` environment variable).

**Comment by Shiny-senni** [comment]
I cannot solve this problem as I don't know how to set up a functional proxy. Buy really thanks to your reply and help!

**Comment by JustAnotherArchivist** [comment]
Yeah, I'm afraid I can't help you with that either. I just used some random proxy list from the web and tried until I found a working proxy. It was very slow and completely unusable for actual scraping, but at least I could confirm it works in principle.

Alternatively, you could rent a (virtual) server at a provider that isn't banned by Twitter (see other issues) and run the scraping on that (and the processing wherever you want).

**Comment by JustAnotherArchivist** [comment]
Closing as a duplicate of #197.
