### ISSUE TITLE
Trying to pull both content: and from: in the same enumerate

### ISSUE THREAD

**Issue by ScottSavaiano** [JustAnotherArchivist/snscrape#276]
Hi thank you so very much, I am having a problem though: 

this query is returning an empty data frame.

```python3
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:HillaryClinton content:"COVID" since:2020-02-01 until:2020-07-31 lang:en').get_items()):
```

any assistance on syntax (assuming this query is possible) would be greatly appreciated!

**Comment by JustAnotherArchivist** [comment]
I assume you mean tweets that contain the keyword? In that case, simply include the keyword directly in the query (without any operator):

    from:HillaryClinton "COVID" since:2020-02-01 until:2020-07-31 lang:en

**Comment by ScottSavaiano** [comment]
Thanks again for this library and for the quick reply!

**Comment by JustAnotherArchivist** [comment]
Happy to help! :-)
