### ISSUE TITLE
`ModuleNotFoundError: No module named 'snscrape.modules'; 'snscrape' is not a package`

### ISSUE THREAD

**Issue by ankitb142** [JustAnotherArchivist/snscrape#278]
I am getting the following error:
`ModuleNotFoundError: No module named 'snscrape.modules'; 'snscrape' is not a package`

I used the following command on the kernel:
`pip install git+https://github.com/JustAnotherArchivist/snscrape.git`

**Comment by JustAnotherArchivist** [comment]
This sounds like something went wrong with the installation or is broken in your environment (possibly Python 2 vs 3?). I just tested it in a fresh virtualenv, and both `import snscrape.modules` and `import snscrape.modules.twitter` work fine.

**Comment by ankitb142** [comment]
I only got Python 3.8.8 installed on my PC and I am referring to the correct python.exe from the Python Interpreter in Anaconda. Would you recommend installing the package in a virtual environment?

**Comment by JustAnotherArchivist** [comment]
Virtual environments (with pyenv and pyenv-virtualenv) are just what I use to keep my various Python and package installations separate. I'm a big fan of this setup, so I'd recommend it in general for anyone looking for something like that, but it's absolutely not required.

I'm not familiar with either Anaconda or using it on Windows, so I'm afraid I can't give any specific further advice there. I'd make sure that `python` and `pip` refer to the same Python installation. I know that on some systems, one needs to install specifically with `pip3` or even `pip3.8` to have it end up in the right place. But if `pip` were using Python 2, the installation should fail anyway as snscrape doesn't support Python 2 at all.

**Comment by JustAnotherArchivist** [comment]
Also, make sure that your own script isn't called `snscrape.py`. Otherwise Python will try to import that instead of the package, which obviously fails, and it would produce exactly that error.

**Comment by ankitb142** [comment]
> 
> 
> Also, make sure that your own script isn't called `snscrape.py`. Otherwise Python will try to import that instead of the package, which obviously fails, and it would produce exactly that error.

Ah this was the issue, thanks so much. So silly of me

**Comment by JustAnotherArchivist** [comment]
Ah yes, easy mistake to make and not very obvious. Glad I was able to help. :-)
