### ISSUE TITLE
How to scrape tweets by user profile location?

### ISSUE THREAD

**Issue by kanissh** [JustAnotherArchivist/snscrape#282]
I am wondering is it possible to scrape tweets by matching the user profile location string to our query string.

The value I mean by user profile location is the below value that we get when a tweet is scraped as a json.
_"..." in the image denotes other values in the json object._ 

![image](https://user-images.githubusercontent.com/44309040/134518700-6027e35d-371f-4857-8cea-2f5120df1aa8.png)

**Comment by JustAnotherArchivist** [comment]
As far as I know, this isn't possible. You can only filter by tweets' geolocation on Twitter's search (which has its own issues, see #225 and #145), not by the account's location.

Potentially, once #263 is implemented, you could use that. But I have no idea how reliable that is. If it works, you'd have to first scrape users from a location and then scrape all their tweets individually (or with a big `from:a OR from:b OR ...` query, though there are limits on that, see #211).

**Comment by kanissh** [comment]
@JustAnotherArchivist thanks for your quick response, really appreciate your help.
