### ISSUE TITLE
How to scrap using userID instead of user

### ISSUE THREAD

**Issue by romulocordova** [JustAnotherArchivist/snscrape#287]
I think there is no functionality, is it?

I only use tweet.username

**Comment by JustAnotherArchivist** [comment]
Yes, there is: `snscrape twitter-user --user-id 1465481`
This works with the `twitter-profile` scraper as well.
Simply resolving a user ID to a username is currently not well-supported.

**Comment by romulocordova** [comment]
> Yes, there is: `snscrape twitter-user --user-id 1465481` This works with the `twitter-profile` scraper as well. Simply resolving a user ID to a username is currently not well-supported.

Wait, but I need it on python. Is there any method for this? (twitter.user-id something like that?)

**Comment by JustAnotherArchivist** [comment]
This is how to do it currently, although this will change sometime in the future:

```python3
snscrape.modules.twitter.TwitterUserScraper('1465481', isUserId = True)
```

Note that the ID must be a string. (That's part of why it will change in the future.)

The same thing also works with the `TwitterProfileScraper`.

**Comment by thepraveen19** [comment]
I have the list of twitter user IDs, I need the usernames. How can I do it?

**Comment by JustAnotherArchivist** [comment]
```python3
import snscrape.modules.twitter

userIds = ['1465481', '86347253']
for userId in userIds:
	scraper = snscrape.modules.twitter.TwitterUserScraper(userId, isUserId = True)
	print(scraper.entity.username)
```

**Comment by thepraveen19** [comment]
Awesome! Thank you so much for the quick response!

**Comment by Jmallone** [comment]
> Note that the ID must be a string. (That's part of why it will change in the future.)

Currently, in the version of **snscrape==0.5.0.20230113** it does not need to be a string, it necessarily needs to be an int for it to make the comparison as demonstrated [in this line](https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/modules/twitter.py#L1575)

E.g:
```python
scraper = snscrape.modules.twitter.TwitterUserScraper(1465481)
print(scraper.entity.username)
 ```

**Comment by JustAnotherArchivist** [comment]
Indeed, this was changed due to #354.

**Comment by AlejandroDGR** [comment]
Hello,

Any idea about iterating through a list of users' IDs in order to get tweets between two dates?

If I use the user's username, I have no problems. The code is:
```
users_name = ['ostatu', 'carloseduardrf']
for n, k in enumerate(users_name):
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:{} since: 2021-01-01 until:2022-01-01'.format(users_name[n])).get_items()):
     if i>100:
        break
     tweets_list1.append([tweet.date, tweet.user.username, tweet.user.id, tweet.rawContent])
```
Then, if I use the user's ID without dates limitations, I get no errors too:
```
users_id = [90402416, 571111858]
for k, userId in enumerate(users_id):
    for i, tweet in enumerate(snscrape.modules.twitter.TwitterUserScraper(userId).get_items()):
     if i>100:
       break
     tweets_list1.append([tweet.date, tweet.user.username, tweet.user.id, tweet.rawContent])
```
But if I try to scrape tweets by using users' IDs between two dates, I do get errors:

Code 1:
```
users_id = [90402416, 571111858]
for k, userId in enumerate(users_id):
    for i, tweet in enumerate(snscrape.modules.twitter.TwitterUserScraper('since: 2021-01-01 until:2022-01-01', userId).get_items()):
     if i>100:
       break
     tweets_list1.append([tweet.date, tweet.user.username, tweet.user.id, tweet.rawContent])
```
Error:
```
TypeError: __init__() takes 2 positional arguments but 3 were given
```
Code 2:
```
users_id = [90402416, 571111858]
for k, userId in enumerate(users_id):
    for i, tweet in enumerate(snscrape.modules.twitter.TwitterUserScraper('from:{} since: 2021-01-01 until:2022-01-01'.format(users_id[n])).get_items()):
     if i>100:
       break
     tweets_list1.append([tweet.date, tweet.user.username, tweet.user.id, tweet.rawContent])
```
Error:
```
ValueError: Invalid username
```
Code 3:
```
users_id = [90402416, 571111858]
for k, userId in enumerate(users_id):
    for i, tweet in enumerate(snscrape.modules.twitter.TwitterSearchScraper('from:{} since:2020-03-15'.format(users_id[n])).get_items()):
     if i>100:
       break
     tweets_list1.append([tweet.date, tweet.user.username, tweet.user.id, tweet.rawContent])
```
In this last case, I'm not getting any errors but results either. `TwitterSearchScraper()` is recognizing ID's as usernames, so the results are blank.

Any idea about how to overcome any of these errors?

Thanks in advance!

**Comment by JustAnotherArchivist** [comment]
Yep, the search doesn't accept user IDs, so you need to resolve the user ID first:

```python3
user = snscrape.modules.twitter.TwitterUserScraper(1465481).entity
for tweet in snscrape.modules.twitter.TwitterSearchScraper(f'from:{user.username} since:2023-01-01').get_items():
	...
```

That's what the `TwitterUserScraper` does internally as well when you provide a user ID.
