### ISSUE TITLE
Few question's

### ISSUE THREAD

**Issue by dnikola** [JustAnotherArchivist/snscrape#289]
Hello

this library look amazing. 
I would have few questions if possible please repaly:

1. Can you tell me is it possible to get data in json response?
2. Is it possible to use proxy's so IP wont get blocked
3. Is it possible to modify json response?
4. Are you available for custom work as freelancer? 

Best regards!

**Comment by dnikola** [comment]
3. i mean when i run this command i would like that output be little bit different I would like to have mentions, hashtags used for some modules (I have seen that some has it already) 
5. please check this  
![image](https://user-images.githubusercontent.com/21372733/136289106-8c7de9c6-397c-44f0-ab68-332bbeab0d4c.png)

**Comment by JustAnotherArchivist** [comment]
3. Right. What you get as JSONL output is everything that snscrape extracts currently. The modules/scrapers differ strongly in that respect. If you have specific suggestions what should be added, please file an issue for that.
4. That sounds like an issue with your Windows terminal. You probably have to enable UTF-8 (cf. #122). `snscrape --jsonl --verbose instagram-hashtag ispričajpričudokraja` works as expected for me and returns 26 posts.

**Comment by dnikola** [comment]
> 5. Facebook doesn't let users list posts with hashtags unless you're logged in. snscrape doesn't support logging in.
> 6. No tricks. That scraper doesn't seem to work at all for me at the moment, although it might depend on the profile page (as some use the old design and others the new). Facebook is a mess and will also quickly ban your IP, so fixing it is tricky.


hi let me replay

5. yes i know that but using right proxy it can be done. We use proxy's from specific country's which are not regulated by GDPR and EU law so hashtag's are available for scraping. I know that because few months we have been working on this, but our scripts are not so fast as yours. I could share more info if you need
6. yes i know that about old / new design. As i mention we use proxy's, also dedicated ig and FB proxy's which are rotating on every request 


could you please check adding Facebook hashtag?  I can share our current scripts with you.

Regards
Nikola

**Comment by dnikola** [comment]
> Reopened #31
> 
> snscrape already handles the scrolling. If it stops mid-feed, that normally means your IP is banned, although snscrape is supposed to throw an error in that situation (cf. #208, #250).

it just return first two post, no error :) so i think that doesn't scroll
