### ISSUE TITLE
Does TwitterSearchScraper scrape all of the relevant tweets or only a random subset of all? 

### ISSUE THREAD

**Issue by cjing1** [JustAnotherArchivist/snscrape#295]
I am using TwitterSearchScraper to scrape tweets based on keywords. Do all tweets including keywords being scraped or only a random subset of all relevant tweets being scraped? 

Thanks

**Comment by JustAnotherArchivist** [comment]
Generally everything. However, some Twitter users are search-banned, i.e. their tweets never show up in searches. There are also various search index issues surrounding account name changes and other weird things. But yeah, for the most part, all public tweets should be included.
