### ISSUE TITLE
How do I use max-results in the python wrapper?

### ISSUE THREAD

**Issue by akselhakim** [JustAnotherArchivist/snscrape#297]

**Comment by usman87626** [comment]
I am using a counter-in for loop, break the loop wherever you want, following code is in the testing mode. Use it if you like and suggest to me the changes where you think we can do it better.

`import snscrape.modules.twitter as sntwitter 
from tqdm import tqdm

class TwitterScraper(object):
    # Container for our scrapped data
    tweet_details = []
    #Constructor to initialize the Scraper
    def __init__(self,keywords,maxTweets,followerLimit):
        self.keywords = keywords
        self.maxTweets = maxTweets
        self.followerLimit = followerLimit
    
    # Function which takes output-filename.csv as argument (You can give the path as well like : data/filename.csv)
    def start_scraping(self):
        counter = 0
        for i,tweet in enumerate(tqdm(
                                    sntwitter.TwitterSearchScraper(self.keywords).get_items(),
                                    desc='Scraping',
                                    total=self.maxTweets+1
                                )):
            # Break when limits reaches
            
            if i > self.maxTweets:
                break
            # If followers are more than followerLimit sent via constructor
            if tweet.user.followersCount >= self.followerLimit:
                self.tweet_details.append({
                            "tweet_id":      tweet.id, 
                            "tweet_url":     tweet.url,
                            "tweet_content": tweet.content, 
                            "tweeted_on":    tweet.date,
                            "tweeted_by":    tweet.user.username, 
                            "display name":  tweet.user.displayname,
                            "user_id"    :   tweet.user.id,
                            "user_description": tweet.user.description,
                            "verified":         tweet.user.verified,
                             "follower_count":  tweet.user.followersCount,
                             "following_count": tweet.user.friendsCount,
                             "status_count":     tweet.user.statusesCount,
                             "profile_url":      tweet.user.linkUrl,
                            "outlinks":        tweet.outlinks,
                            "reply_count":     tweet.replyCount,
                            "retweet_count":   tweet.retweetCount,
                            "tweet_likes":      tweet.likeCount,
                            "tweet_quote_count":tweet.quoteCount,
                            "tweet_lang":       tweet.lang,
                            "tweet_source":     tweet.source,
                            "id_of_original_tweet": tweet.retweetedTweet,
                            "id_of_quoted_tweet":   tweet.quotedTweet,
                            "mentioned_users":      tweet.mentionedUsers
                        })
                counter += 1
        print(counter)
        print(f"Success!! Data of {self.maxTweets} Tweets are scraped...")
        return self.tweet_details`

**Comment by JustAnotherArchivist** [comment]
`--max-results` is a CLI thing, the rest of snscrape knows nothing about it. `get_item` is a simple generator, so just iterate over it until you're satisfied.

Here's the generic pattern to stop after a fixed number of items:

```python3
scraper = ...
for i, item in enumerate(scraper.get_items()):
	if i >= maxResults:
		break
	# Do what you want with `item`
# At this point, `i` will be the number of items you got.
```
