### ISSUE TITLE
Cannot import the snscrape module for twitter

### ISSUE THREAD

**Issue by Logenleedev** [JustAnotherArchivist/snscrape#298]
Hi! I want to scrap some twitter data inside jupyter notebook. My python version is 3.9+ and when I run:
```
import snscrape.modules.twitter as sntwitter
```

I got the following error:
```

/opt/homebrew/lib/python3.9/site-packages/snscrape/modules/telegram.py in <module>
     23 
     24 @dataclasses.dataclass
---> 25 class TelegramPost(snscrape.base.Item):
     26         url: str
     27         date: datetime.datetime

/opt/homebrew/lib/python3.9/site-packages/snscrape/modules/telegram.py in TelegramPost()
     30         linkPreview: typing.Optional[LinkPreview] = None
     31 
---> 32         outlinksss = snscrape.base._DeprecatedProperty('outlinksss', lambda self: ' '.join(self.outlinks), 'outlinks')
     33 
     34         def __str__(self):

AttributeError: module 'snscrape.base' has no attribute '_DeprecatedProperty'
```

Does anyone know how to fix this?

**Comment by JustAnotherArchivist** [comment]
That sounds like a messed up installation, e.g. some sort of mixture of the last release and the current dev code or similar. I'd suggest uninstalling and then reinstalling snscrape. (Can't give any concrete advice for how to do that on your system though. I'm not familiar with macOS/Homebrew.)

**Comment by Logenleedev** [comment]
> That sounds like a messed up installation, e.g. some sort of mixture of the last release and the current dev code or similar. I'd suggest uninstalling and then reinstalling snscrape. (Can't give any concrete advice for how to do that on your system though. I'm not familiar with macOS/Homebrew.)

Hi! I tried to uninstall it and install it again. Does not work neither.....

**Comment by JustAnotherArchivist** [comment]
That's progress though. At least you have a consistent code now.
You installed the release version 0.3.4, I assume? That's not compatible with Python 3.9 (see #111). You'll need to install the dev version or patch that.

**Comment by Logenleedev** [comment]
> That's progress though. At least you have a consistent code now. You installed the release version 0.3.4, I assume? That's not compatible with Python 3.9 (see #111). You'll need to install the dev version or patch that.

Yep. I install the latest release. I do not think the dev version works since it reports the same error as the first one I posted. I guess if I switch my mac python3 to 3.8, it will work.

**Comment by JustAnotherArchivist** [comment]
That's very odd because `_DeprecatedProperty` definitely exists in the dev version. I'm using it daily on Python 3.9. No idea how that could happen unless you have two installations of snscrape in different locations or your Python setup as a whole is majorly broken.

But yes, the release should work on 3.8 I think.

**Comment by Logenleedev** [comment]
> That's very odd because `_DeprecatedProperty` definitely exists in the dev version. I'm using it daily on Python 3.9. No idea how that could happen unless you have two installations of snscrape in different locations or your Python setup as a whole is majorly broken.
> 
> But yes, the release should work on 3.8 I think.

omg... I really don't know what happens. I switch to 3.8.12 and it reported the same error....
<img width="507" alt="image" src="https://user-images.githubusercontent.com/47022821/139616572-fbfdd710-36b6-4e8b-9c4e-96ebe53fdc59.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/47022821/139616619-e52cc46a-d2b8-46be-8874-84a874fccbc9.png">

**Comment by Logenleedev** [comment]
> That's very odd because `_DeprecatedProperty` definitely exists in the dev version. I'm using it daily on Python 3.9. No idea how that could happen unless you have two installations of snscrape in different locations or your Python setup as a whole is majorly broken.
> 
> But yes, the release should work on 3.8 I think.

Thank you so much! I think it works right now.

**Comment by JustAnotherArchivist** [comment]
Great to hear! Now the fun part begins. :-)
