### ISSUE TITLE
Twitter: Is there any language filter?

### ISSUE THREAD

**Issue by giovanniOfficioso** [JustAnotherArchivist/snscrape#300]
Hi dear thank you for share your work, I really appreciate. However I have a stupid question: when I make a research with “twitter-searc” is possible to use a language filter to have the answers only in that language, for example —lang: it? I’m sorry for the stupid question but I don’t find an answer to my questione before posting. Thank you for your patience and attention.

**Comment by JustAnotherArchivist** [comment]
The query on `twitter-search` supports all filters Twitter's search has. That includes the language filter. For example, `snscrape twitter-search 'word lang:it'` will only return tweets in Italian that contain 'word'.

**Comment by giovanniOfficioso** [comment]
> The query on `twitter-search` supports all filters from Twitter's search. That includes the language filter. For example, `snscrape twitter-search 'word lang:it'` will only return tweets in Italian that contain 'word'.

Thank you dear, I didn’t know what is the word with which specify the language. Thank you so much
