### ISSUE TITLE
Support to scrape users' followers, replies, and people they are following

### ISSUE THREAD

**Issue by Logenleedev** [JustAnotherArchivist/snscrape#301]
Hi! Just wondering does snscrape has the feature which enables developers to scrape a user's followers, replies, people they are following and store them in a list?

**Comment by JustAnotherArchivist** [comment]
Followers/followees: #174

'A user's replies' can mean two things. Replies by a given user to others' tweets are included in `twitter-user` and `twitter-profile` scrapes. Replies to a given user by others can be found with `snscrape twitter-search 'to:user'`, though this also includes the user's replies to their own tweets as well as original tweets directed at someone via a mention. The former can be filtered out with a query like `'to:user -from:user'`. I'm not sure there's a way to filter out the latter directly, but comparing the tweet ID with the `conversationId` would work as a post-processing step.

**Comment by Logenleedev** [comment]
As for the replies by a given user to others' tweets, what's the python function to do it? Since there is no official Python documentations, just want to ask.

**Comment by JustAnotherArchivist** [comment]
```python3
import snscrape.modules.twitter

scraper = snscrape.modules.twitter.TwitterUserScraper('username')
for tweet in scraper.get_items():
	# ...
```

(Or `TwitterProfileScraper` if you want the `twitter-profile` equivalent.)

This includes original tweets. If you only want replies:

```python3
scraper = snscrape.modules.twitter.TwitterSearchScraper('from:username filter:replies')`
```

You could add `-to:username` to the query to filter out self-replies.
