### ISSUE TITLE
How do I scrape for tweets with a minimum limit for likes or replies?

### ISSUE THREAD

**Issue by trenkert** [JustAnotherArchivist/snscrape#302]
I want to scrape all tweets with the hashtag `#foo ` that have received more than 50 likes and more than 10 replies. How do I do this with snscrape (with the python wrapper)?

**Comment by JustAnotherArchivist** [comment]
Partial duplicate of #201. I only gave the CLI solution there for that case, but it works the same. So you'll want to run a search query like `'#foo min_faves:50 min_replies:10'` through `snscrape.modules.twitter.TwitterSearchScraper`.

**Comment by trenkert** [comment]
Thank you!
