### ISSUE TITLE
Space in keyword search 

### ISSUE THREAD

**Issue by cjing1** [JustAnotherArchivist/snscrape#303]
Thank you again for the fantastic scraping library. I am curious how does space work in the keyword search when using Twitter scrape. For example, will 'Lockheed Martin' be included in 'LockheedMartin' or Vice versa?

**Comment by JustAnotherArchivist** [comment]
No, it shouldn't.

If you have two words in a search query, you should get all tweets that contain both of those words in any order and context. E.g. `snscrape twitter-search 'Lockheed Martin'` in usual UNIX shells (Bash etc.). The single quotes are interpreted by the shell; snscrape simply sees the arguments `twitter-search` and `Lockheed Martin`. Windows terminal syntax is different I believe, but I'm not familiar with it.

To search for a specific phrase, you can additionally surround it with double quotes. For example, on Bash-like shells: `snscrape twitter-search '"Lockheed Martin"'` (again, the single quotes are for the shell, and snscrape sees `"Lockheed Martin"` as the second argument). This would return tweets that contain exactly 'Lockheed Martin', but it would not match tweets containing e.g. 'Lockheed foo Martin'.

Perhaps it's clearer in Python code: the former would be `TwitterSearchScraper('Lockheed Martin')` (i.e. single string argument containing a space), the latter `TwitterSearchScraper('"Lockheed Martin"')` (same but with double quotes around the phrase).

**Comment by Ashwin-RN** [comment]
hey, so it seems like the phrase search isn't quite working for snscrape anymore. 
My request:

  df_2 = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
'\"covid fever\"  near:\"Boston\"within:10km lang:en').get_items(), total_tweets))[['user', 'date','renderedContent', 'lang']]

any idea how I can fix this?

**Comment by JustAnotherArchivist** [comment]
@Ashwin-RN That syntax never worked (as far as I know). Remove the backslashes and add a space before `within`.

**Comment by Ashwin-RN** [comment]
Yep, its working perfectly. My bad
Any resource to use snscrape for facebook or other social media?
