### ISSUE TITLE
Where the json result is saved

### ISSUE THREAD

**Issue by barripdmx** [JustAnotherArchivist/snscrape#304]
Hi.

I execute:  "**snscrape --jsonl twitter-hashtag "caso bar españa**" and after removing the data I do not see where they are saved. I need to put something in the code?

Best regards.
jb

**Comment by JustAnotherArchivist** [comment]
snscrape does not save anything. It simply writes to standard output. If you execute that exact command, you get the results in your terminal. If you redirect it to a file instead, as in `snscrape --jsonl ... >output.jsonl`, that file is where they end up. If you delete that file, the data is gone.

(By the way, that scrape actually searches for tweets that have the hashtag `#caso` and the two words `bar` and `españa`, which may not be what you're trying to do.)

**Comment by barripdmx** [comment]
Thanks. Is there a way to take all three words together?

**Comment by JustAnotherArchivist** [comment]
Hashtags cannot contain spaces. Perhaps you mean `snscrape twitter-hashtag casobarespaña`, which corresponds to [this search](https://twitter.com/search?q=%23casobarespana&f=live)? If you want to just search for the three words, use the `twitter-search` scraper instead.

**Comment by eldepor** [comment]
Hi, how can I get the json file but just with "url", "date" and "rawcontent" fields? Thanks
