### ISSUE TITLE
Tweet Views

### ISSUE THREAD

**Issue by ateezma** [JustAnotherArchivist/snscrape#306]
Is there a way to find the number of views that a tweet is getting? I can see that it works for videos but not for the actual tweets.

I know that this is not public data available on a tweet and is probably the reason why this is not able to be scraped but is this a possibility?

Sorry if this is a stupid question I am new to web scraping but thank you in advance!

**Comment by JustAnotherArchivist** [comment]
> I know that this is not public data available on a tweet

Correct. If you convince Twitter to make this information available, I'll happily add its extraction to snscrape. Currently, for all practical purposes, this data does not exist.
