### ISSUE TITLE
TwitterTrendsScraper

### ISSUE THREAD

**Issue by EduardErnest** [JustAnotherArchivist/snscrape#308]
Hi @JustAnotherArchivist , good job on this scraper, works really well. I have a question around TwitterTrendsScraper, since documentation on py. wrapper is missing, does the trendsscraper work?

**Comment by JustAnotherArchivist** [comment]
It does for me. Have you tried it?

```python3
import snscrape.modules.twitter

scraper = snscrape.modules.twitter.TwitterTrendsScraper()
for trend in scraper.get_items():
	print(trend.json())
```

**Comment by EduardErnest** [comment]
Fantastic, @JustAnotherArchivist I will give it a go...

**Comment by EduardErnest** [comment]
import snscrape.modules.twitter as sntwitter

scraper = sntwitter.TwitterTrendsScraper()
for trend in scraper.get_items():
	print(trend.json())


this worked.


I have follow up question, can you add parameter to the trends e.g. Crypto for example or Blockchain

**Comment by JustAnotherArchivist** [comment]
To my knowledge, it's not possible to request any trends other than what Twitter returns there. You can't switch the location either and instead always get the trends for the country where Twitter locates you based on your IP as that would require an account.

**Comment by EduardErnest** [comment]
I see...so I guess just get the data and make our own - get creative :)) Thanks for the swift reply,, I appreciate the input a lot. BTW do you have any contact details if anyone wants to follow up for some collab on project?

**Comment by EduardErnest** [comment]
Sounds good JAA, I will reach out. 👍🏽
