### ISSUE TITLE
how to convert "mention user" attribute to list or json

### ISSUE THREAD

**Issue by Logenleedev** [JustAnotherArchivist/snscrape#309]
I noticed that after I get the tweets data from a specific user, the "mention user" column cannot be directly used. It's something like 

`"[User(username='xxxx', id=12345, displayname='xxxx', description=None, rawDescription=None, descriptionUrls=None, verified=None, created=None, followersCount=None, friendsCount=None, statusesCount=None, favouritesCount=None, listedCount=None, mediaCount=None, location=None, protected=None, linkUrl=None, linkTcourl=None, profileImageUrl=None, profileBannerUrl=None, label=None)]"`

The data is stored as an object in pandas dataframe. Is there a way to convert this chunk to something like a list or json object so that I can index it? Thanks for the help!

**Comment by JustAnotherArchivist** [comment]
`mentionedUsers` is a list of `snscrape.modules.twitter.User` objects, which are dataclass objects with JSON support (similar to `Tweet` etc.).  So you can either pull out the fields you're interested in using attributes or convert it to a JSON string with its `.json()` method. Then you can for example wrap that in a list comprehension to do it for every entry in the `mentionedUsers` with a condition for that field not being `None`, e.g. `users = [<your_conversion> for user in tweet.mentionedUsers] if tweet.mentionedUsers else None` with something like `user.username` or `user.json()` as the conversion. The details depend on the exact data structure you need obviously, which is something you'll have to figure out yourself.

**Comment by Logenleedev** [comment]
> `mentionedUsers` is a list of `snscrape.modules.twitter.User` objects, which are dataclass objects with JSON support (similar to `Tweet` etc.). So you can either pull out the fields you're interested in using attributes or convert it to a JSON string with its `.json()` method. Then you can for example wrap that in a list comprehension to do it for every entry in the `mentionedUsers` with a condition for that field not being `None`, e.g. `users = [<your_conversion> for user in tweet.mentionedUsers] if tweet.mentionedUsers else None` with something like `user.username` or `user.json()` as the conversion. The details depend on the exact data structure you need obviously, which is something you'll have to figure out yourself.

I gues the real issue is I am not sure how to convert the string to a JSON array list. Since pd dataframe only stores object, it automatically "stringfy" JSON array. If I can drop the double quote, I think I know what to do after that.

**Comment by JustAnotherArchivist** [comment]
Well yeah, the object clearly gets passed through `repr()` or `str()` somewhere. You need to transform it before even feeding it into Pandas so that Pandas only ever sees objects it can deal with. But I'm not very familiar with Pandas nor do I know what data you're trying to put into it exactly, so I can't really help with that.

Generally, simply treat `User` objects like `Tweet` objects in terms of extracting data into other data structures, just with different fields (username, id, displayname, etc. instead of url, date, content, etc.).

**Comment by Logenleedev** [comment]
> Well yeah, the object clearly gets passed through `repr()` or `str()` somewhere. You need to transform it before even feeding it into Pandas so that Pandas only ever sees objects it can deal with. But I'm not very familiar with Pandas nor do I know what data you're trying to put into it exactly, so I can't really help with that.
> 
> Generally, simply treat `User` objects like `Tweet` objects in terms of extracting data into other data structures, just with different fields (username, id, displayname, etc. instead of url, date, content, etc.).

Got it! I think I know how to solve it. Thanks!
