### ISSUE TITLE
Reddit Subreddit Search and Thread Scraping

### ISSUE THREAD

**Issue by suarezjessie** [JustAnotherArchivist/snscrape#311]
Can the library search within a specific subreddit and also scrape the threads? If yes, is there a sample code for it? Thanks!

**Comment by JustAnotherArchivist** [comment]
The Reddit scrapers return both submissions and comments by default. So when scraping an entire subreddit, it should be possible to reconstruct the full comment trees using the URLs and the comments' `parentId` if present. Scraping an individual submission or comment thread is currently not supported. The former could be added, and I've filed an issue for it (#312); the latter would be much more complicated.

For examples of the current Reddit scrapers, see #286.
