### ISSUE TITLE
How to get all queries in certain time and location

### ISSUE THREAD

**Issue by minsung-k** [JustAnotherArchivist/snscrape#313]
Hi, I want to search all tweets within a certain location and time.
Whenever I skipped the query, the error comes out.
What should I type to get all data?

I used this code.

```python3
import snscrape.modules.twitter

loc = '26.304502, -80.269455, 20km'
snscrape.modules.twitter.TwitterSearchScraper('* geocode:"{}" since:2018-02-12 until:2018-02-17'.format(loc)).get_items()
```

**Comment by JustAnotherArchivist** [comment]
What error?

This works fine for me: `snscrape --jsonl -n 1 twitter-search 'geocode:"26.304502, -80.269455, 20km" since:2018-02-12 until:2018-02-17'`

Equivalent to your code without the `*`. I assume you just forgot to include the iteration over `get_items`.

**Comment by minsung-k** [comment]
Sorry that was my mistake.
Thank you for your sincere help.
