### ISSUE TITLE
`Tweet.coordinates` is sometimes `None` on Twitter scrapes using `geocode` filter

### ISSUE THREAD

**Issue by minsung-k** [JustAnotherArchivist/snscrape#314]
Hi, before asking, I really appreciate you. It really helps me a lot.

Could you solve the problem when .coodinates is none.

When I extract tweets, the code stops when it meets none.
Maybe put some conditions works, I'm not sure...

Here is my code and the screenshot where the none data has.
Thanks in advance.

```
tweets_list = []
loc = '26.304502, -80.269455, 20km'
for i,tweet in enumerate(snscrape.modules.twitter.TwitterSearchScraper('geocode:"{}" since:2018-02-12 until:2018-02-17'.format(loc)).get_items()):
    if i>200000:
        break

    tweets_list.append([tweet.date, tweet.id, tweet.coordinates.longitude, tweet.coordinates.latitude,tweet.content, tweet.place.fullName,tweet.place.name,tweet.user.username, tweet.hashtags]) 
```

![image](https://user-images.githubusercontent.com/41711059/143115660-a3bec426-d270-429f-b937-dc126a4b272c.png)

**Comment by JustAnotherArchivist** [comment]
Unfortunately, this is impossible to fix because Twitter doesn't always return the data. For example, tweet 964644332258152450 is returned by your search, but there are no coordinates nor any other geolocation information in the response:

```
          obj['globalObjects']['tweets']['964644332258152450']['geo'] = None
          obj['globalObjects']['tweets']['964644332258152450']['coordinates'] = None
          obj['globalObjects']['tweets']['964644332258152450']['place'] = None
```
