### ISSUE TITLE
--format spacing issues

### ISSUE THREAD

**Issue by frederico-jose** [JustAnotherArchivist/snscrape#316]
"snscrape --max-results 10 --format '{url} {date}" "{content!r}' twitter-user elonmusk" 
When I run this command it returns me the following error : 
"snscrape: error: argument scraper: invalid choice: '{date}'" 

Can I not get a format containing spaces between the items ?
It works without them.

Also not all values of the dataclass tweet can be shown (i.e.: lang, user, etc..) is there a way to show them ?

**Comment by JustAnotherArchivist** [comment]
Your quoting is wrong. This works fine for me in Bash:

```
$ snscrape --format '{url} {date}' -n 1 twitter-user textfiles
https://twitter.com/textfiles/status/1463568227569745922 2021-11-24 18:00:31+00:00
```

Given the error, I suspect you're using the Windows terminal, which has different quoting rules than standard shells. Namely, as far as I know, single quotes have no special meaning in it: while `'a b'` means a single argument `a b` in normal shells, on Windows, it's the two arguments `'a` and `b'`. So I think you need to use double quotes around the `--format` argument. But I haven't used Windows in many years, so this might not be right, and I can't give other advice on that.

In general, `--format` can handle every field present in items. However, non-trivial data types are not supported very well, e.g. the `Tweet.media` attribute produces a `repr()` output, and you can't pull individual video URLs out of it with `--format`:

```
$ snscrape --format '{media}' -n 1 twitter-search 'from:textfiles filter:consumer_video'
[Video(thumbnailUrl='https://pbs.twimg.com/ext_tw_video_thumb/1447269803543121920/pu/img/lKcp1cvk_1vI5zbY.jpg', variants=[VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1447269803543121920/pu/vid/720x1280/p7qLDvRgUHTh2uRv.mp4?tag=12', bitrate=2176000), VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1447269803543121920/pu/vid/480x852/yBUqt8Qn2STc15xS.mp4?tag=12', bitrate=950000), VideoVariant(contentType='video/mp4', url='https://video.twimg.com/ext_tw_video/1447269803543121920/pu/vid/320x568/FhkiKuCY3rpwA_kD.mp4?tag=12', bitrate=632000), VideoVariant(contentType='application/x-mpegURL', url='https://video.twimg.com/ext_tw_video/1447269803543121920/pu/pl/wZLQbZye2DpZvZhj.m3u8?tag=12&container=fmp4', bitrate=None)], duration=6.25, views=1335)]
```

Likewise, while `--format` will happily print things containing spaces, you can't generally reliably parse its output. I would recommend only using it with fields that have a well-defined format (e.g. `url` never contains spaces, `date` always has one space, and `user.id` is always numeric), unless the output format doesn't really matter (like if you feed the `content` of all Tweets into some analysis tool and don't care where it comes from or which lines belong to a single tweet).
