### ISSUE TITLE
Cannot extract tweet date using snscrape

### ISSUE THREAD

**Issue by PythonNew2** [JustAnotherArchivist/snscrape#318]
Hi @JustAnotherArchivist, I am scraping historical tweets using snscrape and am struggling to extract username and tweet date. I am pretty new to Python and this is my first college project but I am stumped. I have tried multiple different ways. Any advice would be greatly appreciated! Thank you!

**Comment by JustAnotherArchivist** [comment]
Well, it depends on how you're using snscrape.

If you use the CLI, I'd recommend the `--jsonl` option. Then you have one JSON object for each tweet and can do with those whatever you like (they become standard dictionaries when parsed again in Python). Alternatively, you could use the `--format` option, e.g. `--format '{url} {user.username} {date}'`; however, this breaks down quickly if you need to include any fields that can contain a variable amount of whitespace (e.g. `content`).

If you use the (undocumented) Python layer, the `get_items()` generator produces `snscrape.modules.twitter.Tweet` objects, and you can directly access the relevant attributes there:

```python3
import snscrape.modules.twitter

scraper = snscrape.modules.twitter.TwitterUserScraper('textfiles')
for tweet in scraper.get_items():
	print(tweet.user.username)
	print(tweet.date)
```
