### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by DV777** [JustAnotherArchivist/snscrape#321]
Hello,

Firstly, thanks a lot for creating and constantly maintaining this package !

I am stuck with something most will find obvious, but I am a beginner in Python so I do not know exactly where to look for the following information:
Could I get the latest updates on the attributes that are usable on python ?
So far I have that list but I see some of them are outdated:
Attributes: url, date, content, renderedContent, id, user, outlinks, tcooutlinks, replyCount, retweetCount, likeCount, quoteCount, conversationId, lang, source, media, retweetedTweet, quotedTweet, mentionedUsers

For example: "user" became "username"

Thanks for your help !

**Comment by DV777** [comment]
For example, when trying to include replyCount I get:
`AttributeError: 'Tweet' object has no attribute 'replycount'`

**Comment by TheTechRobo** [comment]
That part of snscrape is currently undocumented.

However, I see that `username = snscrape.base._DeprecatedProperty('username', lambda self: self.user.username, 'user.username')` here: https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/modules/twitter.py.

So username is a deprecated property? I'm a bit confused.

**Comment by DV777** [comment]
Well...
When using this simple code:
```
import snscrape.modules.twitter as sntwitter
import pandas
# Creating list to append tweet data 
tweets_list1 = []
# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:###').get_items()): #declare a username 
    if i>1000: #number of tweets you want to scrape
        break
    tweets_list1.append([tweet.url, tweet.date, tweet.content, tweet.id, tweet.username, tweet.outlinks, tweet.tcooutlinks, tweet.replyCount, tweet.retweetCount, tweet.likeCount, tweet.quoteCount, tweet.onversationId, tweet.lang, tweet.source, tweet.media, tweet.retweetedTweet, tweet.quotedTweet, tweet.mentionedUsers]) #declare the attributes to be returned
# Creating a dataframe from the tweets list above 
tweets_df1 = pd.DataFrame(tweets_list1)
```
I get Attribute Errors for many of these attributes...

**Comment by JustAnotherArchivist** [comment]
This part is indeed undocumented currently. Please refer to the module code for the available attributes for the time being. The item dataclasses are always at the very top there.

> So username is a deprecated property? I'm a bit confused.

Correct, `Tweet.username` is deprecated. It's how it was implemented originally and only there for backward compatibility. `Tweet.user.username` should be used instead now.

> I get Attribute Errors for many of these attributes...

Apart from the `onversationId` typo, this works fine with the current dev code. Are you using the release version? Lots of attributes have changed since then.

**Comment by DV777** [comment]
> 
> > I get Attribute Errors for many of these attributes...
> 
> Apart from the `onversationId` typo, this works fine with the current dev code. Are you using the release version? Lots of attributes have changed since then.

Yes , I cannot install git on the server of my university :/ so no dev versions,  I need to use the released version only...
Is it possible to have the list of attributes from this version ? (and where to find them please ?)

**Comment by DV777** [comment]
> This part is indeed undocumented currently. Please refer to the module code for the available attributes for the time being. The item dataclasses are always at the very top there.
> 
> > So username is a deprecated property? I'm a bit confused.
> 
> Correct, `Tweet.username` is deprecated. It's how it was implemented originally and only there for backward compatibility. `Tweet.user.username` should be used instead now.
> 
> > I get Attribute Errors for many of these attributes...
> 
> Apart from the `onversationId` typo, this works fine with the current dev code. Are you using the release version? Lots of attributes have changed since then.

Actually this gave me the argument to get some rights and install git to be able to get the dev version. With this version attributes are working (obviously!). Thanks for your help !

**Comment by JustAnotherArchivist** [comment]
Good to hear.

For future reference, to get the fields of a particular version: the releases are all tagged in the repository. For example, here's the Twitter module as of the most recent release: https://github.com/JustAnotherArchivist/snscrape/blob/v0.3.4/snscrape/modules/twitter.py

**Comment by DV777** [comment]
> Good to hear.
> 
> For future reference, to get the fields of a particular version: the releases are all tagged in the repository. For example, here's the Twitter module as of the most recent release: https://github.com/JustAnotherArchivist/snscrape/blob/v0.3.4/snscrape/modules/twitter.py

Thanks a lot !!

**Comment by TheTechRobo** [comment]
By the way, you can install the dev version without Git!

```
python3 -m pip install --upgrade https://github.com/JustAnotherArchivist/snscrape/archive/refs/heads/master.zip
```
