### ISSUE TITLE
import snscrape.modules.twitter as sntwitter --> TypeError: Multiple inheritance with NamedTuple is not supported

### ISSUE THREAD

**Issue by valo83** [JustAnotherArchivist/snscrape#323]
Goodmorning ,

for my thesis work I was retrieving data from twitter via Snscrape.
With the online guides, everything is fine and everything is fine.
New PC, download packages, download python 3.10 ....

now writing:

import snscrape.modules.twitter as sntwitter

-> TypeError: Multiple inheritance with NamedTuple is not supported

Could you help me?

Thanks a lot

<img width="1130" alt="Schermata 2021-12-07 alle 09 38 33" src="https://user-images.githubusercontent.com/32481886/145006512-8f5dba40-36bd-4f0d-ba08-4de9fc121342.png">

**Comment by JustAnotherArchivist** [comment]
Duplicate of #111
