### ISSUE TITLE
snscrape \\ twitter \\ Variable in query search

### ISSUE THREAD

**Issue by valo83** [JustAnotherArchivist/snscrape#330]
Hey,

just a not-at-all-pro question:

`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('COVID Vaccine since:2021-01-01 until:2021-05-31').get_items()):`

How would be possible to put a variable (instead of "Covid Vaccine") that is linked to a list in a txt file?
In a txt I'd like to list down all the hashtag, keywords, ... I need to search.

Thanks in advance

Valo

**Comment by TheTechRobo** [comment]
If I understand what you mean: Something like this should work.

```
with open("myfile.txt") as file: #opens myfile.txt
    keyword = file.read().strip("\n") # reads myfile.txt and removes the trailing newline

# f-strings are new in python 3.7
# f"{hi}hi" is equivelent to hi + "hi" or "%shi" % hi
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(f'{keyword} since:2021-01-01 until:2021-05-31').get_items()):
```

**Comment by valo83** [comment]
Maybe I was wrong with coding....
But for cicle for the different words not working, but since 10 mins 

snscrape.base.ScraperException: Unable to find guest token

<img width="1728" alt="Schermata 2021-12-15 alle 18 30 25" src="https://user-images.githubusercontent.com/32481886/146235886-01ee147a-9d50-4980-8cc8-ae1793cce13c.png">
 
is it correct the for cicle?
here the txt file. Twitter with these word are present on Twitter.

<img width="1728" alt="Schermata 2021-12-15 alle 18 33 44" src="https://user-images.githubusercontent.com/32481886/146236348-5650053a-fa6b-411c-b561-352e9aa46ce6.png">

**Comment by TheTechRobo** [comment]
see #326

**Comment by valo83** [comment]
After some minutes it works again ... but no result for nested for loop....
