### ISSUE TITLE
TwitterTrendsScraper Location Parameter

### ISSUE THREAD

**Issue by yemregundogmus** [JustAnotherArchivist/snscrape#331]
Hello @JustAnotherArchivist, I am amazed by the work you do. I had a question for you.

In TwitterTrendsScraper, the computer you request or the proxy you use shows the trends of the country in which it is located. Is there any chance we can somehow give the country as a parameter?

``` python
import snscrape.modules.twitter as sntwitter

scraper = sntwitter.TwitterTrendsScraper()
for trend in scraper.get_items():
    print(trend.name)
```

Have a nice day!

**Comment by JustAnotherArchivist** [comment]
See https://github.com/JustAnotherArchivist/snscrape/issues/308#issuecomment-969218445

**Comment by yemregundogmus** [comment]
Thank you!
