### ISSUE TITLE
Scraping Instagram by hashtag, location, and date range

### ISSUE THREAD

**Issue by valo83** [JustAnotherArchivist/snscrape#333]
This next code part would be the Instagram version of the code I found here:
[https://medium.com/dataseries/how-to-scrape-millions-of-tweets-using-snscrape-195ee3594721](
https://medium.com/dataseries/how-to-scrape-millions-of-tweets-using-snscrape-195ee3594721)

The code is: 

```python3
import snscrape.modules.instagram as sntig
import pandas as pd
import re

# Creating list to append tweet data near:"Turin" within:10km
tweets_list1 = []


# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(sntig.InstagramHashtagScraper(
        '#NewGreenDeal near:"Turin" within:10km since:2021-07-01 until:2021-12-15').get_items()):  # declare a username
    if i > 10:  # number of tweets you want to scrape
        break
    tweets_list1.append(
        [id,item.date,item.cleanUrl, item.dirtyUrl, item.content, item.thumbnailUrl, item.displayUrl, item.username ,item.commentsDisabled, item.likes, item.comments])  # declare the attributes to be returned

# Creating a dataframe from the tweets list above
tweets_df01 = pd.DataFrame(tweets_list1,
                           columns=['ID','Date','Url', 'dirtyUrl', 'Text', 'thumbnailUrl','displayUrl' ,'username', 'commentsDisabled', 'likes', 'Comments'])
tweets_df02 = tweets_df01['Device'].apply(lambda s: re.sub('<[^\>]*>', '', s))

tweets_df01 = tweets_df01.drop(['Device'], axis=1)
tweets_df01 = tweets_df01.merge(tweets_df02, left_index=True, right_index=True)

tweets_df01.to_csv('Instagram_test01.csv')
```

Can someone help me to fix?
I need the possibility to search Hashtag or Keyword **PLUS** the location (ex. Turin).

Thanks in advance

valo

**Comment by JustAnotherArchivist** [comment]
Instagram is not Twitter.

Instagram doesn't have a flexible search like Twitter does. You will have to scrape all posts with a hashtag or all posts from a location and then filter it afterwards.

**Comment by valo83** [comment]
> Instagram is not Twitter.
> 
> Instagram doesn't have a flexible search like Twitter does. You will have to scrape all posts with a hashtag or all posts from a location and then filter it afterwards.

is it possible to filter them by date (ex. from May 01 2021 till December 15 2021) ?

**Comment by JustAnotherArchivist** [comment]
No. I think they are always returned in reverse-chronological order (i.e. newest to oldest) though, so you can iterate until you see a post that's older than what you're interested in.

**Comment by valo83** [comment]
it's a long iterations.
I've to try 185+ hashtags and period of analysis should be from July 1st to Decembre 15th.....

**Comment by JustAnotherArchivist** [comment]
Well, good luck then. There's nothing snscrape can do about this because Instagram simply does not have any filters like that (at least not without authentication).

**Comment by JustAnotherArchivist** [comment]
Something like this should work for only fetching posts newer than a certain date (not tested):

```python3
import datetime
import snscrape.modules.instagram

cutoffDate = datetime.date(2021, 7, 1)
for i, post in enumerate(snscrape.modules.instagram.InstagramHashtagScraper('test')):
	if post.date.date() < cutoffDate:
		break
	# add to list or whatever
```

In practice, you'll want to scrape a location and then filter for the hashtag from the post's content because the scraper does not collect a post's location.

(Also, note that the Instagram scraper is essentially unsupported these days. Instagram's request rate limits are so ridiculous that developing the scraper is basically impossible due to constantly having to rotate IPs/proxies. You will likely run into that as well with your project.)

**Comment by valo83** [comment]
Thanks for the suggestion / help.
here the error: 

`    for i, post in enumerate(snscrape.modules.instagram.InstagramHashtagScraper('test')):
TypeError: __init__() missing 1 required positional argument: 'name'`

**Comment by JustAnotherArchivist** [comment]
Oh yeah, I forgot about that. Use `InstagramHashtagScraper('Hashtag', 'test')` instead. (This will change soon.)

**Comment by valo83** [comment]
Thanks 👍 
I'll try asap
