### ISSUE TITLE
After a day or trying to get data \\ .... HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/  During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by valo83** [JustAnotherArchivist/snscrape#334]
![immagine](https://user-images.githubusercontent.com/32481886/147293963-7454d1bc-fed9-4a91-9c7c-fa89024c9bd5.png)

Anyone can tell me how to solve?
or it's just a matter of too many requests per day, isn't it?

Thanks

**Comment by JustAnotherArchivist** [comment]
That isn't snscrape.
