### ISSUE TITLE
tweet.content is not parseable if it is not in english. 

### ISSUE THREAD

**Issue by tsaaii** [JustAnotherArchivist/snscrape#336]
I am trying to run this part where my twitter user tweets non english content. I am unable to see tweet.content despite it being a string and I tried encoding it which shows all the English characters but leaves out the rest. The output I see is bytes. How do I fix this? 
```
import snscrape.modules.twitter as sntwitter
import pandas as pd
# Setting variables to be used below
maxTweets = 100
# Creating list to append tweet data to
tweets_list1 = []
# Using TwitterSearchScraper to scrape data 
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:eenadulivenews').get_items()):
    if i>maxTweets:
        break
    print(tweet.content.encode('utf-8'))
```

**Comment by JustAnotherArchivist** [comment]
> The output I see is bytes.

Yes, `str.encode` in Python returns `bytes`.

A simple `print(tweet.content)` works fine to get UTF-8 output.

**Comment by tsaaii** [comment]
Interesting, I can neither see output on cmd nor when I save it to text file if I use print(tweet.content)

I get this error.

```    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 17-20: character maps to <undefined>```

**Comment by JustAnotherArchivist** [comment]
#122
