### ISSUE TITLE
Implement disk caching of tokens on the CLI

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#339]
The Twitter scraper reuses tokens on multiple runs within the same process (cf. #326). A similar mechanism is needed for the CLI. Specifically, the token should be stored on disk and read again on demand.

The hardest part is cross-platform support with concurrent processes. I simply don't have time to test and debug all the various possible setups (Windows, NFS, etc.). My plan for now is to simply use `filelock`. If anyone has any thoughts on this, I'd like to hear them.

**Comment by mgrandi** [comment]
The filelock library seems to cover the bases well enough, I've seen it used in other projects
