### ISSUE TITLE
Add a --fast option that uses string or regex extraction instead of HTML parsing

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#34]
I haven't done any profiling, but it is likely that the parsing takes up a significant fraction of the total runtime. String/regex extraction is more sensitive to subtle changes in the markup but much more efficient than full parsing. A `--fast` option (or similar) that enables such processing instead of the full parser could be useful in particular for large scrapes.

(Although I've had this idea before, credit goes to /u/dmn002 for bringing it to my attention again.)

**Comment by jodizzle** [comment]
Another possibility would be to try an HTML parser other than Beautiful Soup.  Would need testing, but [selectolax](https://github.com/rushter/selectolax) claims significantly higher speeds.

**Comment by JustAnotherArchivist** [comment]
Because many modules don't even use HTML parsing these days (and rather receive JSON data), the effect of this would be rather limited, and it would create an additional maintenance burden, so I'm closing this.
