### ISSUE TITLE
In the Twitter scraper, what's the difference between a user and a user PROFILE?

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#342]
I saw the user-profile scraper mentioned in another issue, and it appears it's still supported, but what does it do different?

**Comment by JustAnotherArchivist** [comment]
`twitter-user` is a shorthand for a `from:username` search, which returns all original tweets and replies by the user without limits but does not include retweets.

`twitter-profile` collects what's shown on the profile page. This returns the ~3200 most recent tweets by the user, including replies and retweets.

Cf. #5 #83 #85

**Comment by TheTechRobo** [comment]
Thank you!
