### ISSUE TITLE
scrape facebook

### ISSUE THREAD

**Issue by JJery-web** [JustAnotherArchivist/snscrape#346]
So sorry that I am a beginner in learning python. I don't know how to use snscrape to scrape the facebook such as scraping posts.

Who can help me please.

**Comment by TheTechRobo** [comment]
Do you mean using it as the module?

Keep in mind that the Facebook and Instagram scrapers are pretty much unsupported because of how fast they start requiring you to log in.

**Comment by JJery-web** [comment]
> Do you mean using it as the module?
> 
> Keep in mind that the Facebook and Instagram scrapers are pretty much unsupported because of how fast they start requiring you to log in.

Yes. I want to scrape some data from Facebook. Actually I view there is a function about facebook in snscrpe. So do you know how to scrape facebook data?

And I use snscrape.modules.twitter, the error is:

Error retrieving https://twitter.com/search?f=live&lang=en&q=from%3Ajack&src=spelling_expansion_revert_click: ProxyError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=from%3Ajack&src=spelling_expansion_revert_click (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out')))"))
4 requests to https://twitter.com/search?f=live&lang=en&q=from%3Ajack&src=spelling_expansion_revert_click failed, giving up.
Traceback (most recent call last):
  File "G:\facebook\0105test.py", line 9, in <module>
    for i, tweet in enumerate(sntwitter.TwitterSearchScraper('from:jack').get_items()):
  File "D:\Anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 595, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "D:\Anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 289, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "D:\Anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 258, in _get_api_data
    self._ensure_guest_token()
  File "D:\Anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 229, in _ensure_guest_token
    r = self._get(self._baseUrl if url is None else url, headers = {'User-Agent': self._userAgent}, responseOkCallback = self._check_guest_token_response)
  File "D:\Anaconda3\lib\site-packages\snscrape\base.py", line 212, in _get
    return self._request('GET', *args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\snscrape\base.py", line 208, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://twitter.com/search?f=live&lang=en&q=from%3Ajack&src=spelling_expansion_revert_click failed, giving up.

**Comment by TheTechRobo** [comment]
Well, the snscrape.modules.twitter is for Twitter, not Facebook.

I see that you're getting a proxy error. Do you have a proxy or something set up?

**Comment by JJery-web** [comment]
> Well, the snscrape.modules.twitter is for Twitter, not Facebook.
> 
> I see that you're getting a proxy error. Do you have a proxy or something set up?

Maybe not this reason. I just use Vpn. I can visit the twitter website but I can run the code. 
It is strange that I can use this modules two weeks ago. But now I can not use it for scraping twiiter. Is it still work?

**Comment by JJery-web** [comment]
> Well, the snscrape.modules.twitter is for Twitter, not Facebook.
> 
> I see that you're getting a proxy error. Do you have a proxy or something set up?

So is the snscrape still works for **facebook** scraping please?

**Comment by JustAnotherArchivist** [comment]
Yes, it works fine for pages in the old design, at least until your IP inevitably gets banned after a few requests. Pages in the new design produce zero results because support for that is not implemented yet.

**Comment by JJery-web** [comment]
> Yes, it works fine for pages in the old design, at least until your IP inevitably gets banned after a few requests. Pages in the new design produce zero results because support for that is not implemented yet.

Thanks. Very expected for the function of snscrape further.
