### ISSUE TITLE
snscrape.base.ScraperException: Unable to find guest token

### ISSUE THREAD

**Issue by JJery-web** [JustAnotherArchivist/snscrape#347]
Hi, I meet a difficult that snscrape.base.ScraperException: Unable to find guest token.
Is it stiil works?

**Comment by JustAnotherArchivist** [comment]
Yes, the latest version of snscrape works fine. Please upgrade your installation.

**Comment by JJery-web** [comment]
> Yes, the latest version of snscrape works fine. Please upgrade your installation.

The latest version is 0.3.4 right? Maybe I use python3.7 so I can not scrape?

**Comment by JustAnotherArchivist** [comment]
The latest version is 0.4.3, released a couple hours ago, but it requires Python 3.8 or higher.

**Comment by JJery-web** [comment]
> The latest version is 0.4.3, released a couple hours ago, but it requires Python 3.8 or higher.

 I see. But I use “pip install snscrape =0.4.3”, it shows that 
Could not find a version that satisfies the requirement snscra
pe==0.4.3 (from versions: 0.1.3, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3
.3, 0.3.4)
No matching distribution found for snscrape==0.4.3

---------
How to install it please?

**Comment by JustAnotherArchivist** [comment]
pip filters out and refuses to install versions that are incompatible with your Python version. You first need to install Python 3.8 or higher. I recommend pyenv for this if you don't want to or can't upgrade the system version of Python.

**Comment by JJery-web** [comment]
> I recommend pyenv for this if you don't want to or can't upgrade the system version of Python.

Thank you. I will try again.

**Comment by JJery-web** [comment]
> pip filters out and refuses to install versions that are incompatible with your Python version. You first need to install Python 3.8 or higher. I recommend pyenv for this if you don't want to or can't upgrade the system version of Python.

Thank you so much. I use it in python3.9 and it works fine. 
I also have a question. What is the reasonable frequency of scraping twitter posts that you suggest please. I am worried about it is banned or other situation.
(Due to the need for academic reaserach, maybe need to scrape 7000 users posts.)

**Comment by valo83** [comment]
Hey, 
for me it's not possible to update to 0.4.3, not working with python 3.8 or python 3.9 with version 0.3.4.
I'm using PyCharm.
How to solve it? how to force update with PyCharm?

**Comment by JJery-web** [comment]
> Hey, for me it's not possible to update to 0.4.3, not working with python 3.8 or python 3.9 with version 0.3.4. I'm using PyCharm. How to solve it? how to force update with PyCharm?

I can not update 0.4.3 version under the version of python3.7. So I update the python to 3.8 and I refresh the environment, then the 0.4.3 version of snscrape can be downloaded. If you can not download, please check your python environment or you can directly download the file on github of snscrape to forcelly update the local file I think.

**Comment by JustAnotherArchivist** [comment]
> What is the reasonable frequency of scraping twitter posts that you suggest please.

I haven't really found limits so far. Apparently many short scrapes triggered bans in the past (#326), but that's fixed in the current version of snscrape.

**Comment by JJery-web** [comment]
> > What is the reasonable frequency of scraping twitter posts that you suggest please.
> 
> I haven't really found limits so far. Apparently many short scrapes triggered bans in the past (#326), but that's fixed in the current version of snscrape.

Yes. I have used for several hours. It is really so stable. Thanks so much.

**Comment by valo83** [comment]
Update all the packaging 
working win Python 3.9
Thanks

**Comment by JustAnotherArchivist** [comment]
For the record, I filed an issue for pip's UX shortcomings earlier this week: https://github.com/pypa/pip/issues/10784
