### ISSUE TITLE
TwitterProfileScraper: Solution to get the user description only once (not for every tweet)

### ISSUE THREAD

**Issue by heyitsjuju** [JustAnotherArchivist/snscrape#348]
Hi, 
I want to scrape the user.description for a list of usernames. Currently I'm testing my code for one username and as a result get a list where the user.description is scraped for each tweet. Say a user tweeted 278 times, the list repeats the user.description 278 times.
Is there a way to get the user.description just once? I know I would have to somehow write the code without the for-loop, but I tried and didn't get it to work without the loop. I appreciate the help very much as I am still a beginner in coding :)

**Current Code:**
```
import snscrape.modules.twitter as sntwitter
import pandas as pd

list = []

scraper = sntwitter.TwitterProfileScraper('JeffBezos', False)
for tweet in scraper.get_items():
    list.append([tweet.user.description])

tweets_df = pd.DataFrame(list, columns=['desc'])

print(tweets_df)
```

**Output:**
```
                                                 desc
0    Amazon. Blue Origin. Washington Post. Bezos Ea...
1    Amazon. Blue Origin. Washington Post. Bezos Ea...
2    Amazon. Blue Origin. Washington Post. Bezos Ea...
3    Amazon. Blue Origin. Washington Post. Bezos Ea...
4    Amazon. Blue Origin. Washington Post. Bezos Ea...
..                                                 ...
273  Amazon. Blue Origin. Washington Post. Bezos Ea...
274  Amazon. Blue Origin. Washington Post. Bezos Ea...
275  Amazon. Blue Origin. Washington Post. Bezos Ea...
276  Amazon. Blue Origin. Washington Post. Bezos Ea...
277  Amazon. Blue Origin. Washington Post. Bezos Ea...

[278 rows x 1 columns]

Process finished with exit code 0
```

**Comment by JustAnotherArchivist** [comment]
Yes, this is possible. The silly way would be to break the loop after the first tweet. However, that won't work for accounts that have never tweeted, are protected, or can't be found through the search. What you want is the `entity` property of the scraper. This resolves to a `snscrape.modules.twitter.User` object when using the `TwitterUserScraper` or `TwitterProfileScraper`.

```python3
import snscrape.modules.twitter

scraper = snscrape.modules.twitter.TwitterUserScraper('textfiles')
if scraper.entity:
	print(scraper.entity.description)
```

**Comment by JJery-web** [comment]
> Hi, I want to scrape the user.description for a list of usernames. Currently I'm testing my code for one username and as a result get a list where the user.description is scraped for each tweet. Say a user tweeted 278 times, the list repeats the user.description 278 times. Is there a way to get the user.description just once? I know I would have to somehow write the code without the for-loop, but I tried and didn't get it to work without the loop. I appreciate the help very much as I am still a beginner in coding :)
> 
> **Current Code:**
> 
> ```
> import snscrape.modules.twitter as sntwitter
> import pandas as pd
> 
> list = []
> 
> scraper = sntwitter.TwitterProfileScraper('JeffBezos', False)
> for tweet in scraper.get_items():
>     list.append([tweet.user.description])
> 
> tweets_df = pd.DataFrame(list, columns=['desc'])
> 
> print(tweets_df)
> ```
> 
> **Output:**
> 
> ```
>                                                  desc
> 0    Amazon. Blue Origin. Washington Post. Bezos Ea...
> 1    Amazon. Blue Origin. Washington Post. Bezos Ea...
> 2    Amazon. Blue Origin. Washington Post. Bezos Ea...
> 3    Amazon. Blue Origin. Washington Post. Bezos Ea...
> 4    Amazon. Blue Origin. Washington Post. Bezos Ea...
> ..                                                 ...
> 273  Amazon. Blue Origin. Washington Post. Bezos Ea...
> 274  Amazon. Blue Origin. Washington Post. Bezos Ea...
> 275  Amazon. Blue Origin. Washington Post. Bezos Ea...
> 276  Amazon. Blue Origin. Washington Post. Bezos Ea...
> 277  Amazon. Blue Origin. Washington Post. Bezos Ea...
> 
> [278 rows x 1 columns]
> 
> Process finished with exit code 0
> ```

Use _try, except and break_ to just scrape the valid user is ok I think.

**Comment by heyitsjuju** [comment]
> Yes, this is possible. The silly way would be to break the loop after the first tweet. However, that won't work for accounts that have never tweeted, are protected, or can't be found through the search. What you want is the `entity` property of the scraper. This resolves to a `snscrape.modules.twitter.User` object when using the `TwitterUserScraper` or `TwitterProfileScraper`.
> 
> ```python
> import snscrape.modules.twitter
> 
> scraper = snscrape.modules.twitter.TwitterUserScraper('textfiles')
> if scraper.entity:
> 	print(scraper.entity.description)
> ```

Awesome!! That solution works perfectly. Thank you so much! :)

**Comment by heyitsjuju** [comment]
> > Hi, I want to scrape the user.description for a list of usernames. Currently I'm testing my code for one username and as a result get a list where the user.description is scraped for each tweet. Say a user tweeted 278 times, the list repeats the user.description 278 times. Is there a way to get the user.description just once? I know I would have to somehow write the code without the for-loop, but I tried and didn't get it to work without the loop. I appreciate the help very much as I am still a beginner in coding :)
> > **Current Code:**
> > ```
> > import snscrape.modules.twitter as sntwitter
> > import pandas as pd
> > 
> > list = []
> > 
> > scraper = sntwitter.TwitterProfileScraper('JeffBezos', False)
> > for tweet in scraper.get_items():
> >     list.append([tweet.user.description])
> > 
> > tweets_df = pd.DataFrame(list, columns=['desc'])
> > 
> > print(tweets_df)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Output:**
> > ```
> >                                                  desc
> > 0    Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 1    Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 2    Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 3    Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 4    Amazon. Blue Origin. Washington Post. Bezos Ea...
> > ..                                                 ...
> > 273  Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 274  Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 275  Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 276  Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 277  Amazon. Blue Origin. Washington Post. Bezos Ea...
> > 
> > [278 rows x 1 columns]
> > 
> > Process finished with exit code 0
> > ```
> 
> Use _try, except and break_ to just scrape the valid user is ok I think.

Oh man, sometimes it's really the most obvious thing one doesn't think about. Thanks for mentioning it :)) Using _break_ in the loop also works nicely!
