### ISSUE TITLE
Error: Unable to find guest token

### ISSUE THREAD

**Issue by Bartbeckers** [JustAnotherArchivist/snscrape#351]
Hi all,

**Using the code below I get the following error:** 
Error retrieving https://twitter.com/search?f=live&lang=en&q=COVID+Vaccine+since%3A2021-01-01+until%3A2021-05-31&src=spelling_expansion_revert_click: unable to find guest token
4 requests to https://twitter.com/search?f=live&lang=en&q=COVID+Vaccine+since%3A2021-01-01+until%3A2021-05-31&src=spelling_expansion_revert_click failed, giving up.

**Code example**
```import snscrape.modules.twitter as sntwitter
import pandas

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('COVID Vaccine since:2021-01-01 until:2021-05-31').get_items()):
    if i>5000:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
    
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

**Comment by DV777** [comment]
Same problem here.
A code that was working before new year's eve is not working anymore.

```
import pandas as pd
import nest_asyncio
nest_asyncio.apply()
import os
import time
from datetime import datetime
import snscrape
import snscrape.modules.twitter as sntwitter
import subprocess

low_memory = False
os.chdir('C:\\Users\\Timelines')
list_test = pd.read_csv('list_test.csv')
error_accounts = ['error accounts']

for i in tqdm(range(len(list_test))):
    try:
        username = list_test.loc[i, 'username']
        tweet_count = 100000000000
        os.system("snscrape --jsonl --max-results {} twitter-search 'from:{}'> user-tweets.json".format(tweet_count, username))
        tweets_df = pd.read_json('user-tweets.json', lines=True)
        tweets_df.to_csv(list_test.username[i] + '.csv', sep=',', index=False, encoding='utf-8-sig')
    except (RuntimeError, TypeError, NameError, ZeroDivisionError):
        error_accounts.append(list_test.loc[i, 'username'])
        pass
```
Did something happen ? A twitter update perhaps ?

**Comment by TheTechRobo** [comment]
Please please PLEASE try updating your snscrape BEFORE filing an issue. `pip install --upgrade snscrape`

**Comment by JustAnotherArchivist** [comment]
#347

**Comment by numerosos** [comment]
Hi! updated using `pip install --upgrade snscrape` on my local machine, but I keep getting `ScraperException: Unable to find guest token`

Code example:

`# Creating list to append tweet data 
tweets_list1 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('since:2018-01-10 ("siento" OR "tengo") AND ("gripe") AND ("malestar de" OR "sintomas de")').get_items()): 
    if i>100000: #number of tweets you want to scrape
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content]) #declare the attributes to be returned
    
# Creating a dataframe from the tweets list above 
tweets_df1 = pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text'])
tweets_df1`

**Comment by JustAnotherArchivist** [comment]
@numerosos Then you didn't actually upgrade snscrape. Note that you need Python 3.8 or higher, otherwise pip won't install the new version since it's incompatible with 3.7.
