### ISSUE TITLE
Need Guideline for Scraping Telegram data

### ISSUE THREAD

**Issue by sufyanhamid** [JustAnotherArchivist/snscrape#352]
Hi @JustAnotherArchivist ,

Hope you are doing well, I'm facing this issue while scraping the telegram channel data. Plz have a look at that and guide me on how to do it!

**The little part of code**
```python3
import snscrape.modules.telegram as sntwitter
import csv

for i, mydata in enumerate(sntwitter.TelegramChannelScraper('https://t.me/CryptoNewsSource').get_items()):
    print(mydata.username, mydata.members)
```

**The output of above program**
No public post list for this user

**While trying this**
snscrape --jsonl --progress --max-results 50 telegram-channel "https://t.me/CryptoNewsSource" > mydata.json

**The output is**
['2022-01-07 20:14:53.408  WARNING  snscrape.modules.telegram  No public post list for this user',
 'Finished, 0 results']

Kindly help me, how to do this in the right way!
Best Regards!

**Comment by JustAnotherArchivist** [comment]
The `telegram-channel` scraper expects a username, not a URL:

     snscrape --jsonl --progress --max-results 50 telegram-channel CryptoNewsSource > mydata.json

**Comment by sufyanhamid** [comment]
Got it, thanks :)
