### ISSUE TITLE
Is the Twitter search scraper case sensitive?

### ISSUE THREAD

**Issue by KimShan1** [JustAnotherArchivist/snscrape#353]
Hi I'm trying to extract all tweets containing the word 'covid'. I was wondering if the search needs to include: Covid, COVID, covid or is it enough with covid? 

Thanks!

**Comment by JustAnotherArchivist** [comment]
snscrape itself doesn't do any case treatment. It simply passes your query to Twitter and returns all the results.

Twitter's search is not case-sensitive and can't be made case-sensitive either to my knowledge. It has extra (undocumented, I believe) treatment for special characters though. For example, a search for 'cövid' also returns tweets with 'cøvid', 'cövïd', and many more but *not* with 'covid' from what I've seen.
