### ISSUE TITLE
Inconsistent style in Weibo vs Twitter user scrapers

### ISSUE THREAD

**Issue by lahdjirayhan** [JustAnotherArchivist/snscrape#354]
https://github.com/JustAnotherArchivist/snscrape/blob/93e62744d779a7989604410ecf204abd4ac38b68/snscrape/modules/weibo.py#L50-L58

https://github.com/JustAnotherArchivist/snscrape/blob/93e62744d779a7989604410ecf204abd4ac38b68/snscrape/modules/twitter.py#L694-L699

As far as I understand, both appear to have similar requisites:
- Can provide username or user ID
- Only providing one is necessary (or allowed?)

Should this be refactored to be consistent? Or is there an intentional design reason behind this?

**Comment by JustAnotherArchivist** [comment]
Yeah, this is correct. Definitely not an intentional design choice. And neither implementation is great, honestly. I've been meaning to refactor the Twitter one for a while but haven't really thought about how to do this properly yet. Thanks for bringing it to my attention!
