### ISSUE TITLE
CLI-related scraper methods shouldn't be public

### ISSUE THREAD

**Issue by lahdjirayhan** [JustAnotherArchivist/snscrape#355]
e.g. `cli_setup_parser`, `cli_from_args`

These methods appear to only prepare the classes for CLI use. It is unlikely that non-CLI users will use them or find them relevant.

**Comment by JustAnotherArchivist** [comment]
I was thinking about this when I renamed them to have the `cli_` prefix, but yeah, you're right, this should probably all just be private.
If there is ever someone who wants to implement a new scraper, that can be documented separately. That would be needed anyway in that case.
