### ISSUE TITLE
[Feature] is there a way to trace back first message or image?

### ISSUE THREAD

**Issue by tsaaii** [JustAnotherArchivist/snscrape#360]
I am looking to see if there is a way to backtrack a message or an image to a specific user when the message or image was quoted, retweeted a lot.

**Comment by JustAnotherArchivist** [comment]
Message: You can search for the text in double quotes (e.g. in Bash: `snscrape twitter-search '"some text"'`, or via Python: `TwitterSearchScraper('"some text"')`) and then take the last (= oldest) result. If the original tweet is still up, that should be it. Remember that retweets aren't included in search results.

Images: I'm not aware of a method to search by image on Twitter.

**Comment by tsaaii** [comment]
Thank you. I will try this
