### ISSUE TITLE
Twitter token

### ISSUE THREAD

**Issue by SimonSadecky** [JustAnotherArchivist/snscrape#362]
Hello, 
I was wondering to what extent am I allowed to use your library for twitter profile scraping. Therefore will the token be blocked in the case I exceed a given load since I see a hard-coded token in the twitter module source code?

**Comment by JustAnotherArchivist** [comment]
The token in the code is the one of the Twitter web app. You'll get your IP banned long before you manage to get that token blocked. :-)
