### ISSUE TITLE
'snscrape' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by HelloBob10** [JustAnotherArchivist/snscrape#364]
I'm trying to use snscrape from cli and I keep getting this error after completing the install steps on https://medium.com/dataseries/how-to-scrape-millions-of-tweets-using-snscrape-195ee3594721

Everything seemed like it installed correctly...any ideas? I am pretty new to this (sorry)

**Comment by JustAnotherArchivist** [comment]
I'm afraid I can't provide help for Windows installation issues; I haven't used Windows in a decade... Maybe someone else has advice on that.

**Comment by TheTechRobo** [comment]
I'm not good with Windows either, but maybe your PATH variable wasn't set?

Does running pip itself work?

**Comment by HelloBob10** [comment]
yeah pip itself works, and the snscrape installation seemed to work too...really puzzling. 

If anyone is familiar Windows and is willing to take a look that would be great - I'd be happy to pay for the time.

`C:\Users\jak33>pip3 install snscrape
Requirement already satisfied: snscrape in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (0.4.3.20220107.dev8+g7f88678)
Requirement already satisfied: requests[socks] in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from snscrape) (2.27.1)
Requirement already satisfied: lxml in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from snscrape) (4.7.1)
Requirement already satisfied: beautifulsoup4 in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from snscrape) (4.10.0)
Requirement already satisfied: filelock in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from snscrape) (3.4.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from beautifulsoup4->snscrape) (2.3.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests[socks]->snscrape) (2.0.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests[socks]->snscrape) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests[socks]->snscrape) (1.26.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests[socks]->snscrape) (3.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests[socks]->snscrape) (1.7.1)`

These entries are in PATH:

`c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\
c:\users\jak33\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\Scripts`

**Comment by TheTechRobo** [comment]
have you tried reloading cmd or something?

also, if you have WSL, that might work better (since it's linux we'll at least be able to provide better help)

**Comment by marymlucas** [comment]
I don't know if this will be helpful but if you have Anaconda or Miniconda installed, try running the snscrape command from the Anaconda Powershell Prompt. That works for me. I tried adding it to my path and that never worked so I just run it from the Anaconda prompt and it works great.

**Comment by HelloBob10** [comment]
Thanks for the suggestions, I downloaded anaconda and miniconda (same result for me), then installed windows subsystem and the same unrecognized cmd was returned, and then tried again on cmd line and it worked? I've no idea why it's working now which is mildly frustrating, but overall stoked its working now. Thanks everyone.

**Comment by TheTechRobo** [comment]
Well if you did install WSL you'd have to reinstall snscrape from there.
You're running a whole different OS.

**Comment by GodOfHammers** [comment]
I actually have the same issue. <br/>
I have downloaded snscrape using "`pip install snscrape`", "`pip3 install snscrape`" and "`pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git`", all of which were successful but running the snscrape command (i.e., `snscrape --jsonl --progress --max-results 100 twitter-search "from:jack" > user-tweets.json`) still throws an error (i.e., 'snscrape' is not recognized as an internal or external command, operable program or batch file.).<br/>
I want to make it work in the command prompt of Windows specifically and nowhere else.<br/>
Can anyone suggest what I should do to make it work?

**Comment by JustAnotherArchivist** [comment]
@GodOfHammers It's possible that you have multiple installations of Python and `pip`/`pip3` is using a different one than the `snscrape` executable. Does snscrape show up when you run `python3 -m pip freeze`?

**Comment by GodOfHammers** [comment]
@JustAnotherArchivist, yes it does.
```
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
aiodns==3.0.0
aiohttp==3.8.1
aiohttp-socks==0.7.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
beautifulsoup4==4.11.1
cchardet==2.1.7
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.0.12
colorama==0.4.4
dataclasses==0.6
elastic-transport==8.1.2
elasticsearch==8.3.1
fake-useragent==0.1.11
filelock==3.7.1
frozenlist==1.3.0
geographiclib==1.52
geopy==2.2.0
googletransx==2.4.2
idna==3.3
imageio==2.16.1
joblib==1.1.0
lxml==4.8.0
multidict==6.0.2
mysql==0.0.3
mysql-connector-python==8.0.29
mysqlclient==2.1.0
networkx==2.7.1
numpy==1.21.4
pandas==1.4.3
protobuf==4.21.0
pycares==4.2.1
pycparser==2.21
PySocks==1.7.1
python-dateutil==2.8.2
python-socks==2.0.3
pytz==2022.1
PyWavelets==1.3.0
requests==2.28.1
schedule==1.1.0
scikit-image==0.19.2
scipy==1.7.3
six==1.16.0
snscrape==0.4.3.20220107.dev56+gd72b519
soupsieve==2.3.2.post1
threadpoolctl==3.0.0
tifffile==2022.3.25
tqdm==4.62.3
twint==2.1.20
urllib3==1.26.9
yarl==1.7.2
```

**Comment by JustAnotherArchivist** [comment]
@GodOfHammers `python3 -m pip freeze`, not `pip freeze`. This matters if you may have conflicting Python versions installed.
Although it's impossible for me to tell what's wrong with your setup anyway. It certainly sounds like you installed snscrape in a different place than where the shell looks for executables.

**Comment by rrreese** [comment]
@HelloBob10 @GodOfHammers I encountered the above problems and have a resolution

On my machine pip installs the executables to this location:

```
C:\Users\<MYUSERNAME>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts
```

I would suggest navigating to `C:\Users\<MYUSERNAME>\AppData` and doing a search for `snscrape.exe`

You will  then need to add that location to your PATH then restart your shell
