### ISSUE TITLE
Twitter syntax error while importing the library work fine on window but occur error in linux

### ISSUE THREAD

**Issue by Nigel0626** [JustAnotherArchivist/snscrape#366]
import snscrape.modules.twitter as sntwitter
  File "/home/svradmin/venv4/local/lib/python2.7/site-packages/snscrape/__init__.py", line 11
    moduleName = f'snscrape.modules.{fn[:-3]}'
                                             ^
SyntaxError: invalid syntax

**Comment by JustAnotherArchivist** [comment]
> snscrape requires Python 3.8 or higher.

**Comment by TheTechRobo** [comment]
if you do have python 3.8 installed, try running python3.8 instead of simply python.
