### ISSUE TITLE
twitter profile scraping failing 

### ISSUE THREAD

**Issue by lampardlamps** [JustAnotherArchivist/snscrape#367]
`snscrape twitter-profile textfiles` gives error like:
```
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/timeline/profile/1465481.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&include_tweet_replies=true&userId=1465481&count=100&ext=mediaStats%2ChighlightedLabel failed, giving up.
```
whereas `snscrape twitter-user textfiles` works as normal.

**Comment by JustAnotherArchivist** [comment]
Confirmed, seems like they disabled that API endpoint.

**Comment by lampardlamps** [comment]
Thanks for your prompt response.

**Comment by bernardolima95** [comment]
is there any other way to scrape retweets through the python wrapper?

**Comment by JustAnotherArchivist** [comment]
https://github.com/JustAnotherArchivist/snscrape/issues/83#issuecomment-738950400

**Comment by bernardolima95** [comment]
so it would be limited to the last 7 days only? a shame

**Comment by tsaaii** [comment]
is there a way to scrape retweets of a user?

**Comment by PabloConcheiro** [comment]
This issue appears again for me today. I am using twitter-profile in CLI with the dev version of snscrape. Is the API endpoint disabled again? Thank you in advance.
