### ISSUE TITLE
Does this scrape liked/favorited items on Twitter?

### ISSUE THREAD

**Issue by InquilineKea** [JustAnotherArchivist/snscrape#368]
And if not, what's preventing it?

**Comment by TheTechRobo** [comment]
What do you mean?

If you want to see who liked a post,t hat's not supported: #103 

To see what tweets a user liked, that's also not currently supported: #238.

If Twitter makes this info available to the public, it could be added.

**Comment by InquilineKea** [comment]
Tweets a user liked, yes. 

"Unfortunately, I don't believe this is possible because Twitter doesn't let unauthenticated users see others' likes. (See also: #83, #103, #174)"

^Is it possible for this to loginto Twitter as an unauthenticated user?

**Comment by JustAnotherArchivist** [comment]
No: #270
