### ISSUE TITLE
 get number of retweets and tweets in a day

### ISSUE THREAD

**Issue by Vk2341** [JustAnotherArchivist/snscrape#372]
Can we scrape or get count of number of retweets and tweets on a particular day from single account

**Comment by JustAnotherArchivist** [comment]
No, Twitter does not expose that directly. The only way is to scrape them and then count after the complete retrieval.

**Comment by Vk2341** [comment]
> No, Twitter does not expose that directly. The only way is to scrape them and then count after the complete retrieval.

Can we get retweets in the scraped data? I can only scrape the tweet or a reply from particular user..so not able to count retweets..

**Comment by JustAnotherArchivist** [comment]
Please search the issues. This question has been asked many times before.

**Comment by Vk2341** [comment]
Thanks for the prompt response.I will try my luck
