### ISSUE TITLE
Support for Regular Expressions 

### ISSUE THREAD

**Issue by crazyworm04** [JustAnotherArchivist/snscrape#373]
This may be a very obvious question but I'm curious if I can somehow use regular expressions within a Twitter search? As in, I want to be able to match to tweets that have any instance of the string "cyber" (e.g. cybersecurity, cyber-security, cyber security) regardless of whether it's a word on its own or concatenated with other words. Is this possible?

**Comment by JustAnotherArchivist** [comment]
snscrape's twitter-search scraper is merely an interface to Twitter's search; it does not actually do anything with the query at all. Twitter's search does not support regex, so no, this is possible.

**Comment by crazyworm04** [comment]
Ok thanks, I assumed it wasn't, just wanted to confirm.
