### ISSUE TITLE
Switch HTML parsers

### ISSUE THREAD

**Issue by TheQuinbox** [JustAnotherArchivist/snscrape#378]
BeautifulSoup4 works, but is dreadfully slow when compared to thinks like Selectolax or python's built-in html.Parser class. In order to speed up scraping, I think it would be great to switch away from BS4, to something a lot faster.

**Comment by JustAnotherArchivist** [comment]
Some profiling would be in order here, I think. BS4 with lxml was the best solution last time I looked into it several years ago. Note that speed is only one factor here; the ability to parse broken HTML also comes into play, and BS4/lxml is pretty decent at that.

**Comment by TheQuinbox** [comment]
Going to close this, as whatever changes have gone on in the recent months have changed the speed quite drastickly
