### ISSUE TITLE
Question about making new scraper

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#379]
I'm trying `self._post` onto `https://parler.com/open-api/profile-feed.php` with `params` defined as follows

(ignore the bad code style this isn't the actual code)
```
params = { 'user': (None, 'NewtGingrich'), 'page': (None, '1') }
```

but it keeps trying (and failing) to go to `https://parler.com/open-api/profile-feed.php?user=NewtGingrich&page=1` with a get request

What am I doing wrong?

**Comment by JustAnotherArchivist** [comment]
`self._post` definitely sends a POST request. But `params` is query parameters and should be a flat key-value dictionary or a list of 2-tuples (or similar), and `data` is the HTTP body. Is that what causes the confusion?

**Comment by TheTechRobo** [comment]
I was thinking that was the issue, but didn't know how to replace it. I'll try `data`.

**Comment by TheTechRobo** [comment]
I'm still getting the "4 requests to $url, giving up"

```
            import requests
            current_page = requests.post("https://parler.com/open-api/profile-feed.php", files={"user": (None, "NewtGingrich")}).text
            current_page = self._get_api_data("https://parler.com/open-api/profile-feed.php", data) # Doesn't work
```

_get_api_data is:

```
    def _get_api_data(self, endpoint, data):
        r = self._post(endpoint, data = data, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
        try:
            obj = r.json()
        except json.JSONDecodeError as e:
            raise snscrape.base.ScraperException('Received invalid JSON from Parler') from e
        return obj

```

**Comment by JustAnotherArchivist** [comment]
Is `data` a dict or a bytes string containing JSON? I'm not sure what Requests does with a dict, but I guess it might be sending it as a form submission thing. And I suspect the server wants JSON.

**Comment by TheTechRobo** [comment]
The server wants a form. This is clear in the network tab.

![image](https://user-images.githubusercontent.com/52163910/151704462-3c458364-b734-434d-8a50-e1fb55cf0462.png)

_please note that the page parameter is optional if you only want page 1_

**Comment by JustAnotherArchivist** [comment]
After looking at the Requests docs, I think `data = {'page': 5, 'user': 'NewtGingrich'}` should do that, though I haven't tried it.

**Comment by TheTechRobo** [comment]
I don't think that'll work, but I'll try

**Comment by TheTechRobo** [comment]
Still get the "4 requests, giving up". When I use requests.post directly, now the site isn't getting any data.

**Comment by TheTechRobo** [comment]
closing as invalid
