### ISSUE TITLE
How would I scrape like this?

### ISSUE THREAD

**Issue by Spectifix** [JustAnotherArchivist/snscrape#380]
Hi, I'm trying to scrape twitter to find tweets with media ( vids or images ) with 4k+ likes lets say and print the links to them?
I have this but the tweets have less like 4k likes:
`import snscrape.modules.twitter

scraper = snscrape.modules.twitter.TwitterSearchScraper('viral', 'popular', 'english')
for tweet in scraper.get_items():
	if tweet.likeCount >= 4000 or tweet.media:
		print(tweet.json())`

and I've tried replacing or with and, it does nothing

**Comment by TheTechRobo** [comment]
I'm not sure why replacing `or` with `and` would do nothing. You are asking:

If the tweet has 4000 or more likes or it has media, print(tweet.json()).

**Comment by TheTechRobo** [comment]
Try min_faves like I suggested

**Comment by JustAnotherArchivist** [comment]
Duplicate of #376

**Comment by Spectifix** [comment]
> 

Where would I put min_faves?

**Comment by TheTechRobo** [comment]
It's a search operator, I explained this
