### ISSUE TITLE
How to search for popular tweets?

### ISSUE THREAD

**Issue by OmarSammanKaakajiDM** [JustAnotherArchivist/snscrape#381]
Is there a way i can search for popular tweets and not latest using sntwitter?

**Comment by JustAnotherArchivist** [comment]
Yes, use the `--top` option: `snscrape twitter-search --top 'query'`

**Comment by OmarSammanKaakajiDM** [comment]
is it available in the python library? in the sntwitter.TwitterSearchScraper method?

**Comment by JustAnotherArchivist** [comment]
Yes: `snscrape.modules.twitter.TwitterSearchScraper('query', top = True)`
As the API is currently still undocumented, this might change without warning in future versions.
