### ISSUE TITLE
Support for diacritics

### ISSUE THREAD

**Issue by distrob** [JustAnotherArchivist/snscrape#382]
It doesn't seem to support diacritics. My terminal supports UTF-8, but the output in Mac Terminal has corrupted characters.

**Comment by JustAnotherArchivist** [comment]
snscrape prints UTF-8 just fine, although you'd only see that with something like `--format '{content}'` since the default output is URLs (clean or properly encoded) and the JSONL output uses the `\uXXXX` escapes for non-ASCII characters. What corruption are you seeing?
