### ISSUE TITLE
Only Returning Replies without tweets

### ISSUE THREAD

**Issue by arrr444** [JustAnotherArchivist/snscrape#383]
Hi 

i used the following code, but am only getting replies, I don't get actual tweets, I removed the filters and removed the since, I still don't get tweets

any suggestion will be great

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('hastag-filter:links -filter:retweets -filter:replies since:2022-01-27').get_items()):
    tweets_list2.append([tweet.date,tweet.id, tweet.content, tweet.user.username])
    
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2)
```

**Comment by JustAnotherArchivist** [comment]
I'm not sure what you're doing, but your query works correctly (apart from the missing space before the first filter) here.

Excludes replies: `snscrape --jsonl -n 10 twitter-search '#test -filter:links -filter:retweets -filter:replies since:2022-01-27'`
Includes replies: `snscrape --jsonl -n 10 twitter-search '#test -filter:links -filter:retweets since:2022-01-27'`

**Comment by arrr444** [comment]
I dont know why but its not returning an actual tweet, its returning only replies to tweets 

I tried the functions below, but its only returning keywords in replies that contain the keywords

	'TwitterSearchScraper',
	'TwitterProfileScraper',
	'TwitterHashtagScraper',
	'TwitterTweetScraperMode',
	'TwitterTweetScraper',

**Comment by JustAnotherArchivist** [comment]
Please post the complete code that doesn't work for you. The following works fine here and returns only original tweets as expected:

```python3
import snscrape.modules.twitter

for i,tweet in enumerate(snscrape.modules.twitter.TwitterSearchScraper('#test -filter:links -filter:retweets -filter:replies since:2022-01-27').get_items()):
	print(tweet.json())
	if i >= 9:
		break
```

Arabic shouldn't make a difference, though you'll need to make sure that your query string is constructed correctly, which may be a bit tricky to see depending on how your editor renders the LTR and RTL text. The string should have the hash (`#`), then the (possibly Arabic) hashtag, then a space, and then the filters. If you want to make sure that the format is correct regardless of rendering, put the Arabic text in a separate variable like this:

```python3
ht = '...'  # The hashtag you want to search for, *without* the hash symbol (#), i.e. just the Arabic letters
scraper = snscrape.modules.twitter.TwitterSearchScraper(f'#{ht} -filter:replies ...')
for i, tweet in enumerate(scraper.get_items()):
	...
```

**Comment by arrr444** [comment]
Hi @JustAnotherArchivist 

the code i used is exactly as it is in the first post I mentioned above, but you are right, it is getting tweets, but there I was searching for my own tweets and couldn't find them,

is it because I have few tweets or the account is relatively new, does the search scrapper has any preference or does it scan all tweets regardless

thanks alot

**Comment by JustAnotherArchivist** [comment]
The scraper is simply an interface to Twitter's search. It does not run the search itself. You should get exactly the same results as when you enter the query in the search box on https://twitter.com/explore and switch to 'latest'.

There are various reasons why your tweets might not appear in the search results (including your account being search-banned and bugs on Twitter's side), but there's nothing snscrape can do about that.

**Comment by arrr444** [comment]
Hi JustAnotherArchivist

yes, you are right, the tweets weren't appearing on https://twitter.com/search as well.

I will try and find the problem in there, thanks very much for the support

Regards
