### ISSUE TITLE
Large Jump in Number of Tweets from 1/16/2022 to 1/17/2022

### ISSUE THREAD

**Issue by rachelngordon** [JustAnotherArchivist/snscrape#384]
Hello! I noticed a large jump in the number of tweets returned from some of the days in January 2022. I have scraped data from September 2019 through January 2022 in Chicago and have been getting an average of about 10,000-15,000 tweets per day. However, this past week as I was scraping the rest of January 2022 I started getting over 200,000 tweets per day starting on 1/17. For reference, the file size for 1/16 is 30.7 MB (about average for all the previous days scraped), 1/17 is 388.2 MB, and 1/18 is 649.8 MB (the remaining days in January following 1/18 are all around 600-700 MB as well). Because this is such a large jump I am wondering if either I did something wrong or if scraping more recent data could change the way it is interacting with the Twitter API since there would be less restrictions? I am using the developer version of snscrape on a Mac with Python version 3.9.9

Here is the code I am using:
```
def scrape_month(year, month, num_days):


    # scrape one day at a time and output to separate json file
    for i in range(1, num_days + 1):

        date = datetime.date(year, month, i)
        print(date)

        next_day = date + datetime.timedelta(days=1)

        command = 'snscrape --jsonl --progress --since ' + str(date) + " twitter-search 'until:" + str(next_day) + ' near:"Chicago"' + "' > tweets-" + str(date) + ".json"
        print(command)



        # try scraping a specific day and log whether that date was fully scraped or raised an error
        try:
            subprocess.check_call(command, shell = True)
            
            
            with open('ScrapingLog.csv', 'a', newline='') as csvfile:
                errorwriter = csv.writer(csvfile)
                errorwriter.writerow([str(date)])
          
       
        except: 


            with open('TweetErrors.csv', 'a', newline='') as csvfile:
                errorwriter = csv.writer(csvfile)
                errorwriter.writerow([str(date)])


scrape_month(year = 2022, month = 1, num_days = 31)
```

**Comment by TheTechRobo** [comment]
Potentially related: Twitter search is very buggy and sometimes returns an abnormally small number of results. #4

**Comment by JustAnotherArchivist** [comment]
That would be something on Twitter's side. Perhaps they're rolling out adding geolocation to tweets by default again. Or it's just another search bug. Either way, not something snscrape can do anything about.
