### ISSUE TITLE
Scraper sometimes doesn't scrape twitter profiles all the way to the end.

### ISSUE THREAD

**Issue by 343N** [JustAnotherArchivist/snscrape#386]
Hi! In my journey of using SNScrape, it seems as though I can scrape tweets fine, and it works wonderfully, but it ~~always~~ sometimes misses the last few tweets tweeted by a profile. It doesn't seem to matter how many tweets a profile has made, the last few tweets are missed (either tens or hundreds). To demonstrate, I wrote a small script, and used it on two different profiles. ~~Both~~ One of them had seemed to end before their entire profile was scraped:

Here is the script:
```python
import snscrape.modules.twitter as sntwitter

profile = "powerlanguish"
userScraper = sntwitter.TwitterUserScraper(profile)
userdata = userScraper._get_entity()

print(f"Scraping {profile}")

for i, tweet in enumerate(userScraper.get_items()):
    print(f"#{i+1} of {userdata.statusesCount} on ({tweet.date.strftime('%Y-%m-%d %H:%M')}): {tweet.url}")

print("Done!")
```

Here are the logs for the a profile I used it on, [redactdev](https://pastebin.com/cPiZwB7p)

I've checked to make sure it was just counting more tweets than it should be, but no for a few profiles I've come across, if I go to the bottom of every list and get the earliest tweet that's been scraped, there are still tweets older than that, that are not picked up by SNScrape. 

For instance, redactdev's oldest tweet: https://twitter.com/redactdev/status/1351258228005466113
and the last tweet the scraper retrieved: https://twitter.com/redactdev/status/1371440688332693507

There also seems to be an issue where when I use the scraper, it doesn't scrape every tweet that the user has posted (according to `statusesCount`), even if it goes to the end. I'm not sure if the scraper is missing certain kinds of tweets, but for instance, scraping the account [powerlanguish](https://twitter.com/powerlanguish), the scraper doesn't fetch as many tweets as is listed in statusesCount (this account does manage to scrape all the way to the first tweet, though), it ends early. [Here are the script's logs for that](https://pastebin.com/zD7wyF8V).

I apologise if this issue has already been covered elsewhere, I could not find it in my search.

Thank you.

**Comment by JustAnotherArchivist** [comment]
Yeah, the search simply doesn't return those tweets. For example, https://twitter.com/search?q=from%3Aredactdev%20until%3A2021-01-19&f=live should yield that tweet you linked. Basically another case of #4.

`User.statusesCount` is almost never the number of results you will get. It includes retweets, and I've heard claims that it may also include deleted tweets and other edge cases, though I've never verified that.

Also, you should use `userScraper.entity`, not `_get_entity()`; underscore-prefixed names are not part of the public API.
