### ISSUE TITLE
how scrape image of tweet?

### ISSUE THREAD

**Issue by Rasha-Albalawi** [JustAnotherArchivist/snscrape#389]
I want to scrape the tweet's text + tweet's image 
I used tweet.media but there is an error telling 
AttributeError: 'Tweet' object has no attribute 'media'

**Comment by JustAnotherArchivist** [comment]
Please upgrade to the latest version of snscrape. Note that you'll need Python 3.8 or higher for that.

**Comment by Rasha-Albalawi** [comment]
thank you 
its work for me
