### ISSUE TITLE
What Qualifies as "Top" Tweet?

### ISSUE THREAD

**Issue by Aspiring-Economist** [JustAnotherArchivist/snscrape#395]
I may be asking a stupid question or using this incorrectly but I couldn't quite gather how "Top" tweets were identified when looking through the code. What distinguishes these tweets from other tweets?

**Comment by JustAnotherArchivist** [comment]
I don't know either as that's not my doing. They are simply what's shown in the 'Top' tab on Twitter's search results (as opposed to 'Latest'). If I had to guess, I'd say it's probably some combination of recency and engagement.

**Comment by Aspiring-Economist** [comment]
Ah, thanks for the insight and for creating snscrape!
