### ISSUE TITLE
How to fully scrape tweet_urls?

### ISSUE THREAD

**Issue by Mennaruuk** [JustAnotherArchivist/snscrape#402]
Hello JustAnotherArchivist 👋 Hope you are feeling good.

I would like to know how I can fully scrape a profile’s Tweet URLs. I am aware of the 3,200 limit. However, is there a way to get around it? The only way I can think of is selecting a class via BeautifulSoup and having Selenium do infinite scroll, but obviously that’s very cumbersome.

thank you very much

**Comment by TheTechRobo** [comment]
If snscrape's profile limit is 3200, it is more than likely the same for viewing the profile in the browser. snscrape uses twitter's internal API.

The `include:nativeretweets` search operator might help, but it only includes retweets from the past 7 days

**Comment by Mennaruuk** [comment]
I definitely understand. I do not know why they have such a low limit!!! Very frustrating. Oh well, can’t take it for granted, they might lower it in the future, and it’ll be like the Monkey’s Paw.

thank you JustAnotherArchivist. I hope you have a great day.

**Comment by JustAnotherArchivist** [comment]
Duplicate of #85
