### ISSUE TITLE
Lack of full description related to 'mentionedUsers' when using snscrape.modules.twitter.User

### ISSUE THREAD

**Issue by jacksonbourne** [JustAnotherArchivist/snscrape#406]
Hey, I wanted to firstly thank you, this software has been incredibly helpful to me and you keep on top of updates and questions so well!

The issue I've run into is when trying to retrieve information about the users in 'mentionedUsers', and as I've shown below, most of the information does not show up, with the exception of 'username', 'id', and 'displayName'. In particular, I'm hoping to pull the 'followerCount' and 'created', but the other information would be helpful. 

<img width="286" alt="Screenshot 2022-02-15 at 11 43 19" src="https://user-images.githubusercontent.com/72134711/154056711-7998acee-598b-470d-9ab8-97a732885809.png">

Naturally, I understand the workaround is to do a separate search for the users and get the information that way but with a large number of tweets and users, this becomes infeasible as the run time increases by a significant factor. I don't know if this is just what the Twitter API returns, but I thought I'd check. Thank you in advance!

**Comment by JustAnotherArchivist** [comment]
Documentation is WIP, but yes, Twitter only returns the username, user ID, and display name for mentioned users.

It is possible to request info for multiple users at once from Twitter, but that's not currently implemented in snscrape.

**Comment by jacksonbourne** [comment]
Ok good to know - thanks for getting back to me, appreciate it.
