### ISSUE TITLE
Support requesting information about multiple Twitter users at once

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#408]
There's an endpoint which allows querying multiple users in one request given their ID (no, there isn't one with usernames). That could be useful for hydrating lists of user IDs, for example.

Via #406

**Comment by TheTechRobo** [comment]
What's the endpoint?

**Comment by JustAnotherArchivist** [comment]
It's called UsersByRestIds and part of the GraphQL API. I'll have to look up the endpoint ID (i.e. full URL) though.

**Comment by maheshs11** [comment]
> It's called UsersByRestIds and part of the GraphQL API. I'll have to look up the query ID (which appears in the URL before the operation name) though.

any updates on this?

**Comment by trevorhobenshield** [comment]
query id  for **UsersByRestIds** can be found in 

`https://abs.twimg.com/responsive-web/client-web/api.{[a-z0-9]+}a.js`

`https://abs.twimg.com/responsive-web/client-web/endpoints.UsersGraphQL.{[a-z0-9]+}a.js`

just need guest token and auth header

Example request params:
```json
{
  "variables": {
    "userIds": [44196397, 33836629, 1158139840866791424],
    "withSuperFollowsUserFields": true
  },
  "features": {
    "responsive_web_twitter_blue_verified_badge_is_enabled": true,
    "responsive_web_graphql_exclude_directive_enabled": false,
    "verified_phone_label_enabled": true,
    "responsive_web_graphql_skip_user_profile_image_extensions_enabled": false,
    "responsive_web_graphql_timeline_navigation_enabled": false
  }
}
```
