### ISSUE TITLE
Truth Social

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#412]
When Truth Social is finally released to the public (if it's available to the unauthenticated) and I'm finished the parler scraper I'll probably add it to snscrape. It seems like a pretty volatile site.

**Comment by JustAnotherArchivist** [comment]
So... is anything publicly accessible?

**Comment by TheTechRobo** [comment]
Hmm, from Wikipedia:

> The service is only accessible via an [iPhone app](https://en.wikipedia.org/wiki/IPhone_app),<sup>[[2]](https://en.wikipedia.org/wiki/Truth_Social#cite_note-Guardian_2022-03-16-2)</sup> and access is limited to users in the United States and Canada.<sup>[[3]](https://en.wikipedia.org/wiki/Truth_Social#cite_note-Udvarlaki_Feb_2022-3)</sup>

As I don't use and am not planning on using Truth Social, I can't experiment with their app, so I'm not sure if it requires an account, although since it's limited to the US and Canada it probably does.

It's based on Mastodon, apparently, and [open source](https://help.truthsocial.com/open-source) so that stuff can probably be figured out.

**Comment by JustAnotherArchivist** [comment]
As far as I can tell, everything requires auth. So closing this as non-actionable. If someone discovers that there is a way to bypass the login requirement, we can reopen this.

**Comment by JustAnotherArchivist** [comment]
Great timing... When I was experimenting with it last night, it wasn't accessible (at least the things I tested), but now it apparently is, see #493.

**Comment by frisch1** [comment]
Thx. Sorry for posting in sep thread.

**Comment by trislee** [comment]
Here's a Truth Social API wrapper: https://github.com/stanfordio/truthbrush
Unfortunately it requires authentication, there doesn't seem to be a way around that.

**Comment by TheTechRobo** [comment]
snscrape can't and won't do auth: #270.
