### ISSUE TITLE
Can't get sorted dates when extracting data from twitter 

### ISSUE THREAD

**Issue by k-marcelino** [JustAnotherArchivist/snscrape#418]
At first I gotta say I'm a begginner, so if I'm creating an issue that is not according to the best practices I apologize.

I currently use python 3.9.4 - snscrape 0.4.3.20220107.dev31+g3a92b5b on windows 10 and running on jupyter notebook.
I'm using snscrape for some while now, Im' really happy it's the only scrape working in an easy way and there is no need to get access to the credentials from twitter (It's hell trying it, they ask the same questions over and over and people have a too strict and limited tool with this API) ok, so far so good, recently when I run my code searching for any kind of term I started to get data from the most recent to the past. I'll explain better with my code:

# Importing libraries and packages
```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd
import time
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np
from tqdm.notebook import tnrange, tqdm_notebook
```

![image](https://user-images.githubusercontent.com/85710050/156209901-cf723f22-e619-457e-900a-03ba4e7f6efe.png)

```python3
start_time = time.time()
```

# Creating list to append tweet data to
```python3
tweets_list = []
```

# Using TwitterSearchScraper to scrape data
```python3
for i,tweet in tqdm_notebook(enumerate(sntwitter.TwitterSearchScraper('bitcoin since:2014-01-01 until:2022-05-31').get_items())):
    if i > 500:
        break
    tweets_list.append([tweet.date,
                        tweet.content, 
                        tweet.user.username, 
                        tweet.mentionedUsers, 
                        tweet.retweetedTweet, 
                        tweet.likeCount,
                        tweet.retweetCount, 
                        tweet.user.location, 
                        tweet.user.followersCount, 
                        tweet.user.verified])
```

# Creating a dataframe from the tweets list above
```python3
columns=['Datetime', 'Text', 'Username', 'MentionedUsers', 'retweetedTweet', 'Likes', 'Retweets', 'Location', 'Followers', 'Verified']
bitcoin = pd.DataFrame(tweets_list, columns = columns)


end_time = time.time()
print(f"Result calculated in {end_time - start_time} sec")
```

![image](https://user-images.githubusercontent.com/85710050/156210139-7fdb0461-7c20-4f41-9156-640df6a7f7f5.png)

Ok, there is no error or crash here, but the output takes data as showed bellow:

![image](https://user-images.githubusercontent.com/85710050/156209187-4e526828-8e7c-4f49-a497-ee75e1192473.png)

Note the DateTime starts from the most recent, it didn't work like this before, snscrape used to get data from the date I put in "since" till "until" argument. If possible I'd like some help to solve this, and if there are any tips on how I can make this code more efficient and improve the features, since there is no documentation using this as a lib I feel I'm not taking the most advantages of your scraper.

Thanks for creating this amazing tool, It inspires a lot and gives enthusiasts an awesome way to learn with so dinamic data :)

**Comment by TheTechRobo** [comment]
I don't think snscrape sorts the data it gets itself; it simply returns it in the order that Twitter spat out.

You could try sorting them yourself based on the date.

**Comment by k-marcelino** [comment]
Thanks a lot! I guess I got confused.
If there is no way to get data in chronological order this issue can be closed
