### ISSUE TITLE
Not able to fetch all the features given in class "Tweet" in the module "twitter.py"

### ISSUE THREAD

**Issue by SachinVashisth** [JustAnotherArchivist/snscrape#426]
Hi

I was trying to fetch Tweet features with the code as shown:

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd

tweets_list2 = []

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('ChhattisgarhEncounter since:2021-04-03 until:2022-03-08').get_items()):
    if i>20000:
        break
    tweets_list2.append([tweet.url, tweet.date, tweet.id, tweet.content, tweet.renderedContent, tweet.user.username, tweet.user.displayname, tweet.user.id, tweet.user.location, tweet.user.linkUrl, tweet.lang, tweet.source, tweet.media, tweet.retweetedTweet, tweet.quotedTweet, tweet.outlinks, tweet.replyCount, tweet.retweetCount, tweet.likeCount, tweet.quoteCount])

tweets_df2 = pd.DataFrame(tweets_list2, columns=['Url', 'Datetime', 'Tweet Id', 'Text', 'Rendered Text', 'Username', 'Display Name', 'User Id', 'User Location', 'User LinkUrl', 'Tweet Lang', 'Tweet Source', 'Tweet Media', 'Retweeted Tweet', 'Quoted Tweet', 'Outlinks', 'Reply Count', 'Retweet Count', 'Like Count', 'Quote Count'])

print(tweets_df2.head())
print(tweets_df2.shape)
```

So, although class **''Tweet"** has the feature **"renderedContent"**, still it gives the error:

    AttributeError: 'Tweet' object has no attribute 'renderedContent'

Can you help with this issue.

**Comment by JustAnotherArchivist** [comment]
Which snscrape version? I suspect you're running an old one. `renderedContent` works fine for me.

**Comment by SachinVashisth** [comment]
> Which snscrape version? I suspect you're running an old one. `renderedContent` works fine for me.

snscrape 0.4.3.20220106

**Comment by JustAnotherArchivist** [comment]
Hmm, that is the last release, but I don't see how you could possibly get an `AttributeError` on that...

Here's the CLI command equivalent to your code but stopping after the first result and only printing the `renderedContent`. Works perfectly fine for me with 0.4.3.

    snscrape --format '{renderedContent}' -n 1 twitter-search 'ChhattisgarhEncounter since:2021-04-03 until:2022-03-08'

Are you sure you don't have two different versions of snscrape installed, e.g. under different versions of Python? Check by adding this to your script:

```python3
import snscrape.version
print(snscrape.version.__version__)
```

**Comment by SachinVashisth** [comment]
> Hmm, that is the last release, but I don't see how you could possibly get an `AttributeError` on that...
> 
> Here's the CLI command equivalent to your code but stopping after the first result and only printing the `renderedContent`. Works perfectly fine for me with 0.4.3.
> 
> ```
> snscrape --format '{renderedContent}' -n 1 twitter-search 'ChhattisgarhEncounter since:2021-04-03 until:2022-03-08'
> ```
> 
> Are you sure you don't have two different versions of snscrape installed, e.g. under different versions of Python? Check by adding this to your script:
> 
> ```python
> import snscrape.version
> print(snscrape.version.__version__)
> ```

These last two lines give me:
0.3.4

**Comment by JustAnotherArchivist** [comment]
Well there you go, you do have two different versions of snscrape installed. `renderedContent` was added after version 0.3.4. You need to run your script such that it uses the newer version of snscrape. The details will depend heavily on your setup, so I can't really help you with that.

**Comment by sara-02** [comment]
@JustAnotherArchivist I am also facing a similar issue, I am running the scraper version `0.3.4` on Colab and not able to fetch all attributes of a tweet (eg, retweetcount).
```
AttributeError: 'Tweet' object has no attribute 'retweetCount'
```

**Comment by SachinVashisth** [comment]
> @JustAnotherArchivist I am also facing a similar issue, I am running the scraper version `0.3.4` on Colab and not able to fetch all attributes of a tweet (eg, retweetcount).
> 
> ```
> AttributeError: 'Tweet' object has no attribute 'retweetCount'
> ```

I was not able to run the python script which I posted above because it later failed to recognize "snscrape". I was not able to fix that. But I used command line script (in jupyter notebook) like shown below:
`! snscrape --jsonl --max-result 100 --since 2021-04-03 twitter-hashtag "ChhattisgarhEncounter until:2022-03-08" >output.jsonl`

This script worked for me.

**Comment by sara-02** [comment]
> ```python
>  tweet.user.username
> ```

Additionally it sems that `Tweet.user` object is not rendering properly:
```
print(tweet.user.username)
AttributeError: 'Tweet' object has no attribute 'user'
```

**Comment by sara-02** [comment]
> ! snscrape --jsonl --max-result 100 --since 2021-04-03 twitter-hashtag "ChhattisgarhEncounter until:2022-03-08" >output.jsonl
@SachinVashisth  but I am getting this error
```
snscrape: error: unrecognized arguments: --jsonl
```

**Comment by SachinVashisth** [comment]
> > ! snscrape --jsonl --max-result 100 --since 2021-04-03 twitter-hashtag "ChhattisgarhEncounter until:2022-03-08" >output.jsonl
> > @SachinVashisth  but I am getting this error
> 
> ```
> snscrape: error: unrecognized arguments: --jsonl
> ```

I did this before running the above command:

1. `! pip install git+https://github.com/JustAnotherArchivist/snscrape.git`
2. `! pip install --upgrade snscrape`

Then I think it will run fine

**Comment by JustAnotherArchivist** [comment]
@sara-02 Please install the latest snscrape version. See also #347.
