### ISSUE TITLE
File name with the StoryItem

### ISSUE THREAD

**Issue by Lion020279** [JustAnotherArchivist/snscrape#427]
How can I set StoryItem in --filename-pattern ?

**Comment by JustAnotherArchivist** [comment]
I have no idea what you're talking about. Neither `StoryItem` nor `--filename-pattern` exist anywhere in snscrape.

**Comment by Lion020279** [comment]
Sorry. How can I get this into filename&

![name](https://user-images.githubusercontent.com/101483675/158056672-8cda8e9f-62ea-4e8f-a6b4-4c96b5916f86.png)

**Comment by TheTechRobo** [comment]
But what's that text coming from? A Tweet, or something else?

Judging from the "StoryItem" you were talking about, are you using Facebook/Instagram?

**Comment by Lion020279** [comment]
Instagram, I tried download ":saved"

**Comment by JustAnotherArchivist** [comment]
This is definitely not snscrape. A quick web search suggests you may be using instaloader. In any case, definitely irrelevant to here.

**Comment by Lion020279** [comment]
Instagram, I tried download ":saved"

вс, 13 мар. 2022 г., 17:35 TheTechRobo ***@***.***>:
