### ISSUE TITLE
It can not download GIF file

### ISSUE THREAD

**Issue by KonohaVio** [JustAnotherArchivist/snscrape#431]
I want to download GIF files from someone's Twitter , but this program only  recognize GIF files as JPG photos.    "_type": "snscrape.modules.twitter.Photo"  and  "fullUrl": "https://pbs.twimg.com/media/FOEhGASXMAMelfc?format=jpg&name=large".

**Comment by JustAnotherArchivist** [comment]
Please provide the details listed in the pinned issue.

**Comment by JustAnotherArchivist** [comment]
It works fine for me for a random example tweet (1504525803912114176) with both `twitter-tweet` and `twitter-search`.

**Comment by Slider-Whistle** [comment]
KonohaVio: As far as I'm aware, Twitter won't actually host any (animated) GIFs at all. They're all converted to (AVC inside) mp4.
The bit of json you're actually looking for is "media > variants (contentType video/mp4) > url". Will write a `jq` expression for that if you want but I've got to leave for work in 5 minutes.

**Comment by KonohaVio** [comment]
> video

Oh!Thanks for your generous help! It's kind of you.It's my mistake,I lost this message : "variants": [{"_type": "snscrape.modules.twitter.VideoVariant", "contentType": "video/mp4".  Now I'v known how to do. Thanks for both you guys!
