### ISSUE TITLE
how to get user's retweets and and when to retweet

### ISSUE THREAD

**Issue by wxqssr** [JustAnotherArchivist/snscrape#437]
I want to get the network of retweets on twitter, so I need user's retweets and their time. I search some information but didn't find how to realize that.  Or could you tell how to get a tweet's retweet list containg username and time? I can only get username from twitter.
I would appreciate it for your help.

**Comment by wxqssr** [comment]
more accurately, i want to get retweets from specific tweets, and retweets' detail information(time,username and so on)

**Comment by JustAnotherArchivist** [comment]
This is essentially the same as #103 and not possible.
