### ISSUE TITLE
Extract specific research word from specific users 

### ISSUE THREAD

**Issue by BashairA** [JustAnotherArchivist/snscrape#440]
I am not sure if this is supported. I was trying to loop Extract specific research word from specific users. Each time the result came back no found. Could you please help?

**Comment by JustAnotherArchivist** [comment]
I don't understand what you mean. Can you give an example?

**Comment by BashairA** [comment]
Sorry for my previous post. I will try to explain it better. I want to get the tweets that include key words from specific users. For example, the user is “nytimes” , the key words “ economy “. 

tweet_count = 500
username = ["Maaalnew"]
text_query = [ "اقتصاد"]
since_date = "2016-01-01"
until_date = "2021-10-14"

for person in username:
  for word in text_query:
      os.system("snscrape --format '{content!r}{date}'"+ "--max-results {} --since {} twitter-search '{} from:{} until:{}'> user-tweets.text")

**Comment by JustAnotherArchivist** [comment]
This should probably work with minimal changes to your code:

```python3
os.system("snscrape --format '{content!r}{date}' " + f"--max-results {tweet_count} --since {since_date} twitter-search '{word} from:{person} until:{until_date}' >user-tweets.text")
```

(Changes: add a space after the `--format` value, string formatting.)

I would suggest putting the `since_date` in the query instead of using `--since`:

```python3
os.system("snscrape --format '{content!r}{date}' " + f"--max-results {tweet_count} twitter-search '{word} from:{person} since:{since_date} until:{until_date}' >user-tweets.text")
```

Remember that the output file will be overwritten on every `snscrape` call. If you want to append instead, replace the `>` with a `>>`.

**Comment by BashairA** [comment]
Thanks.  I apprciate your reply. Unfortunately, I tried it but still not working get the following error:
  File "<ipython-input-35-799cd1060984>", line 9
    os.system("snscrape --format '{content!r}{date}' " + f"--max-results {tweet_count} twitter-search '{word} from:{person} --since{since_date} twitter-search '{word} from:{person} until:{until_date}' >>user-tweets.text")
                                                                                                                                                                                                                            ^
IndentationError: expected an indented block

I double-check the spaces. still getting the error.

**Comment by JustAnotherArchivist** [comment]
That was just the replacement for the `os.system` call within your loops. In any case, this isn't about how to use snscrape, and I don't have time to provide general Python syntax (indentation, string formatting) support here.
