### ISSUE TITLE
Support for scraping tweets containing multiple keywords!

### ISSUE THREAD

**Issue by mehrnooshazizi** [JustAnotherArchivist/snscrape#442]
> 

Hello! Thanks in advance for this incredible tool for scraping. I'm trying to use this package to scrape some tweets having multiple keywords. This is a sample of my code:

```
import pandas as pd
import snscrape.modules.twitter as sntwitter
import itertools

a = ['blue', 'green', 'yellow', 'red']
b = ['long', 'short']
c = ['tshirt', 'blouse']

products_list = list(itertools.product(a, b, c))
for i in products_list:
       keyword = i[0] + "  "+ i[1]+"  "+ i[2]
       data = sntwitter.TwitterSearchScraper(keyword +' since:2020-12-08 until:2020-12-18').get_items()                          

df = pd.DataFrame(data)
```

But I can't get any tweets. Can you help me? I want tweets for each combination of 3 keywords together. How should I iterate through my list to use multiple keywords?

**Comment by JustAnotherArchivist** [comment]
That's the right approach, but `get_items` is a generator. You need to iterate over it to actually run the scrape and get the results. The simplest way would be to wrap it in a `list(...)` call, but if you need more control, you might have to use a list comprehension or `for` loop.
