### ISSUE TITLE
Unexpected bug when using InstagramHashtagScraper

### ISSUE THREAD

**Issue by ZhangWanlin98** [JustAnotherArchivist/snscrape#443]
Hi developers,

when I was using the InstagramHashtagScraper on a list of keywords ("COVD19", "CoronavirusPandemic", "COVID-19", "2019nCoV", "CoronaOutbreak", "coronavirus").

While using previous keywords is able to output successfully, I encounter the following bug on running with "CoronaOutbreak":

> snscrape.base.ScraperException: 4 requests to https://www.instagram.com/graphql/query/?query_hash=f92f56d47dc7a55b606908374b43a314&variables=%7B%22tag_name%22:%222019ncov%22,%22first%22:50,%22after%22:%22QVFDa1JKdzlZZmw2bl9aMkM4UGVhRnlQalJ4d0hlV2hKSEF1SzdRN2ExQXkxeGxZb3RGVkZURENUV0ZGTEFjTHFVejkxYVo1ZlJRQm5lODBpcldIRE8zVw==%22%7D failed, giving up.

The version I'm using is 0.4.3.20220106. Can I know how to prevent this from happening?

**Comment by JustAnotherArchivist** [comment]
Sounds like the same thing @TheTechRobo reported in https://github.com/JustAnotherArchivist/snscrape/issues/165#issuecomment-1083670202

It works fine for me without having scraped anything previously, so likely this is how Instagram's rate limits manifest now.

**Comment by ZhangWanlin98** [comment]
Thanks for the prompt reply.

**Comment by JustAnotherArchivist** [comment]
Confirmed, this is Instagram rate-limiting more heavily on the API endpoint than the web pages in some cases. Nothing snscrape can do about that, really.

**Comment by ZhangWanlin98** [comment]
Okay, noted with thanks.
