### ISSUE TITLE
Support for scraping twitter topics

### ISSUE THREAD

**Issue by butlfrazp** [JustAnotherArchivist/snscrape#449]
Hello,

I was wondering how I could use this package to get twitter topics. Say I was looking to scrape the topic "trending tweets", is that currently possible? Thanks

**Comment by JustAnotherArchivist** [comment]
Scraping trends is supported via the `twitter-trends` scraper.

Otherwise, [topics](https://help.twitter.com/en/using-twitter/follow-and-unfollow-topics) are only available to logged-in users and therefore not supported by snscrape.

**Comment by butlfrazp** [comment]
Thanks!
