### ISSUE TITLE
__init__() missing 1 required positional argument: 'title'

### ISSUE THREAD

**Issue by Aanchalsagwal21** [JustAnotherArchivist/snscrape#452]
I'm getting the error: __init__() missing 1 required positional argument: 'title'
 i see you have fixed this issue, but could you tell me how I could update it in my code, i tried reinstalling the snscrape package from git, but the error still shows up. Pls help.

**Comment by JustAnotherArchivist** [comment]
Please provide the information mentioned in the pinned issue then.

**Comment by aanchalsagwal** [comment]
> Please provide the information mentioned in the pinned issue then.
I'm using python 3.9.7 in JupyterLab on Windows 10
I have installed the version :snscrape-0.4.3.20220107.dev43+g6c50eee

**Comment by Aanchalsagwal21** [comment]
> 

I'm using python 3.9.7 in JupyterLab on Windows 10
I have installed the version :snscrape-0.4.3.20220107.dev43+g6c50eee

**Comment by JustAnotherArchivist** [comment]
I still don't know what you're scraping...

**Comment by Aanchalsagwal21** [comment]
> I still don't know what you're scraping...
I am trying to scrape tweets with #CAA #NRC hashtags for specific dates. I am using the following code

sntwitter.TwitterSearchScraper('#NRC since:2020-02-15 until:2020-02-17').get_items())

**Comment by JustAnotherArchivist** [comment]
That works fine for me with the latest master (ed3ea944). I'm not familiar enough with JupyterLab or Windows to tell you how you need to install the new snscrape, but I suspect that's where something went wrong. Maybe try explicitly uninstalling it and then installing anew from scratch.
