### ISSUE TITLE
Getting unexpected results when scraping twitter 

### ISSUE THREAD

**Issue by ZiyaoShang** [JustAnotherArchivist/snscrape#455]
Hey! I was trying to scrape for tweets with the exact phrase "happy hour". However, some of the results do not have either the words "happy" or "hour", and more do not have the exact phrase "happy hour". Am I doing it incorrectly?

I tried the following and none of them worked:
```
!snscrape --jsonl --progress --max-results 1000 --since 2019-01-01 twitter-search "Happy hour" > res.json
!snscrape --jsonl --progress --max-results 1000 --since 2019-01-01 twitter-search "'Happy hour'" > res.json
!snscrape --jsonl --progress --max-results 1000 --since 2019-01-01 twitter-search '"Happy hour"' > res.json
```

Examples of scrapped tweet content:
```
@ochocinco @BMarshall This camera work is amazing
@codyschibi @SpecterM91 Dave here - I have a technical question. Do you ink before or after the watercolor?
```

FYI, I am using the anaconda prompt on windows and snscrape version 0.4.3.20220106. 
Thanks a lot!

**Comment by JustAnotherArchivist** [comment]
This is an issue with your terminal. You need to pass `"Happy hour"` *with the quotes* as the last argument. The third of your commands works fine in Bash (and any Unixoid shell that's in significant use, even csh/tcsh I think), but the Windows shell has different quoting rules. I haven't used Windows in many years, so I can't give more specific advice.
