### ISSUE TITLE
scrapes very few tweets

### ISSUE THREAD

**Issue by Aanchalsagwal21** [JustAnotherArchivist/snscrape#462]
Hi I'm using snscrape on jupyter lab and windows operating system. I am tryin to scrape tweets corresponding to # Hathras  #dalit etc, I had put an upper limit of 10000 but it only scrapes around 30 tweets.
Here is the code Im using:

```python3
tweets_CAA_15=[]
n=0
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#hathras #dalit violence since:2020-09-29 until:2020-09-30').get_items()):
    n+=1
    print(n)
    if i>10000:
            break
    
    tweets_CAA_15.append([tweet.user.displayname, tweet.user.description, tweet.user.verified, tweet.user.followersCount, tweet.user.friendsCount, tweet.date, tweet.content, tweet.replyCount, tweet.retweetCount, tweet.likeCount, tweet.lang, tweet.sourceLabel,tweet.media,tweet.coordinates, tweet.place , tweet.hashtags])                         
```

**Comment by TheTechRobo** [comment]
[I only get two tweets when searching using Twitter's UI](https://twitter.com/search?q=%23hathras%20%23dalit%20violence%20since%3A2020-09-29%20until%3A2020-09-30&src=typed_query). snscrape isn't magic. snscrape uses Twitter's own searching UI, and if the website doesn't return very many tweets, snscrape probably won't either.

**Comment by TheTechRobo** [comment]
By the way, if you're trying to get e.g. #Hathras OR #dalit, that's not what's happening in your code. Your code asks for all of those hashtags to be part of the tweet.
