### ISSUE TITLE
likeCount and retweetCount returns NaN for some rows while 0.0 for others?

### ISSUE THREAD

**Issue by nancccyma** [JustAnotherArchivist/snscrape#466]
I was wondering what would cause it to return NaN? Is it a deleted tweet ? 

```python3
query = '("Ukraine" OR "Ukranian") AND ("refugee" OR "immigrant") until:2022-04-24 since:2022-02-24 -filter:replies'
limit = 3000
 
for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, 
                       tweet.user.username, 
                       tweet.content,
                       tweet.likeCount,
                       tweet.retweetCount])
pd.set_option('display.max_colwidth', None)        
df_ukraine = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet', 'Like Count','Retweet Count'])
df_ukraine
```

**Comment by JustAnotherArchivist** [comment]
Can't reproduce.

    snscrape --jsonl --max-results 3000 twitter-search '("Ukraine" OR "Ukranian") AND ("refugee" OR "immigrant") until:2022-04-24 since:2022-02-24 -filter:replies'

produces only output with numeric `likeCount` and `retweetCount`, exactly as expected. Please try to reproduce it without Pandas. If you can, include the tweet ID or URL where it happens.

**Comment by nancccyma** [comment]
Follow up question if you do not mind, when I run the above code, I get some repeat tweets. I was wondering what those are exactly? Are they retweets of the same tweet? For the below code I get 28 repeated tweets

```
query = '("Ukraine" OR "Ukranian") AND ("refugee" OR "immigrant") until:2022-04-24 since:2022-02-24 -filter:replies'
limit = 3000
 
for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, 
                       tweet.user.username, 
                       tweet.content,
                       tweet.likeCount,
                       tweet.retweetCount])
pd.set_option('display.max_colwidth', None)        
df_ukraine = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet', 'Like Count','Retweet Count'])

uk_rows = df_ukraine.shape[0]
ukraine_unique = df_ukraine['Tweet'].unique()
repeats_uk = uk_rows - len(ukraine_unique)
print(repeats_uk)
```

**Comment by JustAnotherArchivist** [comment]
Bots and people spamming/reposting stuff, most likely. You're comparing the text content, not the tweet ID.

**Comment by nancccyma** [comment]
> Bots and people spamming/reposting stuff, most likely. You're comparing the text content, not the tweet ID.

yes I wanted to see the repeats since I just want to keep the one with the highest likeCount. Wasn't sure if when a tweet is deleted its saved as a separate row with a different value or something,. Good to know it's just spam and repost. Thank you!
