### ISSUE TITLE
Scrape all tweets without keywords

### ISSUE THREAD

**Issue by DaisyWatermelon** [JustAnotherArchivist/snscrape#467]
Hi, many thanks for this snscrape, it gives a lot of help! I have a question about how to use it to scrape tweets without keywords. For example, I know the search codes is 
`for i,tweet in enumerate(sntwitter.TwitterSearchScraper('apple since:2022-02-25 until:2022-03-02').get_items()):`
however, if I don't want to use a keyword "apple", I want to search all tweets in this date range, how can I do that? I tried remove "apple" but it would have an error:
`Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=since%3A2022-02-25+until%3A2022-03-02&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=since%3A2022-02-25+until%3A2022-03-02&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.`
Thanks again.

**Comment by JustAnotherArchivist** [comment]
See #254
