### ISSUE TITLE
vkontakte-user doesn't scrape photos

### ISSUE THREAD

**Issue by asvi-s** [JustAnotherArchivist/snscrape#471]
For videos it works beautifully and returns url, thumbnail, duration etc. But it skips photos entirely :(

**Comment by JustAnotherArchivist** [comment]
They used to get extracted. Looks like VK changed something since I wrote that code. Thanks, will take a closer look soonish.

**Comment by asvi-s** [comment]
I tried it like year ago and it did extract photos then. It's only now I have something resembling of a use case for these because I'm very slow lol. Thank you, you're running an amazing project!

**Comment by hgrsd** [comment]
I've opened https://github.com/JustAnotherArchivist/snscrape/pull/518 which includes an updated way of detecting whether we are dealing with a photo, allowing the existing scraping logic to kick in and scrape its urls.
