### ISSUE TITLE
Unable to scrape all old tweets per day

### ISSUE THREAD

**Issue by FaTal-error1** [JustAnotherArchivist/snscrape#472]
Im trying to scrape tweets of April day per day, the older is day the fewer tweets I get (example: in 2022-04-01 I get only 190 tweets, but in 30 april I get 1000), I would like to get all tweets for each day.

**Comment by JustAnotherArchivist** [comment]
This sounds like another Twitter-side search index bug (see e.g. #468), but without the specific search query, it's impossible to tell. Unless you get more results when you run the same search query in a browser, it's most likely not something snscrape can do anything about.
