### ISSUE TITLE
facebook documentation

### ISSUE THREAD

**Issue by mohammad-alqudah** [JustAnotherArchivist/snscrape#473]
is there a documentation for facebook ?
it's not easy to use....

**Comment by JustAnotherArchivist** [comment]
There's only the README and what `snscrape --help` and `snscrape MODULE --help` print. (Plus that PR, which hasn't been thoroughly reviewed yet, so consider it unofficial for the time being.)
If you have specific questions, I might be able to help, but otherwise, this is a duplicate of #6.
