### ISSUE TITLE
FacebookUserScraper not working?

### ISSUE THREAD

**Issue by ehsong** [JustAnotherArchivist/snscrape#477]
I am trying to scrape a user's posts, and I used the following but returns an empty list:
```
import snscrape.modules.facebook as fbscrape
# cleanUrl, dirtyUrl, date, content, outlinks

handles3 = ['minjung.ko.184']

fboutput = []
for handle in handles3:
    scraper = fbscrape.FacebookUserScraper(handle)
    for tweet in scraper.get_items():
        fboutput.append([handle, fbscrape.date, fbscrape.cleanUrl, fbscrape.content]) # what are the fields
```

The user's webpage is intact - [](https://www.facebook.com/minjung.ko.184) but the module is not scraping anything. Also is there a way to scrape posts within a time field?

**Comment by JustAnotherArchivist** [comment]
That profile's posts are not publicly accessible. Facebook only returns a profile overview page.
