### ISSUE TITLE
Resolve content/renderedContent vs rawDescription/description discrepancy

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#479]
`Tweet` objects currently have a `content` attribute that contains the raw tweet content and `renderedContent` for the string that would get shown by the web app. `User` objects store the raw profile description in `rawDescription` and the rendered version in `description`.

I'm not sure which one makes more sense, but this inconsistency should be fixed. Options:

1. Rename the fields on `Tweet` to `rawContent` and `content` to match the ones on `User`.
2. Rename the fields on `User` to `description` and `renderedDescription` to match the ones on `Tweet`.
3. Use `rawContent` and `renderedContent` (and `rawDescription`/`renderedDescription`) to make it always obvious which one you're accessing.

Between the first two options, 2 would probably be preferable to 1 as I would expect more people to make use of tweet contents than user profile descriptions. But both would necessarily be breaking changes while 3 can be handled with deprecations, so 3 is what I'm leaning towards currently.

Any opinions about this from the user perspective would be very welcome!

(Rendering here refers to replacing links; the raw form contains t.co URLs while the rendered one usually contains some truncated version of the actual URL.)

**Comment by openandclose** [comment]
(snscrape version is newest (530f4fa)).
