### ISSUE TITLE
Twitter ignores count parameter

### ISSUE THREAD

**Issue by adamrag** [JustAnotherArchivist/snscrape#481]
https://api.twitter.com/2/search/adaptive.json
this param "count= 100"
is not working and crawling is most slowly  any solution(25 tweet per request)

**Comment by JustAnotherArchivist** [comment]
Looks like Twitter ignores the `count` parameter nowadays and always returns 20 results. Sending it doesn't cause any issues though, it just doesn't affect anything.

**Comment by bxff** [comment]
It does seem to respect the lower bound created by `count` parameter, might be worth it to change the `count` parameter to something larger than `20` just in case. @JustAnotherArchivist

**Comment by JustAnotherArchivist** [comment]
It only respects values smaller than 20. Anything larger than 20 still returns 20 results.
