### ISSUE TITLE
Getting tweets content (not url) with CLI

### ISSUE THREAD

**Issue by Wotrocool** [JustAnotherArchivist/snscrape#482]
Hello,

I tried several ways to get tweets content, dates, comments counts and so on, while using snscrape with CLI into cmd.exe. 

The only thing I can get is the default results (ie. only urls from tweets that match my request)

I don't find how I should write my command despite reading different articles and tutorials online and i dont want to do it with pyhton in something like jupyter because i don't understand anything about that right now (i am learning...)

I tried things like 

`snscrape twitter-search "monday lang:en content"`

but it doesnt work.

Thank you for your help.

**Comment by Wotrocool** [comment]
Thank you for your answer.

It works well when I use only one argument. For example 

`snscrape --format '{content}' twitter-search "monday lang:en"`

But here : https://github.com/JustAnotherArchivist/snscrape/issues/175#issuecomment-751534691

You wrote that for multiple arguments, we should use that formula

`--format '{url} {content}'`

Unfortunatly, when i try it, I get this message

```
usage: snscrape [-h] [--version] [--citation] [-v] [--dump-locals] [--retry N] [-n N] [-f FORMAT | --jsonl]
                [--with-entity] [--since DATETIME] [--progress]
                SCRAPER ...
snscrape: error: argument SCRAPER: invalid choice: "{content}'" (choose from 'facebook-community', 'facebook-group', 'facebook-user', 'instagram-hashtag', 'instagram-location', 'instagram-user', 'mastodon-profile', 'mastodon-toot', 'reddit-search', 'reddit-subreddit', 'reddit-user', 'telegram-channel', 'twitter-hashtag', 'twitter-list-posts', 'twitter-profile', 'twitter-search', 'twitter-trends', 'twitter-tweet', 'twitter-user', 'vkontakte-user', 'weibo-user')
```

**Comment by JustAnotherArchivist** [comment]
That command works fine in every standard shell, but Microsoft decided to use different quoting rules in their terminal because of course they did. I think you need to use double quotes. Cf. #316, #128.
