### ISSUE TITLE
Specifying wanted tweets pre scraping

### ISSUE THREAD

**Issue by mateuszzbaraski** [JustAnotherArchivist/snscrape#488]
Hi all, am using snscrape to research links between Twitter sentiments and violent protests. For now I filter talready downloaded tweets to only be english, however out of 10 000 daily tweets I download approximately 500 are in english. Is it possible to pass an argument specifying to scrap only english tweets?
Is it possible to specify somehow to scrap tweets only from a specific region such as Europe, NA or Africa?

**Comment by JustAnotherArchivist** [comment]
Duplicate of #300 and #145
