### ISSUE TITLE
import snscrape.modules.facebook

### ISSUE THREAD

**Issue by JJery-web** [JustAnotherArchivist/snscrape#489]
Thank you for this project.

I found that the function of snscrape crawling Twitter is quite stable. But I currently need to crawl through Facebook accounts. Can **import snscrape.modules.facebookmeet** this need?

Ilook forward to your reply.

**Comment by TheTechRobo** [comment]
It probably works, but Facebook's rate limiting is awful (see #208).

**Comment by JustAnotherArchivist** [comment]
It should work except for the known bugs around their redesign rollout and the rate limiting already mentioned. You can probably expect it to be less stable than Twitter, if only because it sees less use, so fewer bugs have been ironed out.
