### ISSUE TITLE
command works in powershell, bash but not in cmd

### ISSUE THREAD

**Issue by Pii-R** [JustAnotherArchivist/snscrape#496]
I'm on windows.
I run this command  ```snscrape --jsonl --max-results 30 twitter-search '(from:2badGames, OR from:Panini_fr, OR from:PurinaFr) #concours since:2022-06-14 exclude:replies' > test.jsonl```

It works well on Bash and Powershell and I got this error on CMD : ```snscrape: error: unrecognized arguments: OR from:Panini_fr, OR from:PurinaFr) #concours since:2022-06-14 exclude:replies' ```

What has gone wrong ?

**Comment by JustAnotherArchivist** [comment]
`cmd.exe` ~~is stupid and~~ has different quoting rules than essentially every single other shell out there... #128
