### ISSUE TITLE
Support for Telegram

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#50]
```
2019-06-02 15:04:23 UTC  <@JAA> Relevant URLs: https://t.me/s/Telegram/ -> https://t.me/telegram/91 -> https://t.me/s/telegram/91 which then links to older posts.
2019-06-02 15:05:18 UTC  <@JAA> There's also this: https://t.me/s/Telegram?before=91
```

**Comment by Lonami** [comment]
Not sure if using APIs is out of the scope of the project (it seems so, although there isn't a wiki or website explaining it beyond the README), but it would probably help with both speed and places it can reach. Just dropping that here, in case it's of interest.

**Comment by JustAnotherArchivist** [comment]
Yeah, the idea is to not use APIs and instead emulate what browsers do. The main problem and original motivation for writing snscrape is that the APIs of the major social networks (Twitter, Facebook, Instagram) are quite restricted unless you cough up some serious money. In fact, the goal of snscrape isn't even achievable with APIs in some cases; for example, Twitter's standard search API only lets you search through the past week of tweets, and their user timeline endpoint doesn't return the entire tweet history. Last but not least, using APIs would mean that snscrape would have to handle configuration (API tokens) and do so securely, adding complexity that I'd rather avoid.
