### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by steevenakintilo** [JustAnotherArchivist/snscrape#505]
Hi I'm using tweet.date to get the tweet of a date it works fine except when the time is beetween (00:00 to 02:00) idk why it give the time -2 hours so like if a tweet was made today at 00:34 it will say it was made yesterday at 22h34 (I live in france) do you know why?

**Comment by JustAnotherArchivist** [comment]
Well, yes, time zones are a thing. snscrape tries to always return so-called 'aware' `datetime` objects, i.e. with time zone information. Usually, that will be UTC, although there are exceptions (e.g. VK has Moscow Time). If you want it in a particular time zone, you will need to convert it using the `datetime` object's [`astimezone` method](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone). For getting the time zone information, you can use [the `zoneinfo` module](https://docs.python.org/3/library/zoneinfo.html) (or `pytz` for Python 3.8); the relevant zone for France is `Europe/Paris`.

**Comment by steevenakintilo** [comment]
thanks for the answer I found a solution this morning since the time was always 2h late I just added to the time tweet.date gave me and now it work fine

**Comment by JustAnotherArchivist** [comment]
Well, for now. It will be broken for any tweets between October and April every year because France uses a different time zone in winter. So I still recommend doing it properly. But I'll consider this answered.

**Comment by steevenakintilo** [comment]
ah I forgot about that I will try to do things better then or just made things like:
If we are on november add 2 hours
december add 1 hours 
etc ...
