### ISSUE TITLE
how to crawl from the hottest?

### ISSUE THREAD

**Issue by bovixi** [JustAnotherArchivist/snscrape#508]
hi, if I want to start crawling from the hottest, how should I set, change or increase the parameters?

**Comment by JustAnotherArchivist** [comment]
Are you talking about the 'Top' order on Twitter searches or something else?

**Comment by bovixi** [comment]
yes, I wonder how to set "top" order on crawling data ~

**Comment by bovixi** [comment]
<img width="1015" alt="截屏2022-07-06 18 49 05" src="https://user-images.githubusercontent.com/105959735/177553676-fc122c2e-ca2e-4e8c-bd37-5da75926c46c.png">
this is what I set, but I don't know why it collects data starting with the closest date ?  I wonder how does it randomly select at any given time?

**Comment by JustAnotherArchivist** [comment]
See #381
