### ISSUE TITLE
conversation_id

### ISSUE THREAD

**Issue by unipdjahanifar** [JustAnotherArchivist/snscrape#515]
Hi
Could you please let me know whether it is possible to extract the conversation id of the tweets?

**Comment by JustAnotherArchivist** [comment]
Yes, `snscrape.modules.twitter.Tweet` objects have a `conversationId` attribute.

**Comment by czyborra** [comment]
i miss an `snscrape twitter-conversation $id` or `snscrape.modules.twitter.Tweet.responses[]`

**Comment by TheTechRobo** [comment]
You can use `twitter-tweet` with one of the `scroll` options
