### ISSUE TITLE
Code style questions

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#517]
From how I see it, the naming standpoint of snscrape is:

- snake_case in methods
- camelCase in variables
- PascalCase in class names

Is this correct, or am I missing something?

**Comment by JustAnotherArchivist** [comment]
Correct.

One more nuance: properties are 'like variables', so I use `camelCase` for those as well even though they're methods internally (see e.g. `snscrape.modules.twitter.GuestTokenManager`).
