### ISSUE TITLE
ScraperException: 4 requests .. spelling_expansion_revert_click failed, giving up.

### ISSUE THREAD

**Issue by chaituc** [JustAnotherArchivist/snscrape#521]
```
search_start=time.time()

search_term_names="strangerthings"
for search in search_term_names:
    all_tweets = sntwitter.TwitterSearchScraper(search + 'since 2022-06-01').get_items()
    search_end = time.time()
    start_tweets = time.time()
    for i,tweet in enumerate(all_tweets):\
        tweets_list.append({search:tweet})
    end_tweets = time.time
    print("done")
print("making df")
df_start=time.time()
```

keeps giving error :

`Error retrieving https://twitter.com/search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click: SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))")), retrying
starting search
Error retrieving https://twitter.com/search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click: SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))")), retrying
Error retrieving https://twitter.com/search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click: SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))")), retrying
Error retrieving https://twitter.com/search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click: SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))"))
4 requests to https://twitter.com/search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click failed, giving up.
Traceback (most recent call last):

  File "C:\Users\cramkris\.spyder-py3\temp.py", line 19, in <module>
    for i,tweet in enumerate(all_tweets):\

  File "C:\Users\cramkris\Anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 680, in get_items

  File "C:\Users\cramkris\Anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 369, in _iter_api_data
    items = soup.find_all('li', 'js-stream-item')

  File "C:\Users\cramkris\Anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 338, in _get_api_data

  File "C:\Users\cramkris\Anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 301, in _ensure_guest_token
    feed = reversed(soup.find_all('li', 'js-stream-item'))

  File "C:\Users\cramkris\Anaconda3\lib\site-packages\snscrape\base.py", line 99, in _get
    return self._request('GET', *args, **kwargs)

  File "C:\Users\cramkris\Anaconda3\lib\site-packages\snscrape\base.py", line 95, in _request
    raise ScraperException(msg)

ScraperException: 4 requests to https://twitter.com/search?f=live&lang=en&q=ssince+2022-06-01&src=spelling_expansion_revert_click failed, giving up.`

any help on how to resolve this, gives the same error while using in CLI

**Comment by JustAnotherArchivist** [comment]
Are you using a proxy?

**Comment by JustAnotherArchivist** [comment]
https://github.com/JustAnotherArchivist/snscrape/issues/500#issuecomment-1171339955

> Then something on your system is broken. Perhaps your CA certificate collection is outdated. Or the connection gets proxied without your knowledge. Either way, I don't think this is an issue in snscrape or with Twitter as it works fine for me from three continents.

**Comment by chaituc** [comment]
Thanks! It did work on my other system , will look into whats up. Unrelated but Could it be because of different version? it used python 3.9 and my system is 3.8.

**Comment by JustAnotherArchivist** [comment]
Unlikely, but Python's TLS certificate handling changed quite significantly in the last few versions, so if your CA store is weird, it might be version-dependent whether it works. I tested with Python 3.8 on one machine and 3.10 on two others, FWIW.
