### ISSUE TITLE
Request multiple tweets at once?

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#522]
Is it possible to request, say, 20 tweets at a time (TwitterTweetScraper) with one endpoint? I feel it'd be faster than multiple recursive TwitterTweetScrapers sequentially.  (I wouldn't  need the recursion functionality implemented, I could just implement that myself.)

**Comment by JustAnotherArchivist** [comment]
Last time I checked (a few months ago), I didn't see any endpoint like that. A quick check of their JS suggests that this is still true. There's no reason for it to exist on the web interface (unlike fetching multiple users at once), so I'd be surprised if it did.

**Comment by TheTechRobo** [comment]
Alright, good to know.
