### ISSUE TITLE
Twitter poll

### ISSUE THREAD

**Issue by GlennFischer032** [JustAnotherArchivist/snscrape#525]
Hi, is there a way to scrape/detect whether a given twitter post contains a poll?

**Comment by TheTechRobo** [comment]
Have you checked the `Tweet.card` attribute?

Here's the documentation for a Poll card:

https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/modules/twitter.py#L168

**Comment by JustAnotherArchivist** [comment]
Only available in the dev version currently. I hope to get a few bugs fixed and then release a new version, but time's a limited resource at the moment.
