### ISSUE TITLE
how to get replies and retweeted of a tweet of twitter?

### ISSUE THREAD

**Issue by frida96** [JustAnotherArchivist/snscrape#527]
I create an instance of class TwitterSearchScraper and call get_items() method;
it takes much info; but is it possible for replies and retweeted tweets to be taken?
This is part of my code:

```python3
scraper = sntwitter.TwitterSearchScraper(query)
      scraper_items = scraper.get_items()
```

I checked all the issues of this project,
 but unfortunately, I did not understand.
some answers say that this is not possible.
but for example in issue 8; the use of this command is recommended:

    snscrape twitter-search 'from:user include:nativeretweets'

but it returned this error :

    snscrape: error: unrecognized arguments: include:nativeretweets'

I am confused please help me; thanks

**Comment by TheTechRobo** [comment]
Add `include:nativeretweets` to the search query, so your `query` variable.

Are you using Windows' command prompt? Single quotes don't work right there (#128)

To add replies, one way to do it is using `TwitterTweetScraper` on each Tweet ID you get, with either `SCROLL` or `RECURSE` as the [`TwitterTweetScraperMode`](https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/modules/twitter.py#L1607).

**Comment by frida96** [comment]
Thank you very much for your quick reply.
Yes, I am a Windows user! I ran ` snscrape twitter-search "from:user include:nativeretweets" `
(with the double quotation) and It was executed correctly.
But to get retweets;
I noticed that It returns the retweets of a user; But I want to get retweets of a tweet. Is it possible to get the retweets of a tweet?

**Comment by TheTechRobo** [comment]
I think RECURSE gets replies of replies, etc. Not sure on that one though.

Retweets of a tweet are not supported, unfortunately. #103

**Comment by JustAnotherArchivist** [comment]
`RECURSE` does what the name suggests: it recurses through discovered tweets until there is nothing left to retrieve. So yes, it gets replies of replies and so on.

**Comment by frida96** [comment]
I have  another question in extracting replies:
See my code snippet below for extracting replies of a randomly selected tweet:
`           mode = sntwitter.TwitterTweetScraperMode
            sncraper_reply = sntwitter.TwitterTweetScraper(tweetId=1554254427120439297, mode=mode.SCROLL)
            replies = sncraper_reply.get_items()
            number_of_replies = sum(1 for _ in replies)
            for tweet in replies:
                 print(tweet.content)`
this code returned number_of_replies=9;
And I also see the number of tweets through the tweet link and there are some replies: `https://twitter.com/rachaelmesser/status/1554254427120439297`.
But I don't know what happens that it doesn't enter for loop and I am not able to collect the replies.
This happens in many cases And not just for this particular tweet .

**Comment by JustAnotherArchivist** [comment]
`get_items` is a generator function. You can't iterate over it multiple times. Restructure your code to only do one iteration, e.g. everything in one loop or by first collecting all results into a list.

**Comment by v1nc3nt27** [comment]
@JustAnotherArchivist So you mean just doing `list(replies)`? I just picked a random tweet with a lot of replies from elon musk (id = 1552814045354409985) and I only get back 122 replies, which is much less than the tweet actually has. Any idea why this is?

**Comment by JustAnotherArchivist** [comment]
@v1nc3nt27 That should work, I guess. Or just `replies = list(scraper.get_items())`.
The other thing is Twitter being weird. The counters don't reflect how many publicly viewable replies there actually are. I don't work at Twitter, so I don't know the details, but I think it includes protected and shadowbanned accounts, removed spam stuff, and the like. You can generally never expect Twitter to return exactly the number of replies it indicates in the counters. It can easily be off by an order of magnitude.

**Comment by v1nc3nt27** [comment]
@JustAnotherArchivist Ah Ok, I get it. I thought I was just using the library wrong. Thanks a lot for making that clear!

**Comment by frida96** [comment]
yes; I know that method getitems is a generator
But because the object was created from the TwitterSearchScraper class,
don't be returned in for loop; I thought it would also work here.
thank you very much!

**Comment by solaiman-islam** [comment]
### Fields to Scrape from Twitter tweet: **(Please mention appropriate approach and best practice)**

- Every Commenter Name,
- Commenter profile URL,
- Comment time,
- Comment text/content,
- Who Retweets,
- Retweeted Text,
- Retweeter's URL

**Comment by JustAnotherArchivist** [comment]
@solaiman-islam Please read the messages above. 'Comments' (replies) are available through the individual tweet scraper in recursive mode, retweets are not possible.

**Comment by SyrupTheSrc** [comment]
Is there a way to get quote RTs as well?

**Comment by JustAnotherArchivist** [comment]
#540

**Comment by SyrupTheSrc** [comment]
I have read thread but code still fails.

heres my code

`mode = sntwitter.TwitterTweetScraperMode.RECURSE
scraper = sntwitter.TwitterTweetScraper(tweetId=1630589321890746368, mode=mode)
replies = list(scraper.get_items())`

and i get this error

KeyError: 'variables'

**Comment by JustAnotherArchivist** [comment]
That was fixed over a month ago. #684

**Comment by SyrupTheSrc** [comment]
> That was fixed over a month ago. #684

Thank you for your reply.  I read through the comments and issues.  Do I simply update my version of snscrape because it continues to happen.  I am using version 0.5.0.20230113

**Comment by JustAnotherArchivist** [comment]
As mentioned in the comment on that issue, the fix is only in the development version currently. A new release will probably be out tonight.
