### ISSUE TITLE
Unable to get tweets

### ISSUE THREAD

**Issue by abhalawat** [JustAnotherArchivist/snscrape#528]
I am trying to extract previous 1 hour tweets.But it isn't showing any output.
Any Idea how could I resolve that?

```python3
for i, tweet in enumerate(
            sntwitter.TwitterSearchScraper(f'{keyword} since:{datetime.now() - timedelta(hours=1, minutes=10)} until:{datetime.now()}').get_items()):
        print(tweet)
        print(tweet.id)
```

**Comment by JustAnotherArchivist** [comment]
Twitter's `since` and `until` filters expect a date, not a datetime. You probably want `since_time` and `until_time` with Unix timestamps instead.

**Comment by JustAnotherArchivist** [comment]
`since_time` and `until_time` probably only accept ints, not floats.

**Comment by abhalawat** [comment]
It worked! Thank you
