### ISSUE TITLE
error '>' not supported between instances of 'Tweet' and 'Tweet' in using sntwitter.TwitterSearchScraper(query)

### ISSUE THREAD

**Issue by frida96** [JustAnotherArchivist/snscrape#529]
I am extracting tweets and replies with using ;
`sntwitter.TwitterTweetScraper(tweetId=tweet.id, mode=mode.RECURSE)`
and 
`sntwitter.TwitterSearchScraper(query)`
that I got the following error:
`error '>' not supported between instances of 'Tweet' and 'Tweet'`;
Which I think is not dissimilar to problem #474 .
My code snippet is as follows:

```python3
        import snscrape.modules.twitter as sntwitter

        tweets_list = []
        example_query = ''(nasa)(until:2021 - 04 - 04) (since:2021-03-04)(lang: fa)''
        scraper = sntwitter.TwitterSearchScraper(example_query)
        tweets = list(scraper.get_items())
        for tweet in tweets:
            try:
                mentions = self.get_mension(tweet=tweet)

                tweets_list.append(
                    [str(tweet.user.id), str(tweet.date.date()), str(tweet.date.time()), str(tweet.user.location),
                     tweet.user.followersCount, tweet.user.friendsCount, tweet.user.favouritesCount, str(tweet.id),
                     str(tweet.rawContent), tweet.quoteCount, tweet.retweetCount, tweet.likeCount, tweet.replyCount,
                     str(tweet.conversationId), tweet.lang, str(tweet.user.username), tweet.user.profileImageUrl,
                     tweet.hashtags, str(tweet.inReplyToTweetId), mentions])
            except:
                pass
```
I have similar code for replies.
I want that if the code gets this error in a particular tweet, it will skip that tweet and go to the next tweet without raise error.
It is strange that the exception handling I wrote for it did not do this. 
Thank you in advance for your help.

**Comment by JustAnotherArchivist** [comment]
The error indicates that you're comparing `Tweet` objects. And yes, that's not supported because it's unclear to me what that would even sensibly mean. Your code snippet (which isn't valid Python, by the way, as at least the quotes and the indentation are wrong) doesn't do that, so it must be elsewhere in your code.

**Comment by frida96** [comment]
> The error indicates that you're comparing `Tweet` objects. And yes, that's not supported because it's unclear to me what that would even sensibly mean. Your code snippet (which isn't valid Python, by the way, as at least the quotes and the indentation are wrong) doesn't do that, so it must be elsewhere in your code.

I don't have any comparison of tweets in my code; The code above is the only part of my code that uses tweets I think this error may be caused by ;This is a part of the code that I forgot to attach:
`sncraper_recurse_reply = sntwitter.TwitterTweetScraper(tweetId=tweet.id, mode=mode.RECURSE)`
because by deleted it and using from:
 `        sncraper_scroll_reply = sntwitter.TwitterTweetScraper(tweetId=tweet.id, mode=mode.SCROLL)
`
I did not encounter that error again

**Comment by JustAnotherArchivist** [comment]
That shouldn't matter. But your code above is obviously not complete. For example, there's a call to `self.get_mension`, but neither `self` nor `get_mension` are defined in the snippet...
snscrape never does comparisons between `Item`s, so I'm pretty certain this has to be in your code, either with a direct comparison or with `sorted` or similar. Please share your complete code (but the shortest one that still reproduces your issue), else I can't help you.
