### ISSUE TITLE
What happens for tweet id!!!!

### ISSUE THREAD

**Issue by erfan-sams** [JustAnotherArchivist/snscrape#533]
After new updates, I find this! 
tweet.id = 1.477429e+18

this suppose to be something like 
tweet.id = 1542657904481796104

I guess you're using some library that converts real numbers to scientific representation.

**Comment by TheTechRobo** [comment]
That's Python's automatic conversion is it not?

**Comment by JustAnotherArchivist** [comment]
Please post your complete code. snscrape always emits integers for IDs, but this suggests you converted it to a float somewhere.

**Comment by erfan-sams** [comment]
> Please post your complete code. snscrape always emits integers for IDs, but this suggests you converted it to a float somewhere.

You are right that because of pandas dataframe, when I've converted it to the csv file.
But honestly, I don't figure out why that has happened. This just happening in some specific conditions. After 1 year this is the first time it has happened to me.

**Comment by TheTechRobo** [comment]
> Please post your complete code.
