### ISSUE TITLE
Error While extracting tweets

### ISSUE THREAD

**Issue by abhalawat** [JustAnotherArchivist/snscrape#534]
```
Error retrieving https://api.twitter.com/graphql/-xfUfZsnR_zqjFd-IfrN5A/UserByScreenName?variables=%7B%22screen_name%22%3A%22moonbirds%22%2C%22withHighlightedLabel%22%3Atrue%7D: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /graphql/-xfUfZsnR_zqjFd-IfrN5A/UserByScreenName?variables=%7B%22screen_name%22%3A%22moonbirds%22%2C%22withHighlightedLabel%22%3Atrue%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f38de4aaf10>: Failed to establish a new connection: [Errno -3] Try again'))"))

4 requests to https://api.twitter.com/graphql/-xfUfZsnR_zqjFd-IfrN5A/UserByScreenName?variables=%7B%22screen_name%22%3A%22moonbirds%22%2C%22withHighlightedLabel%22%3Atrue%7D failed, giving up.

 4 requests to https://api.twitter.com/graphql/-xfUfZsnR_zqjFd-IfrN5A/UserByScreenName?variables=%7B%22screen_name%22%3A%22moonbirds%22%2C%22withHighlightedLabel%22%3Atrue%7D failed, giving up.
```
I am not able to understand why this error is coming and how this will resolved.
Could you help in this?

**Comment by TheTechRobo** [comment]
Are you behind a proxy? Is your Internet working?

Can you `ping api.twitter.com`

**Comment by abhalawat** [comment]
I am not using any proxy and yes internet is working.And I am able to ping api.twitter.com

**Comment by abhalawat** [comment]
How much time should it take to extract 5years of tweets?

**Comment by TheTechRobo** [comment]
What command are you running that gets that error? Does the problem still occur?

**Comment by JustAnotherArchivist** [comment]
`snscrape --with-entity -n 0 -v twitter-user moonbirds` (which causes exactly that request) works fine here from three continents. Whatever this is, it's something at your end, likely a network issue, either an incorrect configuration or something like a malfunctioning proxy (either your own or someone else's, like your employer or ISP).
