### ISSUE TITLE
scraping multiple hashtags in an OR sense

### ISSUE THREAD

**Issue by alexntougias** [JustAnotherArchivist/snscrape#537]
Hello. I am trying trying to scrape tweets e. I am able to scrape by location and with tweets that contain specific phrase or a single hashtag. My question is how can I scrape tweets that might have tweets from a list I create. For example let s say I want to look for hashtags the following hastags:

hashtags = ('data analytics', 'data science', 'machine learning')

I want to search in an OR sense (the hashtags can be either 1 of those in the list or a combination of those hashtags or all of them). How do I do that?

**Comment by JustAnotherArchivist** [comment]
Hashtags can't contain spaces, so there's that for a start. But other than that, the syntax on Twitter's search is as you might expect from other search engines: `#hashtag0 OR #hashtag1 OR #hashtag2` for example. Can be combined with keywords and filters as well of course; you likely have to put it in brackets then, e.g. `(#hashtag0 OR #hashtag1) keyword`.

**Comment by alexntougias** [comment]
Hello! Thank you for the feedback. I am trying the following code 
pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
            '#nature OR #environment OR #forest OR #countryside OR #outdoor OR #mothernature OR #getoutside OR ' \
            '#goplay OR #outdoorfamilies OR #playoutside OR #natureheals OR #green OR #outdoors OR #wildlife since:2020-01-22 until:2020-04-07 geocode:"{}"'.format(loc)).get_items()

(also TwitterHashtagScraper) however I am getting the following error : KeyError: "None of [Index(['date', 'content'], dtype='object')] are in the [columns]"

**Comment by JustAnotherArchivist** [comment]
That code excerpt is incomplete, but in any case, the snscrape portion of it is working just fine (minus the geocode value that you didn't share), so that has to be something in your use of Pandas.

```
>>> import snscrape.modules.twitter
>>> s = snscrape.modules.twitter.TwitterSearchScraper(
...             '#nature OR #environment OR #forest OR #countryside OR #outdoor OR #mothernature OR #getoutside OR ' \
...             '#goplay OR #outdoorfamilies OR #playoutside OR #natureheals OR #green OR #outdoors OR #wildlife since:2020-01-22 until:2020-04-07')
>>> t = next(s.get_items(), None)
>>> t
Tweet(url=<snip...>)
```
