### ISSUE TITLE
How to get the first tweet (or date of the first tweet ) that was tweeted with the "sample" word in twitter?

### ISSUE THREAD

**Issue by frida96** [JustAnotherArchivist/snscrape#539]

**Comment by JustAnotherArchivist** [comment]
There is no easy way to do this. What you can do is run several scrapes with the `until` filter starting with values in 2006 (when Twitter launched) and increasing until you get results, then run that scrape to the end. (Of course, this may not get you the true first tweet if that got deleted but rather the oldest *surviving* tweet.)
