### ISSUE TITLE
way to get quote retweets for a specific tweet

### ISSUE THREAD

**Issue by hwork222** [JustAnotherArchivist/snscrape#540]
Is there a way to get quote retweets for a specific tweet?(with a specific Tweet ID)

↓what i want

```python3
for i, tweet in enumerate(sntwitter.TwitterTweetScraper(tweetId=tweet_ID).get_items()):
    print(<quote-tweet.content>) 
```

**Comment by JustAnotherArchivist** [comment]
You can run a search with the `quoted_tweet_id` filter, e.g. [`quoted_tweet_id:1563637504267677696`](https://twitter.com/search?q=quoted_tweet_id:1563637504267677696&f=live).

**Comment by hwork222** [comment]
Thank you.
How are filters used in programs?
sntwitter.TwitterTweetScraper()?
sntwitter.TwitterSearchScraper()?

> `quoted_tweet_id`フィルタを使用して検索を実行できます[`quoted_tweet_id:1563637504267677696`](https://twitter.com/search?q=quoted_tweet_id:1563637504267677696&f=live)。

**Comment by JustAnotherArchivist** [comment]
It's a search filter from Twitter, so yes, `snscrape.modules.twitter.TwitterSearchScraper`.

**Comment by hwork222** [comment]
Thank you for your detailed explanation.
The program below worked fine.

tweets_list = []
for i, tweet in enumerate(sntwitter.TwitterSearchScraper("quoted_tweet_id:1564176531504525312").get_items()):
    if i > 10:
        break
    tweets_list.append([tweet.url, tweet.content, tweet.user.username])
