### ISSUE TITLE
Extract only mentioned user's username twitter

### ISSUE THREAD

**Issue by silkywork** [JustAnotherArchivist/snscrape#543]
Hello, 

First of all, thank you for this awesome tool. 
When scraping tweets, the mentioned users are displayed as an object if I understand correctly. I went through the code trying to figure out how to keep only the username (without the url at the beginning). 

My understanding is that it is contained in a class (Tweet) but I cannot call only the username. As you mentioned in an other issue, I tried to call it using a loop:

```python3
if tweet.mentionedUsers:
          for user in tweet.mentionedUsers:
```

Is there any solution to print only the username? Thank you very much.

**Comment by JustAnotherArchivist** [comment]
```python3
if tweet.mentionedUsers:
	for user in tweet.mentionedUsers:
		print(user.username)
```

**Comment by silkywork** [comment]
Thanks for you answer! 

Actually this is what I've been trying yesterday. 

`for i,tweet in enumerate(sntwitter.TwitterSearchScraper(x).get_items()):
    if i>maxTweets:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username, tweet.mentionedUsers, tweet.likeCount, tweet.retweetCount, tweet.replyCount, tweet.lang, tweet.place, tweet.coordinates, tweet.retweetedTweet])
    
    if tweet.mentionedUsers:
        for user in tweet.mentionedUsers:
            print(user.username)`

But when I do so and then create a DataFrame, it still prints out the url before the user.username. 

The solution I've found is to modify the module twitter.py as such:

`@property
	def url(self):
		return f'https://twitter.com/{self.username}'`

to 

'@property
	def url(self):
		return f'{self.username}'

and it seems to work as expected. 

I am new to python so I am trying my. best to find a solution, and what I did might be wrong ... Do you have any suggestion or did I miss anything while trying to apply the loop? (I would prefer to use a loop instead of modifying the module file as I am afraid to break anything in the code ... 

Thanks again for taking the time to consider my issue.

**Comment by silkywork** [comment]
Thanks!

**Comment by silkywork** [comment]
Another tried option, but it is still printing the url. 

```
 for i,  tweet in enumerate(sntwitter.TwitterSearchScraper(x).get_items()):
    if i>maxTweets:
        break    
    if tweet.mentionedUsers:
        for user in tweet.mentionedUsers:
            print(user.username)    
        
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.mentionedUsers, tweet.likeCount, tweet.retweetCount, tweet.replyCount, tweet.lang, tweet.place, tweet.coordinates, tweet.retweetedTweet])
    ```

**Comment by JustAnotherArchivist** [comment]
You're appending `tweet.mentionedUsers` to your list. That's a list of `User` objects, not a list of usernames. I assume it's later converted to strings somewhere in Pandas or whatever, and the string representation of a `User` is the profile URL.

The other part is working perfectly fine:

```python3
import snscrape.modules.twitter


for tweet in snscrape.modules.twitter.TwitterSearchScraper('from:textfiles').get_items():
	if tweet.mentionedUsers:
		for user in tweet.mentionedUsers:
			print(user.username)
```

You probably want to replace `tweet.mentionedUsers` in your `list.append` call with something like `[user.username for user in tweet.mentionedUsers] if tweet.mentionedUsers else []` or, a bit shorter but less readable, `[u.username for u in tweet.mentionedUsers or []]`.

**Comment by silkywork** [comment]
That is exactly what I wanted. Thank you so much!
