### ISSUE TITLE
The difference in the number of results returned from snscrape and Twitter.com

### ISSUE THREAD

**Issue by frida96** [JustAnotherArchivist/snscrape#545]
Hello.
Why do I get 808 tweets when I crawl with snscrape.TwitterSearchScraper() for #السنكيس_في_خطر hashtag?
While this number is very small and the number of results for this hashtag was expected to be very high.
Also, my second question; why do I search for the same hashtag in Advanced Search on Twitter, and by scrolling to the bottom of the Twitter page, it returns a maximum of 38 tweets as result.
How can I get more results?
Can I get more results by entering small date intervals?
thanks.

**Comment by JustAnotherArchivist** [comment]
808 is what I get as well. And it seems to roughly match what I see in a browser. Note that the search on the web interface is very broken. You sometimes have to scroll up and back down (possibly several times) to make it load the next results.
You could try searching in time intervals, but I'm not sure it will make a difference. Simple searches for hashtags are usually quite reliable.
