### ISSUE TITLE
Twitter scrape `NewsletterCard` `TypeError: __init__() missing 1 required positional argument: 'imageUrl' `

### ISSUE THREAD

**Issue by dk-0x89** [JustAnotherArchivist/snscrape#546]
Hello, everyone,

I got this error for the first time today. I think it's because the user didn't set a banner. But I'm not really sure.

I checked via pip if there is an update, this is not the case. Since it always works with all other users, I guess I have to contact you :( do you need to specify anything else?

```
userName = JHSchneiderMdL

    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:'+userName).get_items()):
  File "/usr/local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 1450, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)
  File "/usr/local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 804, in _v2_timeline_instructions_to_tweets
    yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
  File "/usr/local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 827, in _v2_instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)
  File "/usr/local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 1269, in _tweet_to_tweet
    kwargs['card'] = self._make_card(tweet['card'], _TwitterAPIType.V2, self._get_tweet_id(tweet))
  File "/usr/local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 1095, in _make_card
    return NewsletterCard(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'imageUrl'
```

okay i did some more research because i'm dumb. It's not because of the banner, of course, but because of this tweet:
https://twitter.com/JHSchneiderMdL/status/1417081450449575940

This has no picture and apparently there is simply no query in front of it as to whether the picture is set or not.

```
 elif cardName == '3337203208:newsletter_publication':
                        kwargs = _kwargs_from_map({'newsletter_title': 'title', 'newsletter_description': 'description', 'newsletter_image_original': '>
                        kwargs['revueAccountId'] = int(kwargs['revueAccountId'])
                        kwargs['issueCount'] = int(kwargs['issueCount'])
                        if 'imageUrl' not in kwargs:
                                kwargs['imageUrl'] = None
                        return NewsletterCard(**kwargs)

```

I have now helped myself by simply adding these lines of code.
I saw that you did something similar above ;)
But I didn't push it because I don't know if that's what the inventor intended.

But praise for you! I like your module very much, is it possible to leave a donation somewhere?

**Comment by JustAnotherArchivist** [comment]
Thanks for the report, I hadn't encountered such cards in my tests. I implemented a cleaner fix. And I'm not sure why it's done the way you suggested for broadcast cards; there's no good reason for that I think. Will look into that as well.
