### ISSUE TITLE
Proxies on snscrape

### ISSUE THREAD

**Issue by WilliamBoston11** [JustAnotherArchivist/snscrape#548]
Hello, can I install a proxy when I request to twitter? If so, you can show me how to do it.

**Comment by TheTechRobo** [comment]
If you're using the CLI, use the Requests environment variables:

```
export HTTP_PROXY='PROXY URI'
export HTTPS_PROXY='PROXY URI'
```

(To disable SSL verification, which is an awful idea, use `export CURL_CA_BUNDLE=""`. Better to fix your SSL configuration, though.)

If you're using the Python library, there should be a `proxies` keyword argument you can pass.

**Comment by WilliamBoston11** [comment]
> Если вы используете интерфейс командной строки, используйте переменные среды Requests:
> 
> ```
> export HTTP_PROXY='PROXY URI'
> export HTTPS_PROXY='PROXY URI'
> ```
> 
> (Чтобы отключить проверку SSL, что является ужасной идеей, используйте `export CURL_CA_BUNDLE=""`. Однако лучше исправить конфигурацию SSL.)
> 
> Если вы используете библиотеку Python, должен быть `proxies`аргумент ключевого слова, который вы можете передать. Я думаю, вам нужно пройти набор. (Набор похож на список, но может быть только один элемент каждого элемента. Синтаксис такой `{"apples", "bananas"}`)

In which function should I add the proxy argument ?

**Comment by JustAnotherArchivist** [comment]
You pass `proxies` to the scraper, and it must be a dict that conforms to [Requests's expectations](https://requests.readthedocs.io/en/latest/user/advanced/#proxies). For example:

```python3
scraper = snscrape.modules.twitter.TwitterSearchScraper('query', proxies = {'https': 'http://proxy.example.org'})
```

(All requests made by snscrape are currently using HTTPS, not HTTP, so there's currently no need to also specify the latter.)

**Comment by WilliamBoston11** [comment]
> You pass `proxies` to the scraper, and it must be a dict that conforms to [Requests's expectations](https://requests.readthedocs.io/en/latest/user/advanced/#proxies). For example:
> 
> ```python
> scraper = snscrape.modules.twitter.TwitterSearchScraper('query', proxies = {'https': 'http://proxy.example.org'})
> ```
> 
> (All requests made by snscrape are currently using HTTPS, not HTTP, so there's currently no need to also specify the latter.)


There is no proxies argument in Twitter Search Scraper. What to do?

**Comment by TheTechRobo** [comment]
What version of snscrape are you using?

**Comment by WilliamBoston11** [comment]
> What version of snscrape are you using?

Snscrape version 0.4.3.20220106

**Comment by TheTechRobo** [comment]
Please try the development version. Support for proxies was added a few days after that release. (That release looks like it was January 6th, while the PR was merged on January 13th.)

**Comment by WilliamBoston11** [comment]
> Please try the development version. Support for proxies was added a few days after that release. (That release looks like it was January 6th, while the PR was merged on January 13th.)

Please tell me how can I install snscrape for development

**Comment by TheTechRobo** [comment]
https://github.com/JustAnotherArchivist/snscrape#installation

**Comment by WilliamBoston11** [comment]
> https://github.com/JustAnotherArchivist/snscrape#installation

Thank you!

**Comment by ramandada** [comment]
@JustAnotherArchivist @TheTechRobo  

Errors: blocked (404), blocked (404), blocked (404), blocked (404)
how to resolve this issue

**Comment by ramandada** [comment]
@JustAnotherArchivist @TheTechRobo 

Errors: blocked (404), blocked (404), blocked (404), blocked (404)

facing this issue 
can you please help me with this

**Comment by JustAnotherArchivist** [comment]
@ramandada Please stop spamming and read the issues you've been linked. In particular, #783.
