### ISSUE TITLE
Add snscrape version to its JSONL

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#550]
This would be really helpful for programs that scrape snscrape's JSONL, as it's changed several times.

**Comment by JustAnotherArchivist** [comment]
I've been thinking about this, and I'm not sure. It would make sense if snscrape returned a single JSON object (like yt-dlp does). Including it in every JSONL line seems a bit silly. An extra line with a special version object would break many workflows for obvious reasons.

**Comment by TheTechRobo** [comment]
> Including it in every JSONL line seems a bit silly

I disagree, since there's the option of appending to an existing file.
