### ISSUE TITLE
Snscrape not retrieving tweets 

### ISSUE THREAD

**Issue by adaline2** [JustAnotherArchivist/snscrape#553]
Please help i am new here
I tried to stream tweets using Snscrape but only got the headings i labeled them.
Code worked fine, no error messages
Df.head()
![IMG_20220915_225831](https://user-images.githubusercontent.com/113633201/190524006-07f0538a-4790-4d9e-bb7c-95160c1d0c19.jpg)
#

**Comment by JustAnotherArchivist** [comment]
Remove the spaces around the colon after `until`:

```python3
query = '(#BBNaija) until:2022-08-10 since:2022-08-03'
```

**Comment by adaline2** [comment]
I did that. Now it brings
Name error message, snstwitter is not defined and df is not defined too
![IMG_20220916_080509](https://user-images.githubusercontent.com/113633201/190579881-72385dbf-14bf-4ec3-a214-72344fac1d3f.jpg)

**Comment by adaline2** [comment]
Thanks so much for helping
It's giving me  NameError sntwitter not defined and pd not defined too. Now

**Comment by adaline2** [comment]
It has worked thanks much
