### ISSUE TITLE
Please My Excel filters is not coming with counts can anyone help me! 

### ISSUE THREAD

**Issue by adaline2** [JustAnotherArchivist/snscrape#558]
![IMG-20220921-WA0013](https://user-images.githubusercontent.com/113633201/191546600-efa6de61-418c-4e2d-a098-114984bcb568.jpeg)
Before it will appears with the number of counts 
In bracket but now it's not showing.
How can i resolve this?

**Comment by JustAnotherArchivist** [comment]
I don't see how this could possibly relate to snscrape. If you produce CSV output or similar, you're on your own.
