### ISSUE TITLE
Some accounts are not showing on Twitter scrapper

### ISSUE THREAD

**Issue by Unixcision** [JustAnotherArchivist/snscrape#561]
Hello, good afternoon,
I have a python bot that runs every 20 seconds reading the last 20 Tweets on the search "dfx OR $dfx OR #dfx OR dfxfinance OR @DFXFinance". The program works correctly and returns the most followed accounts that mention the indicated words. However, some Telegram accounts do not appear, as is the case with:
https://twitter.com/Crypto__emily
That is, my bot, before filtering any content, shows with a print each tweet from each account it is browsing, and accounts like that or @dfxfinancenews are "hidden" from the search, from snscrape. However, I can see the Tweets from the server that I run the bot by doing the Twitter search manually.
I have reviewed it and they are not accounts marked as sensitive or pornographic content, so I do not see the point. Any clues?

Note:
If I add a "from:Crypto__emily", then it correctly displays those Tweets, of "from:dfxfinancenews" but they are omitted from the normal search.
`scraper = snscrape.modules.twitter.TwitterSearchScraper('dfx OR $dfx OR #dfx OR dfxfinance OR @DFXFinance').get_items()
`
I've also tried filtering by date, expanding the number of filtered Tweets to 100 or even 200, and I can't get it to work.
Thanks

**Comment by JustAnotherArchivist** [comment]
I don't know what this is exactly, but Twitter's search is weird sometimes. https://twitter.com/search?q=dfx%20OR%20%24dfx%20OR%20%23dfx%20OR%20dfxfinance%20OR%20%40DFXFinance&f=live does not return any Crypto__emily or dfxfinancenews tweets either. So I think snscrape is behaving correctly here, and Twitter's just broken. There is a tendency for that to happen on 'complex' queries, but I'm not sure that's the cause in this case.

**Comment by Unixcision** [comment]
Hi @JustAnotherArchivist,
![image](https://user-images.githubusercontent.com/14082251/192968944-16ce9a21-a8c9-40a8-8764-a0a1c7680c50.png)
As you can see it returns content on my side, as well as the bot, which is reading all the Tweets and posting it into a Telegram channel. However, Tweets from accounts like @dfxfinancenews or @crypto__emily are not shown, while the rest are posted without any problem.

If I run these two scrappers:
```
scraper = snscrape.modules.twitter.TwitterSearchScraper('dfx OR $dfx OR #dfx OR dfxfinance OR @DFXFinance since:2022-09-26 -from:@dfxfinance -from:@dfxfinancenews').get_items()

scraper2 = snscrape.modules.twitter.TwitterSearchScraper('from:Crypto__emily dfx OR $dfx OR #dfx OR dfxfinance OR @DFXFinance since:2022-09-26').get_items()
```
Then it works perfectly and it shows Crypto__emily Tweets as well as the others, but does not make sense, the first one should also show the ones of the second scrapper.

**Comment by JustAnotherArchivist** [comment]
Yes, I also get results, but as I said, there are no tweets from dfxfinancenews or Crypto__emily included.

It does not make sense, but this is a bug on Twitter's side. There is nothing snscrape can do about this. snscrape correctly returns all tweets that Twitter displays on that search as far as I can see.

See also #4 and #468 for other Twitter search bugs.
