### ISSUE TITLE
tweet fields like context_annotations

### ISSUE THREAD

**Issue by VAMSIKRISHNAPALLENI** [JustAnotherArchivist/snscrape#563]
In Twarc2 there are so many tweets fields available and the snscrape is only giving limited number of fields, how can we add more number of tweeter fields and especially context_annotations is field is crucial to over project so how can we enhance these fields?

**Comment by JustAnotherArchivist** [comment]
snscrape can only extract what the unofficial API behind the web interface returns. I don't see the annotations anywhere in those responses. So no, I don't think that can be added. But if you know of a way to get this data without authentication, I can look into it.

**Comment by hassanadnan** [comment]
> snscrape can only extract what the unofficial API behind the web interface returns. I don't see the annotations anywhere in those responses. So no, I don't think that can be added. But if you know of a way to get this data without authentication, I can look into it.

Can you guide how to extract likes from the TwitterSearchScrapper?

**Comment by JustAnotherArchivist** [comment]
Closing this since there doesn't seem to be a way to access that information without auth.
