### ISSUE TITLE
Question about the tweet.id

### ISSUE THREAD

**Issue by ronming1303** [JustAnotherArchivist/snscrape#567]
Hey guys,

I use below code and it works fine. However, I can't figure out the meaning of "tweet.id", it is inconsistent with the id of that tweet which is shown in twitter's web URL.

```
maxTweets = 100

tweets_list1 = []

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:elonmusk').get_items()):
    if i>maxTweets:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.likeCount, tweet.retweetCount, tweet.replyCount])
```

**Comment by JustAnotherArchivist** [comment]
How is it inconsistent?

**Comment by ronming1303** [comment]
> How is it inconsistent?

Hello Sir, I think I made a mistake when using your library. Now I fix it and it works perfectly. Thank you so much for your quick response and sharing your effort. 

Good luck to you!

**Comment by JustAnotherArchivist** [comment]
Fun fact: that quote is wrong. The JSON specs don't restrict the range of numbers in any way. ECMA-404 doesn't even mention anything about it, and RFC 8259 only notes that there may be interoperability problems. But the value of a JSON `number` in both can have arbitrary length and precision.
