### ISSUE TITLE
ModuleNotFoundError: No module named 'snscrape.modules'; 'snscrape' is not a package

### ISSUE THREAD

**Issue by KimGladen** [JustAnotherArchivist/snscrape#568]
Hi, 
I've used snscrape on a different project and it was working as it should. Recently I created a new project on Pycharm using python 3.10 and tried both snscrape and dev but faced the issue as per titled.

**Comment by TheTechRobo** [comment]
Do you have a file named `snscrape.py` ? If so,t hat's your problem.

**Comment by TheTechRobo** [comment]
For reference, it's because Python looks in the current directory first when deciding where to import modules from - if you have a file named `snscrape.py`, python sees that and ignores any other modules named `snscrape`.
