### ISSUE TITLE
sncrape is returning lorem ipsum text

### ISSUE THREAD

**Issue by Hammadoo** [JustAnotherArchivist/snscrape#569]
Hi, i am using snscape for a university project. Scrapping tweets from user's timelines.
I am getting an issue that after running the code it returns lorem ipsum text. 

I was able to scrape 1.2 million+ tweets and it was working fine then but it is returning lorem ipsum now .
![image](https://user-images.githubusercontent.com/96050500/196183823-8c61ff08-abd6-49d4-bd24-73ff8b362b97.png)

**Comment by JustAnotherArchivist** [comment]
Well, I can guarantee you that snscrape does not contain *lorem ipsum*. So this would be coming from Twitter. And there are a bunch of people tweeting that: https://twitter.com/search?q=%22Lorem%20ipsum%20is%20a%20placeholder%20text%22&f=live

Which user are you scraping?
