### ISSUE TITLE
Scraping tweets from specified timeline only return tweets from a random date 

### ISSUE THREAD

**Issue by KimGladen** [JustAnotherArchivist/snscrape#571]
Theses were the results that I expected, and got it by chance.
![date_filter_workng2](https://user-images.githubusercontent.com/60123734/196358895-30c04e6c-ddaa-404e-9578-54d8d82fc088.jpg)

These were mostly the results that were returned.
![random_date](https://user-images.githubusercontent.com/60123734/196358852-2a184a1f-0cc7-474b-9010-a7cbaefb1e1a.JPG)

I know that to scrape tweets from a timeline, I have to use the `since:` and `until:`, but it seems to only return a single date every time I run the code. (I'm using snscrape as a wrapper and not from CLI)

**Comment by JustAnotherArchivist** [comment]
Please share your code then.

**Comment by KimGladen** [comment]
Hi, here is the code that I'm currently using:
![extract_code](https://user-images.githubusercontent.com/60123734/196500940-af44a273-0fec-40cc-8efd-da590cd86aa3.JPG)

I tinkered with this code and added location `near:` and radius `within:` and it manages to pull tweets within the specified date. Prior to this, I did not include location and radius parameters and it will only pull tweets from a single day. 

Based on my observations I believe the loop terminates when:
1. it has cycled through the specified date
2. reaches the specified limit 

So perhaps when pulling tweets with only a keyword and specified date it will most likely be the second outcome? since the number of tweets within specified dates would be too large that it will terminate at the specified limit. In that case will the limit need to be raised to hundred thousands or even in the millions? in order to capture the whole range of dates?

**Comment by JustAnotherArchivist** [comment]
Well yes, if you break your loop after ten thousand results, you only get ten thousand results. And if there are many search results, those might all be tweets from a single day. If you want to get everything, don't break out of the loop early at all.
