### ISSUE TITLE
snscrape twitter does not scrape full volume of tweets for tweets dated more than 1 month ago

### ISSUE THREAD

**Issue by keanepotato** [JustAnotherArchivist/snscrape#574]
Hi, I am trying to scrape tweets from the start of 1st Jan 2014 to today. I realise, after performing the scraping option `df_tweets = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper('climate change since:2014-01-01 until:2022-10-21 geocode:"{}" lang:en'.format(loc)).get_items(),None))[['user', 'date','content']]` , with geolocation at the centre of the United States, that I am able to obtain an extremely high number of tweets for the past month, but beyond the past month, the volume of tweets significantly reduces, indicating that the scraper isn't returning ALL of the tweets which were made. Is there a way I can fix this?

![image](https://user-images.githubusercontent.com/89380565/197217334-c701e6f6-9a79-4ebb-94e8-657e8dca1717.png)

**Comment by keanepotato** [comment]
Also, could I understand why it is behaving this way, and how is the scraper obtaining the tweets that are dated more than 1 month ago? (i.e is it a completely random sample of tweets for each time period that is more than 1 month ago?)

**Comment by JustAnotherArchivist** [comment]
snscrape simply retrieves what a search on Twitter's web interface would show, and their search is sometimes weird and unreliable, see numerous other issues filed here. Geolocation filtering in particular was always unstable (cf. #145). I'm not sure what's causing this particular effect, but unless you get different results in a browser, it's just another bug on Twitter's side that can't be worked around.

**Comment by keanepotato** [comment]
> snscrape simply retrieves what a search on Twitter's web interface would show, and their search is sometimes weird and unreliable, see numerous other issues filed here. Geolocation filtering in particular was always unstable (cf. #145). I'm not sure what's causing this particular effect, but unless you get different results in a browser, it's just another bug on Twitter's side that can't be worked around.

Hey, thanks for the clarification. When you say a search on Twitter's web interface, do you mean using the advanced search function? Also, are the 'top' results returned or the 'latest' results returned? Thanks once again for your help!
