### ISSUE TITLE
twitter-user does not return all tweets

### ISSUE THREAD

**Issue by ejoebstl** [JustAnotherArchivist/snscrape#581]
Hello, 

We recently stumbled over the following issue: 

```
snscrape --jsonl twitter-user chmlaw | wc -l
```

Returns 8 tweets. 

[Ther user has 12 tweets](https://twitter.com/chmlaw). I can't see a pattern why certain tweets are returned and others are not.

**Comment by JustAnotherArchivist** [comment]
Duplicate of #468 and others. Twitter's search is weird and not entirely reliable. See also https://twitter.com/search?q=from:chmlaw&f=live displaying no results randomly.

**Comment by ejoebstl** [comment]
Gotcha, thank you for pointing this out!
