### ISSUE TITLE
Twitter scraping with `lang: ar` filter also returns other languages

### ISSUE THREAD

**Issue by Kutayykilic** [JustAnotherArchivist/snscrape#585]
Hi there,

I have read this problem that occurred with the package, just wanted to let you know.  I tried to answer it using my knowledge but your help will be much appreciated over there:
[Stackoverflow question](https://stackoverflow.com/questions/74170116/scraping-tweets-in-the-arabic-language/74343484#74343484)

**Comment by TheTechRobo** [comment]
(I put this in an answer over there) There can't be a space between `lang:` and `ar`. It needs to be just `lang:ar`
