### ISSUE TITLE
Getting alt text from gif media in twitter

### ISSUE THREAD

**Issue by prateek-joshi** [JustAnotherArchivist/snscrape#588]
This module is amazing, great work! I have a bot scraping gifs from trending tweets. I was wondering if there is a way to also get the alt text (description text) of media, this will help me with metadata creation and tag generation. Thanks!
![image](https://user-images.githubusercontent.com/70139937/200740043-54c60a42-080f-4d44-97af-9bcb0b02e5a9.png)

PS: Sorry for the huge screenshot, didn't know how to reduce its size.

**Comment by JustAnotherArchivist** [comment]
This has been on my todo list for a while, but looks like I never filed it as an issue here. Not currently possible but definitely planned.

**Comment by prateek-joshi** [comment]
I see. Thank you for the quick reply!
