### ISSUE TITLE
Support for VKontakte communities

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#59]
There are three different types of communities apparently, which should all be supported: https://vk.com/faq12817 / https://vk.com/pages?oid=-59800369&p=%D0%92%D1%8B%D0%B1%D0%BE%D1%80_%D0%B2%D0%B8%D0%B4%D0%B0_%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%B0

https://vk.com/yandex is a "public page", I think. If you have any examples for the other two types, "groups" and "events", that would be much appreciated.

**Comment by JustAnotherArchivist** [comment]
Public pages like https://vk.com/yandex can already be scraped with the existing `vkontakte-user`.

**Comment by JustAnotherArchivist** [comment]
I still haven't come across any examples that didn't work with the existing `vkontakte-user` scraper, so until someone finds some, I'll close this.

**Comment by vaino2** [comment]
I'm scraping vkontakte with `vkontakte-user`. It works but I'm getting tons of warnings like this: 

> 2022-04-23 15:20:28.387  WARNING  snscrape.modules.vkontakte  Skipping non-photo and non-video thumb wrap on https://vk.com/wall-133441491_134624 

Also it seems photo urls are not included in the data.

I'm using snscrape version 0.4.3.20220107.dev45+ged3ea94

**Comment by JustAnotherArchivist** [comment]
@vaino2 Please file a separate issue for that. It has nothing to do with this issue.
