### ISSUE TITLE
How to scrape tweets between specific dates and with a likes count filter?

### ISSUE THREAD

**Issue by annanasi-mon** [JustAnotherArchivist/snscrape#592]
I would like to scrape tweets from a certain date range and only those who have more than 10 like. How to specify a query like this?
I tried using query with only dates specified and the other when there is only likes amount specified, however combining this two conditions in a query doesn't work. How to combine it then?
Here is what I've tried to do:

start_date = datetime.strptime("2022-01-01", '%Y-%m-%d')
data_sentiment = pd.DataFrame(columns = ['url', 'date', 'content', 'id', 'username', 'outlinks', 'outlinksss', 'tcooutlinks', 'tcooutlinksss'])
tweets = []
maxTweets = 10

for single_date in (start_date + timedelta(n) for n in range(3)):
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper( f'"#bitcoin since:{single_date} until:{end_date} (min_faves:10) lang:en"').get_items()):
    if i>maxTweets:
      break
    tweets.append([tweet.date, tweet.id, tweet.content, tweet.username])

But it returns an empty list. Am I writing the query correctly?

**Comment by JustAnotherArchivist** [comment]
I guess you already figured it out since you closed the issue, but the issue are the double quotes surrounding the query string.
