### ISSUE TITLE
Output counts

### ISSUE THREAD

**Issue by OliverMuwo** [JustAnotherArchivist/snscrape#593]
First of all, great job of creating an amazingly useful tool! 
I have one question: Is it possible to output only a count (e.g. a Twitter tweet count) for a search?

**Comment by JustAnotherArchivist** [comment]
No, but each result gets printed as one line by default, so you can simply pipe the output to a tool that counts lines, e.g. `snscrape twitter-search foo | wc -l`. This does still run the full scrape, and there's no way to avoid that.

**Comment by OliverMuwo** [comment]
Thanks a lot!
