### ISSUE TITLE
Twitter search limitations?

### ISSUE THREAD

**Issue by aydv** [JustAnotherArchivist/snscrape#599]
Twitter search provide only a subset of all results for a search query for any given day.. Search for a particular query over multiple days and comparing data from other sources, it looks like twitter search for a particular query/word is hovering around 80k for a given day. Little variance of 20-30k is observe but average over multiple days, it is around 80k, when there are  more than a 500k mention for that word over a day. I know twitter search is broken, just wanted to know if any one else has faced this issue recently and any ways to get around it.

**Comment by rroell** [comment]
Hi, I am having the same issue:

I am trying the scrape tweets that mention a particular word. However, I only get about 20/30% of the tweets.

**Comment by JustAnotherArchivist** [comment]
See also #616 and #574
