### ISSUE TITLE
Cant rip a twitter profile

### ISSUE THREAD

**Issue by nihelmasell** [JustAnotherArchivist/snscrape#60]
Hi, I can't rip the URLs for the following profile https://twitter.com/Car*lucha*For*te (please remove asterisks). Its not a private profile and I tried ripping other profiles using big caps with no problems. Can you tell me what's happening? Best Regards

**Comment by JustAnotherArchivist** [comment]
Hi, I'm unable to reproduce this. `snscrape -n 10 -v twitter-user CarluchaForte` works fine here and produces the ten most recent tweets from that account. Can you try again please? If it works now, it might be another temporary case of #4.

**Comment by nihelmasell** [comment]
> Hi, I'm unable to reproduce this. `snscrape -n 10 -v twitter-user CarluchaForte` works fine here and produces the ten most recent tweets from that account. Can you try again please? If it works now, it might be another temporary case of #4.

Yeah, you are right, sorry my mistake. I used the full url instead of just the username. I think I was tired that night.

**Comment by JustAnotherArchivist** [comment]
No problem. :-)
