### ISSUE TITLE
Unknown result type 'TweetTombstone' while using the TwitterUserProfileScraper

### ISSUE THREAD

**Issue by ronnypollak** [JustAnotherArchivist/snscrape#603]
Hello!

I am using the TwitterUserProfileScraper to fetch the tweets and retweets of certain users.
It works fine until I encounter the error "Unknown result type 'TweetTombstone'".
As I have seen in another issue already I assume this means I fetched a deleted tweet.

My question is, how do I handle this TweetTombstone without encountering errors?

The code I am using is the following:

```python3
for handle in linke_handles:
    for tweet in enumerate(sntwitter.TwitterProfileScraper(handle).get_items()):
        if date_start < tweet[1].date < date_end:
            tweets_list1.append(tweet[1])
```

Here you can see the error:

![image](https://user-images.githubusercontent.com/51246474/204564522-d96118c1-79c4-4977-a081-e1da82009b15.png)
![image](https://user-images.githubusercontent.com/51246474/204563219-d3d6cceb-75c2-4131-a0d2-6fd7e3b1c5ae.png)

**Comment by JustAnotherArchivist** [comment]
What's your snscrape version, and do you have some examples of profiles that trigger this?

**Comment by ronnypollak** [comment]
Hello, my snscrape version is 0.4.3.20220106. For example, the user handle "SevimDagdelen" triggers this Exception.
