### ISSUE TITLE
Fandom support

### ISSUE THREAD

**Issue by upintheairsheep** [JustAnotherArchivist/snscrape#607]
Examples of Fandom: https://apple.fandom.com/f
https://backrooms.fandom.com/f
https://backrooms.fandom.com/wiki/Level_0 (comments)
https://backrooms.fandom.com/wiki/User:Egglord (user DMs)
Make sure to include both the post URLs and the JSON files of the items that cannot be linked directly.

**Comment by JustAnotherArchivist** [comment]
I don't think so. Fandom is first and foremost a wikifarm. It happens to also have some social features, but I don't think it can seriously be considered a social network.

**Comment by upintheairsheep** [comment]
You should put a list of qualifications to be a “social network site” on the readme

**Comment by TheTechRobo** [comment]
Just because a website has comments, DMs, etc doesn't make it a social network (IMO). Look at a website's main purpose. Is it a wiki? Is it a hosting company? Then it's probably not a social network in my view.
