### ISSUE TITLE
Question: Could we merge our extractors with yt-dlp?

### ISSUE THREAD

**Issue by upintheairsheep** [JustAnotherArchivist/snscrape#608]
Hello, this is a question that I'm asking about snscrape, and I feel like yt-dlp would benefit from the Twitter, Reddit, and Facebook scrapers, as yt-dlp does not currently have support for "playlists" for those platforms. I used it in congestion with tubeup for archiving the videos of endangered "AppleInternal" (Shows internal apple software and prototype Apple hardware, apple isn't happy about them) accounts, and it works really nicely.

**Comment by JustAnotherArchivist** [comment]
No, there may be some overlap, but social networks and video hosting platforms are different things.
