### ISSUE TITLE
YouTube community posts 

### ISSUE THREAD

**Issue by upintheairsheep** [JustAnotherArchivist/snscrape#610]
https://www.youtube.com/c/TheGreatUnknownProductions/community
https://www.youtube.com/channel/UCgP9fheyDumxpk_35IgB3bw/community

Community posts are text, links to videos, images, polls, and comments on youtube. Support should add support for scraping community posts, their metadata, and their comments.

**Comment by JustAnotherArchivist** [comment]
Google+ was Google's social network (and was supported by snscrape). YouTube is a video platform with comments and a couple other minor social features. Please stop suggesting the addition of things that aren't social networks to a social network scraper.
