### ISSUE TITLE
Get more than 20 trends using TwitterTrendsScraper

### ISSUE THREAD

**Issue by michalbidzinski1** [JustAnotherArchivist/snscrape#613]
Hello, is is possible to get more than 20 trends using TwitterTrendsScraper? As because, this code:
```
scraper = snscrape.modules.twitter.TwitterTrendsScraper()
for trend in (scraper.get_items()):
	print(trend.json())

```
Prints only 20 results

**Comment by JustAnotherArchivist** [comment]
Not to my knowledge since https://twitter.com/i/trends always only returns 20.
