### ISSUE TITLE
Facebook number of posts with a hashtag

### ISSUE THREAD

**Issue by pj-mathematician** [JustAnotherArchivist/snscrape#62]
I want this feature where we can get the number of total posts which include a particular hashtag

**Comment by JustAnotherArchivist** [comment]
This is effectively a duplicate of #31. In general, there is no way to get the (correct) number of results without scraping the entire list, and then it's as simple as counting the output lines (e.g. `wc -l`). As noted in #31, it may not really be possible to scrape Facebook hashtags without an account.
