### ISSUE TITLE
twitter-profile scraper fails on some accounts with `KeyError: 'result'`

### ISSUE THREAD

**Issue by michecode** [JustAnotherArchivist/snscrape#620]
Hi, I'm trying to back up my twitter account so I could hopefully build a front end from this scraped data but Im struggling to get all of it. I used the scraper twitter-user and it worked well except I was missing like hundreds of tweets compared to what the app says I have. I assume it just retweets maybe so I am trying to user the twitter-profile scraper. I switched to the development build with `pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git` this command. Mostly confused because I tested with other twitter accounts and they work fine at fetching ~3200 tweets whereas mine fails with the below error at the same point every time.

My cli command with my profile handle removed.
`snscrape --jsonl --progress "twitter-profile" "TWITTER_USER">twitter-@me.jsonl`

```
Scraping, 100 results so far
Scraping, 200 results so far
Scraping, 300 results so far
Scraping, 400 results so far
2022-12-15 17:33:56.483  CRITICAL  snscrape._cli  Dumped stack and locals to /var/folders/b0/f8dgxw6121343kt577fpjlh40000gn/T/snscrape_locals_uxy4ft9d
Traceback (most recent call last):
  File "/opt/homebrew/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/snscrape/_cli.py", line 318, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/opt/homebrew/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1592, in get_items
    yield from self._graphql_timeline_instructions_to_tweets(instructions)
  File "/opt/homebrew/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1313, in _graphql_timeline_instructions_to_tweets
    yield self._graphql_timeline_tweet_item_result_to_tweet(entry['content']['itemContent']['tweet_results']['result'])
KeyError: 'result'
```

Running this command will cause it to fail at the same point every time so im not sure if theres some element on my profile that is breaking it.   
I'm happy to dm the local dumps / account handle if you need to test :)

**Comment by JustAnotherArchivist** [comment]
This is almost certainly the same bug @ronnypollak mentioned in <https://github.com/JustAnotherArchivist/snscrape/issues/604#issuecomment-1335228416>. So I already have a reproducer. :-)

**Comment by cong-1** [comment]
As there have been issuses reported by Elon Musk, maybe they are blocking by IP (Colab) or killing the adaptive.json at all. I haven't checked yet, but since the release of ChatGPT is was widely known to the public that this backdoor has also been used by OpenAI.
