### ISSUE TITLE
Respect #nobot on Mastodon

### ISSUE THREAD

**Issue by hughrun** [JustAnotherArchivist/snscrape#621]
The `#NoBot` hashtag in Mastodon profiles is a widely used indicator that users wish to not have their accounts scraped. `snscrape` should respect this by checking for the presence of `#nobot` and skipping those accounts.

**Comment by TheTechRobo** [comment]
I'm not the developer, but personally while I think adding an option for this is fine, it shouldn't be the default as it will result in less data retrieved than expected.

If it is made the default, it should be documented well and there should be a method of disabling it.

Potentially relevant: [ArchiveTeam's stance on robots.txt](https://wiki.archiveteam.org/index.php/Robots.txt)

**Comment by JustAnotherArchivist** [comment]
Some people seem to be using `#nobot` specifically for bots (e.g. automatic replies or boosts) but don't mind the scraping/indexing. There are separate `#noindex` or `#noarchive` tags in use as well, see e.g. [here](https://fosstodon.org/@djnavarro/109492348330872491). Others are arguing that it should be opt-in and instead use `#yesbot` etc. Then there are variations of the hashtags, such as `#nobots`. I assume non-English users might use something else altogether. I'm sorry, but I don't intend to support such a messy hack with ambiguous meaning.

There is an actual profile preference to opt out of search indexing. That's a much more sensible approach. (Stupidly enough, Mastodon apparently doesn't expose that flag on the API...)

That said, I don't think any of this would really apply to snscrape anyway. This is not an automated tool that crawls the entire Fediverse, instance timeline, or similar; it only runs on request by a user for a specific account. This user might be the account owner themselves or someone who got permission from the account owner. I'm not going to throw rocks in the path of someone trying to preserve the social media life of a loved one that passed away (yes, I've helped people do that before using snscrape, more than once).

I'm not opposed to adding a warning when that noindex preference is enabled though.
