### ISSUE TITLE
Whats the use of Cursor and Top in TwitterSearchScraper?

### ISSUE THREAD

**Issue by MazenTayseer** [JustAnotherArchivist/snscrape#624]
What does the args cursor and top do when changed in TwitterSearchScraper

**Comment by TheTechRobo** [comment]
I think `top` is a selection between `top` and `latest` (as on Twitter's web ui).

I believe `cursor` is from Twitter's API (basically the "next page" of the results), but I'm not 100% sure on that.

**Comment by JustAnotherArchivist** [comment]
Correct on both counts. I'd recommend to ignore `cursor` unless you know you need it; it might well get removed or hidden as an undocumented flag at some point because it can easily cause trouble.

**Comment by MazenTayseer** [comment]
I will need it to get results from different pages, as Im using multiprocessing to scrape alot of results at a short time

**Comment by JustAnotherArchivist** [comment]
I mean, feel free to reverse-engineer the cursors returned by Twitter if you want, I guess, but it will be a painful exercise. I recommend splitting the scrape into time slices instead, which will be independent from each other and can easily be parallelised. Cf. #132.

**Comment by MazenTayseer** [comment]
Thank you so much, really appreciate it!
