### ISSUE TITLE
TwitterSearchScraper bugs when given a place ID to scrape tweets from

### ISSUE THREAD

**Issue by MazenTayseer** [JustAnotherArchivist/snscrape#625]
### Describe the bug

I want to get tweets from certain location so I use this code
`for tweet in sntwitter.TwitterSearchScraper(f'{query} and place:{place_id}').get_items()`

It works well but when it doesnt find anymore results, the for loop doesnt quit, instead it bugs, doesnt advance with the code, making the code stop.

### How to reproduce

The for loop shall quit when it doesnt find results anymore, I tried setting a time to make it quit after a certain time, but that doesnt work as it bugs, stopping the code from executing

### Expected behavior

The for loop shall quit when it doesnt find results anymore

### OS / Distro

Windows 11

### Output from `snscrape --version`

0.4.3.20220106

### Scraper

TwitterSearchScraper

### Backtrace

doesnt gives any errors

### How are you using snscrape?

Module

**Comment by JustAnotherArchivist** [comment]
This might be similar to #584. But I can't check unless you tell the actual exact query you're running.

(By the way, `and` in lower case will just mean the matched tweets will have to contain 'and'. I don't know whether `AND` exists, but you can just omit it. Filters are automatically combined with logical and unless you use `OR`.)

**Comment by MazenTayseer** [comment]
@JustAnotherArchivist That is my code: 
```py
query = "Ronaldo"
places = api.search_geo(query="Egypt", granularity="country")
place_id = places[0].id
for tweet in sntwitter.TwitterSearchScraper(f'{query} place:{place_id}').get_items():
    print(tweet.user.username)
```
After finding the results, the for loop doesnt quit

**Comment by JustAnotherArchivist** [comment]
What's the `place_id`?

**Comment by MazenTayseer** [comment]
I use the `search_geo` from the official API to to get the ID of the country, then I use the ID to get tweets from this country with it, It works fine at scraping results from the country that I want, it just does not quit

**Comment by JustAnotherArchivist** [comment]
Right, I understood that, but I'm asking what the actual value is.

**Comment by MazenTayseer** [comment]
`c659cb4912229666`

**Comment by JustAnotherArchivist** [comment]
It 'hangs' for a while as it goes through empty pagination, but then it terminates, exactly as expected. So yeah, this is a variant of #584 and an upstream bug that snscrape can't do anything about.

**Comment by JustAnotherArchivist** [comment]
I made a mistake on last night's test. It does seem to go through a *lot* of empty pagination; my test scrape still hasn't finished after many hours now. I see no evidence that it's an infinite loop or similar though. It looks very much like that already known Twitter bug. I'll let it run for a while more and see where it goes.

**Comment by MazenTayseer** [comment]
Okay, Update me when you can! @JustAnotherArchivist

**Comment by JustAnotherArchivist** [comment]
It's still running. So far, it has retrieved almost 380k pages, but they all have unique cursors, so it doesn't appear to be looping. Looks like you found a pathological case. Let's see when it will finish... :-)

**Comment by JustAnotherArchivist** [comment]
Quick update: still running through empty pages, over 2.2 million of them by now...

**Comment by JustAnotherArchivist** [comment]
With the removal of the 'latest' search (#634), my scrape finally crashed after over 3.8 million empty pages. And unless they revert that removal, I guess this issue will be irrelevant. But #636 will probably lead to a limit on empty pages being followed, which would also 'fix' this in a sense.

**Comment by MazenTayseer** [comment]
I used multiprocessing and killed the process after n seconds and it works perfectly fine!
Thank you for your effort
