### ISSUE TITLE
How to scrape tweets that contain a link and are from a specified user?

### ISSUE THREAD

**Issue by leakyhose** [JustAnotherArchivist/snscrape#627]
I am trying to scrape tweets from a user that contain a link. I have looked for query options that would only include links, but have not found any. Is there any way to only get links without getting every tweet and filtering out those without a link?

**Comment by JustAnotherArchivist** [comment]
`filter:links`

That includes media (which are technically links), so you may want to combine it with `-filter:media`. This probably also excludes tweets containing both though.
