### ISSUE TITLE
Search "since: and until: " for a date range does not return result

### ISSUE THREAD

**Issue by Retji** [JustAnotherArchivist/snscrape#628]
### Describe the bug

I have been trying to scrape data using a date range. However, snscrape seems not to return any data;
tday=date.today()
earlier=tday-timedelta(days=1)
for i,tweet in enumerate(sntwitter.TwitterSearchScraper( 'Peter Obi since:{tday} until:{earlier}').get_items()):
    if i>100:
        break
    po_tweets.append([tweet.date,tweet.user.username,tweet.user.displayname,tweet.content,tweet.likeCount,tweet.retweetCount,tweet.sourceLabel,tweet.user.followersCount,tweet.user.location])

the day range does not return a result
    

### How to reproduce

I have no idea

### Expected behavior

What I needed was the data between the previous day and the current day

### OS / Distro

windows version 11

### Output from `snscrape --version`

none

### Scraper

twitter

### How are you using snscrape?

Module

**Comment by JustAnotherArchivist** [comment]
Well yes, there obviously are no tweets that are both newer than today (`since:{today}`) and older than yesterday (`until:{yday}`). Swap the values.
