### ISSUE TITLE
Cant able to scrape from the latest tweet to final tweet...

### ISSUE THREAD

**Issue by Aravindh-123** [JustAnotherArchivist/snscrape#632]
For example: 

```python3
for i, tweet in enumerate(sntwitter.TwitterSearchScraper('from:vistara').get_items()):
    if i >= 100:
        break
    else:
        tweets_detail.append([tweet.user.username, tweet.date.date(), tweet.content])
```

output:

Username | Date | Content
-- | -- | --
Vistara | 2022-11-03 | @elonmusk Same can be said about morons
Vistara | 2022-10-28 | @RealCliveBarker\nMy heart... 🥰 https://t.co/W...
Vistara | 2022-10-19 | @Yairir Something is always growing with you...
Vistara | 2022-06-13 | @sayollo #CandyCrush has probably eaten as muc...
Vistara | 2021-11-12 | @tridentgum Flavor flavor
... | ... | ...
Vistara | 2019-08-05 | @hotpockets my imaginary friends! :D :/ :(
Vistara | 2019-07-31 | @neilhimself Now I need an audio recording of ...
Vistara | 2019-07-31 | @Klondikebar Israel...
Vistara | 2019-07-21 | @amithpr How do we get this to go viral? ;)\n...
Vistara | 2019-07-21 | @FullFrontalSamB Dickhole. The word you're loo...

It start from the year of 2022. How can i scrape from the latest 2023 ?

**Comment by JustAnotherArchivist** [comment]
Vistara hasn't tweeted since 2022-11-03, so obviously you can't get any newer results than that.
