### ISSUE TITLE
Twitter search scrapes in default 'latest' order fail with 401 ('non-200 status code')

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#634]
Since today, any `twitter-search` scrapes (i.e. including `twitter-user` and `twitter-hashtags`, which are just wrappers around the search) that do not include the `--top` flag fail. Twitter removed the 'Latest' tab from the search page this afternoon, and since approximately 22:35 UTC, the API seems to fail as well.

**Comment by MazenTayseer** [comment]
When is this going to be solved?

**Comment by constantin-barbu** [comment]
The "Latest" tag seems to be back now on Twitter search pages.

**Comment by JustAnotherArchivist** [comment]
It's unclear right now whether the functionality is still available at all. If not, it might never get fully solved. You can probably work around it by using `--top`, but I'm not sure whether you can get the full feed that way.

**Comment by AhmetcanFR** [comment]
This sounds like an issue, Is there any fix to that?

**Comment by JustAnotherArchivist** [comment]
@constantin-barbu They might be doing more changes at the minute. I don't see it. I'm also seeing claims that it is only available when logged in (which would be useless for snscrape).

**Comment by constantin-barbu** [comment]
You're right, it's only available when logged in :(.

**Comment by AhmetcanFR** [comment]
Is there a way to log in our access token so we can have access to it?

**Comment by JustAnotherArchivist** [comment]
@AhmetcanFR No, logging in is not and will not be supported: #270

**Comment by AhmetcanFR** [comment]
What can we do for now?

**Comment by JustAnotherArchivist** [comment]
There's currently no known workaround apart from the one I mentioned above.

**Comment by MazenTayseer** [comment]
@JustAnotherArchivist if I set 'top=False'
Will it work as before?

**Comment by JustAnotherArchivist** [comment]
@MazenTayseer No, only `top = True` will work currently.

**Comment by Goitsemedi888** [comment]
where would this be used top = True??? 

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#CRM OR #Salesforce, since:2022-1-1 until:2023-1-10').get_items()):
    if i>250000:
        break
    tweets_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username])
    
# Creating a dataframe from the tweets list above
CRM_tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

**Comment by JustAnotherArchivist** [comment]
@Goitsemedi888 It's an optional argument to the scraper: `TwitterSearchScraper('query', top = True)`

**Comment by richardjozsa** [comment]
```top=True``` not working for me

**Comment by JustAnotherArchivist** [comment]
@richardjozsa I just verified that `--top` (or, equivalently, `top = True`) still works from three continents. Please file a separate issue with all required details.

**Comment by richardjozsa** [comment]
Sorry false alarm, it was jut one particular error!

**Comment by ShionNorimo** [comment]
Hello, I use the command line to do my data extraction from Twitter and since it's my first time doing it (I don't have any experience with coding or data extraction) is there an alternative to work around with it or should I wait untill further update?

**Comment by jannat5134** [comment]
After adding top=true, I have found results, but it doesn't go to the next query :( Have anyone face this problem?

**Comment by tmtsmrsl** [comment]
> @Goitsemedi888 It's an optional argument to the scraper: `TwitterSearchScraper('query', top = True)`

I have tried using top=True, but the scraper still does not work. The error message is similar to when we set top=False.

Example code:

```tweet_data = []
for i, tweet in enumerate(
    sntwitter.TwitterSearchScraper(query="apple lang:en", top=True).get_items()
    ):
    if i >= 100:
        break
    tweet_data.append(
            [tweet.user.username, tweet.date, tweet.likeCount, tweet.content]
        )

tweet_df = pd.DataFrame(tweet_data, columns=["Username", "Date", "Like Count", "Tweet"])```

**Comment by JustAnotherArchivist** [comment]
@tmtsmrsl `snscrape -n 10 twitter-search --top 'apple lang:en'` works fine for me. In any case, that would be a different issue if it didn't work.

**Comment by tmtsmrsl** [comment]
> @tmtsmrsl `snscrape -n 10 twitter-search --top 'apple lang:en'` works fine for me. In any case, that would be a different issue if it didn't work.

Hmm, on Python it won't work if we use "lang:". Also here's the screenshot from the Twitter site (not logged in).
![image](https://user-images.githubusercontent.com/106854419/211707838-afe6aeea-89c1-48b6-84cf-ae6939af1e04.png)

**Comment by jieklee** [comment]
After adding top=true, it prompt the errors shown above as well. Did anyone facing this issue?

**Comment by someguy-2020** [comment]
Snscrape version: snscrape-0.4.2.20211215.dist-info

class TwitterSearchScraper(TwitterAPIScraper):
	name = 'twitter-search'

	def __init__(self, query, cursor = None, top = True, **kwargs):

If you change the top to "True" in the above line of code in the twitter module you can get the latest twits of a user.

**Comment by JustAnotherArchivist** [comment]
@someguy-2020 Just pass `--top` on the CLI or `top = True` if you use it from Python rather than modifying the snscrape code. That's why it's an optional parameter.

**Comment by jannat5134** [comment]
> where would this be used top = True???
> 
> ```python
> for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#CRM OR #Salesforce, since:2022-1-1 until:2023-1-10').get_items()):
>     if i>250000:
>         break
>     tweets_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username])
>     
> # Creating a dataframe from the tweets list above
> CRM_tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])
> ```
tweets_list=[]
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('Swift AND TaylorSwift AND Taylor AND love AND relationship AND things OR movies OR Alwyn OR London OR loves OR source, since:2022-1-1 until:2023-1-10',top='True').get_items()):
    print(i)
    print(tweet)
    if i>100:
        break
    tweets_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.user.username])
    
# Creating a dataframe from the tweets list above
CRM_tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

when Top='True' and the query result can be reached up to maximum tweets, it returns. But however for the long query where query results are less than maximum tweets, it's infinite loop. I worked from the last night :(

**Comment by JustAnotherArchivist** [comment]
Please stop commenting on using `--top` / `top = True` here. This issue is about the broken 'latest' scraping only. If you have a problem with or question about 'top' scraping, open a separate issue (if one doesn't exist yet).

**Comment by engkimo** [comment]
@jannat5134 
I don't know why it loops infinitely, but I suggest using asyncio when you use `top=True` and you can't get next return.
But also I don't know of any other good solutions either tho.. :S

**Comment by jannat5134** [comment]
> asyncio

But how to use asyncio here !!!!!! Please help

**Comment by engkimo** [comment]
@jannat5134 
I used like this following asyncio.wait_for :)
https://docs.python.org/3.11/library/asyncio-task.html#asyncio.wait_for
But I think asyncio is a temporary workaround for this issue .. and then,
I created this issue https://github.com/JustAnotherArchivist/snscrape/issues/636 .

**Comment by jannat5134** [comment]
> @jannat5134 I used like this following asyncio.wait_for :) https://docs.python.org/3.11/library/asyncio-task.html#asyncio.wait_for But I think asyncio is a temporary workaround for this issue .. and then, I created this issue #636 .

can you give me a code where I can use ayncio in twittersearchscrapper. I badly need a code sample

**Comment by JustAnotherArchivist** [comment]
'Top' searches are now broken as well: #647

**Comment by JustAnotherArchivist** [comment]
Twitter seems to have reverted this change. The 'latest' search scraping works again, even though it's still unavailable on the web interface.

**Comment by MazenTayseer** [comment]
`TwitterSearchScraper` is still not working for me

**Comment by JustAnotherArchivist** [comment]
If you (or anyone else) have a problem on the latest snscrape version and no issue exists yet for it, file a complete bug report please.

**Comment by MariaPng** [comment]
i downloaded the latest version of snscrape but still the error remains,what i have to do?

**Comment by JustAnotherArchivist** [comment]
@MariaPng You [file a complete bug report](https://github.com/JustAnotherArchivist/snscrape/issues/new?assignees=&labels=bug&template=bug_report.yml), as the comment just before yours says.

**Comment by Satarupa22-SD** [comment]
I am still facing this issue, i have implemented  top = True  in my code but the error is persisting.
