### ISSUE TITLE
Infinite loop on scraping top tweets

### ISSUE THREAD

**Issue by engkimo** [JustAnotherArchivist/snscrape#636]
This problem that surfaced at the same time as this problem [#634](https://github.com/JustAnotherArchivist/snscrape/issues/634) :).

When `Top='True'` and the long query where query results are less than maximum tweets, it's infinite loop and keep return empty object. 
I had a temporary workaround for this issue by specifying a timeout with asyncio. However, I think that it is necessary to fix it because the object from the following continues to be returned.
`{'globalObjects': {'tweets': {}, 'users': {}, 'moments': {}, 'cards': {}, 'places': {}, 'media': {}, 'broadcasts': {}, 'topics': {}, 'lists': {}}, 'timeline': {'id': 'TopTabSrpProduct-Timeline', 'instructions': [{'replaceEntry': {'entryIdToReplace': 'cursor-top-9223372036854775807', 'entry': {'entryId': 'cursor-top-9223372036854775807', 'sortIndex': '9223372036854775807', 'content': {'operation': {'cursor': {'value': 'xxxx', 'cursorType': 'Top'}}}}}}, {'replaceEntry': {'entryIdToReplace': 'cursor-bottom-0', 'entry': {'entryId': 'cursor-bottom-0', 'sortIndex': '0', 'content': {'operation': {'cursor': {'value': 'xxxx', 'cursorType': 'Bottom'}}}}}}]}}`

https://github.com/JustAnotherArchivist/snscrape/issues/634#issuecomment-1378214922

**Comment by JustAnotherArchivist** [comment]
Yeah, Twitter's 'top' pagination is a bit weird. Unfortunately, it's impossible to know beforehand whether further pages will contain more tweets, and I've seen cases in the past with multiple empty pages followed by pages with results. The cursors get longer, but they stay unique. The only 'proper' approach is to keep going through pagination until it stops; that's also what the web interface does (if its scrolling behaviour wasn't semi-broken). The next best thing I can think of is a generic 'stop after N empty pages' parameter – with a high default value to avoid almost all false positives but customisable for weird cases. A warning would also be emitted if the pagination stops due to that limit rather than cleanly. How does that sound?

**Comment by engkimo** [comment]
@JustAnotherArchivist 
Thanks :)
When I made changes like this, I avoided long empty pagination and it worked.
There may be a better idea, but would an approach like this, for example, work in this case?

https://github.com/JustAnotherArchivist/snscrape/pull/638

**Comment by 0bmay** [comment]
might be a bad fix, but limiting the number of tweets worked for me... 100 failed.. but 40 seems ok.

```
    limit = 40
    tweets = []
    for tweet in sntwitter.TwitterUserScraper(username=user, top=True).get_items():
        if len(tweets) == limit:
            break
        else:
             ...
```

**Comment by JustAnotherArchivist** [comment]
@0bmay This loop still happens if you get fewer search results than your chosen limit, e.g. because the account never made that many tweets.

**Comment by 0bmay** [comment]
True... I did say it might be a bad fix : )  but it's a temporary workaround for me.  The account I was searching has way more than 100 tweets.. Thank you for your hard work @JustAnotherArchivist

**Comment by SmithsFAS1** [comment]
looks like even the Top=True is returning "Forbidden" JSON responses this morning?

**Comment by 0bmay** [comment]
I have a feeling it's going to be a bigger game of cat and mouse at twitter for a while.

**Comment by Ramizworking** [comment]
> I have a feeling it's going to be a bigger game of cat and mouse at twitter for a while.

Fxked it seems yeah :)

**Comment by Mr-Freewan** [comment]
This is a very big problem.
Now I give a query like "from:username "since:2023-01-08 -filter:replies", then .get_items() goes into an infinite loop.

Maybe you can add timeout argument and throw an exception or return only received tweets? (If the timeout is exceeded)

**Comment by JustAnotherArchivist** [comment]
See #391 for why there isn't an overall timeout.

I'll be implementing my suggestion from above later unless someone has a better idea.

**Comment by jannat5134** [comment]
> @JustAnotherArchivist Thanks :) When I made changes like this, I avoided long empty pagination and it worked. There may be a better idea, but would an approach like this, for example, would be good in this case?
> 
> #638

Do you add parameter to stop after N empty pages?

**Comment by AlesyaSeliazniova30032012** [comment]
> > @JustAnotherArchivist Thanks :) When I made changes like this, I avoided long empty pagination and it worked. There may be a better idea, but would an approach like this, for example, would be good in this case?
> > #638
> 
> Do you add parameter to stop after N empty pages?

Hi. sorry? I dont unerstand where is necessary to add that parameter?

**Comment by AlesyaSeliazniova30032012** [comment]
and if the top=True parameter didn't work in my code, the same exception was thrown, nothing more can be done?
`
 for tweet in sntwitter.TwitterSearchScraper(query, top = True).get_items():
    bla-bla-bla
`
