### ISSUE TITLE
ScraperException

### ISSUE THREAD

**Issue by Kituva** [JustAnotherArchivist/snscrape#640]
**import snscrape.modules.twitter as sntwitter
import pandas as pd

def scraper(counter, user):
    # List to append all tweet attributes(data)
    attributes_container = []
    # Using TwitterSearchScraper to scrape data and append tweets to list
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:{}'.format(user)).get_items()):
        if i>counter:
            break
        attributes_container.append([tweet.date, tweet.user.username, tweet.sourceLabel, tweet.sourceUrl, tweet.content, tweet.media])
        # Creating a dataframe from the tweets list above 
        tweets_df = pd.DataFrame(attributes_container, columns=["Date Created", "User", "Source label of Tweet", "Source URL", "Tweets", "Media"])
    return tweets_df

counter = 10
user = 'DanaherCorp'

try:
    posts_df = scraper(counter, user)
except UnboundLocalError:
    print("\nNo Tweets")**
    
    
I was trying to run the above code and it threw a ScraperException.
    
ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3ADanaherCorp&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up. 

Can anyone kindly help me with this?

**Comment by Neo6163** [comment]
I am facing the same issue and tried everything I could. Did you find any solution?

**Comment by patryk-loda-binance** [comment]
#634 Is the same issue you're having, adding 'top=True' to the query should solve your problem. However #636 outlines a different issue that may occur after adding 'top=True' due to a bug.

**Comment by Ramizworking** [comment]
Hey buddy, everyone is facing the same issue right now but the weird thing I don't get is like 

When I use "working since:2023-01-10" it still works for me

A workaround would probably be, let's say if you look for 7 days of tweets", use this command in the search bar of twitter :
"working since:2023-01-03" 

Cause it seems snscrape was using "Latest" tab to scrap the tweets but that's actually no more possible due to recent updates

Hope @JustAnotherArchivist will find a workaround

**Comment by Kituva** [comment]
> I am facing the same issue and tried everything I could. Did you find any solution?

I could not find any solution till now. But good to know that everyone is facing the same issue and I am not alone.

**Comment by Kituva** [comment]
> #634 outlines the cause of the problem and the temporary solution, adding 'top=True' to the query should solve your problem. However #636 outlines a different issue that may occur after adding 'top=True' due to a bug.

Thanks for the workaround. I will try implementing the same and check.

**Comment by jelleheijne1997** [comment]
I have the same issue. None of the workarounds have worked for me so far. I hope someone will find a solution

**Comment by marrcco** [comment]
did Twitter mention anything about removing the "Latest" tab if you re not logged in?

**Comment by Neo6163** [comment]
Top=True is not working anymore

**Comment by rezzamohammad** [comment]
Hmm don't know why Twitter remove their "Latest" tab on their wierd change. Will they return it ¯\_(ツ)_/¯

**Comment by Neo6163** [comment]
I was using this code until now and it was working perfectly fine but now it is giving "**error retrieving**" 
```
tweets_list2 = []
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('COVID Vaccine since:2021-05-01 until:2021-05-31', top=True).get_items()):
    if i>4:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
```

top=True, worked well for a while but the issue still persists

**Comment by Shifter2600** [comment]
I swapped from Latest yesterday to Top and it was working over night with Top but this morning I woke up to Top no longer working with the same failed, giving up. error as being reported now.

**Comment by 0bmay** [comment]
I tried adding the different adaptive.json values from the live site to the paginationParams and it didn't change the error state. Added more headers to the calls and still get a 404 getting the adaptive.json call...
