### ISSUE TITLE
ERROR:snscrape.base:Error retrieving

### ISSUE THREAD

**Issue by ilkeronurisik** [JustAnotherArchivist/snscrape#641]
Here is the error I got since this morning. I don't understand why. 
can you help?
![Uploading error.PNG…]()

**Comment by Ramizworking** [comment]
Hey this is a common issue, everyone is facing that actually

Twitter just removed "Latest" tab when you are unconnected to twitter...

**Comment by ilkeronurisik** [comment]
> Hey this is a common issue, everyone is facing that actually
> 
> Twitter just removed "Latest" tab when you are unconnected to twitter...

Thanks.So how did you solve it?

**Comment by marrcco** [comment]
> > Hey this is a common issue, everyone is facing that actually
> > Twitter just removed "Latest" tab when you are unconnected to twitter...
> 
> Thanks.So how did you solve it?

I don't think that we can solve it until they bring back the "Latest" tab. You could try to crawl the data from the "Top" tab if that suit your needs > (https://github.com/JustAnotherArchivist/snscrape/issues/634#issuecomment-1378089639)

**Comment by ilkeronurisik** [comment]
> > > Hey this is a common issue, everyone is facing that actually
> > > Twitter just removed "Latest" tab when you are unconnected to twitter...
> > 
> > 
> > Thanks.So how did you solve it?
> 
> I don't think that we can solve it until they bring back the "Latest" tab. You could try to crawl the data from the "Top" tab if that suit your needs > ([#634 (comment)](https://github.com/JustAnotherArchivist/snscrape/issues/634#issuecomment-1378089639))

Can you teach me this? :(

**Comment by TheTechRobo** [comment]
Read the linked comment. In the Python API, you add `top=True`, in the cli you use `--top`

**Comment by Ramizworking** [comment]
> 

it's  not fixing the issue, then you get another error, it loops without stoping

**Comment by ilkeronurisik** [comment]
I think library owners should take care of it.

**Comment by JustAnotherArchivist** [comment]
#634 and #636

**Comment by Ramizworking** [comment]
> #634 and #636

But #634 is just closed, we can't discuss on it

**Comment by JustAnotherArchivist** [comment]
Well yes, there isn't anything to discuss at this time, and the issue was getting spammed. The only known (and poor) workaround has been mentioned, and nothing of substance has been said in any of the duplicate issues.
