### ISSUE TITLE
Twitter error when scraping 

### ISSUE THREAD

**Issue by myt-christine** [JustAnotherArchivist/snscrape#646]
ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=halalan&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.

i'm getting this error, can you please check this out?

**Comment by brihuang99** [comment]
getting the same issue as well. the code was working flawless yesterday, wonder if something happened on twitter's end?

**Comment by annanasi-mon** [comment]
How do you specify top=True using CLI?

**Comment by annanasi-mon** [comment]
> How do you specify top=True using CLI?

I already found out, you can do this the following:
snscrape --jsonl --progress --max-results 500 --since 2017-01-01  twitter-search "#Bitcoin until:2022-12-31" --top > text-query-tweets.json

**Comment by JustAnotherArchivist** [comment]
#634
