### ISSUE TITLE
non-200 status code

### ISSUE THREAD

**Issue by chayma1999** [JustAnotherArchivist/snscrape#654]
### Describe the bug

2 days ago, my code worked correctly. However, yesterday, requests failed and showed a non-200 status code. 

### How to reproduce

I m trying to scrape Twitter

### Expected behavior

scraping Twitter by hashtag and date

### OS / Distro

windows 10

### Output from `snscrape --version`

lastest vervion

### Scraper

TwitterSearchScraper

### How are you using snscrape?

CLI

**Comment by JustAnotherArchivist** [comment]
Duplicate of #634
