### ISSUE TITLE
Api Request error

### ISSUE THREAD

**Issue by steevenakintilo** [JustAnotherArchivist/snscrape#657]
### Describe the bug

Hi I've been running a twitter bot since 1 year and more using sncrape but since yesterday I keet getting this error I don't know why:

**4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28on+a+tous+d%C3%A9j%C3%A0++++installer+twitter+++rien+compris+au+d%C3%A9lire+++d%C3%A9sinstaller+++revenir+et+kiffer+%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment failed, giving up.**

The line of code that "crash":

**for tweet in sntwitter.TwitterSearchScraper(query).get_items():**

### How to reproduce

This bug happend when I tried to fetch tweet

### Expected behavior

It should give me all the tweet containing the keyword I wanted

### OS / Distro

Raspberry Pi OS

### Output from `snscrape --version`

0.3.4

### Scraper

twitter-tweet

### Backtrace

4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28on+a+tous+d%C3%A9j%C3%A0++++installer+twitter+++rien+compris+au+d%C3%A9lire+++d%C3%A9sinstaller+++revenir+et+kiffer+%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment failed, giving up

### How are you using snscrape?

CLI

**Comment by marcosmadr** [comment]
I noticed the **Latest** link is not present if we are not logged in. I was looking the code and it seems related to the request parameter `tweet_search_mode=live`. Could it be that twitter is not allowing this request without login?

Not logged in:

![Screenshot from 2023-01-12 11-11-33](https://user-images.githubusercontent.com/22649551/212039452-c12f45c4-ad28-479a-9176-0d0b88f363f1.png)

Logged in:

![Screenshot from 2023-01-12 11-11-49](https://user-images.githubusercontent.com/22649551/212039486-2042afd8-6d4c-4d56-bb4a-c53a5270b29d.png)

**Comment by pawertrem** [comment]
Yes, it seems so, check #647, Twitter has just removed the 'Latest' tab, thus, a parser is not working right now, unfortunately

**Comment by steevenakintilo** [comment]
Ok I see that's sad

**Comment by steevenakintilo** [comment]
> Hi @steevenakintilo I noticed the **Latest** link is not present if we are not logged in. I was looking the code and it seems related to the request parameter `tweet_search_mode=live`. Could it be that twitter is not allowing this request without login?
> 
> Not logged in:
> 
> ![Screenshot from 2023-01-12 11-11-33](https://user-images.githubusercontent.com/22649551/212039452-c12f45c4-ad28-479a-9176-0d0b88f363f1.png)
> 
> Logged in:
> 
> ![Screenshot from 2023-01-12 11-11-49](https://user-images.githubusercontent.com/22649551/212039486-2042afd8-6d4c-4d56-bb4a-c53a5270b29d.png)

Can't we login to an account with sncrape?

**Comment by michalbidzinski1** [comment]
> Yes, it seems so, check #634, Twitter has just removed the 'Latest' tab, thus, a parser is not working right now, unfortunately

What if I don't want to get the latest tweets, but just from the 'Top' tab? I tried adding 'top=True' parameter but I still get same error as above.

**Comment by pawertrem** [comment]
> > Yes, it seems so, check #634, Twitter has just removed the 'Latest' tab, thus, a parser is not working right now, unfortunately
> 
> What if I don't want to get the latest tweets, but just from the 'Top' tab? I tried adding 'top=True' parameter but I still get same error as above.

Yeah, in #647 it is noted that 'Top' searches also started to fail for some reason, personally, I don't really understand wh
