### ISSUE TITLE
TwitterSearchScraper started giving snscrape.base.ScraperException 4 requests failed, giving up

### ISSUE THREAD

**Issue by AlekseiShkurin** [JustAnotherArchivist/snscrape#660]
### Describe the bug

Hey crew! I have a code that I've been running for some time getting tweets of given users and a couple days ago it stopped working giving the "snscrape.base.ScraperException 4 requests failed, giving up" error.

Here's the function that's having an issue

```
def get_tweets_by_user(username, limit=1000):
    raw_tweet_objs = []
    request = 'from:{}'.format(username)

    for i, tweet in enumerate(sntwitter.TwitterSearchScraper(request).get_items()):
        if i > limit:
            break
        raw_tweet_objs.append(tweet)

    return raw_tweet_objs
```

Were there any recent changes on the backend that might be causing this error? If not, what could've caused the change in behaviour? The function used to work fine for quite a long period of time, until about two days ago

### How to reproduce

```
import snscrape.modules.twitter as sntwitter

username = '@elonmusk'
limit = 100


def get_tweets_by_user(username, limit=1000):
    raw_tweet_objs = []
    request = 'from:{}'.format(username)

    for i, tweet in enumerate(sntwitter.TwitterSearchScraper(request).get_items()):
        if i > limit:
            break
        raw_tweet_objs.append(tweet)
    return raw_tweet_objs


elon_tweets = get_tweets_by_user(username, limit)
```

### Expected behavior

The code is expected to return a list of the most recent tweets for a given user up to the given limit. Currently, the code breaks with the ScraperException error

### OS / Distro

macOS 12.5

### Output from `snscrape --version`

0.4.3.20220106

### Scraper

TwitterSearchScraper

### Backtrace

Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3A%40elonmusk&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3A%40elonmusk&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<input>", line 5, in get_tweets_by_user
  File "/Users/user/Desktop/test/venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/Users/user/Desktop/test/venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/Users/user/Desktop/test/venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/Users/user/Desktop/test/venv/lib/python3.10/site-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "/Users/user/Desktop/test/venv/lib/python3.10/site-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3A%40elonmusk&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

### How are you using snscrape?

Module

**Comment by Ramizworking** [comment]
Bro everyone's aware of the situation dw, justyou know that @JustAnotherArchivist is on it and we hope he'll fix that sht. Be patient.

**Comment by liyuduan817** [comment]
hey bro, did you resolve this problem now, huge thanks!

**Comment by JustAnotherArchivist** [comment]
@liyuduan817 It was fixed a long time ago. #634 and #647
