### ISSUE TITLE
 Gives that error when executing non-200 status code (404)

### ISSUE THREAD

**Issue by dadiaz14** [JustAnotherArchivist/snscrape#662]
### Describe the bug

ror retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=germancaceres&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo: non-200 status code (404)

### How to reproduce

began to fail from today in the search for a specific topic

### Expected behavior

began to fail from today in the search for a specific topic

### OS / Distro

windows10

### Output from `snscrape --version`

snscrape 0.4.3.20220107.dev76+gceb0666

### Scraper

twitter-user

### How are you using snscrape?

Module

**Comment by JustAnotherArchivist** [comment]
#634 and #647

**Comment by dadiaz14** [comment]
open any solution?
