### ISSUE TITLE
Twitter-profile CLI issue

### ISSUE THREAD

**Issue by PabloConcheiro** [JustAnotherArchivist/snscrape#667]
### Describe the bug

Error received when scraping a profile from CLI with snscrape twitter-profile.

### How to reproduce

Scrape a profile from CLI with the command above. For example: snscrape twitter-profile marca

### Expected behavior

Receive the info related to the @marca twitter profile.

### OS / Distro

Windows 10

### Output from `snscrape --version`

snscrape 0.4.3.20220106

### Scraper

twitter-profile

### Dump of locals

![image](https://user-images.githubusercontent.com/118831099/212283480-b22cf792-b369-483f-8fa3-3660a7b1e339.png)

### How are you using snscrape?

CLI

### Additional context

The command was working as expected until 30 minutes ago.

**Comment by JustAnotherArchivist** [comment]
Ah, so you're using the release version, not the dev version, and this is indeed the same as #367. Either switch to the dev version or wait until I publish a new release probably later today and then upgrade to that.

**Comment by PabloConcheiro** [comment]
Sorry, I was in another env  and the dev version was not there. If i reproduce with the dev version, this error appears for me: 

![image](https://user-images.githubusercontent.com/118831099/212286328-ac5bbde9-969d-4109-8db5-f9f3407591e9.png)

**Comment by JustAnotherArchivist** [comment]
That's not the latest dev version either; I fixed that crash an hour ago.
(The second error in that screenshot also indicates that your terminal isn't set up correctly for Unicode characters.)

**Comment by PabloConcheiro** [comment]
Solved, thank you for all and for the quick response.
