### ISSUE TITLE
Trying to "recode" latest with log in.

### ISSUE THREAD

**Issue by steevenakintilo** [JustAnotherArchivist/snscrape#669]
Since twitter removed latest pages withouth login, I would like to know how hard would it be to try the same with login account?
I've thought of an idea using selenium but I don't know if it's good.

**Comment by steevenakintilo** [comment]
> snscrape does not and will not support authentication: #270

you don't get I will try to remake that all alone withouth using sncrape like building from nothing just using python and internet to have help

**Comment by steevenakintilo** [comment]
> snscrape does not and will not support authentication: #270

Saying that because I've got a twitter bot https://twitter.com/TwittosBot that have been using sncrape since july and since twitter rework their website I need to find an alternative.

**Comment by JustAnotherArchivist** [comment]
> you don't get I will try to remake that all alone withouth using sncrape like building from nothing just using python and internet to have help

So this issue is spam then, got it.
