### ISSUE TITLE
I use google colab to scrape twitter and it works on my end and @brihuang99 also commented

### ISSUE THREAD

**Issue by Goitsemedi888** [JustAnotherArchivist/snscrape#672]
I use google colab to scrape twitter and it works on my end and @brihuang99 also commented

> I'm running snscrape 0.4.3.20220106. It's the same as what I have on my Raspberry Pi, not sure why only my desktop is working

maybe it has something to do with python version?

I'm using these versions and it currently works on my end 
Python 3.8.16
snscrape-0.4.3.20220106

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/47768819/212204685-a3216afc-eab9-4f88-824f-0b049e68adbc.png">

_Originally posted by @Idan-Garay in https://github.com/JustAnotherArchivist/snscrape/issues/647#issuecomment-1381111439_

**Comment by JustAnotherArchivist** [comment]
Outdated snscrape version

**Comment by Goitsemedi888** [comment]
On my end it's scraping however it is not retrieving historic data. the earliest I can get is 01/04/2023 then a message below that reads "WARNING:snscrape.modules.twitter:Stopping after 20 empty pages"

Can you test for a year interval and max retrieval 50k and let me know if you can get data from 2020?

How do i get the latest version of snscrape.

**Comment by JustAnotherArchivist** [comment]
Well yes, the 'latest' search is broken, as you undoubtedly know from the open issues. And the 'top' search only returns up to a couple hundred results at most, usually less. There is no workaround for this currently. You can try different search queries filtered by time windows, I guess.

You get the latest snscrape just like you get the latest version of any Python package: `pip install --upgrade snscrape`
