### ISSUE TITLE
TwitterSearchScraper not working when setting a proxy

### ISSUE THREAD

**Issue by anasmcl** [JustAnotherArchivist/snscrape#677]
### Describe the bug

TwitterSearchScraper works properly but when setting proxy I get a connection error.

(the proxy was also working properly before updating to the new version of snscrape that integrates proxies. before that, I was simply setting it in the base.py file, under def _request : "self._session.proxies = proxies")

**Proxies setting**
```
proxies = {'https': 'http://<user>:<password>@p.webshare.io:80/'}
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('{} since_time:{} until_time:{}'.format(coin_name, start_time, end_time), proxies = proxies ).get_items()):
```
(it's a rotating proxy with authentification)

**Connexion error**

File "C:\Users\HP\AppData\Roaming\Python\Python310\site-packages\snscrape\base.py", line 221, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=%24NEAR+since_time%3A1672524000+until_time%3A1672527600&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=%24CRO+since_time%3A1672524000+until_time%3A1672527600&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: non-200 status code (404)

### How to reproduce

probably by setting a proxy with authentification

### Expected behavior

make the request through proxy

### OS / Distro

Windows10

### Output from `snscrape --version`

Version: 0.3.5.dev138+ga6b6f3f

### Scraper

twitter-search

### How are you using snscrape?

Module

### Additional context

I have installed snscrape since 1+ year, I use it frequently (with proxy) without any pb.

I just replaced base.py, twitter.py and module __init__.py with latest versions during last twitter search bug.

**Comment by JustAnotherArchivist** [comment]
> Version: 0.3.5.dev138+ga6b6f3f

This is ancient. Please install the current version.

> I just replaced base.py, twitter.py and module \_\_init\_\_.py with latest versions during last twitter search bug.

I don't provide support for modified code.
