### ISSUE TITLE
Getting ScraperException that seems to block the tweet retrieval 

### ISSUE THREAD

**Issue by tarinisudhakar** [JustAnotherArchivist/snscrape#678]
### Describe the bug

Getting a ScraperException when I run my code to scrape all Tweets with the user @econ_ra: 

snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%40econ_ra&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

### How to reproduce

If you run the following code, you should be able to reproduce the problem:

```python3
import snscrape.modules.twitter as sntwitter

data = []
for I, tweet in enumerate(sntwitter.TwitterSearchScraper('@econ_ra').get_items()):
     if i>50:
          break
    data.append([tweet.date, tweet.user.username, tweet.content, tweet.url, tweet.id])
```

### Expected behavior

It should store the data in a list but I end up getting the ScraperException. 

### OS / Distro

macOS 12.5

### Output from `snscrape --version`

snscrape.modules.twitter

### Scraper

TwitterSearchScraper

### Backtrace

snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%40econ_ra&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

### How are you using snscrape?

CLI

**Comment by JustAnotherArchivist** [comment]
> Output from `snscrape --version`
>
> snscrape.modules.twitter

Uhuh...

But if that's the only error message you get, you're not on the latest snscrape version.

**Comment by michalbidzinski1** [comment]
@JustAnotherArchivist  I have snscrape 0.5.0.20230114.dev2+g5d3f27b version and i get same error.

**Comment by tarinisudhakar** [comment]
> > Output from `snscrape --version`
> > snscrape.modules.twitter
> 
> Uhuh...
> 
> But if that's the only error message you get, you're not on the latest snscrape version.

I updated the version and now it is working. Thank you!
