### ISSUE TITLE
Scrapes with current snscrape version find less tweets than old version

### ISSUE THREAD

**Issue by lukaszpeee** [JustAnotherArchivist/snscrape#679]
Hi,

I have noticed  that currently my script has found less tweets than few days ago, when it used old version of snscrape. Why has it happened?

Best Regards

**Comment by AhmetcanFR** [comment]
Are you sure about that, for me it still scrapes the correct amount for a given word.

When you then type the word in twitter search bar like let's say : jumping off since:2023-01-16

it returns me the same amount as snscrape

**Comment by 0bmay** [comment]
also possible that users deleted items or deleted their accounts. Both would remove returned items from a search...

**Comment by JustAnotherArchivist** [comment]
And if that doesn't explain it, Twitter also has countless bugs in its search. See #574, #562, #468, and many more.
The changes made shouldn't affect this in any way.
