### ISSUE TITLE
Scrapes returns empty list.

### ISSUE THREAD

**Issue by ValeOG** [JustAnotherArchivist/snscrape#680]
### Describe the bug

Hi,

As everyone I had the "Error retrieving https://api.twitter.com/.." a few days ago. After that I could run one successful scrape, but now I get and empty list (with the same parameters).

### How to reproduce

https://colab.research.google.com/drive/1-UAhpRaxqeqv8hfNKiMS7blCDJiMKWlN?usp=sharing
https://docs.google.com/spreadsheets/d/1Fasp9cwdB8ADNiv0nBx2SxDHTua0YfU5/edit?usp=sharing&ouid=117483678855248599595&rtpof=true&sd=true

### Empty query results

![Screen Shot 2023-01-16 at 11 56 11 AM (2)](https://user-images.githubusercontent.com/118480739/212757216-78876744-5f6c-45d3-9720-beaf32574d32.png)

### OS / Distro

GoogleColab on chrome

### Output from `snscrape --version`

snscrape-0.5.0.20230113-py3-none-any.whl 

### Scraper

by location

### How are you using snscrape?

CLI

**Comment by JustAnotherArchivist** [comment]
Do you get different results when you enter the same search query on Twitter's web interface?

**Comment by ValeOG** [comment]
Yes! I do get results

**Comment by JustAnotherArchivist** [comment]
So, example query where you get results in the browser but not with snscrape?

**Comment by ValeOG** [comment]
<img width="1512" alt="Screen Shot 2023-01-16 at 12 24 42 PM" src="https://user-images.githubusercontent.com/118480739/212760366-103a9082-cc84-4c19-a656-b1aa4f3c0b43.png">
Yes, the query was "parking lots", I added "Los Angeles" as I am scraping by coordinates location

**Comment by ValeOG** [comment]
While in Snscrape:
![Screen Shot 2023-01-16 at 12 26 55 PM (2)](https://user-images.githubusercontent.com/118480739/212760854-38463753-3109-4b43-89cd-f51023a77c82.png)

**Comment by JustAnotherArchivist** [comment]
Those are different queries. `parking lot los angeles` is obviously not the same thing as `parking lot geocode:"..."`. `snscrape -n 10 twitter-search 'parking lot los angeles'` works just fine for me from multiple locations.

**Comment by ValeOG** [comment]
Right. I'm not sure how to search by geocode in the browser. But I used to have tweets when I run the same code last week.
Could it be something related to the search by geocode?

**Comment by JustAnotherArchivist** [comment]
You can use the exact same queries as you do with snscrape. That's exactly what snscrape does, anyway; it emulates that search.

https://twitter.com/search?q=parking+lot+geocode:%2234.05,%20-118.25,%205km%22&f=live

**Comment by JustAnotherArchivist** [comment]
As for 'but it worked last week': https://github.com/JustAnotherArchivist/snscrape/issues/675#issuecomment-1383551142

**Comment by ValeOG** [comment]
Fantastic, I'll give it a look. Thanks!
