### ISSUE TITLE
Scraped 'content' marked as an error in when converting to JSON

### ISSUE THREAD

**Issue by San-texnik** [JustAnotherArchivist/snscrape#681]
Hi, 

I used to use this code for scraping Twitter by search, converting the results into json and exporting them into a new txt file.  However, today the issue arised as in the attached picture, where it it marks 'content' as an error. What could be the issue?

<img width="959" alt="issue ss" src="https://user-images.githubusercontent.com/93559360/212771909-82418ce6-3472-4a4a-916a-d09e656b2d54.png">

**Comment by JustAnotherArchivist** [comment]
`content` is deprecated and isn't exported to JSON (related: #611). Use `renderedContent` or `rawContent` instead.

Also, there's no reason to first convert to JSON and then load that again. You can just use `tweet.rawContent` etc. directly instead.
