### ISSUE TITLE
TwitterProfileScrapping

### ISSUE THREAD

**Issue by AlanTellezS** [JustAnotherArchivist/snscrape#685]
Is there any way to get more than 3200 tweets or use a filter to get older ones? I'm missing some retweets I need that I can't even see in the website anymore since the query "(from:User) include:nativeretweets" doesn't work with "since" and "until" and scrolling doesn't work either, I'm really lost as to how to get more tweets (The last one I get is from 2022/08/08 and the missing retweets go up to 2021/08/dd) it's like 200 missing

**Comment by JustAnotherArchivist** [comment]
https://github.com/JustAnotherArchivist/snscrape/issues/83#issuecomment-738950400
