### ISSUE TITLE
Fetch most relevant tweets for a specified time period

### ISSUE THREAD

**Issue by arthurGrigo** [JustAnotherArchivist/snscrape#688]
### Describe the feature

As decribed in the following post ( https://twittercommunity.com/t/introducing-the-sort-order-parameter-for-search-endpoints-in-the-twitter-api-v2/166377 ) the '/recent' API endpoint  allows to fetch for example the 100 most relevant tweets for a given time period. As I know, this endpoint only allows to fetch tweets not older than 7 days.

Is it possible for snscrape to implement such a functionality using other API endpoints than the '/recent' endpoint ( e.g. the /2/search/adaptive.json API endpoint)?

It would be helpful to opbtain, for example, the 100 most relevant tweets of a frequently used topic of a specific day in the last months.

**Comment by JustAnotherArchivist** [comment]
Does that API endpoint return something different than the 'top' search? If so, is this functionality available anywhere on Twitter's web interface without authentication?
