### ISSUE TITLE
twitter limitations

### ISSUE THREAD

**Issue by lukaspistelak** [JustAnotherArchivist/snscrape#69]
I have question:
For twitter-search flag exist same API limitations_?

Because it looks like works like charm after 1000 calls...and i Know twitter is One big limit:)

**Comment by JustAnotherArchivist** [comment]
snscrape emulates the web interface, so no, the API limits do not apply.

**Comment by jannat5134** [comment]
> snscrape emulates the web interface, so no, the API limits do not apply.

can you please explain it broadly?
