### ISSUE TITLE
How can I scrape information about a specific user?

### ISSUE THREAD

**Issue by dadiaz14** [JustAnotherArchivist/snscrape#692]
I want to do a scraping of a user by xyz to know if he is verified, how many tweets he has published etc.
Could you help me?

**Comment by TheTechRobo** [comment]
On Twitter?

**Comment by dadiaz14** [comment]
> On Twitter?

Yes, please

**Comment by JustAnotherArchivist** [comment]
You're looking for the `--with-entity` option, probably combined with `--max-results 0` unless you want to scrape the tweets themselves as well. And `--jsonl` to not only get the URL back.

    snscrape --jsonl --with-entity --max-results 0 twitter-user username
