### ISSUE TITLE
404 on Twitter scrapes when using proxies

### ISSUE THREAD

**Issue by Shifter2600** [JustAnotherArchivist/snscrape#693]
CRITICAL: Errors: non-200 status code (404), non-200 status code (404), non-200 status code (404), non-200 status code (404)

I've tried Rayobyte and SSLprivateproxy for Twitter. 
Using either of these proxies result in Error. Is the issue with the proxy service? Does anyone have TwitterSearchScraper working with , proxies = {'https': 'http://IP:PORT'}

I am using the most resent version.

**Comment by JustAnotherArchivist** [comment]
This is an issue with your proxies, most likely wrong TLS settings when the proxy connects to Twitter's servers.

**Comment by Shifter2600** [comment]
> This is an issue with your proxies, most likely wrong TLS settings when the proxy connects to Twitter's servers.

I have wrapped the solution posted into my .py. it works with out the proxies but as soon as I put proxies in that is when i get the 404 error. The 3 proxies services are ISP private proxies which are not shared so I would expect one of them to work. Below is my code with the solution that was posted about. 

`#!/usr/bin/env python3
# python3 parser.py --results "1000" --type crypto --query "bitcoin OR btc lang:en" --endpoint 0.0.0.0:15111 --since "60"

import argparse
import json
import logging
import subprocess
import time
from datetime import datetime, timedelta
import ssl
from requests.adapters import HTTPAdapter
from urllib3.poolmanager import PoolManager
from urllib3.util.ssl_ import create_urllib3_context
import requests
import snscrape.modules.twitter as sntwitter
CIPHERS = "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384"

class TlsAdapter(HTTPAdapter):
    def __init__(self, ssl_options=0, **kwargs):
        self.ssl_options = ssl_options
        super(TlsAdapter, self).__init__(**kwargs)

    def init_poolmanager(self, *pool_args, **pool_kwargs):
        ctx = create_urllib3_context(ciphers=CIPHERS, cert_reqs=ssl.CERT_REQUIRED, options=self.ssl_options)
        self.poolmanager = PoolManager(*pool_args, ssl_context=ctx, **pool_kwargs)
        
logging.basicConfig(format='[%(asctime)s] %(levelname)s: %(message)s',
                    level=logging.INFO, datefmt='%Y/%m/%dT%H:%M:%S')

parser = argparse.ArgumentParser(description='Description of your program')
parser.add_argument('-r', '--results', help='Number of results to gather.', required=True, type=int)
parser.add_argument('-t', '--type', help='Type of the data to inject into results.', required=True, type=str)
parser.add_argument('-q', '--query', help='Search query.', required=True, type=str)
parser.add_argument('-e', '--endpoint', help='Endpoint URL.', required=True, type=str)
parser.add_argument('-s', '--since', help='Since time tweak.', required=True, type=int)
args = vars(parser.parse_args())
#adapter = TlsAdapter(ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1)
adapter = TlsAdapter(ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1)  # prioritize TLS 1.2

while True:
    since = datetime.now() - timedelta(seconds=args['since'])
    logging.info('Requesting data since %s', since)
    session = requests.Session()
    session.mount("https://", adapter)

    for n, tweet in enumerate(
            sntwitter.TwitterSearchScraper(
                f"{args['query']} since:{datetime.now().strftime('%Y-%m-%d')}", proxies = {'https': 'http://0.0.0.0:0000'}).get_items()):
        if n > args['results']:
            break
        data = json.loads(tweet.json())
        if datetime.strptime(data['date'], "%Y-%m-%dT%H:%M:%S+00:00") < since:
            break
        data.update({'type': args['type']})
        logging.info(data)
        response = requests.post(f"http://{args['endpoint']}",
                                 json=data,
                                 auth=("twitter", "password")
                                 )
        logging.info(f"Response: {response.text}, Status: {response.status_code}")`

**Comment by JustAnotherArchivist** [comment]
I believe you can't control the ciphers used by the proxy if it doesn't reuse the client ciphers for its upstream connections. Your options are: a) use a different proxy; b) host a proxy with a working configuration yourself, but then you might as well just run snscrape on that machine; or c) if you can connect to Twitter directly, stop using a proxy altogether.

**Comment by Shifter2600** [comment]
> I believe you can't control the ciphers used by the proxy if it doesn't reuse the client ciphers for its upstream connections. Your options are: a) use a different proxy; b) host a proxy with a working configuration yourself, but then you might as well just run snscrape on that machine; or c) if you can connect to Twitter directly, stop using a proxy altogether.

I can connect directly to twitter so how else can you protect your IP from getting banned by twitter if you are not using a proxy to hide your IP?

**Comment by JustAnotherArchivist** [comment]
Even with quite heavy usage (a dozen+ scrapes in parallel for days), I haven't managed to get myself banned so far, but that's not a guarantee obviously. Running it on expendable cloud servers would be an option I suppose.
