### ISSUE TITLE
Will the twitter scraper still work after the announcement that twitter will end free access to its API?

### ISSUE THREAD

**Issue by kathulhur** [JustAnotherArchivist/snscrape#695]

**Comment by JustAnotherArchivist** [comment]
snscrape has never used the API. So yes, it will still work. This obviously doesn't include any other changes they might make.

**Comment by kathulhur** [comment]
Aren't you using a v2 endpoint?

I saw that you use: https://api.twitter.com/2/search/adaptive.json

Will they not possibly restrict the entire api endpoint? given that they will no longer have any free tier?

**Comment by JustAnotherArchivist** [comment]
No, this is not part of the official API that is being closed down.

**Comment by kathulhur** [comment]
Great. Thank you

**Comment by MathiasExorde** [comment]
Are you sure about that?  Do you have some source detailing what is going to be disrupted and what isn't?
I expect an interruption in 7 days.

**Comment by JustAnotherArchivist** [comment]
@MathiasExorde I don't. But snscrape just does what the website does, and I'm assuming they aren't going to intentionally break their own website with this change. As I said, this doesn't mean things might not break for *other* reasons – including them changing the website to a different internal interface – but that's unrelated to the official API being made unavailable to free users.

**Comment by MathiasExorde** [comment]
I understand the distinction, thanks! Let's see, and let's adapt if we can.

**Comment by guusec** [comment]
the authorization token snscrape uses is what twitter's api appends to authenticated users and requests that use the api keys. 
https://github.com/JustAnotherArchivist/snscrape/blob/23ebdd2a3ce6c3e93012e2b5bc7c2b02c749aaf2/snscrape/modules/twitter.py#L52
am i wrong about this? is snscrape's twitter module running off a single session from an authenticated twitter account?
