### ISSUE TITLE
Got Error "4 requests to twitter API" when using multithreads

### ISSUE THREAD

**Issue by obada-jaras** [JustAnotherArchivist/snscrape#696]
### Describe the bug

The code was working properly with me, but when I uses multithreading in python I got error `4 requests to https://api.twitter.com/2/sea...`

You can check my code in [this repository](https://github.com/obada-jaras/Arabic-Tweets-Scraper)

### How to reproduce

The error disappear without using multithreading 

### Expected behaviour

the code expected to work properly and scrap tweets in multithreads, each thread should scrap tweets for a user and save them in a separated text file.

### Operating system

Windows 11

### Python version: output of `python3 --version`

3.10.2

### snscrape version: output of `snscrape --version`

0.5.0.20230113

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
#623
