### ISSUE TITLE
Key error: 'tweet_results'

### ISSUE THREAD

**Issue by bro-web3-dev** [JustAnotherArchivist/snscrape#697]
### Describe the bug

Hi! A couple of hours ago I parsed twitter and everything worked, but now when using twitter.Twitter profile scraper error occurs:
Backtrace (the most recent call last):
File "<PATH>", line 19, in <module>
    for j, tweet in enumerate(scraper.get_items()):
File "<PATH>\Python311\Lib\site-packages\snscrape\modules\twitter.py ", line 1706, in get_items
    exit self._graphql_timeline_tweet_item_result_to_tweet(instruction['entry']['content']['itemContent']['tweet_results']['result'])
                            
![image](https://user-images.githubusercontent.com/121391659/216618070-14c23068-375a-492b-a520-db39d4c57675.png)

                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
Key error: 'tweet_results'

### How to reproduce

Use **scraper = sntwitter.TwitterProfileScraper(f'{influener}')** and **scraper.get_items()**



### Expected behaviour

Just a couple of hours ago everything was working, but now an error occurs

### Screenshots and recordings

_No response_

### Operating system

Windows10

### Python version: output of `python3 --version`


Python3.11

### snscrape version: output of `snscrape --version`


snscrape0.5.0.20230113

### Scraper

TwitterProfileScraper

### Backtrace

ERROR:
    yield self._graphql_timeline_tweet_item_result_to_tweet(instruction['entry']['content']['itemContent']['tweet_results']['result'])
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'tweet_results'

### Dump of locals

_No response_

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Additional context

_No response_

**Comment by bro-web3-dev** [comment]
Now it's working! It looks like I'm stupid or I've been blocked

**Comment by JustAnotherArchivist** [comment]
I've seen another random crash last night which also resolved itself soon after. Twitter currently seems to be returning incorrect and inconsistent data sometimes. So yeah, best to wait a bit and then retry.

**Comment by bro-web3-dev** [comment]
> I've seen another random crash last night which also resolved itself soon after. Twitter currently seems to be returning incorrect and inconsistent data sometimes. So yeah, best to wait a bit and then retry.

thx bro, snscrape really helped me out, I am insanely grateful
And I want to say thank you, brother!
