### ISSUE TITLE
How does this code works?

### ISSUE THREAD

**Issue by yangyangdotcom** [JustAnotherArchivist/snscrape#70]
Sorry, I am new to web crawling. How do I make this program work? I try to` snscrape twitter-user textfiles` but it only shows the link of Jason Scott. How do I change the user I want to scrap? Also, if I want to scrap tweet by using keyword, how do I do that?

**Comment by solocarrie** [comment]
> Sorry, I am new to web crawling. How do I make this program work? I try to` snscrape twitter-user textfiles` but it only shows the link of Jason Scott. How do I change the user I want to scrap? Also, if I want to scrap tweet by using keyword, how do I do that?

Hi, the example you point to `snscrape twitter-user textfiles` refers to the Jason Scott who has the twitter handle textfiles. To change the user simply change `textfiles` to the twitter handle of the user you want to scrape.

To scrape tweets by keywords, I believe you have to use `snscrape twitter-search keyword`, where `keyword` is whatever keyword you want to scrape.

**Comment by yangyangdotcom** [comment]
Appreciate it! I tried it with user whose id has no space and it works! But what it does not work when I want to scrape someone whose id has space in between? Also, does this program capable of keeping the data we found in a file?

**Comment by solocarrie** [comment]
> Appreciate it! I tried it with user whose id has no space and it works! But what it does not work when I want to scrape someone whose id has space in between? Also, does this program capable of keeping the data we found in a file?

I don't think there are twitter handles with spaces in them.

In terms of storing the data, I'm not too familiar with using it in the cli. However you can always do it yourself if you use it as a module within python. For example if I want the text for every tweet by user textfiles stored into a textfiles.csv I could always do something like:

`
import snscrape.modules
import csv

tweets=snscrape.modules.twitter.TwitterUserScraper(username='textfiles')

with open('textfiles.csv', 'a', encoding='utf-8') as f:
    wr=csv.writer(f, lineterminator = '\n')
    for i in tweets.get_items():
        wr.writerow([i.content])
`

Within the Tweet object you can access url, date, content, id, username, outlinks, outlinksss, tcooutlinks, tcooutlinksss

**Comment by zhixideyu** [comment]
> > 赞赏！我尝试使用其ID没有空格的用户使用，并且可以正常工作！但是，当我要刮擦其ID之间有空格的人时，什么不起作用？另外，此程序是否能够将我们找到的数据保留在文件中？
> 
> 我认为其中没有包含空格的Twitter句柄。
> 
> 在存储数据方面，我不太喜欢在cli中使用它。但是，如果将其用作python中的模块，则始终可以自己进行操作。例如，如果我希望每条推文的文本由存储在textfiles.csv中的用户文本文件存储，则可以始终执行以下操作：
> 
> ```
> import snscrape.modules
> import csv
> 
> tweets=snscrape.modules.twitter.TwitterUserScraper(username='textfiles')
> 
> with open('textfiles.csv', 'a', encoding='utf-8') as f:
>     wr=csv.writer(f, lineterminator = '\n')
>     for i in tweets.get_items():
>         wr.writerow([i.content])
> ```
> 
> 在Tweet对象中，您可以访问url，日期，内容，id，用户名，外链，外链SS，tcooutlinks，tcooutlinksss

Hello, how to limit the search time range？

**Comment by solocarrie** [comment]
> Hello, how to limit the search time range？

I'm not too sure about that since I haven't looked into the code too much and there currently isn't any documentation for it. Hopefully someone else can provide further detail on this.

What I do know though is that on the cli you can do something like this:

`snscrape --since "2020-09-21 12:00:00" twitter-user textfiles`

with any of the below date time formats: 

`'%Y-%m-%d %H:%M:%S %z', '%Y-%m-%d %H:%M:%S', '%Y-%m-%d %z', '%Y-%m-%d'`

For using it as a module I am currently just using a break statement if the returned date time is less than your desired set start date time. This appears to be fine since the objects are always returned in order from newest to oldest.

**Comment by topliftarm** [comment]
> > > 赞赏！我尝试使用其ID没有空格的用户使用，并且可以正常工作！但是，当我要刮擦其ID之间有空格的人时，什么不起作用？另外，此程序是否能够将我们找到的数据保留在文件中？
> > 
> > 
> > 我认为其中没有包含空格的Twitter句柄。
> > 在存储数据方面，我不太喜欢在cli中使用它。但是，如果将其用作python中的模块，则始终可以自己进行操作。例如，如果我希望每条推文的文本由存储在textfiles.csv中的用户文本文件存储，则可以始终执行以下操作：
> > ```
> > import snscrape.modules
> > import csv
> > 
> > tweets=snscrape.modules.twitter.TwitterUserScraper(username='textfiles')
> > 
> > with open('textfiles.csv', 'a', encoding='utf-8') as f:
> >     wr=csv.writer(f, lineterminator = '\n')
> >     for i in tweets.get_items():
> >         wr.writerow([i.content])
> > ```
> > 
> > 
> > 在Tweet对象中，您可以访问url，日期，内容，id，用户名，外链，外链SS，tcooutlinks，tcooutlinksss
> 
> Hello, how to limit the search time range？

how get number of like, number or retweet, number of comment? you know?

**Comment by topliftarm** [comment]
> > > 赞赏！我尝试使用其ID没有空格的用户使用，并且可以正常工作！但是，当我要刮擦其ID之间有空格的人时，什么不起作用？另外，此程序是否能够将我们找到的数据保留在文件中？
> > 
> > 
> > 我认为其中没有包含空格的Twitter句柄。
> > 在存储数据方面，我不太喜欢在cli中使用它。但是，如果将其用作python中的模块，则始终可以自己进行操作。例如，如果我希望每条推文的文本由存储在textfiles.csv中的用户文本文件存储，则可以始终执行以下操作：
> > ```
> > import snscrape.modules
> > import csv
> > 
> > tweets=snscrape.modules.twitter.TwitterUserScraper(username='textfiles')
> > 
> > with open('textfiles.csv', 'a', encoding='utf-8') as f:
> >     wr=csv.writer(f, lineterminator = '\n')
> >     for i in tweets.get_items():
> >         wr.writerow([i.content])
> > ```
> > 
> > 
> > 在Tweet对象中，您可以访问url，日期，内容，id，用户名，外链，外链SS，tcooutlinks，tcooutlinksss
> 
> Hello, how to limit the search time range？

tweets = snscrape.modules.twitter.TwitterSearchScraper("to:@username since:2020-09-20 until:2020-09-21")

**Comment by topliftarm** [comment]
> > > > 赞赏！我尝试使用其ID没有空格的用户使用，并且可以正常工作！但是，当我要刮擦其ID之间有空格的人时，什么不起作用？另外，此程序是否能够将我们找到的数据保留在文件中？
> > > 
> > > 
> > > 我认为其中没有包含空格的Twitter句柄。
> > > 在存储数据方面，我不太喜欢在cli中使用它。但是，如果将其用作python中的模块，则始终可以自己进行操作。例如，如果我希望每条推文的文本由存储在textfiles.csv中的用户文本文件存储，则可以始终执行以下操作：
> > > ```
> > > import snscrape.modules
> > > import csv
> > > 
> > > tweets=snscrape.modules.twitter.TwitterUserScraper(username='textfiles')
> > > 
> > > with open('textfiles.csv', 'a', encoding='utf-8') as f:
> > >     wr=csv.writer(f, lineterminator = '\n')
> > >     for i in tweets.get_items():
> > >         wr.writerow([i.content])
> > > ```
> > > 
> > > 
> > > 在Tweet对象中，您可以访问url，日期，内容，id，用户名，外链，外链SS，tcooutlinks，tcooutlinksss
> > 
> > 
> > Hello, how to limit the search time range？
> 
> how get number of like, number or retweet, number of comment? you know?

and how to get conversation_id ??

**Comment by yangyangdotcom** [comment]
> 
> 
> > Appreciate it! I tried it with user whose id has no space and it works! But what it does not work when I want to scrape someone whose id has space in between? Also, does this program capable of keeping the data we found in a file?
> 
> I don't think there are twitter handles with spaces in them.
> 
> In terms of storing the data, I'm not too familiar with using it in the cli. However you can always do it yourself if you use it as a module within python. For example if I want the text for every tweet by user textfiles stored into a textfiles.csv I could always do something like:
> 
> ```
> import snscrape.modules
> import csv
> 
> tweets=snscrape.modules.twitter.TwitterUserScraper(username='textfiles')
> 
> with open('textfiles.csv', 'a', encoding='utf-8') as f:
>     wr=csv.writer(f, lineterminator = '\n')
>     for i in tweets.get_items():
>         wr.writerow([i.content])
> ```
> 
> Within the Tweet object you can access url, date, content, id, username, outlinks, outlinksss, tcooutlinks, tcooutlinksss

Sorry, I am a little bit confused. I opened a new python project in the modules file and put the code you gave me in it.
When I run `snscrape twitter-user textfiles`. It gives me error like this
`Traceback (most recent call last):
  File "c:\users\chopagne\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\chopagne\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chopagne\anaconda3\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "c:\users\chopagne\anaconda3\lib\site-packages\snscrape\cli.py", line 224, in main
    args = parse_args()
  File "c:\users\chopagne\anaconda3\lib\site-packages\snscrape\cli.py", line 159, in parse_args
    import snscrape.modules
  File "c:\users\chopagne\anaconda3\lib\site-packages\snscrape\modules\__init__.py", line 15, in <module>
    _import_modules()
  File "c:\users\chopagne\anaconda3\lib\site-packages\snscrape\modules\__init__.py", line 12, in _import_modules
    module = importlib.import_module(moduleName)
  File "c:\users\chopagne\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\chopagne\anaconda3\lib\site-packages\snscrape\modules\files.py", line 4, in <module>
    tweets=snscrape.modules.twitter.TwitterUserScraper("9Gag")
AttributeError: module 'snscrape' has no attribute 'modules'`
Do I have to change my command when I put in the new code you gave me?

**Comment by solocarrie** [comment]
> how get number of like, number or retweet, number of comment? you know?

Hi, if you really want to get something like the number of likes etc (right now) I think you will have to modify the source code since these options do not currently appear in the tweet object. For example, if you wanted the number of likes you would modify twitter.py within the modules folder:

1. add `likes: int` to the Tweet class.
2. add `likes = tweet['favorite_count']`  to the get_items function within the TwitterSearchScraper class.
3. modify the yield statement at the end of the get_items function to include `likes`.

**Comment by lukaspistelak** [comment]
when i run 

`for i in tweets.get_items():`
I get :
`ValueError: time data 'Mon Aug 24 17:01:54 +0000 2020' does not match format '%a %b %d %H:%M:%S +0000 %Y'`

**Comment by JustAnotherArchivist** [comment]
@topliftarm snscrape currently doesn't extract like count, conversation ID, etc. The data is definitely returned by Twitter's endpoint though, so it should not be difficult to add that in principle.

@lukaspistelak I assume that your system language is set to something other than English? I think Python's datetime parsers are locale-dependent.

**Comment by Harrypeas** [comment]
I tried to collect tweets by searching the keyword and it worked!
`snscrape twitter-search 'keyword' > ./test.txt`
However, after collecting about 300 tweets, the process terminated and I got a KeyError: '1308942484832227328'. I tried three times and got the same keyErrors.
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/17609739/94094091-3dbfaf80-fe51-11ea-9c87-6e36cccfa682.png">

**Comment by JustAnotherArchivist** [comment]
@Harrypeas I also found that crash earlier and have a fix, but it's not committed yet. Note that you're using the current development version, which may break at any time.

Also, for everyone: if you find bugs (including crashes), please file a proper issue instead of replying here.

**Comment by Bakdaulet1** [comment]
Can I find location (the one sometimes indicated in their profiles) of the followers on Twitter?

**Comment by JustAnotherArchivist** [comment]
@Bakdaulet1 No, that's not currently supported. Followers are not accessible without a login as far as I know, so this is impossible to implement.

**Comment by Bakdaulet1** [comment]
> @Bakdaulet1 No, that's not currently supported. Followers are not accessible without a login as far as I know, so this is impossible to implement.

Thanks for quick answer. How about info (like their profile bio) on the users that tweeted a certain hashtag?

**Comment by JustAnotherArchivist** [comment]
@Bakdaulet1 Yes, some of that information is extracted in the most recent dev version. Specifically: description (raw and with t.co URLs replaced), verified flag, registration date, followers/friends/statuses count, link, profile image, and profile banner. There's a `user` key for every `Tweet` object which contains that. Details [in the code only](https://github.com/JustAnotherArchivist/snscrape/blob/f1428fa0e04370f98327c703e714e7298b92f21a/snscrape/modules/twitter.py) for now, no documentation, sorry. I will likely add a few more fields soon (location, media count, name, and possibly some others that I still need to investigate).

**Comment by Bakdaulet1** [comment]
> @Bakdaulet1 Yes, some of that information is extracted in the most recent dev version. Specifically: description (raw and with t.co URLs replaced), verified flag, registration date, followers/friends/statuses count, link, profile image, and profile banner. There's a `user` key for every `Tweet` object which contains that. Details [in the code only](https://github.com/JustAnotherArchivist/snscrape/blob/f1428fa0e04370f98327c703e714e7298b92f21a/snscrape/modules/twitter.py) for now, no documentation, sorry. I will likely add a few more fields soon (location, media count, name, and possibly some others that I still need to investigate).

I am sorry. I am new to this. What function would I call to retrieve the user information?

**Comment by JustAnotherArchivist** [comment]
There are two options: API or postprocessing. In both cases, you will get duplicates for users who posted multiple matching tweets.

The API is undocumented. To list all users who tweeted the hashtag \#something:

```python
import snscrape.modules.twitter
for tweet in snscrape.modules.twitter.TwitterHashtagScraper('something').get_items():
	print(tweet['user'])
```

You could also use the JSONL output of snscrape (see README, `snscrape --jsonl twitter-hashtag something`) and then process it however you like after the scraping.

All of this requires the current development version since user extraction (beyond the username) didn't exist yet in the last release. Due to that, it's possible that this will break at any time as I decide to rewrite the relevant code. (This is mostly a warning for possible people reading this in the future.)

**Comment by lukaspistelak** [comment]
> There are two options: API or postprocessing. In both cases, you will get duplicates for users who posted multiple matching tweets.
> 
> The API is undocumented. To list all users who tweeted the hashtag #something:
> 
> ```python
> import snscrape.modules.twitter
> for tweet in snscrape.modules.twitter.TwitterHashtagScraper('something').get_items():
> 	print(tweet['user'])
> ```
> 
> You could also use the JSONL output of snscrape (see README, `snscrape --jsonl twitter-hashtag something`) and then process it however you like after the scraping.
> 
> All of this requires the current development version since user extraction (beyond the username) didn't exist yet in the last release. Due to that, it's possible that this will break at any time as I decide to rewrite the relevant code. (This is mostly a warning for possible people reading this in the future.)



> @lukaspistelak I assume that your system language is set to something other than English? I think Python's datetime parsers are locale-dependent.

u v got right ! thanks!

**Comment by JustAnotherArchivist** [comment]
@lukaspistelak I fixed that last night in 2332c30e.

**Comment by JSMboli** [comment]
> outlinks, outlinksss, tcooutlinks, tcooutlinksss

All these works but how can I likecount and retweet count working too?
Thank you

**Comment by frida96** [comment]
hi. How can I get names of friends(follower and followings) a user?

**Comment by frida96** [comment]
how do i get a user friends(followings and followers) usernames?thanks

**Comment by TheTechRobo** [comment]
@frida96 #174

**Comment by frida96** [comment]
> @frida96 #174

there is no way? ok .Thank you for fastly answer
