### ISSUE TITLE
Does sncrape use twitter api?

### ISSUE THREAD

**Issue by steevenakintilo** [JustAnotherArchivist/snscrape#701]
Since twitter api will soon cost money I wanted to know if snscrape is using any part of the twitter api?

Thanks for the answer

**Comment by JustAnotherArchivist** [comment]
Please search the issues before creating one. There's even a pinned issue about the upcoming API changes.

#695

**Comment by steevenakintilo** [comment]
Sorry for the issue I will do it thanks
