### ISSUE TITLE
I cannot install latest snscrape version (latest possible is 0.3.4)

### ISSUE THREAD

**Issue by MikicDanko** [JustAnotherArchivist/snscrape#702]
Hi, I am trying to start using snscrape to scrape tweets but I keep getting the below error:

ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=Ukraine+until%3A2023-02-04+since%3A2022-02-24+exclude%3Aretweets&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment failed, giving up.

I found out that the cause of this error is my snscrape version, but I cannot upgrade it to the latest.

**Comment by JustAnotherArchivist** [comment]
You're likely using Python 3.7. snscrape has required Python 3.8 or higher since 0.4.0. Cf. #347

**Comment by MikicDanko** [comment]
I am using Python 3.9.12. I downloaded the tar.gz file and replaced the 0.3.4 folder in my env with the 0.5 one from tar.gz.
But I am still getting this error message when trying to use TwitterSearchScraper:

ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=Ukraine+until%3A2023-02-04+since%3A2022-02-24+exclude%3Aretweets&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment failed, giving up.

**Comment by JustAnotherArchivist** [comment]
The scraper error is irrelevant since you have the wrong version of snscrape. And messing with the files directly is a good way of breaking things further. So before proceeding, I'd recommend uninstalling and then reinstalling snscrape.

How are you installing snscrape? Do you have multiple Python versions on your system? If you use `pip install snscrape`, possibly your `pip` points at a different Python version than `python3` does. What do `which python3`, `which pip`, `python3 --version`, and `pip --version` print?

**Comment by MikicDanko** [comment]
Yes, you are completely right, I was using an environment that had python 3.6, switched to the one with 3.9.12 and it's all good. 
Thanks for the support.
