### ISSUE TITLE
Twitter user does not return retweets?

### ISSUE THREAD

**Issue by IvanTrendafilov** [JustAnotherArchivist/snscrape#705]
Maybe I'm missing a setting or an option, but it looks like when I run the following command:

```
snscrape --max-results 100 --with-entity --jsonl twitter-user user
```

I don't see any retweets in that list, even very recent ones. Is there a way to include them as part of the above?

**Comment by JustAnotherArchivist** [comment]
#8 https://github.com/JustAnotherArchivist/snscrape/issues/85#issuecomment-698998263
