### ISSUE TITLE
Error "module 'snscrape.modules.telegram' has no attribute 'TelegramScraper'"

### ISSUE THREAD

**Issue by janmatti** [JustAnotherArchivist/snscrape#708]
Hi,

I have repeatedly received the above error. Using Python 3.11 and snscrape version 0.5.0.20230113 on mac BigSur 11.6. Any help is appreciated!

**Comment by JustAnotherArchivist** [comment]
Well, yes, there is no `TelegramScraper`, only a `TelegramChannelScraper`.
