### ISSUE TITLE
Are you scrapping twitter?

### ISSUE THREAD

**Issue by jhuvehicle** [JustAnotherArchivist/snscrape#709]
Are you scrapping twitter to get some of this data? (I ask since twitter has implemented new policies on their api access as of recent)

**Comment by TheTechRobo** [comment]
Does #695 answer your question?

**Comment by jhuvehicle** [comment]
It does not.

**Comment by JustAnotherArchivist** [comment]
The name kind of gives it away, doesn't it? Yes, it's a scraper.

#69 #162 etc.
