### ISSUE TITLE
Help required for running the code in Anaconda environment

### ISSUE THREAD

**Issue by baraths92** [JustAnotherArchivist/snscrape#71]
Hi. Can you help me with running this code in anaconda environment? My target is to scrape all tweets from a user timeline within a particular range of date and save it as a csv file. I do not have linux environment and I am clueless in running this program. How should i run this in anaconda? HOw to run this program in a jupyter notebook?

**Comment by JustAnotherArchivist** [comment]
I'm afraid I can't help you with this as I use neither Anaconda nor Jupyter Notebook.

**Comment by JustAnotherArchivist** [comment]
In principle it should be the same as installing any other Python package in those environments. You just need also the libxml2 and libxlst dependencies for lxml. lxml is popular enough that you can probably find instructions for that elsewhere, or perhaps someone else can help you.

Closing this as I don't think there's anything that needs to be done about this from my/the code development side.
