### ISSUE TITLE
skipping tweets with media?

### ISSUE THREAD

**Issue by TMDR** [JustAnotherArchivist/snscrape#710]
### Describe the bug

![image](https://user-images.githubusercontent.com/34814447/217283360-16eac9a8-2103-44e4-a336-03f5a155d757.png)
this is the code I have been using, and when I print the results, I get only tweets that do not include any media for some reason.
any idea why? the media is not sensitive neither is flagged as so.

### How to reproduce

run the code above, and check the results

### Expected behaviour

all tweets to show including tweets with media

### Operating system

Windows 10

### Python version: output of `python3 --version`

Python 3.9.13

### snscrape version: output of `snscrape --version`

snscrape 0.5.0.20230114.dev8+g23ebdd2

### Scraper

TwitterUserScraper

### Backtrace

FutureWarning: content is deprecated, use rawContent instead

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by TMDR** [comment]
I figured that I should replace content with rawContent in order to avoid the warning, but the issue still persists.

**Comment by JustAnotherArchivist** [comment]
Which user are you actually scraping? I'm sure it isn't [myusername](https://twitter.com/myusername).

**Comment by TMDR** [comment]
haha yes it isnt, I just wanted to add a placeholder because I dont feel comfortable disclosing the account I am scraping.
anyway, Im sorry for bothering you, media was indeed censored but I never noticed because I was logged in (I also did not notice that, tough day man), so the library was working fine, the problem was the account.
again, sorry for bothering you, I usually figure things out myself but I wasnt exactly in the mood.
Thanks for your contribution, I will now close the issue.
