### ISSUE TITLE
Twitter scraper returns None for viewCount attribute.

### ISSUE THREAD

**Issue by hoseinbehrad** [JustAnotherArchivist/snscrape#712]
### Describe the bug

scraper works fine for other attributes, but only returns None for tweet.viewCount 
viewCount type is defined as: typing.Optional[int] = None

viewCount link in code ([link](https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/modules/twitter.py#:~:text=viewCount%3A%20typing.Optional%5Bint%5D%20%3D%20None))

### How to reproduce

```
pip install snscrape
```

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd


# Creating list to append tweet data to
attributes_container = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid since:2020-04-01 until:2020-04-12').get_items()):
    if i>100:
        break
    attributes_container.append([tweet.user.username, tweet.date, tweet.likeCount,tweet.lang, tweet.sourceLabel, tweet.content, tweet.viewCount])
    
    
# Creating a dataframe to load the list
tweets_df = pd.DataFrame(attributes_container, columns=["User", "Date Created", "Number of Likes","Lang", "Source of Tweet", "Tweet", "viewCount"])
```

### Expected behaviour

since Twitter made view publicly available recently, I expect to receive the number of views for each tweet.

### Operating system

Ubuntu 20.04

### Python version: output of `python3 --version`

Python 3.8.10

### snscrape version: output of `snscrape --version`

snscrape-0.5.0.20230113

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by TheTechRobo** [comment]
The tweets you're getting are too old. Twitter only added view count for tweets published AFTER the change, which suggests they don't have historical data themselves.

**Comment by hoseinbehrad** [comment]
oh thanks
I thought the view count policy applies to all time horizons!
