### ISSUE TITLE
Meaning of returned tweets' fields

### ISSUE THREAD

**Issue by scn0901** [JustAnotherArchivist/snscrape#713]
I want to understand the meaning of all the fields of tweets obtained by crawling with snscrape, but I can't find the relevant documentation. Where can I find out it?

**Comment by JustAnotherArchivist** [comment]
There is no documentation of the individual fields yet. Besides the general lack of documentation, I haven't yet figured out how to properly document the fields (Python doesn't have attribute docstrings). But for the most part, they should be self-explanatory. Which ones do you find unclear?
