### ISSUE TITLE
Search excluding retweets, replies, and quote tweets from Twitter search results?

### ISSUE THREAD

**Issue by ViennaMike** [JustAnotherArchivist/snscrape#714]
I would like to search for recent tweets, by keyword, but only retrieve original tweets, not retweets, replies, or quote tweets. In the API, I can do this by including -is:retweet -is:reply -is:quote in the query.
1) Is there a way to do this with snscrape using snscrape.modules.twitter as a python library? If so, how?
2) Alternatively, is there a parameter returned in the search results that would then let me filter them out?

Thanks! Great tool!

**Comment by TheTechRobo** [comment]
https://github.com/igorbrigadir/twitter-advanced-search is a handy resource.

**Comment by ViennaMike** [comment]
Thanks! Looks like I could then include  -filter:retweets	-filter:replies and -filter:quote	 to keep these out. I'll give it a try!

**Comment by ViennaMike** [comment]
Tested and working. Thanks again.
