### ISSUE TITLE
Disappearing tweets

### ISSUE THREAD

**Issue by jnelson92** [JustAnotherArchivist/snscrape#715]
### Describe the bug

When I try to scrape tweets published over a given period of time in a csv file, the csv sometimes comes back completely empty.

### How to reproduce

script is as follows :
```python3
import pandas as pd
from tqdm.notebook import tqdm
import snscrape.modules.twitter as sntwitter
scraper = sntwitter.TwitterSearchScraper('#chatgpt since:2022-11-01 until:2022-11-30 lang:fr')
tweets = []
for i,tweet in enumerate(scraper.get_items()):
	data = [tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.likeCount, tweet.retweetCount]
	tweets.append(data)
	if i>500000:
		break
tweet_df = pd.DataFrame(tweets, columns=['date','id','content','username','likeCount', "retweetCount"])
tweet_df.to_csv("python-tweets.csv", index=False)

```

### Expected behaviour

I would expect a csv file to be created with all tweets containing the hashtag #chatgpt, published over the month of november 2022. In fact there is nothing at all !
On the other hand, when I use the script to collect all tweets published in december, the script works as expected.

### Operating system

Windows 10, Alienware m15 Ryzen

### Python version: output of `python3 --version`

python 3.8

### snscrape version: output of `snscrape --version`

snscrape 0.5.0.20230114.dev5+g36e85c5

### Scraper

twitter

### Backtrace

none

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
snscrape's behaviour matches [Twitter's web interface](https://twitter.com/search?q=%23chatgpt%20since%3A2022-11-01%20until%3A2022-11-30%20lang%3Afr&f=live). But also, ChatGPT was only released on 30 November; are you sure there were tweets with that hashtag before then? I'm not aware OpenAI did any prior announcements of it.
