### ISSUE TITLE
Getting the latest tweet as fast as possible

### ISSUE THREAD

**Issue by alksndrrrr** [JustAnotherArchivist/snscrape#716]
I'm not entirely sure that snscrape is built for this so my apologies if it is not, but seems like it should support this. Here is my code

```python3
list_id = 'public_list_id_here'
s = sntwitter.TwitterListPostsScraper(list_id)
content = []

while True:
    # start_time = time.time()
    for i, t in enumerate(s.get_items()):
        if len(content) > 0:
            if content[-1] != t.rawContent:
                content.append(t.rawContent)
                print (content[-1])
        else:
            content.append(t.rawContent)
            print (content[-1])
        # print ("My program took", time.time() - start_time, "to run")
        break
```

So the goal here is constantly look at a twitter list and grab the latest tweet, just doing some checking to make sure it only tells me if its a new tweet, and that's it. The program itself takes around 1.6 seconds to run on average, and not only does it miss some tweets because of that, it seems to not even pick up that a new tweet has been made for around 5-6 seconds at a time. Missing tweets is painful, as well as the 5-10 seconds that sometimes pass before it finds the newest tweet.

I'm not sure if I am just not setting it up right, or maybe for this use case I would run it like in 10 diff processes to just cover that whole time frame? How can I best utilize snscrape capabilities for this goal?

thank you for any advice

**Comment by JustAnotherArchivist** [comment]
While snscrape doesn't support the actual polling you'd get on the web interface (loading new tweets when you scroll to the top), you can emulate it with something similar to what you did, yeah. I'd recommend comparing tweet IDs rather than content for reliability, and then just keep iterating until you get a tweet previously seen, which ensures that you won't miss tweets. #148 has an example of that. However, I wouldn't be surprised if aggressive polling would lead to a ban. You'll have to balance the very real possibility of complete breakage against your desire to get the tweets in real time.

**Comment by alksndrrrr** [comment]
Thank you for the very prompt reply. I'm willing to sleep it for half a second+ to not get insta banned, but do you have any thoughts on the general delay in gathering the tweet? Just the reality of it or is there anything that can be done? I can't understand what is the difference because sometimes a tweet from this code will pop up before I even see it on tweetdeck and then the next one will be delayed by like 7 seconds

**Comment by JustAnotherArchivist** [comment]
> I'm willing to sleep it for half a second+ to not get insta banned

Well, ok, good luck then. I'd be surprised if that lasted. I would like to know how quickly you get banned though. :-)

> do you have any thoughts on the general delay in gathering the tweet?

There are definitely delays. The search isn't particularly great at recent tweets. They need to get indexed first, and that can sometimes take a bit. It's somewhat random, but the details would only be known to Twitter employees (or, more realistically, to a handful of former and no current employees). I've only used this polling strategy with profiles before, which are more reliable but probably not useful for your purposes.

**Comment by alksndrrrr** [comment]
Ah man, if I'd get banned quickly I may have to rethink this :( 

This sure is hard to do, would pay some serious money to be able to get tweets asap... I don't mind doing it per user (even though I'd have to do it on like 50 users, I can do an AWS for each).. I'll give that a shot and see if thats any faster. Thanks for the explanation, good to know I'm at least working with snscrape correctly
