### ISSUE TITLE
does not parse tweets for today

### ISSUE THREAD

**Issue by yarosh01** [JustAnotherArchivist/snscrape#717]
hello everyone, are you parsing tweets for today? every day it worked fine, now tweets do not come, I use this query: "'(bitcoin OR btc) lang:en until:2023-02-10 since:2023-02-09'"

**Comment by JustAnotherArchivist** [comment]
Please file a complete bug report if it isn't working correctly; this isn't a question. `snscrape -n 10 twitter-search '(bitcoin OR btc) lang:en until:2023-02-10 since:2023-02-09'` works fine here.
