### ISSUE TITLE
no longer returns retweets

### ISSUE THREAD

**Issue by zoubidabida** [JustAnotherArchivist/snscrape#718]
### Describe the bug

since 09 feb, the API no longer returns retweets. I get a list of tweets and replies but no RT.
They simply aren't in the list returned by TwitterSearchScraper(search).get_items()

I'm using the release version, not the latest git, will try with it.

### How to reproduce

search = f"from:{from} since_id:{lastid}"
for tweet in enumerate(sntwitter.TwitterSearchScraper(search).get_items()):

### Expected behaviour

RT should be included in the results, they used to be

### Operating system

debian 11

### Python version: output of `python3 --version`

Python 3.9.2

### snscrape version: output of `snscrape --version`

snscrape 0.5.0.20230113

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by zoubidabida** [comment]
fixed with the current git version !

**Comment by TheTechRobo** [comment]
Huh? The search shouldn't ever return retweets unless you specify them with `include:nativeretweets`.

**Comment by zoubidabida** [comment]
maybe my vocabulary isn't right.
I mean it shows tweets that are RT, like this one, which is in my results : https://twitter.com/joshtpm/status/1623656227275169793

**Comment by TheTechRobo** [comment]
Oh, ok. I thought you meant just the tweets that have the "X person retweeted" on them.

**Comment by JustAnotherArchivist** [comment]
Those are called 'quote tweets'. I do see it with 0.5.0, and there haven't been any changes in the dev version that should cause a change in behaviour in this area anyway.
