### ISSUE TITLE
scrape twitter for all languages

### ISSUE THREAD

**Issue by topliftarm** [JustAnotherArchivist/snscrape#72]
how  disable "lang":"en" for scrape whole tweets?

**Comment by topliftarm** [comment]
i can use lang:.. but how disable or how select whole lang?

**Comment by p-dre** [comment]
With snscrape twitter-search "python lang:de" >twitter-@textfiles as example you get the german tweets with the keyword python. 

So with snscrape twitter-search "python" >twitter-@textfiles you get all tweets with the keyword python

**Comment by JustAnotherArchivist** [comment]
`'lang': 'en'` is only passed to be guaranteed an English interface. It does not filter the results but returns everything. You would have to explicitly add a `lang:x` filter to the search query to only get English tweets (or another language).

**Comment by JustAnotherArchivist** [comment]
@p-dre To avoid any confusion, the thing after `>` is just the output filename. `twitter-@username` is the convention I've been using for years for scraping users, and similarly `twitter-#hashtag`. If you scrape something else like a search, you should change that to reflect that.
