### ISSUE TITLE
Recurse Key Error: Variables

### ISSUE THREAD

**Issue by NewtoCoding48** [JustAnotherArchivist/snscrape#721]
### Describe the bug

Hi! Love the code, thank you. 

I'm trying to pull all the replies and replies to replies from a given conversation_ID. The code works perfectly with `mode=sntwitter.TwitterTweetScraperMode.SCROLL` but when I set it to `mode=sntwitter.TwitterTweetScraperMode.RECURSE` I get the error `KeyError: 'variables'`

this is the code (but obviously I change 'TWEET_ID' to be the integer tweet ID, I just left it out for privacy): 

```python3
tweet_comments = []
tweet = ['TWEET_ID']
for i, tweet in enumerate(sntwitter.TwitterTweetScraper(tweetId=tweet,mode=sntwitter.TwitterTweetScraperMode.RECURSE).get_items()):
    tweets = {
            "tweetid": str(tweet.id),
            "author_ID" : tweet.user.id,
            "inReplyToTweetId": str(tweet.inReplyToTweetId),
            "conversationId": str(tweet.conversationId),
            "lang" : tweet.lang,
            "tweet.username" : tweet.user.username,
            "tweet.content" : tweet.rawContent,
            "tweet.date" : tweet.date,
            "tweet.user.location" : tweet.user.location,
            "tweet.likeCount" : tweet.likeCount, 
            "tweet.replyCount" : tweet.replyCount,
            "tweet.retweetCount" : tweet.retweetCount,
            "tweet.url" : tweet.url
            }
    tweet_comments.append([tweet.user.id, tweet.date, tweet.place, tweet.conversationId, tweet.user.username, tweet.id, tweet.lang, tweet.likeCount, tweet.quoteCount, tweet.replyCount, tweet.retweetCount, tweet.rawContent])
```

### How to reproduce
```python3
tweet_comments = []
tweet = ['TWEET_ID']
for i, tweet in enumerate(sntwitter.TwitterTweetScraper(tweetId=tweet,mode=sntwitter.TwitterTweetScraperMode.RECURSE).get_items()):
    tweets = {
            "tweetid": str(tweet.id),
            "author_ID" : tweet.user.id,
            "inReplyToTweetId": str(tweet.inReplyToTweetId),
            "conversationId": str(tweet.conversationId),
            "lang" : tweet.lang,
            "tweet.username" : tweet.user.username,
            "tweet.content" : tweet.rawContent,
            "tweet.date" : tweet.date,
            "tweet.user.location" : tweet.user.location,
            "tweet.likeCount" : tweet.likeCount, 
            "tweet.replyCount" : tweet.replyCount,
            "tweet.retweetCount" : tweet.retweetCount,
            "tweet.url" : tweet.url
            }
    tweet_comments.append([tweet.user.id, tweet.date, tweet.place, tweet.conversationId, tweet.user.username, tweet.id, tweet.lang, tweet.likeCount, tweet.quoteCount, tweet.replyCount, tweet.retweetCount, tweet.rawContent])
```

### Expected behaviour

As far as I'm aware, Recurse should work much like scroll, but for getting each of the replies to the replies to the conversation_ID. 

### Screenshots and recordings

<img width="549" alt="image" src="https://user-images.githubusercontent.com/43789748/218311196-ec51dec8-01f3-44ef-b97e-ef4a35277c64.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/43789748/218311214-9d0c3d45-130e-483f-a268-c7cf8d134120.png">

### Operating system

Windows11

### Python version: output of `python3 --version`

3.10.8

### snscrape version: output of `snscrape --version`

0.5.0.20230113

### Scraper

TwitterTweetScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
This is the same as #684. It has been fixed in the development version and will be in the soon-to-come next release.
