### ISSUE TITLE
Getting users by hashtag

### ISSUE THREAD

**Issue by Akira-Kuru** [JustAnotherArchivist/snscrape#722]
Hello there,

I attempted to use the TwitterHashtagScraper() option to get users and this did work.
However, it returned many users that were duplicate or mentioned many times in the entries.

I am looking for an approach to get Users by Hashtags but by using this approach.
https://mobile.twitter.com/search?q=sports&f=user

I was thinking of using the TwitterSearchScraper() approach but I am not sure where to apply the f=user parameter.

Would be glad for any help.

Kind Regards

**Comment by JustAnotherArchivist** [comment]
User searches are not currently supported: #263

**Comment by Akira-Kuru** [comment]
Is there possible any alternative I could use? 
Like any search option, I could get the users without needing to get them duplicated.

**Comment by JustAnotherArchivist** [comment]
As I said, not currently with snscrape. I don't know whether there are other tools that support it.
