### ISSUE TITLE
Timezones - Twitter Data

### ISSUE THREAD

**Issue by LT41** [JustAnotherArchivist/snscrape#723]
Hi, quick question. I've seen a similar question to this in resolved issues but I just wanted 100% clarification before I continue working with my project. 

Are the tweets that snscrape collects standardized to UTC time, or is there some magic happening to center them on my own location's timestamp? 

Thanks for making this by the way, it's fantastic. Cheers!

**Comment by JustAnotherArchivist** [comment]
snscrape produces [aware](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects) datetime objects. When serialising to JSON, they get translated into an ISO 8601/RFC 3339 string, still with time zone data. What the time zone is depends both on the scraper and on what the server returns, i.e. there are no guarantees about what you might get. Twitter in particular currently returns RFC 2822 strings in some places, which may in principle have any time zone. You should write your code around the aware objects and perform the conversions as necessary, using `datetime.datetime.astimezone` if you want human-readable strings in a specific TZ or `datetime.datetime.timestamp` to get a POSIX timestamp.

**Comment by LT41** [comment]
Thank you for the fast reply.

**Comment by LT41** [comment]
I know you closed this, but I wanted to leave a post from stackoverflow here in case anyone else needs to solve this problem too. It turns out that UTC time can be extracted from the tweet id:

https://stackoverflow.com/questions/31539243/are-twitters-id-time-ordered
