### ISSUE TITLE
I can't start WARNING  snscrape.modules.telegram  No public post list for this user

### ISSUE THREAD

**Issue by researcher591** [JustAnotherArchivist/snscrape#727]
Hello world! Sorry for the stupid question, but what could be the point? It also fails to make the command import.
import snscrape.modules.telegram
It's all in Linux Debian 11

**Comment by JustAnotherArchivist** [comment]
Please file a complete bug report: https://github.com/JustAnotherArchivist/snscrape/issues/new?assignees=&labels=bug&template=bug_report.yml

**Comment by JustAnotherArchivist** [comment]
Actually, the bug report would be needed for the importing issue only.

The cause for that warning is obviously that the user's posts are not publicly viewable. If there is no 'Preview channel' link on the `https://t.me/NAME` page, seeing the posts requires an account. https://t.me/telegram is an example of a public channel.

**Comment by JustAnotherArchivist** [comment]
I'm sorry, I don't understand your question. Which user are you trying to scrape?
