### ISSUE TITLE
Determine a user's timezone when they sent a tweet

### ISSUE THREAD

**Issue by SyrupTheSrc** [JustAnotherArchivist/snscrape#729]
Is there a way to use the datetime lib to deduce what timezone a user was in when they sent out a tweet?

**Comment by JustAnotherArchivist** [comment]
Twitter doesn't return this information. I would be a bit surprised if they even had it. There is no easy way to reliably collect it in the general case.

What they do have is the user's time zone setting on Twitter (which affects rendering of timestamps throughout the site for that user, I imagine). Or at least [they did in 2020](https://stackoverflow.com/questions/19013206/how-to-reliably-determine-time-zone-for-a-user-from-the-twitter-api). But that appears to be API-exclusive.

So no, not possible with snscrape.
