### ISSUE TITLE
snscrape from with script 

### ISSUE THREAD

**Issue by p-dre** [JustAnotherArchivist/snscrape#73]
Is there a way to use snscrape inside a script and not over the terminal?

If I try I get only the object. Or if that not possible how I could impliment a rotating proxy such that I can run the scraper over the cmd.

`import snscrape as sn    
sn.modules.twitter.TwitterSearchScraper("corona lang=en")

<snscrape.modules.twitter.TwitterSearchScraper at 0x16f14ff45c8>
`

**Comment by JustAnotherArchivist** [comment]
```python
import snscrape.modules.twitter
for tweet in snscrape.modules.twitter.TwitterSearchScraper('corona lang:en').get_items():
    # do something
```

However, as this internal structure is currently undocumented, it may change at any time.

**Comment by arpitshah99-cpu** [comment]
for using TwitterSearchScraper, do we need Twitter Premium Api Access? Does it search historical tweets? old than 30 days?
