### ISSUE TITLE
How to scrape tweets from a specific user through his username

### ISSUE THREAD

**Issue by liyuduan817** [JustAnotherArchivist/snscrape#730]
Hey Bro:
I am a college student and doing some research on tweets, I have some usernames and I want to scrape their tweets between a specific timewindow. should i use TwitterSearchScraper or TwitterUserScraper, I am confused after reading issues,could you please give me some advice,huge thanks!
<img width="600" alt="image" src="https://user-images.githubusercontent.com/65487612/219402747-e0100438-22fa-4db4-aa80-3e2c967d55df.png">

**Comment by JustAnotherArchivist** [comment]
`TwitterUserScraper` (aka `twitter-user` on the CLI) uses the search `from:username`, `TwitterProfileScraper` (aka `twitter-profile`) scrapes the 'Tweets & replies' tab on the profile page. The difference is explained here: https://github.com/JustAnotherArchivist/snscrape/issues/85#issuecomment-698998263

**Comment by liyuduan817** [comment]
Bro! I tried TwitterUserScraper on jupyter notebook, but i met a question.when i scrape username:youtube, it has 51.1k tweets,after i run TwitterUserScraper, the script run a long time and it will met bug such as 'Error:non-200 response(429)'. I think maybe i request too often and refused, or my vpn is not stable. 
I need not all 51.1k tweets of youtube, I only need tweets contain specific keyword and specific time limit, is there any methods to solve my problem?
Looking forward to your reply, huge thanks! @JustAnotherArchivist
