### ISSUE TITLE
Some fields in the tweets crawled with snscrape that I'm not sure what they mean

### ISSUE THREAD

**Issue by scn0901** [JustAnotherArchivist/snscrape#731]
I want to know the meaning and difference of some fields in tweets crawled by snscrape:

(1) The difference between the 'renderedContent' field and the 'content' field
(2) Meaning of the 'conversationId' field
(3) Meaning of the 'tcooutlinks' field
(4) Meaning of the 'retweetedTweet' field
(5) Meaning of the 'quotedTweet' field

Also, in the 'user' field of a tweet:

(1) The difference between the 'rawDescription' field and the 'description' field
(2) Meaning of the 'descriptionUrls' field
(3) Meaning of the 'listedCount' field
(4) The difference between the 'linkTcourl' field and the 'linkUrl' field

**Comment by JustAnotherArchivist** [comment]
Tweet:

* `content` and `tcooutlinks` are deprecated and only exist for backward compatibility; ignore them.
* `conversationId` identifies the thread containing the tweet; it is equal to the tweet ID of the first tweet in the thread in my experience, though that might not be guaranteed.
* `retweetedTweet` and `quotedTweet` are relevant when a tweet is a retweet or a quote tweet. They then contain the other tweet object.

User:

* `description`, `descriptionUrls`, `linkUrl`, and `linkTcourl` are deprecated; ignore them.
* `listedCount` is the number of public lists that contain the user.

**Comment by scn0901** [comment]
Thank you for your answer, it turns out that some fields have been deprecated.

So I would like to ask about the fields in Tweet and User:

1. Which ones are deprecated and which ones are being used?
2. What are the meanings of the fields being used?

**Comment by JustAnotherArchivist** [comment]
You can see the deprecated fields (and what they correspond to) in the code, e.g. [here](https://github.com/JustAnotherArchivist/snscrape/blob/d60ce38b6a2d8aa55f29502f5517d47c1d9e4a5c/snscrape/modules/twitter.py#L90-L95) for `Tweet`s. You will get a `FutureWarning` when trying to access them, so unless you disabled warnings, you will know when you access a deprecated field.

I still think most (non-deprecated) fields have obvious self-describing names. There are lots of them, and I don't have time right now to describe them all for you. Quite a few are named very similarly to what the Twitter API returns, so their docs on [tweet](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet) and [user](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/user) objects may be of use. If you have questions about any particular field, let me know.

**Comment by scn0901** [comment]
Thank you for your patience in answering, I will check the code and Twitter API docs according to your suggestion, and contact you if I encounter problems that I cannot understand.
