### ISSUE TITLE
How to dump Tweet() to json

### ISSUE THREAD

**Issue by davira** [JustAnotherArchivist/snscrape#735]
Hi community,

I came up with a need to dump the Tweet (and all the contents) to the JSON format. I am deserializing myself, and I doubt is the correct way. 

Thanks a lot!

**Comment by TheTechRobo** [comment]
Have you tried the `.json()` method? All items are `_JsonDataclass`es, so it _should_ work: https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/base.py#L84

**Comment by davira** [comment]
Okay, I just realized I lost 2 days of my life. 

Thanks a lot @TheTechRobo .
