### ISSUE TITLE
Instagram User

### ISSUE THREAD

**Issue by xya137** [JustAnotherArchivist/snscrape#736]
### Describe the bug

Hey, as you thought, instagram changed things again and the index out of bound is thrown for line 88 when trying to get instagram user data.

### How to reproduce

snscrape instagram-user elonmusk_____official for exemple

### Expected behaviour

Not an index out of bound

### Operating system

Windows 10

### Python version: output of `python3 --version`

3.9.10

### snscrape version: output of `snscrape --version`

0.5.0.20230113

### Scraper

instagram-user

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by JustAnotherArchivist** [comment]
#520
