### ISSUE TITLE
Limited number of tweets

### ISSUE THREAD

**Issue by nv78** [JustAnotherArchivist/snscrape#738]
### Describe the bug

When running code, I can only get 1000 tweets. When I try to obtain more tweets, say 3,000 or 25,000, the program either does not work or takes very slow to run. How can I get more tweets?

### How to reproduce
```python3
def search_tweets(
    search_query: str,
    n_tweets: int = 150,
    start_date: str = "2022-06-06",
    end_date: str = str(date.today()),
) -> pd.DataFrame:
    # To Run: search_tweets('arsenal soccer', '2022-06-06' ,'2022-07-06', n_tweets=15)

    query = str(search_query) + " since:" + str(start_date) + " until:" + str(end_date)
    # Creating list to append tweet data to
    attributes_container = []

    # Using TwitterSearchScraper to scrape data and append tweets to list
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
        if i>n_tweets:
            break
        attributes_container.append([tweet.user.username, tweet.date, tweet.likeCount, tweet.sourceLabel, tweet.content])

    # Creating a dataframe to load the list
    tweets_df = pd.DataFrame(attributes_container, columns=["User", "Date Created", "Number of Likes", "Source of Tweet", "Text"])

    return tweets_df

df = search_tweets(search_query="deprem", n_tweets=150, start_date="2023-02-06")
print(df.head())

df = search_tweets(search_query="deprem", n_tweets=25000, start_date="2023-02-06")
print(df.head())
```
### Expected behaviour

Should get 25,000 tweets

### Operating system

Mac OS

### Python version: output of `python3 --version`

3.9

### snscrape version: output of `snscrape --version`

snscrape==0.5.0.20230113

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
It can take a long time to go through all search results. That is normal.
The only potential bug here is 'does not work', but you need to be more specific about *what* doesn't work and how it breaks.

**Comment by nv78** [comment]
Thanks, it would be great if at least there was a checkpoint so you could see how many tweets have been scraped (at a given time) if n is larger than say 3000 tweets.

**Comment by JustAnotherArchivist** [comment]
That's something you need to do yourself when you use the Python modules, e.g. with a `print(...)` in the loop. The CLI has a `--progress` option.
