### ISSUE TITLE
twitter scrapper error

### ISSUE THREAD

**Issue by jeanrebeka** [JustAnotherArchivist/snscrape#739]
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=BSD+banjir+-tol+-toll+-anies+until%3A2022-12-12+since%3A2022-01-01&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=BSD+banjir+-tol+-toll+-anies+until%3A2022-12-12+since%3A2022-01-01&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
---------------------------------------------------------------------------
ScraperException                          Traceback (most recent call last)
Input In [14], in <cell line: 1>()
----> 1 for tweet in sntwitter.TwitterSearchScraper(query).get_items():
      2     print(vars(tweet)) #vars = semua variabel yg ada di query mau kita ambil
      3     break

File ~\anaconda3\lib\site-packages\snscrape\modules\twitter.py:680, in TwitterSearchScraper.get_items(self)
    677 	del params['tweet_search_mode']
    678 	del paginationParams['tweet_search_mode']
--> 680 for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
    681 	yield from self._instructions_to_tweets(obj)

File ~\anaconda3\lib\site-packages\snscrape\modules\twitter.py:369, in _TwitterAPIScraper._iter_api_data(self, endpoint, params, paginationParams, cursor, direction)
    367 while True:
    368 	_logger.info(f'Retrieving scroll page {cursor}')
--> 369 	obj = self._get_api_data(endpoint, reqParams)
    370 	yield obj
    372 	# No data format test, just a hard and loud crash if anything's wrong :-)

File ~\anaconda3\lib\site-packages\snscrape\modules\twitter.py:339, in _TwitterAPIScraper._get_api_data(self, endpoint, params)
    337 def _get_api_data(self, endpoint, params):
    338 	self._ensure_guest_token()
--> 339 	r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
    340 	try:
    341 		obj = r.json()

File ~\anaconda3\lib\site-packages\snscrape\base.py:216, in Scraper._get(self, *args, **kwargs)
    215 def _get(self, *args, **kwargs):
--> 216 	return self._request('GET', *args, **kwargs)

File ~\anaconda3\lib\site-packages\snscrape\base.py:212, in Scraper._request(self, method, url, params, data, headers, timeout, responseOkCallback, allowRedirects)
    210 	msg = f'{self._retries + 1} requests to {req.url} failed, giving up.'
    211 	logger.fatal(msg)
--> 212 	raise ScraperException(msg)
    213 raise RuntimeError('Reached unreachable code')

ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=BSD+banjir+-tol+-toll+-anies+until%3A2022-12-12+since%3A2022-01-01&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

**Comment by jeanrebeka** [comment]
query="BSD banjir -tol -toll -anies until:2022-12-12 since:2022-01-01"
for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    print(vars(tweet)) #vars = semua variabel yg ada di query mau kita ambil
    break

**Comment by JustAnotherArchivist** [comment]
You're using an outdated version of snscrape. Also, the issue templates exist for a reason.

**Comment by jeanrebeka** [comment]
> You're using an outdated version of snscrape. Also, the issue templates exist for a reason.

how can I install the new one?
