### ISSUE TITLE
How to add a proxy to this project?

### ISSUE THREAD

**Issue by helloqwerasdf** [JustAnotherArchivist/snscrape#74]
hello,everyone! I am a newer and I have a question about how to add a proxy in this code to solve connection time out problem.Please help me,thanks!

**Comment by JustAnotherArchivist** [comment]
At the core, snscrape just uses the requests package, which has [documentation on using proxies](https://2.python-requests.org/en/master/user/advanced/#proxies) (SOCKS proxies are also supported, #28). Setting the `HTTP_PROXY` environment variable appropriately works on Linux and probably other Unix-like systems. I will not add Windows-specific code, but you can probably make it work based on the requests documentation linked above.

**Comment by helloqwerasdf** [comment]
> At the core, snscrape just uses the requests package, which has [documentation on using proxies](https://2.python-requests.org/en/master/user/advanced/#proxies) (SOCKS proxies are also supported, #28). Setting the `HTTP_PROXY` environment variable appropriately works on Linux and probably other Unix-like systems. I will not add Windows-specific code, but you can probably make it work based on the requests documentation linked above.

Thanks，I will try~

**Comment by helloqwerasdf** [comment]
@JustAnotherArchivist hi，I tried but failed,please help me! 
I just change base.py like this 
"""
import socks
import socket
socks.set_default_proxy(socks.SOCKS5,"127.0.0.1",1080)
socket.socket = socks.socksocket
"""
but got an error below
"""
2020-09-24 17:26:27.375  WARNING  snscrape.base  Error retrieving https://twitter.com/search?f=live&lang=en&q=from%3Atextfiles&src=spelling_expansion_revert_click: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='twitter.com', port=443): Read timed out. (read timeout=10)")), retrying
2020-09-24 17:26:41.414  ERROR  snscrape.base  Error retrieving https://twitter.com/search?f=live&lang=en&q=from%3Atextfiles&src=spelling_expansion_revert_click: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='twitter.com', port=443): Read timed out. (read timeout=10)"))
2020-09-24 17:26:41.414  CRITICAL  snscrape.base  4 requests to https://twitter.com/search?f=live&lang=en&q=from%3Atextfiles&src=spelling_expansion_revert_click failed, giving up.
"""

**Comment by JustAnotherArchivist** [comment]
Please read the requests documentation I linked. You need to add a `proxies` keyword argument somewhere in the `Scraper._request` method (probably on the `self._session.send` but I didn't check).

**Comment by helloqwerasdf** [comment]
@JustAnotherArchivist thanks！the problem is solved!

**Comment by lukaspistelak** [comment]
@helloqwerasdf 

```
self.proxies = {'socks5': 'http://127.0.0.1:9050'}	

r = self._session.send(req, allow_redirects = allowRedirects, timeout = timeout,proxies=self.proxies)
```

dont work for me

**Comment by essentialols** [comment]
> @JustAnotherArchivist thanks！the problem is solved!

Could you please post your solution? Thank you!

**Comment by ytaijp** [comment]
hello,

I use snscrape on AWS and gcloud

If I set a proxy correctly, can I use snscrape on aws and gcp? I set http_proxy with tor proxy and ran snscrape on aws/gcp, but no scrape..

**Comment by carnak** [comment]
I wasted more time than I should have sorting this out, so wanted to share exactly what I changed in order to get this app to be proxy-aware.  Note, I also turn off ssl verification, which is only necessary if you have an intercepting outbound proxy doing ssl decryption:

      $ diff base.py base_orig.py
      134,141d133
      <               proxies = {
      <                       'http': 'http://your_proxy-host:your_proxy_port',
      <                       'https': 'http://your_proxy-host:your_proxy_port',
      <               }
      <               self._session.proxies = proxies
      <               self._session.verify = False
      <
      <
      160d151
      <
      162d152
      <
      219c209
      <               pass
      ---
      >               pass
      \ No newline at end of file

**Comment by ytaijp** [comment]
@carnak 

thank you for sharing 

I tried like below ,but it doesn't work... 


        def __init__(self, retries = 3):
                proxies={'http': 'http://127.0.0.1:5566'}
                self._retries = retries
                self._session = requests.Session()
                self._session.proxies = proxies
                self._session.verify = False

**Comment by ramandada** [comment]
@carnak the given solution is not working

@JustAnotherArchivist i want to use proxy but it's not working

**Comment by TheTechRobo** [comment]
@ramandada https://github.com/JustAnotherArchivist/snscrape/issues/548#issuecomment-1242373966

**Comment by JustAnotherArchivist** [comment]
@ramandada I have no idea what 'the issue' even is. snscrape supports proxies as explained in the linked comment. If your proxies aren't playing nice with Twitter, that's an issue with your proxy selection, not snscrape (cf. #783). If you have an actual technical issue with getting snscrape to respect your proxy settings, please file a complete bug report.

**Comment by ramandada** [comment]
@JustAnotherArchivist @TheTechRobo 

Error retrieving https://twitter.com/search?f=live&lang=en&q=%28from%3Aelonmusk%29+until%3A2023-03-29+since%3A2023-03-28&src=spelling_expansion_revert_click: ProxyError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=%28from%3Aelonmusk%29+until%3A2023-03-29+since%3A2023-03-28&src=spelling_expansion_revert_click (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))"))

Facing this issue, while using 
sntwitter.TwitterSearchScraper("(from:elonmusk) until:2023-03-29 since:2023-03-28",proxies = {'https': 'https://proxy_ip:port'}).get_items()

but the proxy is working on browser

not in code

**Comment by DrSocket** [comment]
@helloqwerasdf hi, could you let us know how you solved the issue?

**Comment by JustAnotherArchivist** [comment]
@DrSocket

> [#548 (comment)](https://github.com/JustAnotherArchivist/snscrape/issues/548#issuecomment-1242373966)
