### ISSUE TITLE
TwitterProfileScraper - 'result' key not in result['quotedRefResult']['result']['__typename']

### ISSUE THREAD

**Issue by davira** [JustAnotherArchivist/snscrape#740]
### Describe the bug

When scrapping TwitterProfileScraper, line 1375, in _graphql_timeline_tweet_item_result_to_tweet fails beacause result does not have key result:

error:
```
  File "/blablablablablalbala/venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1375, in _graphql_timeline_tweet_item_result_to_tweet
    if result['quotedRefResult']['result']['__typename'] == 'TweetTombstone':
KeyError: 'result'
```

### How to reproduce
```python3
username = "Santi_ABASCAL"

    scraper = twitterScrapper.TwitterProfileScraper(username)
    all_user_tweets = []


    for i, tweet in enumerate(scraper.get_items()):
        all_user_tweets.append(tweet)
```

### Expected behaviour

Scrap the tweets without problems

### Operating system

Ubuntu 18.04

### Python version: output of `python3 --version`

Python 3.10.10

### snscrape version: output of `snscrape --version`

snscrape 0.5.0.20230113

### Scraper

TwitterProfileScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
Twitter is so broken... Thanks, confirmed, will fix soon!

**Comment by JustAnotherArchivist** [comment]
1475208266372292612 is the problematic tweet. It's a retweet of 1475207842454028304, which quotes 1475172288802791430, which is shown as 'unavailable' even though it exists. The profile endpoint returns it differently than the search or individual tweet endpoints, which work fine.

**Comment by davira** [comment]
Hi guys, 

In fact, there is another SIMILAR problem. Please, check this user: 
@IdiazAyuso / Twitter](https://twitter.com/IdiazAyuso)

**Comment by JustAnotherArchivist** [comment]
That's probably #604.
