### ISSUE TITLE
Twitter Module | tweet.mentionedUsers to provide only the username

### ISSUE THREAD

**Issue by jalescaur** [JustAnotherArchivist/snscrape#742]
### Describe the feature

Currently, the assignment 'tweet.mentionedUsers' returns all users involved in the extracted post. However, at the time of the request, it ends up pulling all the information from these users and gets quite complicated when it comes to cleaning up the data by hand.

Below is an example of the return:

`[User(username='infomoney', id=59773459, displayname='InfoMoney', rawDescription=None, renderedDescription=None, descriptionLinks=None, verified=None, created=None, followersCount=None, friendsCount=None, statusesCount=None, favouritesCount=None, listedCount=None, mediaCount=None, location=None, protected=None, link=None, profileImageUrl=None, profileBannerUrl=None, label=None)]`

Would there be a possibility to return only the username, this way?

`infomoney`

If there is already such a way, I am more than happy to hear about! Thank you very much in advance for your hard work!

**Comment by JustAnotherArchivist** [comment]
There isn't, but this is very simple to do in user code as needed:

```python3
mentionedUsernames = [u.username for u in tweet.mentionedUsers]
```

I'm sure you can do the same thing on JSONL data easily with tools like `jq` but don't know the syntax right now.

**Comment by profmanuel** [comment]
Hi @jalescaur I hope this can help you 

# Extract just the usernames from the MentionedUsers column
tweets_df1['MentionedUsers'] = [[user.username for user in users] if type(users) == list else [] for users in tweets_df1['MentionedUsers']]

**Comment by profmanuel** [comment]
Hi @jalescaur I hope this helps

`# Extract just the usernames from the MentionedUsers column
tweets_df1['MentionedUsers'] = [[user.username for user in users] if type(users) == list else [] for users in tweets_df1['MentionedUsers']]`

**Comment by profmanuel** [comment]
Hi @jalescaur I hope this helps 

```
# Extract just the usernames from the MentionedUsers column

tweets_df1['MentionedUsers'] = [[user.username for user in users] if type(users) == list else [] for users in tweets_df1['MentionedUsers']]
```
