### ISSUE TITLE
Twitter Ads seem to break tweetId logic

### ISSUE THREAD

**Issue by SuspiciousBytes** [JustAnotherArchivist/snscrape#751]
### Describe the bug

I'm running into an issue with what appears to be twitter ads when using twitter-tweet --scroll. Occasionally snscrape can raise a ValueError when extracting the tweetId on some tweets where a hex suffix is present, which is throwing off the int() conversion. A few of the failing IDs I manually tested were ad-related, and adding a try except to work around the mismatch has worked so far to allow scraping to continue.

### How to reproduce

On CLI, I can pass snscrape a single tweet (scroll enabled) and raise the error, though the ad may or may not appear on your end when testing.
One example tweet + thread:

```
# snscrape twitter-tweet --scroll 1631767456342745089
```

To which a few urls will appear, then the crash.
(locals and backtrace included below)

### Expected behaviour

Snscrape should extract the tweetId and continue executing.

### Operating system

Alpine Linux 3.17.1 -- Docker Container

### Python version: output of `python3 --version`

Python 3.10.10

### snscrape version: output of `snscrape --version`

snscrape 0.6.0.20230303

### Scraper

twitter-tweet

### Backtrace
```pytb
Traceback (most recent call last):
  File "/usr/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/snscrape/_cli.py", line 320, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/usr/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1951, in get_items
    yield from self._graphql_timeline_instructions_to_tweets(obj['data']['threaded_conversation_with_injections_v2']['instructions'], includeConversationThreads = True)
  File "/usr/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1470, in _graphql_timeline_instructions_to_tweets
    tweetId = int(item['entryId'][len(entry['entryId']) + 7:])
ValueError: invalid literal for int() with base 10: '1629804636143079425-1812ac542207c416'
```

### Dump of locals

[snscrape_locals_tremlmnd.txt](https://github.com/JustAnotherArchivist/snscrape/files/10890834/snscrape_locals_tremlmnd.txt)

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by JustAnotherArchivist** [comment]
Interesting, thanks! I haven't seen this one before, and I can't reproduce it either (which isn't surprising since that heavily depends on IP geolocation and probably various other things).
I have been wondering about what should happen with ads, i.e. whether to extract or ignore them. I'm still not sure.

**Comment by lun-4** [comment]
I can reproduce the issue, I ran an older version of snscrape ( as `snscrape -vv --progress --jsonl twitter-tweet --recurse root_status_id...` and it was adding completely unrelated tweet chains than the main thread, which made me confused, so I updated snscrape and now I hit the ValueError described above.

I'd argue for ignoring, as they're not part of what you expect, if that doesn't work, maybe an opt-in `--allow-ads` or `--exclude-ads` option, so the user gets to choose?

**Comment by JustAnotherArchivist** [comment]
With the current dev version of snscrape, ads show up in searches as warnings with a message like

     Skipping unrecognised entry ID: 'promoted-tweet-1655860425999761411-43736743222b639'

I still haven't been able to reproduce the crash though.

And yeah, there would certainly be an option for it, but they'd probably be ignored by default.

**Comment by SuspiciousBytes** [comment]
I'm unfortunately still seeing a crash in a similar area.

Snscrape --version:
```
snscrape 0.6.2.20230321.dev13+g786815d
```
Reproduction command on my end:
```
snscrape twitter-tweet --scroll 1656103380253814786
```

And the resulting crash:

```
https://twitter.com/tsunomakiwatame/status/1656103380253814786
https://twitter.com/Silence_WDMavis/status/1656103486357139456
https://twitter.com/dochanjin/status/1656104023240617986
2023-05-11 04:05:40.663  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_mjlmrwuh
Traceback (most recent call last):
  File "/usr/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/snscrape/_cli.py", line 320, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/usr/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 2006, in get_items
    yield from self._graphql_timeline_instructions_to_tweets(obj['data']['threaded_conversation_with_injections_v2']['instructions'], includeConversationThreads = True)
  File "/usr/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1528, in _graphql_timeline_instructions_to_tweets
    tweetId = int(item['entryId'][len(entry['entryId']) + 7:])
ValueError: invalid literal for int() with base 10: '1631321262256521216-47ea127541b29f2'
```
where 1631321262256521216 is an astrology daily ad that pops up.

Should I go ahead and add the dump of locals again?

I can also look into dumping the web traffic if you believe it'd help. If this is indeed a regional ad issue it might be good to have an offline reproduction case.

**Comment by JustAnotherArchivist** [comment]
I'm sure there is a geo-IP aspect to it, yeah. I tried again on a number of different machines and found one that reproduces it. :-)

**Comment by Loai-Hassan** [comment]
for the current version is it supported

**Comment by JustAnotherArchivist** [comment]
The crash has been fixed, yes, that's why the issue is closed.
