### ISSUE TITLE
non-200 Response TwitterProfile. 403 error

### ISSUE THREAD

**Issue by Mr-Freewan** [JustAnotherArchivist/snscrape#752]
### Describe the bug

CRITICAL:snscrape.base:Errors: non-200 response (403), non-200 response (403), non-200 response (403), non-200 response (403)

4 requests to https://twitter.com/mclachbot failed, giving up. (or other profile)

### How to reproduce

`for i, tweet in enumerate(sntwitter.TwitterUserScraper('mclachbot').get_items()):
        if i == 10:
            break`

### Expected behaviour

Must return twitter profile tweets

### Operating system

Windows 10, Ubuntu 20.04 etc

### Python version: output of `python3 --version`

3.8-3.9

### snscrape version: output of `snscrape --version`

snscrape 0.6.0.20230303

### Scraper

sntwitter.TwitterUserScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Additional context

It stopped working. Gives out this error. Different computers, different locations, different operating systems, and different versions of python

**Comment by backschool99** [comment]
Yeah is happening again, probably like 2 months ago. Elon screw up the party, this error happening on me too like 25 minutes ago.

**Comment by backschool99** [comment]
It work again on me, wierd.

**Comment by Mr-Freewan** [comment]
Elon is going to kill Twitter((

**Comment by JustAnotherArchivist** [comment]
Twitter had technical issues earlier, around the time when you filed this issue. Cf. https://twitter.com/TwitterSupport/status/1632792942262747136
It seems to be resolved now.

**Comment by Mr-Freewan** [comment]
Yes. It resolved.

I don't know what to expect from the Mask team. Sorry)
