### ISSUE TITLE
 Error retrieving https://api.twitter.com/1.1/guest/activate.json: non-200 response (429)

### ISSUE THREAD

**Issue by aalpv** [JustAnotherArchivist/snscrape#754]
Hi, I'm having this error everytime I execute my code. 
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/1.1/guest/activate.json failed, giving up.
Error retrieving https://api.twitter.com/1.1/guest/activate.json: non-200 response (429)
4 requests to https://api.twitter.com/1.1/guest/activate.json failed, giving up.
Errors: non-200 response (429), non-200 response (429), non-200 response (429), non-200 response (429)

Anyone knows why is it happening and how to fix it?

**Comment by JustAnotherArchivist** [comment]
Twitter's guest token activation is strongly rate-limited. Either you're requesting too many tokens (which would be due to what you're doing or how you're doing it; use the CLI for best results) or your IP is on a stricter limit.

**Comment by akshannaldas** [comment]
tweet_count = 120
username = "@virendersehwag"

# Using OS library to call CLI commands in Python
os.system("snscrape --jsonl --max-results {} twitter-search 'from:{}'> user-tweets.json".format(tweet_count, username))

@JustAnotherArchivist i have written my code above bt im not able to extract tweets it was working it yesterdat bt today it is not

**Comment by JustAnotherArchivist** [comment]
snscrape's working fine here. Twitter probably banned your IP. Nothing snscrape can do about that.

**Comment by akshannaldas** [comment]
how to reslove this issue?

**Comment by JustAnotherArchivist** [comment]
Use a different IP, either with a proxy (if you can find one that isn't broken) or by running snscrape on another machine.

**Comment by LLSean** [comment]
> Use a different IP, either with a proxy (if you can find one that isn't broken) or by running snscrape on another machine.

I meet the same problem. Do you know the rate-limited detail information? What frequency is more appropriate?

**Comment by LLSean** [comment]
> I do not. Keep the frequency as low as possible and hope for the best.

I can use TwitterUserScraper _get_entity to get user profile, but get_items will return Errors: non-200 response (429), non-200 response (429), non-200 response (429), non-200 response (429).

**Comment by JustAnotherArchivist** [comment]
(Don't use `_get_entity`; as the underscore indicates, this is private API. Just use the `entity` property instead.)

The entity and the search scraping use the same token. Unless it expired between the two, the token activation URL isn't even accessed. If you see the 429s on the search endpoint instead, that's not the same thing (but also caused by IP/rate limiting).

**Comment by LLSean** [comment]
> (Don't use `_get_entity`; as the underscore indicates, this is private API. Just use the `entity` property instead.)
> 
> The entity and the search scraping use the same token. Unless it expired between the two, the token activation URL isn't even accessed. If you see the 429s on the search endpoint instead, that's not the same thing (but also caused by IP/rate limiting).

Thanks for replying. I tried again. The return status change to 404, before is 429.

**Comment by JustAnotherArchivist** [comment]
I'm almost certain you're seeing that on the `adaptive.json` URL, *not* `activate.json`, which this issue's about.
