### ISSUE TITLE
Parallel TwitterSearchScraper use

### ISSUE THREAD

**Issue by yemregundogmus** [JustAnotherArchivist/snscrape#755]
Hello there,

At the same time, I search Twitter for keywords with TwitterSearchScraper with 8-9 python scripts. However, at certain points

```
  4 requests to https://api.twitter.com/1.1/guest/activate.json failed, giving up.
```

I am encountering the error. Is there a way I can have them use shared guest tokens when throwing these requests?

**Comment by JustAnotherArchivist** [comment]
The CLI shares tokens between processes, so I would recommend using that if you can. There is currently no official way of sharing tokens between processes using snscrape from Python; you'd have to implement your own `GuestTokenManager` for that.

**Comment by yemregundogmus** [comment]
i use snscrape for tracking latest tweets. Do you have any implementation for that?

**Comment by JustAnotherArchivist** [comment]
Not something directly reusable, but that should just be a matter of a small (e.g. Bash) script calling snscrape in a loop and keeping track of the most recent known tweet ID, stopping snscrape as soon as it gets a lower ID than that.

**Comment by yemregundogmus** [comment]
I use tweet timestamps for scraping latest tweets. Maybe i can use cli with since_time parameter.

My active code is like; 

'''
df = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(f"dolar lang:tr since_time:{timestamp}").get_items(), 250))

timestamp = round(datetime.datetime.timestamp(df.date.max()))
'''

I do this in while loop.
PS: Sorry for no usable code im in mobile right now

What do you think about my proxy question? Do you have any proxy service suggestions for snscrape?

**Comment by JustAnotherArchivist** [comment]
Sure, timestamps work as well.
I have no comments on proxies.
Closing this as I consider the original question answered.

**Comment by yemregundogmus** [comment]
> Sure, timestamps work as well. I have no comments on proxies. Closing this as I consider the original question answered.

Do you have any example "get above or below tweet_id" for search in cli?

**Comment by JustAnotherArchivist** [comment]
You could use Twitter's `since_id` and `max_id` filters, respectively.

**Comment by yemregundogmus** [comment]
For example, when I scrape 250 tweets, should I give since_id = min(id) max_id = max(id) parameters?

**Comment by JustAnotherArchivist** [comment]
For your purposes, you'd run a search for `query` once (fetching however many results you want), remember the highest ID, then use `query since_id:1234` using that highest previously seen ID. Twitter's search is sometimes weird, so it's not guaranteed to yield all tweets, but it should usually work I think.
`max_id` is the same concept but for an upper bound of the tweet ID.
