### ISSUE TITLE
Parsing VK doesn't work

### ISSUE THREAD

**Issue by KariSause** [JustAnotherArchivist/snscrape#756]
### Describe the bug

I write command to parsing VK group but it isn't work and return an error. 
Command is correct "snscrape --max-results 10 vkontakte-user <here name of group>"
And errors are AttributeError and UnicodeEncodeError

### How to reproduce

When I run a command "snscrape --max-results 10 vkontakte-user <here name of group>" I can got that error

### Expected behaviour

I need got a posts of user in group or just user posts. But I said earlier what I got

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/92746525/224118265-7a36e5b0-92da-4361-a23c-1337e81806c3.png)

### Operating system

Windows 7

### Python version: output of `python3 --version`

python 3.8

### snscrape version: output of `snscrape --version`

0.6.0.20230303

### Scraper

vkontakte-user

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by JustAnotherArchivist** [comment]
#122

**Comment by KariSause** [comment]
> #122

What about AttributeError. and UnicodeEncodeError didn't fixed I tried it

**Comment by JustAnotherArchivist** [comment]
Oh, missed that, the AttributeError is #737.
