### ISSUE TITLE
Installing lxml on macOS

### ISSUE THREAD

**Issue by thierryfournier** [JustAnotherArchivist/snscrape#757]
Hi, 
Sorry if this is a newbie questions, but I installed Python (3.10.10) on Mac (Big Sur 11.6), everything was fine, then I installed Snscrape (with the installer provided on Github) with the command line "pip3 install snscrape" and at the end of the process I get the error below. What should I do please? 
Many thanks in advance, best
Thierry 

 xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      Perhaps try: xcode-select --install
      *********************************************************************************
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by JustAnotherArchivist** [comment]
This is an issue with installing a dependency, not snscrape itself. lxml depends on libxml2, and that's what you're lacking, as the error says. I don't know how to fix this as I don't use macOS, but a quick internet search suggests that libxml2 itself should be included with macOS. However, since it's trying to compile lxml, you also need the headers, and those apparently come with XCode (as the error also hints at).

**Comment by thierryfournier** [comment]
Hi,
Thank you very much for your quick and efficient answer. I didn't know that Xcode was a prerequisite for this on OSX. I did install it (xcode-select --install) and then everything was ok for the installation of snscrape, which is now working perfectly.
Thierry

**Comment by JustAnotherArchivist** [comment]
It's for lxml, not snscrape, and, as I understand it, only when lxml needs to be compiled from source. If pip could use one of the available precompiled wheels from PyPI, XCode would not be required. It looks like the existing wheels are only for x86_64, and there is an open issue on Launchpad about [a lack of wheels for M1](https://bugs.launchpad.net/lxml/+bug/1913032) in particular.

**Comment by thierryfournier** [comment]
Ok, thanks for this clarification, I'll go and see. But installing the whole Xcode was not complicated, and in any case now snscrape seems to work very well.
