### ISSUE TITLE
Syntax for Twitter query

### ISSUE THREAD

**Issue by thierryfournier** [JustAnotherArchivist/snscrape#758]
Hi again, 
I searched in the help file: how can you search for a twitter query, and with a phrase, like "I am waiting"? 
https://twitter.com/search?q=I%20am%20waiting&src=typed_query
Thank you in advance, best
Thierry

**Comment by JustAnotherArchivist** [comment]
Does #303 answer your question?

**Comment by thierryfournier** [comment]
Yes it’s perfect. Thank you very much for this tool, it’s really great!!
Best
Thierry

Thierry Fournier
06 63 66 08 53
www.thierryfournier.net <http://www.thierryfournier.net/>
