### ISSUE TITLE
`DeprecatedFeatureWarning` on scraping top tweets 

### ISSUE THREAD

**Issue by MykhailoYampolskyi** [JustAnotherArchivist/snscrape#766]
I want to extract top tweets and tried to use the code 
`(sntwitter.TwitterSearchScraper('keyword since:2022-05-24 until:2022-06-15 lang:en', top=True)`

However it gives an error: 
```
C:\Users\m\AppData\Local\Temp\ipykernel_21400\2575674760.py:5: DeprecatedFeatureWarning: `top` argument is deprecated, use `mode = snscrape.modules.twitter.TwitterSearchScraperMode.TOP` instead of `top = True`
  for i,tweet in enumerate(sntwitter.TwitterSearchScraper(' since:2022-02-24 until:2022-03-15 lang:en', top=True).get_items()):
```
I suspect the answer might be in the error code, but could someone help. Thanks.
The installed version of snscrape isnt developer.

**Comment by JustAnotherArchivist** [comment]
This is not an error. It's a warning that the `top` keyword argument is deprecated and will be removed in some future version of snscrape, and that you should replace it with `mode` as explained in the message.

**Comment by MykhailoYampolskyi** [comment]
I replaced it to mode=True and it works. Thank you!!

**Comment by JustAnotherArchivist** [comment]
Please reread the warning message. `mode = True` is not valid.

**Comment by MykhailoYampolskyi** [comment]
So, where do I put it?
I did the following:
`mode_param = snscrape.modules.twitter.TwitterSearchScraperMode.TOP
`
`(sntwitter.TwitterSearchScraper(search_query, mode = mode_param)`

but it says: 
module 'snscrape.base' has no attribute 'modules'
snscrape updated to latest ver

**Comment by MykhailoYampolskyi** [comment]
Oh wait, I did 
`import snscrape.modules.twitter as sntwitter`
and then
`mode_param = sntwitter.TwitterSearchScraperMode.TOP` instead. Is this correct? Seems to work
