### ISSUE TITLE
historic tweets not available when filtering by minimum number of retweets

### ISSUE THREAD

**Issue by Akhorramrouz** [JustAnotherArchivist/snscrape#767]
### Describe the bug

When I specify a minimum number of retweets in my query using sntwitter, the API only returns data from the last two weeks.

### How to reproduce

When I specify a minimum number of retweets in my query using sntwitter, the API only returns data from the last two weeks. Is there a workaround to bypass this limitation and retrieve older tweets that meet the specified criteria? Thank you in advance for your help.

### Expected behaviour

 Is there a workaround to bypass this limitation and retrieve older tweets that meet the specified criteria? 

Thank you in advance for your help.

### Operating system

Windows 11

### Python version: output of `python3 --version`

3.9

### snscrape version: output of `snscrape --version`

6.1

### Scraper

twitter

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
I can't reproduce this. E.g. `snscrape --format '{date}' twitter-search 'nasa min_retweets:10000'` returns tweets back to 2012. What's your exact query?

**Comment by Akhorramrouz** [comment]
> I can't reproduce this. E.g. `snscrape --format '{date}' twitter-search 'nasa min_retweets:10000'` returns tweets back to 2012. What's your exact query?

thanks for your fast response, this is my exact query: 
query = f'(که OR از OR به OR با OR در) lang:fa since:2022-01-01 until:2022-02-01 -filter:links min_retweets:23'

**Comment by JustAnotherArchivist** [comment]
Interesting. It seems to be quite unreliable. I'm getting no results with your query or `min_retweets:20`, but I'm getting plenty with `min_retweets:10`. Removing `lang:fa` also works. I suspect this just has to do with the complex query. Generally, the more search terms you have, the less reliable Twitter's search is. So this is likely the same underlying issue as #616, #162, and more. The only known workaround is to simplify the query. In particular, I would try to split those `OR` terms into five separate scrapes and then combine the results afterwards.

**Comment by Akhorramrouz** [comment]
I just made a double check even with only one condition it is not going any time earlier than 2 weeks ago.
Though I appreciate your help

**Comment by JustAnotherArchivist** [comment]
```
$ snscrape -n 10 twitter-search '(که OR از OR به OR با OR در) lang:fa since:2022-01-01 until:2022-02-01 -filter:links min_retweets:10'
https://twitter.com/mmhhkk2016/status/1488301047240142848
https://twitter.com/_zia___/status/1488300419059044353
https://twitter.com/REGIME_CHANGE03/status/1488299885220835329
https://twitter.com/esmaeilion/status/1488298397270523910
https://twitter.com/cutbabybear/status/1488296822980370438
https://twitter.com/ElaheBoghrat/status/1488296477365518344
https://twitter.com/ayyarom/status/1488294720686247942
https://twitter.com/ali_bitarafan5/status/1488292075871350788
https://twitter.com/1mobarez11/status/1488290914808307712
https://twitter.com/haj_komeil/status/1488290182126260229
```

These are tweets from over a year ago, of course, due to the `until` filter. But I only get results sometimes. As I said, it's unreliable. Use a simpler query. There's nothing that can be done about it I'm afraid.

**Comment by Akhorramrouz** [comment]
I see,

 thanks for the clarification
