### ISSUE TITLE
[Twitter] Question about maxEmptyPages and TwitterSearchScraperMode.LIVE, TwitterSearchScraperMode.TOP

### ISSUE THREAD

**Issue by TheGreatestNyanCat** [JustAnotherArchivist/snscrape#768]
Hello. I have a question.
Currently, 'snscrape-twitter' defaults 'maxEmptyPages' to '20'. (When using 'TwitterSearchScraperMode.TOP')
1) Is there any special meaning to this value?
2) Also, are there any tweets that are lost even if this number is set close to '1'?
3) Does 'TwitterSearchScraperMode.LIVE' **contain all the results** of 'TwitterSearchScraperMode.TOP'?
I think I saw that there are tweets that are not in 'TwitterSearchScraperMode.LIVE', but are in 'TwitterSearchScraperMode.TOP'.

Thank you.

**Comment by TheTechRobo** [comment]
As far as I'm aware (could be wrong), Twitter's search is very broken and sometimes has a ton of empty API responses, but still says there are more pages. Sometimes there ARE more pages, even after empty ones. However, with the Top search, a seemingly infinite amount of empty pages sometimes builds up (#636). As such, maxEmptyPages was added. 20 is usually a good number to prevent huge slowdowns or infinite loops, but for very rare edge cases, increasing the number may be necessary.

**Comment by TheGreatestNyanCat** [comment]
@TheTechRobo Thank you. Questions 1 and 2 have been answered.
