### ISSUE TITLE
snscrape: error: unrecognized arguments: --jsonl

### ISSUE THREAD

**Issue by rodolfopardo** [JustAnotherArchivist/snscrape#77]
This is my shell command? 
Can i help me? 

snscrape --jsonl twitter-user rodipardo_

Result: 

snscrape: error: unrecognized arguments: --jsonl

**Comment by WhiteLin3s** [comment]
Hey,

guess you installed it from repository using pip. The "--jsonl"" flag seems to be present only in the newer version that is available on github. So either run

`pip3 install --upgrade git+https://github.com/JustAnotherArchivist/snscrape@master`

or

`pip install --upgrade git+https://github.com/JustAnotherArchivist/snscrape@master`

to get the newest version. Then your command should work as desired.

**Comment by rodolfopardo** [comment]
Thanks so much! , but now i have other issue 

snscrape --jsonl twitter-user rodipardo_

Result: 

module 'functools' has no attribute 'cached_property'

**Comment by JustAnotherArchivist** [comment]
The newest version of snscrape requires Python 3.8, as listed in setup.py.
