### ISSUE TITLE
snscrape multiple iterative search not working

### ISSUE THREAD

**Issue by alice23DS** [JustAnotherArchivist/snscrape#770]
### Describe the bug

I am trying to fetch data from the config file and then trying to scrape data with the iterative search for those keywords.

The code has been into the processing for a while and doesn't show any error or result.

Initially I tried to search for a week data, now just to confirm i tried to scrape for a day, still the code is not retrieving anything. 

### How to reproduce
```python3
for n in (account_name):
    
    for i, tweet in enumerate(sntwitter.TwitterSearchScraper(f'{n} + near:"United States" + since:{datestamp_start} until:{datestamp_end}').get_items()):
```

### Expected behaviour

![image](https://user-images.githubusercontent.com/123429653/225372658-7fbaf404-5691-441c-bcfe-6c48790ac41f.png)

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/123429653/225358704-0957daa8-ee62-4afa-8517-98949d743583.png)

![image](https://user-images.githubusercontent.com/123429653/225361026-c1535ddf-3936-4be3-a359-011391831233.png)

### Operating system

Windows 10

### Python version: output of `python3 --version`

3.8.8

### snscrape version: output of `snscrape --version`

Version 0.6.1

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
What concrete query are you running, which doesn't return results? And does the same query give results on Twitter's web interface?

**Comment by alice23DS** [comment]
sntwitter.TwitterSearchScraper(f'{account_name[n]} + near:"United States" + since:{datestamp_start} until:{datestamp_end}').get_items()

It works when i am not using iterative search for account_name and give combination of keywords directly.

But when i put it under the loop for iterative search with -----for n, k in enumerate(account_name):

it is neither producing any result nor giving any error.

**Comment by alice23DS** [comment]
account_name is a variable which has keywords 

![image](https://user-images.githubusercontent.com/123429653/225409304-98b3ef63-38e2-417f-874a-3c4d64e18621.png)

**Comment by alice23DS** [comment]
Can I send you my code?

**Comment by JustAnotherArchivist** [comment]
I'm sorry, but I don't have time to debug your code.
I just noticed that you have some plus signs in your query, but that doesn't make a difference for me.
Add a `print(repr(...))` for your query string in the loop and make sure it matches what I used above.

**Comment by alice23DS** [comment]
sure. Thanks, Ill try that

**Comment by alice23DS** [comment]
![image](https://user-images.githubusercontent.com/123429653/225433257-bd916d76-c323-4aae-b2e8-f1db7269e08c.png)

can anyone tell what this means 'Unsupported unified_card type on tweet 1587186251718959107: 'commerce_drop' '

Getting this while running the query

**Comment by JustAnotherArchivist** [comment]
It's a warning that snscrape couldn't extract the card on that tweet. I have never seen `commerce_drop` before, thanks. Apparently Twitter's own web client also has no idea how to render it.

**Comment by JustAnotherArchivist** [comment]
I assume this means you got your code working?

**Comment by alice23DS** [comment]
Yes thank you, there was issue with my query as is it was not able to pass value of account_name[n]
