### ISSUE TITLE
Please help me resolve the 404 status code Errors

### ISSUE THREAD

**Issue by Nitigya-Handa** [JustAnotherArchivist/snscrape#771]
Hi there,

I was trying to run the simple code given below. It was working perfectly fine yesterday but for some reason I am getting errors numerous errors when I tried to run it today. I think these are related to the API being inaccessible all of a sudden but I am not sure. I'll greatly appreciate some help regarding this. 
  
**Code:**

import snscrape.modules.twitter as sntwitter
import pandas as pd

tweetsDf = pd.DataFrame()

maxTweets = 2
keyword='COVID'
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(keyword + ' since:2021-11-01 until:2023-01-01 lang:"en" -filter:retweets').get_items()):
    if i > maxTweets:
            break
    tweets = {
            "tweet/reply id": "a"+str(tweet.id),
            "inReplyToTweetId": "a"+str(tweet.inReplyToTweetId),
            "conversationId": "a"+str(tweet.conversationId),
            "tweet.username" : tweet.username,
            "tweet.content" : tweet.content,
            "tweet.date" : tweet.date,
            "tweet.user.location" : tweet.user.location,
            "tweet.likeCount" : tweet.likeCount, 
            "tweet.replyCount" : tweet.replyCount,
            "tweet.retweetCount" : tweet.retweetCount,
            "tweet.user.followersCount" : tweet.user.followersCount,
            "tweet.user.description": tweet.user.description,
            "tweet.user.friendsCount": tweet.user.friendsCount,
            "tweet.user.statusesCount": tweet.user.statusesCount,
            "tweet.user.favouritesCount": tweet.user.favouritesCount,
            "tweet.user.listedCount": tweet.user.listedCount,
            "tweet.user.mediaCount": tweet.user.mediaCount,
            "tweet.url" : tweet.url
            }
    tweetsDf = tweetsDf.append(pd.json_normalize(tweets))

**Getting the following error:**
**Error retrieving** https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=COVID+since%3A2021-11-01+until%3A2023-01-01+lang%3A%22en%22+-filter%3Aretweets&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: non-200 status code (404)
**4 requests** to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=COVID+since%3A2021-11-01+until%3A2023-01-01+lang%3A%22en%22+-filter%3Aretweets&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
**Errors: non-200 status code (404), non-200 status code (404), non-200 status code (404), non-200 status code (404)**
---------------------------------------------------------------------------
**ScraperException: 4** requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=COVID+since%3A2021-11-01+until%3A2023-01-01+lang%3A%22en%22+-filter%3Aretweets&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.

**Comment by JustAnotherArchivist** [comment]
Please file a complete bug report.
