### ISSUE TITLE
Base examples not working anymore

### ISSUE THREAD

**Issue by maciejskorski** [JustAnotherArchivist/snscrape#773]
### Describe the bug

I am experiencing problems with even basic calls to `snscrape.TwitterSearchScraper`, through both CLI and API, likely due to  recent policy changes of Twitter ?

### How to reproduce

The MWE from README
```
snscrape --max-results 100 twitter-hashtag archiveteam
```
fails
```
2023-03-15 22:39:43.420  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_...
```

### Expected behaviour

Tweets are retrieved

### Operating system

Ubuntu 20.04

### Python version: output of `python3 --version`

3.10

### snscrape version: output of `snscrape --version`

0.5.0.20230114.dev9+gd60ce38

### Scraper

TwitterSearchScraper

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

### Backtrace

CRITICAL  snscrape.base  Errors: non-200 status code (404), non-200 status code (404), non-200 status code (404), non-200 status code (404)
2023-03-15 22:39:43.463  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_pff0q_rn
Traceback (most recent call last):
  File "/home/mskorski/anticipate/anticipatio/.venv/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/home/mskorski/anticipate/anticipatio/.venv/lib/python3.10/site-packages/snscrape/_cli.py", line 318, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/mskorski/anticipate/anticipatio/.venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1556, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "/home/mskorski/anticipate/anticipatio/.venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 737, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
  File "/home/mskorski/anticipate/anticipatio/.venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 703, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/home/mskorski/anticipate/anticipatio/.venv/lib/python3.10/site-packages/snscrape/base.py", line 257, in _get
    return self._request('GET', *args, **kwargs)
  File "/home/mskorski/anticipate/anticipatio/.venv/lib/python3.10/site-packages/snscrape/base.py", line 253, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=%23archiveteam&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.

**Comment by JustAnotherArchivist** [comment]
You're using an outdated version of snscrape. Cf. #760 etc.

**Comment by pushshift** [comment]
This is actually a valid bug. Twitter rolled out two changes at midnight UTC (or right around it). One on the 13th/14th and one on the 14th/15th. It looks like you addressed the issue with the changes on the 13th/14th (The Chrome user-agent issue when getting the guest token). The change on midnight 14th/15th was a much harder issue to debug. Twitter no longer accepts http 1.x calls to adaptive.json (and their error messages are not helpful at all). We had to go from using requests library to using httpx library which has support for http/2 (the only protocol that adaptive.json will work with now). https://www.python-httpx.org/http2/

I don't know if you want to keep this here or open a new ticket for this change but once you start calling adaptive with http/2, you should be good to go. It tooks hours of debugging before I figured out this very esoteric bug / change. My guess is that Twitter engineers are trying to speed up the loading time for the Twitter timelines by making it possible to parallelize calls to the API along with other assets.

**Comment by JustAnotherArchivist** [comment]
@pushshift Hi Jason! That's interesting, because I'm successfully running snscrape 0.6.1 (i.e. requests and HTTP/1.1 with a custom TLS cipher selection and a modern Chrome UA) on multiple machines from three continents without any errors of this sort. And so far, all 'I'm getting 404s' reports (including this one) turned out to be users not using the current snscrape version. So HTTP/2 doesn't seem to be required yet. But it's certainly something worth keeping in mind for the future as it's only a matter of time before it will break again.

**Comment by pushshift** [comment]
Wow, that is really interesting. I'm not sure what's going on then! In any event, keep this in memory if something changes on your end. This is for the https://api.twitter.com/2/search/adaptive.json endpoint (if that's the one you're using). If you can successfully connect using HTTP 1.x with that endpoint, the only thing I can think of is perhaps they reverted it at some point today. We were trying from Heztner in Germany and multiple Linode locations and couldn't get anything but HTTP/2 to work with that endpoint. 

Glad it is working for you then!

**Comment by JustAnotherArchivist** [comment]
Yeah, that is the endpoint I'm using. I haven't tried Hetzner or Linode, but Twitter has previously banned large IP ranges of major server providers (e.g. all of AWS was banned years ago), so it wouldn't surprise me. Interesting though that HTTP/2 would bypass that.

**Comment by maciejskorski** [comment]
> You're using an outdated version of snscrape. Cf. #760 etc.

Indeed, a minor bump fixed the issue. thanks
