### ISSUE TITLE
Twitter-search on Mac : command not found: snscrape

### ISSUE THREAD

**Issue by thierryfournier** [JustAnotherArchivist/snscrape#775]
### Describe the bug

Hello,
I installed and tested Xcode and Snscrape 3 days ago and everythink worked perfectly.
Today this simple command : snscrape -n 10 twitter-search '"I love"’  > test.txt
doesn't work anymore. The terminal returns the error : zsh: command not found: snscrape
Do you have any idea about that please ?
Thank you very much in advance
Best

### How to reproduce

snscrape -n 10 twitter-search '"I love"’  > test.txt

### Expected behaviour

creation of a file test.txt with the result of the twitter searches

### Operating system

Mac OS 11.6.6

### Python version: output of `python3 --version`

3.10.10

### snscrape version: output of `snscrape --version`

0.6.0.20230303

### Scraper

twitter-search

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

### Backtrace

zsh: command not found: snscrape

**Comment by MykhailoYampolskyi** [comment]
Try to update snscrape. Current version is 0.6.1.20230314.

**Comment by JustAnotherArchivist** [comment]
This isn't caused by the snscrape version but by a broken installation. I have no idea what could cause it though. Try uninstalling and then reinstalling snscrape.

**Comment by thierryfournier** [comment]
Hi,
Many thanks for your quick answer. I uninstalled and installed again snscrape and now it's working. I would prefer to understand what happened, as I installed nothing since the last time I worked with it 1 week ago, but anyway the problem seems to be solved. Thank you very much! 
Best
Thierry
