### ISSUE TITLE
Get, store, and use Scroll-id

### ISSUE THREAD

**Issue by kelcheone** [JustAnotherArchivist/snscrape#778]
Hey there!

Wanted to ask if it's possible to store the scroll id when scraping. 
## WHY?

The scroll-id can be used to resume the search from the last scraped point.
This is important for long-lived scraping that may crash due to some constraints such as when running on a lambda function that allows only for 15 minutes run.

**Comment by JustAnotherArchivist** [comment]
No this is not supported. The cursor alone is not sufficient for resuming a scrape anyway these days in the general case (e.g. tweets in scroll mode; all scrolling on the Twitter module uses the same code). The ability to specify it at all dates back to when snscrape had less functionality around scrolling, and it should probably be (deprecated and) removed as its presence is simply misleading now.

For search scrapes in 'latest' order specifically, you can instead use the `max_id` filter with a value one less than your last complete result to restart the scrape after a crash.

**Comment by kelcheone** [comment]
So when performing a search with snscrape I can switch the tabs to the `latest` tab?

**Comment by JustAnotherArchivist** [comment]
Searches use the 'latest' tab by default. You can switch to 'top' or 'user' on the CLI with the `--top` and `--user` options, respectively. From Python, you can use the `mode` argument, set to one of the `TwitterSearchScraperMode` values.

**Comment by kelcheone** [comment]
Thanks.
