### ISSUE TITLE
Extract real name of user from tweet 

### ISSUE THREAD

**Issue by lukaspistelak** [JustAnotherArchivist/snscrape#78]
how can i get the real name of user  from tweet ?,    i can see only user_name in api

**Comment by JustAnotherArchivist** [comment]
The real name is not extracted by snscrape currently. It's on my list to add along with a few other fields.

**Comment by lukaspistelak** [comment]
Thanks for add this Method :+1: 
i would like to ask If is Possible to get display Name directly from the object tweet? (there is still only username)

i have to everytime call method : `user_obj=snscrape.modules.twitter.TwitterUserScraper(tweet_obj.username)`
to get ONLY displayname, i think this is overkill for me and the twitter api! thanks
