### ISSUE TITLE
Twitter search scrapes fail with non-200 status code (404) - 20/Mar/2023 V.0.6.1.20230314

### ISSUE THREAD

**Issue by luisvivasg** [JustAnotherArchivist/snscrape#780]
### Describe the bug

Hello. 

Last week I had the same error. I upgraded snscrape to version snscrape 0.6.1.20230314, today it is not working again. Is anyone having the same problem?

Same as https://github.com/JustAnotherArchivist/snscrape/issues/760

Regards.

### How to reproduce

I can reproduce this byb scraping any twitter account

### Expected behaviour

It should return data from twitter account

### Operating system

Ubuntu 20.04

### Python version: output of `python3 --version`

3.10.6

### snscrape version: output of `snscrape --version`

0.6.1.20230314

### Scraper

sntwitter.TwitterSearchScraper

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by luisvivasg** [comment]
I read this https://github.com/JustAnotherArchivist/snscrape/issues/783. I am using a cloud server meaning that one of the requirements is False. It is a shame it has stopped working. It worked flawlessly for 4 months. I will need to find a workaround.

**Comment by JustAnotherArchivist** [comment]
Yeah, Twitter is becoming more and more annoying. I'm sure the correlation with who owns it is just a coincidence...
