### ISSUE TITLE
Snscraper turns the domain mentioned in the tweet into link (Google.com -> https://t.co/UL7RweQX1l). How to avoid it?

### ISSUE THREAD

**Issue by PeschykhinLev** [JustAnotherArchivist/snscrape#781]

**Comment by JustAnotherArchivist** [comment]
snscrape returns all relevant information in the `Tweet`'s `links` attribute: text (as it's rendered), t.co URL, and actual URL (plus indices within `rawContent` where the link appears).

**Comment by PeschykhinLev** [comment]
Changed to 'renderedContent', it works!
