### ISSUE TITLE
Implement proxy support

### ISSUE THREAD

**Issue by jus3q** [JustAnotherArchivist/snscrape#788]
### Describe the feature

I'd like my connection to use a proxy so twitter doesn't rate limit a certain IP.  (It happened to me)

### Would this fix a problem you're experiencing? If so, specify.

My VPS has a rate limit from twitter.

### Did you consider other alternatives?

I've tried many and don't have a good solution that works.  I'd like for this code to work:

```python3
def get_latest_tweets():

    os.environ['HTTP_PROXY'] = ''
    os.environ['HTTPS_PROXY'] = ''

    attributes_container = []
    current_date = datetime.now(pytz.utc)

    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:elonmusk filter:safe', proxies = {'http': '234.13.222.66:80'}).get_items()):

        date_diff = current_date - tweet.date
        if date_diff > timedelta(days=1):
            break

        pacific = pytz.timezone('US/Pacific')
        date_created_pacific = tweet.date.astimezone(pacific)


        attributes_container.append([date_created_pacific, tweet.rawContent])

    tweets_df = pd.DataFrame(attributes_container, columns=["Date Created", "Tweets"])

    return tweets_df

print(get_latest_tweets())
```

**Comment by JustAnotherArchivist** [comment]
snscrape already supports proxies. You just need to find one that works with Twitter. Many don't, especially since the changes in January. Or alternatively, run snscrape on a different machine.

**Comment by jus3q** [comment]
Ok.  I'm having a lot of trouble with it, is the method I have correct it setting the proxy?  by setting the os.environ['HTTP_PROXY'] variable to the proxy address?  it doesn't seem like passing the proxies through TwitterSearchScraper does anything.

**Comment by JustAnotherArchivist** [comment]
Modifying `os.environ` does not necessarily work (and should be avoided in general, anyway), but that would depend on internal code from requests or urllib3. Using the `proxies` argument to the `Scraper` is the correct way to do it, but you're only supplying a proxy for HTTP requests in your code; the Twitter module uses HTTPS throughout. Enable debug logging, and you should see whether the proxy is being used or not.
