### ISSUE TITLE
How do I search a  Twitter username in another language 

### ISSUE THREAD

**Issue by Nasseh123** [JustAnotherArchivist/snscrape#789]
Hello kindly help me with this. I try to pass an Arabic username ,or something different from english,  when I check on the get request it changes the **from** string.I am not sure how am supposed to tackle this kindly help me out. Thanks
![image](https://user-images.githubusercontent.com/48709361/227073156-84b4523f-8e58-4432-b1fd-801a41586cea.png)

**Comment by Nasseh123** [comment]
I also get this on my terminal when searching for a user. What should I add or where could I be going wrong. Thanks in advance
![image](https://user-images.githubusercontent.com/48709361/227073420-7f160041-9ccc-4390-acfb-2fd011375578.png)

**Comment by JustAnotherArchivist** [comment]
You're passing a `bytes` object for the username. Use a string instead.

**Comment by JustAnotherArchivist** [comment]
But also, Twitter usernames can't contain characters from another alphabet. They are restricted to a-z, A-Z, 0-9, and the underscore.

**Comment by Nasseh123** [comment]
how can i achieve something like this with snscrape? [SAMPLE URL](https://twitter.com/search?q=%D8%A7%D9%84%D8%B5%D9%85%D8%AF&src=typed_query)
![image](https://user-images.githubusercontent.com/48709361/227076701-917c9d41-e63e-4d59-94e0-4a732299cbdd.png)

**Comment by Nasseh123** [comment]
What could i be doing wrong to getting this?


> I also get this on my terminal when searching for a user. What should I add or where could I be going wrong. Thanks in advance ![image](https://user-images.githubusercontent.com/48709361/227073420-7f160041-9ccc-4390-acfb-2fd011375578.png)

**Comment by TheTechRobo** [comment]
> You're passing a bytes object for the username. Use a string instead.

**Comment by Nasseh123** [comment]
I am actually passing a string but  being somehow on the url its an object.This is because am passing a param with another language eg الصمد
Maybe could you help me out with a doc to reference the options that I can use to reference what and how should pass arguments?
In regards to date(since & until) its also not filtering appropriately. Am not so sure why.Maybe help me with somewhere i can reference to figure out how the tool expects params
![image](https://user-images.githubusercontent.com/48709361/227094448-49c35ca5-62a2-4bb6-b0e7-a4e730691636.png)

**Comment by JustAnotherArchivist** [comment]
The URLs above very clearly show that what you passed in is not a string (and also your latest screenshot doesn't match either of those URLs). `b%27...%27` is the URL-encoded version of `b'...'`, Python's representation of a `bytes` object. My guess is that you did something like `f'{word} since:...'`, and if `word` is a `bytes` object, it results in that.

If you want help, share your complete code (as text, not as a screenshot), what you get when you run that exact code, and what you expected instead.
