### ISSUE TITLE
"Unable to find guest token" exception on Twitter calls from AWS

### ISSUE THREAD

**Issue by arranjdavis** [JustAnotherArchivist/snscrape#79]
I am using a `conda` environment on a Linux machine (an AWS instance) using `Python 3.8.3`. 

I have installed `snscrape` using `pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git`

When I run any call to Twitter from the command line, such as:

`snscrape twitter-user textfiles >twitter-@textfiles`

I get the `snscrape.base.ScraperException: Unable to find guest token` exception. I saw that this is a closed issue #64, but it is closed. Sorry, not sure if I should bring this up here since #64 is closed!

Thanks for  the help, and all of your work on this!

**Comment by JustAnotherArchivist** [comment]
I've heard this before. It appears that all AWS IPs are blocked on Twitter. This isn't something that I can work around in snscrape I'm afraid.

**Comment by arranjdavis** [comment]
Ahh, I see. Thanks for clarifying that! It is really useful to know. Good luck with this project!

**Comment by arranjdavis** [comment]
Just to say, I have figured out how to run `snscrape` from a Google Colab, although you will need to figure out a way to run `Python 3.8` on the Colab if you want to use arguments like `--jsonl`.

[This](https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory) worked for me (see comments on the accepted answer, as well).

**Comment by Hamma111** [comment]
> I get the `snscrape.base.ScraperException: Unable to find guest token` exception. I saw that this is similar to issue #64, but it is closed. Sorry, not sure if I should bring this up here or on #64!

I'm in google colab and getting this exception. Were you able to this working?

BTW thanks for this
> [This](https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory) worked for me (see comments on the accepted answer, as well).

**Comment by OllyWelch** [comment]
I was planning on using snscrape as part of a flask web app deployed on Heroku but obviously that method of deployment won't work due to this issue. Are there other deployment methods that will actually work?

**Comment by tungstenm** [comment]
Has anyone found a workaround/solution for running snscrape on aws?
I am getting the same error: "ScraperException: Unable to find guest token"

**Comment by mahdix** [comment]
Same issue on DO. Works perfectly fine on my laptop but on my VPS fails.
