### ISSUE TITLE
weird symbols

### ISSUE THREAD

**Issue by yudeng2022** [JustAnotherArchivist/snscrape#793]
Hi 
Thank you so much for providing this tool. It is super helpful. I used the following codes to scrape tweets. However, some of the tweets contain weird symbols (see example sentences below) when I save them to csv file. Any idea how to fix this? 
```
res = []
k = 0 
for keyword in products_list:
    k = k + 1
    print(k) 
    for j,tweet in enumerate(sntwitter.TwitterSearchScraper(keyword +  ' since:2019-01-1 until:2021-12-30 lang:en').get_items()):
        res.append([ tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])
        if j > 400: 
            break

data1 = pd.DataFrame(res, columns = ['date', 'id','content', 'username','lang'])
data1.to_csv('temp.csv')
```
@username If it wasnâ€™t for copay assistance, I could never afford the 250.00 a month for my Humira. We pay 236.00 a week for health insurance. What a scam.

@username Hank I SO feel you! Currently switching from Remicade to Humira for Crohnâ€™s and going through the same damn thing ðŸ˜…ðŸ’©

**Comment by JustAnotherArchivist** [comment]
The CSV file is almost certainly fine and encoded as UTF-8, but whatever software you use to look at it reads it as ISO-8859-1 (aka Latin1). These legacy encodings need to die already.
