### ISSUE TITLE
viewCount missing information

### ISSUE THREAD

**Issue by AnaMaono** [JustAnotherArchivist/snscrape#800]
### Describe the bug

I have downloaded 1000 tweets from one user, but the viewCount has only 304 non-null entries. Is this a bug with the scraper or something to do with Twitter or the user account? (I am able to retrieve all 1000 values for likeCount, quoteCount, replyCount, retweetCount)

I am using snscrape via jupyter notebook. 

### How to reproduce
```python3
# Setting variables to be used in format string command below
tweet_count = 1000
username = "username"

# Using OS library to call CLI commands in Python
os.system("snscrape --jsonl --max-results {} twitter-search 'from:{}'> tweets.json".format(tweet_count, username))
```

### Expected behaviour

I was expecting all 1000 tweets to have a value for the viewCount

### Operating system

MacOs BigSur 11.6.4

### Python version: output of `python3 --version`

python3.10.4

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230320

### Scraper

twitter-user

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Backtrace

None

**Comment by TheTechRobo** [comment]
does #712 answer your question?

**Comment by AnaMaono** [comment]
> 

yes! thank you
