### ISSUE TITLE
{"errors":[{"message":"Bad Authentication data","code":215}]}

### ISSUE THREAD

**Issue by massiveboss** [JustAnotherArchivist/snscrape#802]
Hello Guys. I follow theese steps:
1) pip install virtualenv
2) virtualenv hakenv
3)source hakenv/bin/activate
4)pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git

and I write code :

import  snscrape.modules.twitter as sntwitter 

maxTweets =30

keyword = 'COVID-19'

for i,tweet in enumerate(sntwitter.TwitterSearchScraper(keyword + ' since:2020-11-01 until:2020-12-06 lang:"en" ').get_items()):
    if i>maxTweets:
        break
    print([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.user.location,
                             tweet.likeCount,tweet.retweetCount, tweet.user.followersCount])

But I have a error that : 

Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=COVID-19+since%3A2020-11-01+until%3A2020-12-06+lang%3A%22en%22+&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: blocked (404)
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=COVID-19+since%3A2020-11-01+until%3A2020-12-06+lang%3A%22en%22+&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
Errors: blocked (404), blocked (404), blocked (404), blocked (404)
Traceback (most recent call last):
  File "/Users/farukaydin/Desktop/Twetter/main.py", line 7, in <module>
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(keyword + ' since:2020-11-01 until:2020-12-06 lang:"en" ').get_items()):
  File "/Users/farukaydin/Desktop/Twetter/hakenv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1661, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "/Users/farukaydin/Desktop/Twetter/hakenv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 761, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
  File "/Users/farukaydin/Desktop/Twetter/hakenv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 727, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/Users/farukaydin/Desktop/Twetter/hakenv/lib/python3.10/site-packages/snscrape/base.py", line 251, in _get
    return self._request('GET', *args, **kwargs)
  File "/Users/farukaydin/Desktop/Twetter/hakenv/lib/python3.10/site-packages/snscrape/base.py", line 247, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=COVID-19+since%3A2020-11-01+until%3A2020-12-06+lang%3A%22en%22+&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.

And When I open link there is " {"errors":[{"message":"Bad Authentication data","code":215}]} " error. So please help me. How can I fix this?

**Comment by JustAnotherArchivist** [comment]
#783

**Comment by alinaqi12** [comment]
I am getting the same issue while fetching tweets? why is it happening?

**Comment by JustAnotherArchivist** [comment]
People not reading #783 is what's happening. And also, the 'Bad Authentication data' error is a red herring from mistakenly opening the URL in the error in a browser even though it isn't meant to be accessed that way.
