### ISSUE TITLE
Verify whether twitter account opens dm message

### ISSUE THREAD

**Issue by EyonJoshua91** [JustAnotherArchivist/snscrape#804]
### Describe the feature

Check whether twitter account opens dm message

### Would this fix a problem you're experiencing? If so, specify.

It is better to talk to people who has DM opened.

### Additional context

No the UI of each person's twitter profile, if their DM is open, there is additonal button to allow you send a direct message. I wonder whether that can be a direction to detect whether the user opens DM or not.

**Comment by JustAnotherArchivist** [comment]
To my knowledge, this information is only available when you're logged in.

**Comment by JustAnotherArchivist** [comment]
#270
