### ISSUE TITLE
Scrape a user's tweet in a fixed period of time

### ISSUE THREAD

**Issue by scn0901** [JustAnotherArchivist/snscrape#805]
Hello, I want to use twitter-user to scrape elonmusk's tweet since:2022-01-01 until:2023-01-01, however I failed, I used`snscrape --jsonl twitter-user 'elonmusk since:2022-01-01 until:2023-01-01' > data/elonmusk1.jsonl`, but it only returned `snscrape twitter-user: error: argument user: invalid user value: 'elonmusk since:2022-01-01 until:2023-01-01'`, how can I do? thank u!

**Comment by JustAnotherArchivist** [comment]
Use the `twitter-search` scraper. `twitter-user` only takes a username, not a search query.

    snscrape --jsonl twitter-search 'from:elonmusk since:2022-01-01 until:2023-01-01'

#112

**Comment by scn0901** [comment]
thank you!
