### ISSUE TITLE
Collect Twitter direct messages

### ISSUE THREAD

**Issue by mraliagha** [JustAnotherArchivist/snscrape#806]
### Describe the feature

Hi there,

We have a use case where we get to access user direct messages via Twitter official API. Given the API access is being revoked soon, is there any plan to bring private messages to Snscrape? I guess that would be an authenticated call, but user token can be used as long as the end-user provides permission to do so.

### Did you consider other alternatives?

Using Twitter Official API, which will be shutdown pretty soon.

**Comment by JustAnotherArchivist** [comment]
No: #270
