### ISSUE TITLE
Facing the same issues as #783, would like to discuss potential solutions

### ISSUE THREAD

**Issue by Jmallone** [JustAnotherArchivist/snscrape#809]
I am currently facing the same issue as mentioned in #783 regarding accessing the adaptive.json endpoint. 
However, I have found an alternative endpoint that serves the same purpose as shown in the following Python function:

```python
def get_twt(self, username, count=100, cursor=None):
    user_id = self.scrape_user(username)['rest_id']

    variables = {
        "userId": str(user_id),
        "count": str(count),
        "includePromotedContent": True,
        "withQuickPromoteEligibilityTweetFields": True,
        "withSuperFollowsUserFields": True,
        "withDownvotePerspective": False,
        "withReactionsMetadata": False,
        "withReactionsPerspective": False,
        "withSuperFollowsTweetFields": True,
        "withVoice": True,
        "withV2Timeline": True,
    }

    features = {
        "responsive_web_twitter_blue_verified_badge_is_enabled": True,
        "responsive_web_graphql_exclude_directive_enabled": False,
        "verified_phone_label_enabled": False,
        "responsive_web_graphql_timeline_navigation_enabled": True,
        "responsive_web_graphql_skip_user_profile_image_extensions_enabled": False,
        "tweetypie_unmention_optimization_enabled": True,
        "vibe_api_enabled": True,
        "responsive_web_edit_tweet_api_enabled": True,
        "graphql_is_translatable_rweb_tweet_is_translatable_enabled": True,
        "view_counts_everywhere_api_enabled": True,
        "longform_notetweets_consumption_enabled": True,
        "freedom_of_speech_not_reach_appeal_label_enabled": False,
        "standardized_nudges_misinfo": True,
        "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": False,
        "interactive_text_enabled": True,
        "responsive_web_text_conversations_enabled": False,
        "responsive_web_enhance_cards_enabled": False,
    }

    if cursor:
        variables["cursor"] = cursor

    params = {
        "variables": json.dumps(variables),
        "features": json.dumps(features),
    }

    url = "https://api.twitter.com/graphql/rCpYpqplOq3UJ2p6Oxy3tw/UserTweets"
    response = self.s.get(url, params=params)

    return response

```

This function is analogous to the following endpoint:
 https://github.com/JustAnotherArchivist/snscrape/blob/285d5874fc20a9d9463ed261f45c5f4118277d05/snscrape/modules/twitter.py#L1661 

Since the alternative endpoint is still accessible through my AWS EC2 instance, could we attempt to use this endpoint when the error as in #783 occurs instead? I would appreciate any input or discussion on this potential solution

Another alternative, although not directly related, is to obtain the token from a different source:
```python
def get_tokens(self):
    s = self.s

    headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0',
        'Accept': '*/*',
        'Accept-Language': 'pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3',
        'content-type': 'application/json',
    }

    s.headers.update(headers)

    # get auth token
    main_js_url = "https://abs.twimg.com/responsive-web/client-web/main.e46e1035.js"
    main_js_text = s.get(main_js_url).text
    token = re.search(r's="([\w\%]{104})"', main_js_text)[1]

    # update headers with authorization token
    s.headers.update({"authorization"	:	f"Bearer {token}"})

    # activate token and get guest token
    activate_token_url = "https://api.twitter.com/1.1/guest/activate.json"
    guest_token = s.post(activate_token_url).json()["guest_token"]

    return guest_token
```

**Comment by JustAnotherArchivist** [comment]
> ```python3
>    url = "https://api.twitter.com/graphql/rCpYpqplOq3UJ2p6Oxy3tw/UserTweets"
> ```

That's a similar endpoint to the one used by the `TwitterProfileScraper`. It obviously only allows fetching a user's tweets, not searching. It is also not equivalent for that limited subset of search queries either because the profile only returns about 3200 tweets and includes retweets (cf. [here](https://github.com/JustAnotherArchivist/snscrape/issues/83#issuecomment-738950400)).
The `TwitterProfileScraper` uses the `UserTweetsAndReplies` endpoint instead, which, as the name suggests, includes replies as well.

> obtain the token from a different source

Extracting the bearer token from the script file like that is probably not reliable, but that token hasn't changed in at least three years anyway. It identifies the Twitter web app, not the user.
The other endpoint is already what snscrape uses.

**Comment by Jmallone** [comment]
Ah got it, so not much to do while issue https://github.com/JustAnotherArchivist/snscrape/issues/783, I will try to use proxies on my ec2

I had become aware that this endpoint had further limitations, but I was uncertain about the extent of the restrictions. 

Aside from my proxy idea, do you have any suggestions on how I could bypass the 404 error? Even a vague idea would be helpful.

**Comment by JustAnotherArchivist** [comment]
To rephrase for clarity: you can probably just use the `TwitterProfileScraper` as it is. It may well be that only the search endpoint is limited. So if scraping profiles is all you need, that should be fine. Similarly, other scrapers that aren't wrappers around the search might also be fine.

I don't know of ways to bypass the bans other than changing your IP (by whatever means you have, from proxies of various forms to switching server providers). I also don't know the extent of the restrictions.

**Comment by Jmallone** [comment]
Thank you very much, I will try to avoid this in other ways, thanks for the feedback
