### ISSUE TITLE
KeyError: 'broadcaster_username' at scraping Twitter tweets

### ISSUE THREAD

**Issue by flamenco18** [JustAnotherArchivist/snscrape#810]
### Describe the bug

I tried to scrape Twitter tweets from 2022-01-09, but it gave an error: KeyError: 'broadcaster_username'.  (I installed snscrape upgrades)

### How to reproduce

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd
from time import sleep
from datetime import datetime, date
import os
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.pyplot import figure
import numpy as np
from datetime import timedelta
import glob
from matplotlib.colors import ListedColormap

tweets_list = []
e = 0
max_result = 20000
dates = pd.DataFrame()
dates["start_date"] = pd.date_range(start='9/1/2017', end='3/8/2023')
dates["end_date"] = pd.date_range(start='9/2/2017', end='3/9/2023')
dates = dates[dates.start_date > datetime(2022, 1, 8)]
dates = dates.astype("str")

for index, row in dates.iterrows():
    tweets_list = []
    naming = row['start_date']
    term = '(ethereum OR eth OR ether OR ETH OR ETHEREUM OR ETHER OR #eth OR #ethereum) since:'+row['start_date']+' until:'+row['end_date']+' lang:en'
    print(naming + " in progress!")
    for i, tweet in enumerate(sntwitter.TwitterSearchScraper(f'{term}').get_items()):  # declare a username
        e += 1
        print(f"Current scrape index: {e}", end="\r", flush=True)
        if i>max_result: #number of tweets you want to scrape
            break
            # print(movie_name, i, tweet)
        try:
            tweets_list.append([tweet.date, tweet.id, tweet.rawContent, tweet.likeCount, tweet.user.username, tweet.user.followersCount, tweet.user.location, tweet.user.verified, tweet.mentionedUsers, tweet.quoteCount, tweet.quotedTweet]) 
        except:
            continue
        
    tweets_df = pd.DataFrame(tweets_list, columns=['datetime', 'tweet_id', 'text', 'likes', 'username', 'user_followers', "user_location", "user_verified", "mentioned_users", "quote_count", "quoted_tweet_id"])
    tweets_df.to_csv("src/section2/twitter/scrapes/{}.csv".format(naming))
```

### Expected behaviour

Srapce user_name or pass if it returns error.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/99558508/228183108-9a02dd63-6dbe-41e8-8893-c270d9c79f7e.png)

### Operating system

Windows 11

### Python version: output of `python3 --version`

Python 3.10.7

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230320

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by victorleeasu** [comment]
Hi, I ran into the same error. But, mine happened after failing to retrieve media (source app). 
Pasting the error for your reference.

`Tweet 1631215106632609794 contains an app icon medium key '4_1640462300288102401' on app 'android_app'/'com.adamrocker.android.input.simeji', but the corresponding medium is missing; dropping`

**Comment by JustAnotherArchivist** [comment]
@victorleeasu That's a warning log message about something unrelated (incomplete/inconsistent data returned by Twitter) and most likely on a different tweet. Please share your search query because I'm interested in seeing more examples of the crash.

**Comment by victorleeasu** [comment]
@JustAnotherArchivist Oh, sorry for the confusion. My query is simple as following
`"chatgpt since:2023-03-01 until:2023-03-15"`

I just checked the date for the last batch of tweets I have saved, "2023-03-09 13:13:33+00:00"
The problematic tweet should be more recent but around that time (I save every 1k tweets).

**Comment by JustAnotherArchivist** [comment]
Thanks. The troublemaker is older, because scrapes are in reverse-chronological order.
Found it: 1633814979823681536

**Comment by flamenco18** [comment]
Soo I tried to **if out** this tweet id: 1480264238874521600, but it return keyerror again :(
What should I do? @JustAnotherArchivist

**Comment by JustAnotherArchivist** [comment]
Wait; it will have to be fixed in snscrape's code. I should have time for that tomorrow or so.

Some technical details: all the cases I've seen so far involved Periscope cards where the `site` and `broadcaster` are the same user. Apparently Twitter no longer includes the username for the latter in that case, or something along those lines. So that case needs to be handled and the information pulled from the site user object instead.

**Comment by flamenco18** [comment]
Okay, thank you very much. If I would be an expert of this Repo and codes, I would make a PR request to help you to save your time. Thanks for your time!:) @JustAnotherArchivist

**Comment by flamenco18** [comment]
@JustAnotherArchivist what's up? Could you refactor the codes? :)

**Comment by JustAnotherArchivist** [comment]
Other things have interfered with my free time schedule, so I haven't been able to look into it yet. Hopefully this weekend.

As a workaround, you can exclude tweets that could contain such broken broadcast cards on Twitter searches with the `-card_name:"745291183405076480:broadcast"` filter. Few such tweets cause this crash though, so depending on your query, you might be losing a considerable amount of data. Once this is fixed, you could of course add them to your dataset with a separate scrape for just those cards.

**Comment by JustAnotherArchivist** [comment]
Some more examples in case they're needed in the future to validate this: 1641575445018845190 1641218971897851905 1641165338854424576 1640850350201798658 1640790912816254979
