### ISSUE TITLE
Increase the limit tweets received per second

### ISSUE THREAD

**Issue by h114mx001** [JustAnotherArchivist/snscrape#811]
Hi there. I am using TwitterSearch module for scraping tweets. However, it just reaches around 20 tweets/second. Can I increase the speed of this? I have tried both run on my local machine and a Azure cloud and it just went around this number. Thank you so much!

**Comment by JustAnotherArchivist** [comment]
Once upon a time, it was possible to increase the number of tweets returned by Twitter for a single request. But then they removed that. 20 tweets per request is the hard limit now on searches. I can usually do about 3 requests per second, but it varies. Your only option is to play around with different providers and network locations to try to reduce the latency.

**Comment by JustAnotherArchivist** [comment]
Cf. #481

**Comment by bxff** [comment]
Is it possible to increase the limit by using multiple threads? @JustAnotherArchivist
