### ISSUE TITLE
Can't access details on options and arguments

### ISSUE THREAD

**Issue by edwood99** [JustAnotherArchivist/snscrape#814]
Hi!
I try to run "snscrape --help" as described in the documentation, but I get the following error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[35], line 1
----> 1 snscrape --help

TypeError: bad operand type for unary -: '_Helper'
```

What am I doing wrong?

Here is my code (using Jupyter Notebook):
```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd
snscrape --help
```

**Comment by JustAnotherArchivist** [comment]
`snscrape --help` is the CLI, not the Python package. It isn't valid Python code; you'd use it on a terminal. There is no official documentation for the package yet.

**Comment by kzaman1** [comment]
> `snscrape --help` is the CLI, not the Python package. It isn't valid Python code; you'd use it on a terminal. There is no official documentation for the package yet.



> `snscrape --help` is the CLI, not the Python package. It isn't valid Python code; you'd use it on a terminal. There is no official documentation for the package yet.

Do you need help putting together the official documentation?

**Comment by JustAnotherArchivist** [comment]
There's an open PR for it already, but I haven't found the time to review and merge it. :-/

**Comment by JustAnotherArchivist** [comment]
Run it in the terminal (Bash or whatever it is), not the Python REPL. That is, type it where you ran `python3` above.

**Comment by edwood99** [comment]
Perfect, that did the job. Thank you!
