### ISSUE TITLE
snscrape.base:Errors: non-200 status code (404)

### ISSUE THREAD

**Issue by rlacalle** [JustAnotherArchivist/snscrape#815]
### Describe the bug

Using snscrape in a python script, I get the following error:
"CRITICAL:snscrape.base:Errors: non-200 status code (404), non-200 status code (404), non-200 status code (404), non-200 status code (404). snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/"

I confirm that:
- I am using the latest version of snscrape (0.6.2.20230320)
- I am not using a proxy or VPN.
- I am not using a cloud computing provider such as AWS or GCP.
- I can run the same search query successfully in a browser (in a private window/no pre-cookies) from the same machine.
(Screenshot attached in Screenshots and recordings)

### How to reproduce

Search code:

```python3
texto_noticia = "comisión europea coloca la sanidad madrileña como una de las mejores "
fecha_inicio = ' since:2022-11-01'
retweets = ' include:nativeretweets'
texto_buscar = texto_noticia+fecha_inicio+retweets
for i,tweet in enumerate(sntwitter.TwitterSearchScraper(texto_buscar).get_items()):
```

### Expected behaviour

Print data of the tweets obtained in the following search (code example:):

```python3
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_text).get_items()):
                print("tweet nº "+str(i))
                print("date: "+str(tweet.date))
                print("tweet id: "+str(tweet.id))
                print("nº likes: "+str(tweet.likeCount))
                print("nº retweets: "+str(tweet.retweetCount))
                if (tweet.retweetedTweet):
                    print("RETWEET:")
                    print("link retweetedTweet: "+str(tweet.retweetedTweet))
                    id_tweet_retweeted = str(tweet.retweetedTweet)[-19:]
                    print("id_tweet_retweeted: "+id_tweet_retweeted)
                else:
                    id_tweet_retweeted = 'None'           
```

### Screenshots and recordings

![screenshot](https://user-images.githubusercontent.com/96888048/228877500-fddc1dbe-03e0-4d99-a256-ce8596ac14ef.png)

### Operating system

Windows 10

### Python version: output of `python3 --version`

3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230320

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Backtrace

CRITICAL:snscrape.base:Errors: non-200 status code (404), non-200 status code (404), non-200 status code (404), non-200 status code (404). 
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/

### Log output

[Snscrape - Error DEBUG.txt](https://github.com/JustAnotherArchivist/snscrape/files/11112678/Snscrape.-.Error.DEBUG.txt)

**Comment by JustAnotherArchivist** [comment]
> I am using the latest version of snscrape (0.6.2.20230320)

You clearly aren't; the 'non-200 status code (404)' error does not exist in 0.6.2.

**Comment by rlacalle** [comment]
I think I have the latest version installed: snscrape 0.6.2.20230320
(Screenshot attached)
![screenshot version](https://user-images.githubusercontent.com/96888048/228884816-2a746f11-ec11-4fb7-b1d8-de810d00d3be.png)

**Comment by JustAnotherArchivist** [comment]
What does this print?

`python3 -c 'import snscrape.version; print(snscrape.version.__version__)'`

**Comment by Mr-Freewan** [comment]
> ok... now this print does: 0.5.0.20230113 You're right... but how is this possible?... what could be the reason?

Maybe you start you script outside venv?)

**Comment by rlacalle** [comment]
> 

Ok... Manually checked in the python environment libraries, apparently a previous version remained installed.

Now it works correctly with the latest version snscrape 0.6.2.20230320

_**Thank you very much [JustAnotherArchivist](https://github.com/JustAnotherArchivist), for the answer and contributions.**_
