### ISSUE TITLE
Is there a way to scrape tweets by mentions

### ISSUE THREAD

**Issue by anish-vempaty** [JustAnotherArchivist/snscrape#819]
I want to scrape tweets that mention someone like @rdj

**Comment by JustAnotherArchivist** [comment]
`snscrape twitter-search '@rdj'`

If you don't want the user's own tweets, you have to exclude those explicitly: `snscrape twitter-search '@rdj -from:rdj'`

You may also be interested in the `to` operator, which are replies to the user: `snscrape twitter-search 'to:rdj'`

**Comment by anish-vempaty** [comment]
Sorry for the late reply but THANK YOU SO MUCH!!!!!
You saved my project, I didn't know that you can do `-from:rdj`. so yea, thanks for the info
