### ISSUE TITLE
Unsure how to parse JSON file

### ISSUE THREAD

**Issue by VioletLinguist** [JustAnotherArchivist/snscrape#82]
I'm very new to all of this so this is most likely me missing a step. I used --jsonl to receive the data in the JSON format and had the file output as .json too. When I try to convert the information to .csv or some other format that I can digest, the python code does understand the file.

>\>\>\> import json
\>\>\> with open('test.json') as json_file:
...     data = json.load(json_file)
...     print(data)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 2940)

test.json is my scraped json file. Can anyone help me figure this out?

**Comment by JustAnotherArchivist** [comment]
JSONL is 'JSON lines', not plain JSON. Basically, each line in the output is one JSON object. So you could do this for example:

```python
import json
with open('test.json') as json_file:
	for line in json_file:
		data = json.load(line)
		print(data)
```

**Comment by helloqwerasdf** [comment]
I have a question about how to scrape the push of a twitteruser~anyone can help me?

**Comment by VioletLinguist** [comment]
@JustAnotherArchivist Thank you! I didn't realize there was a difference. I ran into a new problem though.

>\>\>\> with open('test.json') as json_file:
...     for line in json_file:
...         data = json.load(line)
...         print(data)
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'

I'm so new to this. I'm sorry for all the confusion.

**Comment by JustAnotherArchivist** [comment]
I edited my comment shortly after posting. It's `json.loads`, not `json.load`, to parse a string rather than a file object.
