### ISSUE TITLE
Has anyone used proxies successfully? 

### ISSUE THREAD

**Issue by DrSocket** [JustAnotherArchivist/snscrape#821]
I've been trying for a few days to run the requests to twitter through proxy using the method mentioned in issue: #548 
I've also tried to run a tor server on the machine and route everything through tor. 
With the proxies I get a blocked 404 error, have tried a couple of different proxies services and the proxies work if I add the to my browser and go on twitter manually (add to foxyproxy on browser).
Running the requests through Tor gives a mix of '404 blocked' error and 'non-200 response (429)'.
Any suggestions are most welcome.

**Comment by DrSocket** [comment]
why is this not a valid question?

**Comment by TheTechRobo** [comment]
This isn't really related to snscrape, though. Sounds like the proxy is either misconfigured or IP-banned - there's nothing much snscrape can do about that.

**Comment by DrSocket** [comment]
I've tried accessing twitter using the proxy on the browser and it works, so it doesn't seem like it's an IP ban.

**Comment by DrSocket** [comment]
@TheTechRobo have you managed to use snscrape with a proxy?

**Comment by DrSocket** [comment]
@TheTechRobo ok i'll try that thank you, although I guess it will get closed without any remark. I have no idea why this question got closed. 
Yes I add proxy to browser then check the ip on https://httpbin.org/ip and it's the proxy ip. also tried adding proxy to the computer network connection so that everything runs through the proxy, https://httpbin.org/ip also confirms the proxy ip address but running the scraper fails.

**Comment by TheTechRobo** [comment]
Before you do, are you logged in to Twitter on the browser? If so, try while logged out. It's possible twitter only does some checks if you're logged out.

**Comment by JustAnotherArchivist** [comment]
I'm closing these because every single issue so far about proxies has been either 'please recommend me a proxy' (off-topic, you're on your own on that one) or 'snscrape isn't working with my proxy' (because the proxy is broken or changes the TLS signature, or because people weren't using the current snscrape version). If you have a genuine case of a proxy working in a blank browser request (private window or clean profile, not logged in or anything) but not in snscrape, yeah, please file a complete bug report with a debug log and all details, then there's something actually actionable.

**Comment by DrSocket** [comment]
Alright, yes I'm logging in using proxy in a private window, tried on chrome and brave, confirmed the proxy ip address. twitter is working with proxy but not with snscrape + proxy.

**Comment by JustAnotherArchivist** [comment]
> blank browser request (private window or clean profile, ***not logged in*** or anything)

Logged-in sessions get treated differently.

**Comment by DrSocket** [comment]
@JustAnotherArchivist tests were done on private window (not logged in)

**Comment by JustAnotherArchivist** [comment]
@DrSocket Uh, but you just said the opposite above?

> yes I'm logging in using proxy in a private window

Anyway, if you can access Twitter's search without any prior login or cookies but can't scrape, yes, complete bug report please.

**Comment by DrSocket** [comment]
I just meant I'm successfully going into twitter.com from the browser on a private window using the proxy, but haven't managed to make it work using snscrape
