### ISSUE TITLE
Twitter Blue status when scraping

### ISSUE THREAD

**Issue by thewozniak** [JustAnotherArchivist/snscrape#822]
### Describe the feature

The script returns false for the verified field for a user with Twitter Blue.
I assume that this field is for the so-called Legacy Veryfied

Is it possible to read Twitter Blue status while scraping data or can it be added in future updates?

**Comment by JustAnotherArchivist** [comment]
Blue checkmark (e.g. iamjohnoliver) seem to always be true. The gold one is not currently considered at all; for example, BBC and SpaceX are true but Tesla is false. I assume that depends on how and/or when they were verified. The grey checkmark for government entities (e.g. nasa) isn't reflected anywhere either.

Not possible currently, but could and should certainly be added.

**Comment by thewozniak** [comment]
> `Blue checkmark (e.g. iamjohnoliver) seem to always be true`

That's weird. Try for user OrsonDzi or thewoz. It will return false :(

**Comment by JustAnotherArchivist** [comment]
Huh, indeed. The ones I checked were all true. I guess it also depends on when and how they were verified then.

**Comment by thewozniak** [comment]
It looks like something might be broken on the twitter side. I (thewoz) have Twitter Blue almost from the very beginning - from the second stage, after the changes that were made due to impersonation of other users after taking out a subscription. OrsonDzi has subscribed to Twitter Blue since it was recently made available world wide.

**Comment by AntoinePaix** [comment]
There is a verification_type field in the json of a tweet (in the user section) indicating the type of verification. For example for NASA it's "Government".

**Comment by thewozniak** [comment]
> There is a verification_type field in the json of a tweet (in the user section) indicating the type of verification. For example for NASA it's "Government".

I don't see any. This is what I get for user: @iamjohnoliver

> {"_type": "snscrape.modules.twitter.Tweet", "url": "https://twitter.com/iamjohnoliver/status/1642959509462065152", "date": "2023-04-03T18:37:26+00:00", "rawContent": "Here's our piece from last night on solitary confinement...https://t.co/lTWc9ZWcKS", "renderedContent": "Here's our piece from last night on solitary confinement...youtube.com/watch?v=_uSZwE\u2026", "id": 1642959509462065152, "user": {"_type": "snscrape.modules.twitter.User", "username": "iamjohnoliver", "id": 316389142, "displayname": "John Oliver", "rawDescription": "Comedian. @LastWeekTonight, @TheDailyShow, The Bugle Podcast (@hellobuglers)", "renderedDescription": "Comedian. @LastWeekTonight, @TheDailyShow, The Bugle Podcast (@hellobuglers)", "descriptionLinks": null, "verified": true, "created": "2011-06-13T11:25:14+00:00", "followersCount": 5577715, "friendsCount": 151, "statusesCount": 681, "favouritesCount": 1, "listedCount": 15490, "mediaCount": 353, "location": "New York", "protected": false, "link": {"_type": "snscrape.modules.twitter.TextLink", "text": "iamjohnoliver.com", "url": "http://www.iamjohnoliver.com", "tcourl": "http://t.co/qbOinEMIHG", "indices": [0, 22]}, "profileImageUrl": "https://pbs.twimg.com/profile_images/1393958859/main_normal.jpg", "profileBannerUrl": null, "label": null, "description": "Comedian. @LastWeekTonight, @TheDailyShow, The Bugle Podcast (@hellobuglers)", "descriptionUrls": null, "linkTcourl": "http://t.co/qbOinEMIHG", "linkUrl": "http://www.iamjohnoliver.com", "url": "https://twitter.com/iamjohnoliver"}, "replyCount": 80, "retweetCount": 204, "likeCount": 1219, "quoteCount": 24, "conversationId": 1642959509462065152, "lang": "en", "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>", "sourceUrl": "https://mobile.twitter.com", "sourceLabel": "Twitter Web App", "links": [{"_type": "snscrape.modules.twitter.TextLink", "text": "youtube.com/watch?v=_uSZwE\u2026", "url": "https://www.youtube.com/watch?v=_uSZwErdH3I", "tcourl": "https://t.co/lTWc9ZWcKS", "indices": [59, 82]}], "media": null, "retweetedTweet": null, "quotedTweet": null, "inReplyToTweetId": null, "inReplyToUser": null, "mentionedUsers": null, "coordinates": null, "place": null, "hashtags": null, "cashtags": null, "card": {"_type": "snscrape.modules.twitter.PlayerCard", "title": "Solitary Confinement: Last Week Tonight with John Oliver (HBO)", "url": "https://www.youtube.com/watch?v=_uSZwErdH3I", "description": "John Oliver discusses solitary confinement, how prevalent it is, how damaging it can be, and, of course, how to hit the woah. Connect with Last Week Tonight ...", "imageUrl": "https://pbs.twimg.com/card_img/1642777054922899457/yjyNhz2j?format=jpg&name=orig", "siteUser": {"_type": "snscrape.modules.twitter.User", "username": "YouTube", "id": 10228272, "displayname": "YouTube", "rawDescription": "like and subscribe.", "renderedDescription": "like and subscribe.", "descriptionLinks": null, "verified": true, "created": "2007-11-13T21:43:46+00:00", "followersCount": 78865094, "friendsCount": 1191, "statusesCount": 52484, "favouritesCount": 6153, "listedCount": 80236, "mediaCount": 15366, "location": "San Bruno, CA", "protected": false, "link": {"_type": "snscrape.modules.twitter.TextLink", "text": "youtube.com", "url": "http://youtube.com", "tcourl": "https://t.co/bUisN3YzpE", "indices": [0, 23]}, "profileImageUrl": "https://pbs.twimg.com/profile_images/1427292844612595720/RC1YSvuT_normal.jpg", "profileBannerUrl": "https://pbs.twimg.com/profile_banners/10228272/1680292897", "label": null, "description": "like and subscribe.", "descriptionUrls": null, "linkTcourl": "https://t.co/bUisN3YzpE", "linkUrl": "http://youtube.com", "url": "https://twitter.com/YouTube"}}, "viewCount": 356401, "vibe": null, "content": "Here's our piece from last night on solitary confinement...https://t.co/lTWc9ZWcKS", "outlinks": ["https://www.youtube.com/watch?v=_uSZwErdH3I"], "outlinksss": "https://www.youtube.com/watch?v=_uSZwErdH3I", "tcooutlinks": ["https://t.co/lTWc9ZWcKS"], "tcooutlinksss": "https://t.co/lTWc9ZWcKS", "username": "iamjohnoliver"}

**Comment by TheTechRobo** [comment]
@thewozniak I believe they are referring to the JSON that Twitter returns, not snscrape's.

**Comment by nbrahmani** [comment]
As far as I can see the api endpoint to get user data 'https://twitter.com/i/api/graphql/7mjxD3-C6BxitPMVQ6w0-Q/UserByScreenName' does not have the verified_by key. I could only see it while getting tweets data from 'https://twitter.com/i/api/graphql/nrdle2catTyGnTyj1Qa7wA/UserTweetsAndReplies'. Is there any other api that could work instead of getting the tweets?

**Comment by AntoinePaix** [comment]
Actually, the old `verified` field is now systematically `False`. Now you have to look at the `is_blue_verified` field in the twitter json response.

When the account is certified as government or business, the `verified_type` field is added in the json response.

**Comment by nbrahmani** [comment]
Yeah I used the 'verified_type' label, but I could only find it embedded in the tweets, but not in the user information. Not sure I missed something or Twitter is just weird 🤷‍♀️
