### ISSUE TITLE
members not being returned with telegram again

### ISSUE THREAD

**Issue by Shifter2600** [JustAnotherArchivist/snscrape#823]
### Describe the bug

looks like this was an issue before where members were not being returned.

This is a fresh install using.
pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git

### How to reproduce

```
import snscrape.modules.telegram

scraper = snscrape.modules.telegram.TelegramChannelScraper('CryptoNewsSource')
for i, item in enumerate(scraper.get_items()):
	print(item.json())
	if i >= 10:
		break
```

### Expected behaviour

field members returned with int 

### Operating system

python

### Python version: output of `python3 --version`

Python 3.9.13

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev3+g3dd9c28

### Scraper

TelegramChannelScraper

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by JustAnotherArchivist** [comment]
The code is not a reproducer; the bug's in the entity extractor, not posts.

```
$ snscrape --with-entity -n 0 telegram-channel telegram
<snip>
ValueError: invalid literal for int() with base 10: '6400358sub'
```
