### ISSUE TITLE
Adopt Chrome’s UA reduction scheme

### ISSUE THREAD

**Issue by horsemankukka** [JustAnotherArchivist/snscrape#827]
### Describe the feature

Noticed that commit e47fbe3 bumped user agent, fixing bug #760. It however fixes it to create user-agent string that does not exist anymore, which may cause problems at some point. Chrome browsers `>=101` have all been in [UA reduction Phase 4](https://www.chromium.org/updates/ua-reduction/#sample-ua-strings-phase-4) since 2022-06-13, which means that the token is always `Chrome/<majorVersion>.0.0.0`.

One way to fix the user-agent getting old could be to interpolate the newest version based on [Chrome’s release calendar](https://chromiumdash.appspot.com/schedule). I tested these parameters and plain linear interpolation seems to work fairly well at least compared against the current planned schedule.

If desired, random platform and slight version randomization could also be added, for example:

```python
import random
from datetime import date

def random_user_agent():
    def lerp(a1, b1, a2, b2, n):
        return (n - a1) / (b1 - a1) * (b2 - a2) + a2

    version = lerp(
        date(2023, 3, 7).toordinal(),
        date(2030, 9, 24).toordinal(),
        111,
        200,
        date.today().toordinal()
    )
    version = int(version) + random.randint(-5, 1)
    version = max(version, 101)

    platform = random.choices([
        'Windows NT 10.0; Win64; x64',
        'Macintosh; Intel Mac OS X 10_15_7',
        'X11; Linux x86_64'
    ], weights=[82, 12, 6])[0]

    return f'Mozilla/5.0 ({platform}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{version}.0.0.0 Safari/537.36'
```

One bit of more randomness would be to add `f'OPR/{version - 14}.0.0.0'` as the last token randomly, but that adds complexity and brittleness as the offset from Chrome’s version might not be guaranteed.

I can make a pull request, but would like some comments about how much randomization is desired in exchange to growing complexity, and whether the main function should be moved to utils or something.

The code is my own and can be used with CC0 license.

### Would this fix a problem you're experiencing? If so, specify.

There doesn’t seem to be any problems yet, but if unexplained problems start to appear, this could be one reason.

**Comment by JustAnotherArchivist** [comment]
Good points and great ideas! I love the lerp in particular.

The current code (apart from that version bump you mentioned) dates back to a long time ago when Twitter was doing weird things to individual UAs, especially on parallel scrapes IIRC. It was simply the easiest way to minimise the problems and was probably overkill. It might be time to check whether such randomisation is still necessary at all. The fuzzy major version lerp is excellent either way though to avoid regular updating and/or a reoccurrence of #760 the next time Twitter decides to no longer like older browser versions. Might actually want to do that across (almost) all modules, not just for Twitter.

**Comment by JustAnotherArchivist** [comment]
I went with a weaker implementation that merely handles the major version. In my tests, it appeared that anything beyond that is unnecessary these days. I will roll this out to other scrapers over time.
