### ISSUE TITLE
username and the date from input

### ISSUE THREAD

**Issue by ihabpalamino** [JustAnotherArchivist/snscrape#829]
### Describe the feature

![image](https://user-images.githubusercontent.com/86556941/230374699-0eb655c9-d64f-4190-9db2-9049df6bfa33.png)
this is my code i wanna know instead of scraper=sntwitter.TwitterSearchScraper(f"(from:Medi1TV) until:2023-04-6 since:2023-02-01") how can i make the username and the until and since date dynamically from an input?

**Comment by JustAnotherArchivist** [comment]
Python can do string formatting, but this is not the place to ask general Python questions.
