### ISSUE TITLE
Twitter: extract number of bookmarks

### ISSUE THREAD

**Issue by sinaFa** [JustAnotherArchivist/snscrape#831]
### Describe the feature

Twitter recently made public the number of impressions as well as the number of bookmarks for every tweet. 
Would it be possible to add it to the library so one could also retrieve this information with other engagement metrics such as replyCount, likeCount, etc.?

That would be a great addition to the library. 

Thanks

**Comment by AntoinePaix** [comment]
@sinaFa What is the name of the impression field ? For bookmarks it's `bookmark_count` but I don't see any `impression_count` field inside the json.
