### ISSUE TITLE
from: user 

### ISSUE THREAD

**Issue by Ashwin-RN** [JustAnotherArchivist/snscrape#832]
is this feature still working, it is returning an empty df. If it is working, can I add multiple accounts in the same request?
PLS note: this syntax works perfectly for keyword searches.

```python3
df_2 = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    from:NYCHealthCommr since:2020-01-01 near:"new york"within:30km lang:en).get_items(), total_tweets))[['user',date','renderedContent', 'lang']]
```

**Comment by JustAnotherArchivist** [comment]
The code you included isn't valid Python (missing quotes around the query), but the reason you get no results is probably the lack of a space before the `within` filter (which I [already pointed out to you once before](https://github.com/JustAnotherArchivist/snscrape/issues/303#issuecomment-1494502960)).

**Comment by Ashwin-RN** [comment]
> The code you included isn't valid Python (missing quotes around the query), but the reason you get no results is probably the lack of a space before the `within` filter (which I [already pointed out to you once before](https://github.com/JustAnotherArchivist/snscrape/issues/303#issuecomment-1494502960)).

Hey, so I do set it up as a query. The issue was the '@'. Anyway, thanks.
