### ISSUE TITLE
why the place variable in the twitter module cannot be scraped

### ISSUE THREAD

**Issue by Fadlanbima** [JustAnotherArchivist/snscrape#833]
I'm trying to retrieve the place variable to find out where a tweet came from, but when the scraping process is complete, the value of this variable is empty. is there any configuration I should do to handle this?

**Comment by JustAnotherArchivist** [comment]
There is no configuration. If snscrape returns `place` `None`, that's because Twitter didn't return any geolocation for the tweet. If you have a case where a tweet has geolocation information but snscrape doesn't return it, please file a complete bug report.
