### ISSUE TITLE
How to call snscrape and pass in parameters

### ISSUE THREAD

**Issue by break404** [JustAnotherArchivist/snscrape#84]
How to call snscrape and pass in parameters in my own python script? Such as since, jsonl

**Comment by JustAnotherArchivist** [comment]
Well, you could execute snscrape with `subprocess.run` or similar, but it's better to use the API directly instead, which gives you much more control. See #73 for an example.

**Comment by break404** [comment]
OK,Thank's ,But how do I pass more parameters? For example, limit?

**Comment by JustAnotherArchivist** [comment]
With `subprocess.run`, you just use the same things as on the command line. With the API, you need to implement yourself on what condition you want to break the loop. For a count limit, I'd use `enumerate`. But you can also use any arbitrary condition.

**Comment by break404** [comment]
Hello, I want to know how to use api such as calling in python script, for example import snscrape.modules.twitter
for tweet in snscrape.modules.twitter.TwitterSearchScraper('corona lang:en').get_items():
This example is to crawl Twitter in English language. How to pass parameters if I want to limit the number of returns each time? And how do I realize that the data I want to return is in json format? Thank you for your help

**Comment by JustAnotherArchivist** [comment]
You do not pass these parameters to the API. The API does not need or care about them.

```python
import snscrape.modules.twitter
for i, tweet in enumerate(snscrape.modules.twitter.TwitterSearchScraper('corona lang:en').get_items()):
	# Do something
	if i >= 49: # Stop after the 50th result; enumerate counts from zero
		break
```

You can do whatever you want with the `tweet` object inside the loop, e.g. do further analysis on the tweet, extract the exact information you need, or send it to a central server for collection.

Directly converting it to JSON, however, is not supported. The CLI performs conversion magic to handle `datetime` objects and `NamedTuple`s as those are not serialisable in JSON. This code (in `snscrape/cli.py`) is not part of the public API of snscrape, so it may break at any time. I've been considering moving this to the general code, but I couldn't come up with a clean way of doing that so far.

**Comment by Hamma111** [comment]
if you use jupyter, use `!snscrape`  to get results. 

For example,

```
results  = !snscrape --jsonl twitter-user username
for r in results:
res = json.load(r)
     print(res.content)
```

**Comment by Hamma111** [comment]
> if you use jupyter, use `!snscrape` to get results.
> 
> For example,
> 
> ```
> results  = !snscrape --jsonl twitter-user username
> for r in results:
> res = json.load(r)
>      print(res.content)
> ```

for `json.load` make sure to `import json` lib

**Comment by break404** [comment]
> ```python
>  i >= 49: 
> ```

Hello, thank you for writing such good code. I need to call it in a python script program, but I hope that the returned result is not only a url but a rich json, such as calling cli.py --jsonl directly It turned out to be that way. Can you help modify the code? Increase the ability to directly call and pass parameters such as time limit, json and other functions?

**Comment by JustAnotherArchivist** [comment]
As I mentioned already, it is not possible to pass those parameters to the API. The parameters only exist in the CLI.
And converting to JSON, as also already explained, is not currently supported outside of the CLI.

**Comment by MartinoMensio** [comment]
If you don't need to use your current `sys.argv` in your scripts, you could do the following (you could do a backup and restore them afterwards):

```python
import io
import json
import sys
import snscrape
import contextlib

# set all the arguments you want, that will be used by the scraper
sys.argv = ['snscrape', '--max-results', '10', '--jsonl', 'twitter-user', 'realDonaldTrump']



# you can use the context manager to redirect the output to a file
with open('trump.jsonl', 'a') as f:
    with contextlib.redirect_stdout(f):
        # run the scraper
        snscrape.cli.main()



# or if you want to use it directly in the program you can do the following
f = io.StringIO()
with contextlib.redirect_stdout(f):
    snscrape.cli.main()

s = f.getvalue()
# and then parse the string
tweets = [json.loads(el) for el in s.splitlines()]
```

**Comment by JustAnotherArchivist** [comment]
Be warned that I do not consider the CLI part of the public API, so this may break at any time.

Also, closing this issue since it's been answered multiple times by now.

**Comment by ihahawen** [comment]
> As I mentioned already, it is not possible to pass those parameters to the API. The parameters only exist in the CLI.
> And converting to JSON, as also already explained, is not currently supported outside of the CLI.

how can i catch the twitter_id,like this "https://twitter.com/LibertyCliff/status/1309144326417666051",i just want to get "1309144326417666051", i can use this for API

**Comment by JustAnotherArchivist** [comment]
It is now (bd53e729) possible to convert items returned by `get_items()` to a JSON string with `item.json()`.

**Comment by vistamou** [comment]
I want to call snscrape and pass parameters in my own python script running -> ` TwitterUserScraper` and passing also the date parameter (since="xxx"). Is that possible?

**Comment by JustAnotherArchivist** [comment]
> As I mentioned already, it is not possible to pass those parameters to the API. The parameters only exist in the CLI.

For Twitter and `since` specifically, you can use the `TwitterSearchScraper` with the search query `'from:username since:2020-01-31'` instead to let Twitter do the filtering. For other scrapers, you have to do the filtering or breaking in your own code.

**Comment by vistamou** [comment]
Thanks a lot!!!

**Comment by mateuszzbaraski** [comment]
Hi all, am using snscrape to research links between Twitter sentiments and violence during protests. For now I filter the downloaded tweets to only be english, however out of 10 000 daily tweets there are approximately 500 in english. Is it possible to pass an argument specyfing to scrap only english tweets?

**Comment by stealthOG** [comment]
how to specify language using the snscrape library
