### ISSUE TITLE
how to filter using _ - replyCount	_ - retweetCount	_ - likeCount	_ - quoteCount

### ISSUE THREAD

**Issue by wanghaisheng** [JustAnotherArchivist/snscrape#847]
Is there anyway to define quantity of these params to get a smaller json output
    print('scrapeing job:',f'snscrape --jsonl --progress --since {DATE_START} twitter-hashtag "{keyword}" > {JSON_FILENAME}.json')

**Comment by JustAnotherArchivist** [comment]
#302
