### ISSUE TITLE
How many results can we get while scrapping for some user's tweets?

### ISSUE THREAD

**Issue by Hamma111** [JustAnotherArchivist/snscrape#85]
I ran the script twice with a counter and got the results up to the limit of 3283. 

I am trying to scrape an account's tweets. How far can I actually go? Is there some specific limit to which I cant exceed?

**Comment by JustAnotherArchivist** [comment]
With the `twitter-user` scraper, you should get all of a user's own tweets, including replies but without retweets, without a limit, except when Twitter is broken (#4). With the `twitter-profile` scraper, you will get the ~3200 most recent tweets, including replies and retweets.

**Comment by Hamma111** [comment]
Thanks for reply. How do I get user's tweets with `twitter-user`. 
`snscrape twitter-user username` returns links to the tweets. Is there an argument I have to include in this command to return the the tweet content too? I tried `-h` command but didnt quite get/understand what I need. I am kinda new to this. Thanks.

**Comment by JustAnotherArchivist** [comment]
See 'Other noteworthy options' under 'Usage' in the README. You probably want `--jsonl` to get everything. Note that this option is only available in the current development version.

**Comment by JustAnotherArchivist** [comment]
@Hamma111 What's the reason for reopening?

**Comment by Hamma111** [comment]
Sorry had to reopen the issue.

I tried `snscrape --jsonl twitter-user username`. It increased the number of results returned by ~200 results i.e. it returned ~3400 tweets

**Comment by Hamma111** [comment]
UPDATE: I tried doing it for some more accounts and it worked fine for them. Could there be an issue why is it not collecting all the tweets of some users and doing it rightly for the others?

**Comment by Hamma111** [comment]
There is a subscripted total number of tweets made by the user at top of every profile below user's name. 

In all cases, the number of tweets returned by `snscrape --jsonl twitter-user username` returns the number of tweets approximately to the number of total tweets at top of profile.

But is is misbehaving in this one case. `snscrape` returns ~3400 tweets but actual total shows to be over 48k. Could there be a reason for the number mismatch?

**Comment by Hamma111** [comment]
I probably should open a new issue for this maybe?

**Comment by JustAnotherArchivist** [comment]
Sometimes Twitter's search is broken, as mentioned earlier (#4). A gross mismatch with the number on the profile page could also be due to the vast majority of a user's tweets being retweets, which aren't found by the search. Lastly, I've heard that deleted tweets still count toward the profile page total, though I haven't been able to verify that.
