### ISSUE TITLE
Mastodon scraper crashing

### ISSUE THREAD

**Issue by Ultimatesicko** [JustAnotherArchivist/snscrape#853]
Command:
`snscrape mastodon-profile @securityaffairs@infosec.exchange`
Output:
`yield from self._entries_to_items(soup.find('div', class_ = 'activity-stream').find_all('div', class_ = 'entry'), r.url)
AttributeError: 'NoneType' object has no attribute 'find_all'`

**Comment by JustAnotherArchivist** [comment]
#587
