### ISSUE TITLE
date with TwitterProfileScraper

### ISSUE THREAD

**Issue by ihabpalamino** [JustAnotherArchivist/snscrape#862]
since the Methode TwitterSearchScraper does not work anymore i tried twitterProfileScraper and its still working my question is "is it possible to use it for a period given to scrape "for example using it to scrape tweets since a date until a date with the TwitterProfileScraper?!!

**Comment by JustAnotherArchivist** [comment]
No, not directly. You will need to filter the results yourself.

**Comment by ihabpalamino** [comment]
> No, not directly. You will need to filter the results yourself.

so while scraping i think i may have tweets scraped in a repeated way !!is there any solution to avoid this?for example if the tweet already exist then no need to scrap it?

**Comment by ihabpalamino** [comment]
and the filter could be using code or just manually?

**Comment by JustAnotherArchivist** [comment]
Scraping profiles shouldn't return tweets repeatedly. If you scrape multiple times, then yes, you will obviously get duplicates. You might want to keep the largest tweet ID already seen and stop when you see any ID equal to or lower than that.

Of course this can be done in code. The `Tweet` objects returned by the scraper contain all information needed to decide whether to `break` the loop or not.
