### ISSUE TITLE
How to get a Twitter user's profile picture URL?

### ISSUE THREAD

**Issue by AlesyaSeliazniova30032012** [JustAnotherArchivist/snscrape#867]
Hi. Can I do a user search by username, without using user Id to find profile Image Url. Getting tweets from realDonaldTrump doesn't work right now, and I need to get a photo. Thanks

```python3
for user in sntwitter.TwitterUserScraper(username)._get_entity():
                print('user', user)
```

It doesn't work that way
warning: `'User' object is not iterable`

**Comment by JustAnotherArchivist** [comment]
Don't use `._get_entity()`. The leading underscore means it's private API. Use `.entity` instead

Looping makes no sense here. The entity is a single `User` object. I think you want this:

```python3
user = snscrape.modules.twitter.TwitterUserScraper(username).entity
print(user.profileImageUrl)
```
