### ISSUE TITLE
Improve exceptions on profile scraper when the user doesn't exist

### ISSUE THREAD

**Issue by umerkhan95** [JustAnotherArchivist/snscrape#869]
I got through the the error and found out that the ID is not available for scraping, I searched the ID on twitter and found the same as well that the account is not there currently. 

My question is that I could not found a way to pass the ScraperException Error:

```python3
for username in usernames["Twitter Account Name"]:
    query = username

    try:
        profile_scraper = sntwitter.TwitterProfileScraper(query)
        for tweet in profile_scraper.get_items():
            print(username)
            try:
                tweets.append([tweet.date, tweet.username, tweet.content, tweet.likeCount, tweet.retweetCount, tweet.replyCount, tweet.quoteCount])
            except AttributeError:
                # If the object is a tombstone, skip it
                continue
    except sntwitter.TwitterScraperException:
        print("Username not found")
        continue

# Convert list of tweets to Pandas DataFrame
result = pd.DataFrame(tweets, columns=["Date", "User", "Tweet", "Likes", "Retweets", "Replies", "QuoteCount"])
result.to_csv('scraped_tweets_3rd.csv', index=False)

# Print first 5 rows of DataFrame
print(result.head())
```

Bascially I cannot find a class of the error in which to relate it in the code so that it can pass it. Can you help me out on this one?

**Comment by zaferk19** [comment]
You should wrap you function like this:

try: 
     YOUR LOOP HERE
except Exception:
      break

**Comment by TheTechRobo** [comment]
@zaferk19 It's probably best to know what the issue is before you ignore it.

**Comment by JustAnotherArchivist** [comment]
Probably the entity retrieval should already raise an error instead of just (emitting a warning and) returning `None`. The code that raises the `Could not resolve username 'x' to ID` `ScraperException` doesn't actually know what the problem is; there are multiple things that could lead to the error.

**Comment by JustAnotherArchivist** [comment]
The immediate error in your code is that you need to catch `snscrape.base.ScraperException`; there is no such thing as a `TwitterScraperException`.
