### ISSUE TITLE
Lack of data in User objects inside Tweet.mentionedUsers list

### ISSUE THREAD

**Issue by mox8** [JustAnotherArchivist/snscrape#870]
### Describe the bug

Each of the `Tweet` objects with mentioned users in it keeps them as `User` objects in `mentionedUsers` list field. 
Currently `User` objects lack mostly all of the data, except for `username`, `displayname` and `id`

Example tweet: **https://twitter.com/MarioNawfal/status/1649998880296300544**

**not None fields now:**
`username`
`displayname`
`id`

**None fields now:**
`created`
`descriptionLinks`
`favouritesCount`
`followersCount`
`friendsCount`
`label`
`link`
`listedCount`
`location`
`mediaCount`
`profileBannerUrl`
`profileImageUrl`
`protected`
`rawDescription`
`renderedDescription`
`statusesCount`
`verified`

### How to reproduce

```python
from snscrape.modules import twitter as tw
from pprint import pprint

# https://twitter.com/MarioNawfal/status/1649998880296300544


tweet = list(tw.TwitterTweetScraper(tweetId=1649998880296300544).get_items())[0]
for user in tweet.mentionedUsers:
    print(f"\nusername = {user.username}")  # not None
    print(f"displayname = {user.displayname}")  # not None as well
    print(f"followersCount = {user.followersCount}")   # None
    pprint(user.__dict__)

```

### Expected behaviour

All the User object fields returned

### Operating system

MacOS Ventura 13.0.1 (22A400)

### Python version: output of `python3 --version`

3.11

### snscrape version: output of `snscrape --version`

0.6.2.20230320

### Scraper

TwitterProfileScraper, TwitterTweetScraper

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by JustAnotherArchivist** [comment]
This is intentional. Twitter does not return this data for mentioned users. Filling it in would require a separate request for each mentioned user on each tweet. That would destroy scrape performance.

When you need it, you can use the `TwitterProfileScraper`'s `entity` attribute to retrieve the full object:

```python3
user = snscrape.modules.twitter.TwitterProfileScraper(tweet.mentionedUsers[0].username).entity
```

This currently returns `None` if the user doesn't exist and on some other conditions, which will change soon; cf. #869.

**Comment by JustAnotherArchivist** [comment]
Also relevant: #408
