### ISSUE TITLE
RedditSearchScraper Attribute error

### ISSUE THREAD

**Issue by MykhailoYampolskyi** [JustAnotherArchivist/snscrape#871]
Hi, I've been using RedditSearchScraper and RedditSubredditScraper with Python.
I want to make a dataframe consisting only from 'body', 'url' etc.
My RedditSubredditScraper code is (and works fine):

```python3
import snscrape.modules.reddit as snreddit
attributes_container = []
scraper = snreddit.RedditSubredditScraper('worldnews')
for i, item in enumerate(scraper.get_items()):
    if i >= 10:
        break
    attributes_container.append([item.body, item.url, item.date, item.subreddit])
df = pd.DataFrame(attributes_container, columns=["body", "url", "date", "subreddit"])
```

However, it doesn't work with RedditSearchScraper and gives an error **AttributeError: 'function' object has no attribute 'body'** 
Why wouldn't it work?

**Also**, is there a way to kind of merge Search and Subreddit i.e. look for a keyword in subreddits? Many thanks.

**Comment by JustAnotherArchivist** [comment]
Only comments have a `body`, submissions don't. The Reddit scrapers (including the subreddit scraper) return both by default, so you need to either disable submissions or check what type of `item` you have (`snscrape.modules.reddit.Submission` or `snscrape.modules.reddit.Comment`).

Filtering by multiple conditions is currently not supported.

**Comment by JustAnotherArchivist** [comment]
I don't see how you get a `'function' object` with that code though. I'm getting an

    AttributeError: 'Submission' object has no attribute 'body'

as expected.

**Comment by MykhailoYampolskyi** [comment]
My bad, it indeed shows 'Submission'.
How can I disable submissions? Is it done with Python or CLI?

**Comment by JustAnotherArchivist** [comment]
The Reddit scrapers take optional arguments `submissions` and `comments`, both defaulting to `True`. To disable submissions, set the former to `False`:

```python3
snscrape.modules.reddit.RedditSubredditScraper('worldnews', submissions = False)
```

**Comment by MykhailoYampolskyi** [comment]
Thank you, it works.
