### ISSUE TITLE
Fixing searching problem

### ISSUE THREAD

**Issue by steevenakintilo** [JustAnotherArchivist/snscrape#872]
### Describe the feature

Real question why can't we just login and do the search scrapping?
I've been working on a code that use selenium and I just login via my twitter info and I can like rt and even comment a tweet, I can also search but the problem is I can only get the url of top tweet of the page.
Other than that If someone know how to get the url of all the tweet present on the page I could try helping you on your recent problem with twitter.

### Would this fix a problem you're experiencing? If so, specify.

Here is the code of what I've done
S is just a class I use  to login to with selenium
Even with the scroll down selenium always print the first tweet I don't know why 

class Scraper:
    wait_time = 5
    options = webdriver.ChromeOptions()
    #options.add_argument('headless')
    driver = webdriver.Chrome(executable_path="chromedriver", options=options)  # to open the chromedriver    
`
def test_test(S,url):
    a = "https://twitter.com/search?q=concours%20since%3A2023-04-18%20min_faves%3A20%20min_retweets%3A200%20lang%3Afr&src=typed_query&f=live"
    url = a
    down = 1
    c = []
    test = 3
    try:
        for i in range(test):
            S.driver.get(url)
            element = WebDriverWait(S.driver, 30).until(
            EC.presence_of_elements_located((By.CSS_SELECTOR, '[data-testid="tweetText"]')))
            
            print(element)
            time.sleep(10)
            elements.click()
            new_url = S.driver.current_url
            print(new_url)

            S.driver.back()
           for i in range(down):
               S.driver.execute_script("window.scrollBy(0, 550)")        
            down = down + 1
        time.sleep(100)

    except Exception as e:
        print(e)
        return ("fail")`

**Comment by TheTechRobo** [comment]
#270

**Comment by steevenakintilo** [comment]
> #270

Oh I see thanls for the info do you know how to use selenium?
