### ISSUE TITLE
How to scrape tweets since a date?

### ISSUE THREAD

**Issue by poojansheth** [JustAnotherArchivist/snscrape#88]
I am using the code below to scrape tweets for a search query but I would like to get tweets between two specified dates. How can I do so? Thanks. 

import snscrape.modules
import csv

tweets=snscrape.modules.twitter.TwitterSearchScraper(query='lochness')

with open('textfiles.csv', 'a', encoding='utf-8') as f:
    wr=csv.writer(f, lineterminator = '\n')
    for i in tweets.get_items():
        wr.writerow([i.content])

**Comment by poojansheth** [comment]
This worked-

tweets=snscrape.modules.twitter.TwitterSearchScraper('lochness since:2020-09-24')

**Comment by tiger-cpu** [comment]
Hello @poojansheth ,
Can you help me little bit on how to get this working?
I had downloaded  the code locally and having issues consuming it from my own main.py
How can I use this code as a library and invoke it from my program?
[ I 'm  getting all sorts of basic import errors. Guess, given I am new to python world, I am doing something terribly wrong]
Appreciate your help in advance.
Regards.
