### ISSUE TITLE
200 response, the library is working fine, but the output is 0 tweets

### ISSUE THREAD

**Issue by AlesyaSeliazniova30032012** [JustAnotherArchivist/snscrape#880]
Hi. I can't figure out what's going on. In the last hour of the next request, I do not receive a tweet and 2-5 pieces.
`tweets = sntwitter.TwitterSearchScraper(query).get_items()`
200 response, the library is working fine
In this connection, such a situation may arise. I run on ubuntu server. Thanks for the help.

**Comment by JustAnotherArchivist** [comment]
The search scraper should not be working at all currently. But in any case... Please file a complete bug report using [the template](https://github.com/JustAnotherArchivist/snscrape/issues/new?assignees=&labels=bug&template=bug_report.yml).
