### ISSUE TITLE
Snscrape tweets result less than it should be?

### ISSUE THREAD

**Issue by eriAliBaba** [JustAnotherArchivist/snscrape#886]
Thank you for updating snscrape so Twitter searches can run again.

I want to ask why the results obtained by snscrape, why for some search keywords the number of tweets obtained by snscrape is less than the results it should be?

For example, I used the keyword "Prabowo Subianto" from 2 or 3 days ago or tweet from past month, I only got hundreds of tweets, whereas if I used the Twitter V2 API with same keyword and same date range, I would get more results. when I search manually on Twitters pages I also got lots of tweets

*snscrape 0.6.2.20230321.dev13+g786815d
*Python 3.10.6

**Comment by JustAnotherArchivist** [comment]
It appears that the GraphQL API is quite unreliable, yeah. I noticed fewer results on random dates or date ranges, too. This is something that's broken on Twitter's side as far as I can tell.

**Comment by JustAnotherArchivist** [comment]
The underlying issue is not new: #468 #574 etc. But it's unfortunately noticeably more pronounced with the new endpoint.

**Comment by eriAliBaba** [comment]
> The underlying issue is not new: #468 #574 etc. But it's unfortunately noticeably more pronounced with the new endpoint.

thanks for the response

i also have more issue, for twitter account with gold check, json response user.verified detected as False 


example json from snscrape cli

`{"_type": "snscrape.modules.twitter.Tweet", "url": "https://twitter.com/detikcom/status/1656932232244924416", "date": "2023-05-12T08:00:03+00:00", "rawContent": "Cinta Laura diundang untuk menghadiri Cannes Film Festival 2023 yang digelar pada 16-27 Mei mendatang di Prancis. Selain Cinta Laura, Putri Marino juga turut diundang. https://t.co/Tll6GVaFAn", "renderedContent": "Cinta Laura diundang untuk menghadiri Cannes Film Festival 2023 yang digelar pada 16-27 Mei mendatang di Prancis. Selain Cinta Laura, Putri Marino juga turut diundang. https://t.co/Tll6GVaFAn", "id": 1656932232244924416, "user": {"_type": "snscrape.modules.twitter.User", "username": "detikcom", "id": 69183155, "displayname": "detikcom", "rawDescription": "Official Twitter of https://t.co/jtXZ3Wcfhf. redaksi@https://t.co/jtXZ3Wuovn | promosi@https://t.co/jtXZ3Wuovn | Android: https://t.co/l5tQVBgqbD iPhone: https://t.co/NleJXySGkT", "renderedDescription": "Official Twitter of detik.com. redaksi@https://t.co/jtXZ3Wuovn | promosi@https://t.co/jtXZ3Wuovn | Android: detik.com/android iPhone: detik.com/iphone", "descriptionLinks": [{"_type": "snscrape.modules.twitter.TextLink", "text": "detik.com", "url": "http://detik.com", "tcourl": "https://t.co/jtXZ3Wcfhf", "indices": [20, 43]}, {"_type": "snscrape.modules.twitter.TextLink", "text": "detik.com/android", "url": "http://detik.com/android", "tcourl": "https://t.co/l5tQVBgqbD", "indices": [122, 145]}, {"_type": "snscrape.modules.twitter.TextLink", "text": "detik.com/iphone", "url": "http://detik.com/iphone", "tcourl": "https://t.co/NleJXySGkT", "indices": [154, 177]}], "verified": false, "created": "2009-08-27T03:03:05+00:00", "followersCount": 20358100, "friendsCount": 37, "statusesCount": 2217339, "favouritesCount": 1592, "listedCount": 13127, "mediaCount": 417035, "location": "Jakarta, Indonesia", "protected": null, "link": {"_type": "snscrape.modules.twitter.TextLink", "text": "detik.com", "url": "http://www.detik.com", "tcourl": "https://t.co/qldGGYWfHu", "indices": [0, 23]}, "profileImageUrl": "https://pbs.twimg.com/profile_images/1605081002795098112/LiGjnYaA_normal.jpg", "profileBannerUrl": "https://pbs.twimg.com/profile_banners/69183155/1649218274", "label": null, "description": "Official Twitter of detik.com. redaksi@https://t.co/jtXZ3Wuovn | promosi@https://t.co/jtXZ3Wuovn | Android: detik.com/android iPhone: detik.com/iphone", "descriptionUrls": [{"_type": "snscrape.modules.twitter.TextLink", "text": "detik.com", "url": "http://detik.com", "tcourl": "https://t.co/jtXZ3Wcfhf", "indices": [20, 43]}, {"_type": "snscrape.modules.twitter.TextLink", "text": "detik.com/android", "url": "http://detik.com/android", "tcourl": "https://t.co/l5tQVBgqbD", "indices": [122, 145]}, {"_type": "snscrape.modules.twitter.TextLink", "text": "detik.com/iphone", "url": "http://detik.com/iphone", "tcourl": "https://t.co/NleJXySGkT", "indices": [154, 177]}], "linkTcourl": "https://t.co/qldGGYWfHu", "linkUrl": "http://www.detik.com", "url": "https://twitter.com/detikcom"}, "replyCount": 0, "retweetCount": 0, "likeCount": 0, "quoteCount": 0, "conversationId": 1656932232244924416, "lang": "in", "source": null, "sourceUrl": null, "sourceLabel": null, "links": null, "media": [{"_type": "snscrape.modules.twitter.Video", "thumbnailUrl": "https://pbs.twimg.com/ext_tw_video_thumb/1656921724666118144/pu/img/4nSAUMpNBa9JxLwd.jpg", "variants": [{"_type": "snscrape.modules.twitter.VideoVariant", "url": "https://video.twimg.com/ext_tw_video/1656921724666118144/pu/vid/480x270/1ZEdtxYUjJ1d1s2x.mp4?tag=12", "contentType": "video/mp4", "bitrate": 256000}, {"_type": "snscrape.modules.twitter.VideoVariant", "url": "https://video.twimg.com/ext_tw_video/1656921724666118144/pu/pl/LqqHhWGvnx4Hxd_t.m3u8?tag=12&container=fmp4", "contentType": "application/x-mpegURL", "bitrate": null}, {"_type": "snscrape.modules.twitter.VideoVariant", "url": "https://video.twimg.com/ext_tw_video/1656921724666118144/pu/vid/640x360/GvJNhy8OaWOFpv6s.mp4?tag=12", "contentType": "video/mp4", "bitrate": 832000}, {"_type": "snscrape.modules.twitter.VideoVariant", "url": "https://video.twimg.com/ext_tw_video/1656921724666118144/pu/vid/1280x720/rfb78WroZusC-Bv8.mp4?tag=12", "contentType": "video/mp4", "bitrate": 2176000}], "duration": 67.768, "views": 0, "altText": null}], "retweetedTweet": null, "quotedTweet": null, "inReplyToTweetId": null, "inReplyToUser": null, "mentionedUsers": null, "coordinates": null, "place": null, "hashtags": null, "cashtags": null, "card": null, "viewCount": null, "vibe": null, "content": "Cinta Laura diundang untuk menghadiri Cannes Film Festival 2023 yang digelar pada 16-27 Mei mendatang di Prancis. Selain Cinta Laura, Putri Marino juga turut diundang. https://t.co/Tll6GVaFAn", "outlinks": [], "outlinksss": "", "tcooutlinks": [], "tcooutlinksss": "", "username": "detikcom"}`

is there any way to tell if account have different verified status? (gold check and blue check)
`

**Comment by JustAnotherArchivist** [comment]
No, and there's already an open issue about that: #822
