### ISSUE TITLE
Is there a way to get the retweets when fetching the search and profile data?

### ISSUE THREAD

**Issue by carlosdcuba1** [JustAnotherArchivist/snscrape#887]
With the previous version when I did the searches this worked for me "filter:retweets include:nativeretweets"

The recovery does not return these types of messages. Greetings, thank you very much for your contributions and congratulations on the excellent work you do.

**Comment by JustAnotherArchivist** [comment]
Yeah, I can confirm that. It appears that the new search endpoint does not support searching for retweets, even those from the last few days. The profile scraper (twitter-profile, not twitter-user) still has them.
