### ISSUE TITLE
Stopping after 20 empty pages

### ISSUE THREAD

**Issue by AhmadGhachim** [JustAnotherArchivist/snscrape#888]
### Describe the bug

I am trying to scrape the Tweets of a specific Twitter user

### How to reproduce

import snscrape.modules.twitter as sntwitter
import csv
username = 'user'
with open(f'{username}.csv', 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['id', 'date', 'content', 'retweets', 'likes', 'comments'])

    maxTweets = 1000
    for i, tweet in enumerate(sntwitter.TwitterUserScraper(username).get_items()):
        if i > maxTweets:
            break
        # Write the data to the file
        writer.writerow([tweet.id, tweet.date, tweet.content, tweet.retweetCount, tweet.likeCount, tweet.replyCount])

### Expected behaviour

A list of all tweets into a .csv file

### Operating system

Windows 11

### Python version: output of `python3 --version`

Python 3.11.3

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev13+g786815d

### Scraper

TwitterUserScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Backtrace

Stopping after 20 empty pages

Process finished with exit code 0

**Comment by JustAnotherArchivist** [comment]
As the warning suggests, this happens when Twitter returns no results on many pages in a row. It appears that the new API endpoint is very bad at this; I see it happen on every search. But stopping on the first empty page is also incorrect as it can miss results.

If desired, you can tweak how many empty pages are tolerated with the `--max-empty-pages` option on the CLI or the `maxEmptyPages` argument to any of the search-based scraper classes in Python.

**Comment by muenze8** [comment]
I am facing the same issue with the following code:

`for q in query:
        for i,tweet in enumerate(sntwitter.TwitterSearchScraper(q + f' since:{date}').get_items()):
            if i>maxTweets:
                break
            allTweets.append([
                tweet.user.displayname, 
                tweet.user.username,  
                tweet.rawContent,
                tweet.date,
                tweet.url,
                tweet.id
                ])`

**Comment by jlkk971** [comment]
Hi, I set the maxEmptyPages=2000 and got the same error (Stopping after 2000 empty pages). Here my code:

`from snscrape.modules import twitter
import pandas as pd

scraper=twitter.TwitterSearchScraper('bitcoin', maxEmptyPages=2000)
counter=0


for tweet in scraper.get_items():
        counter=counter+1
        print(tweet)
        print(counter)`

**Comment by TheTechRobo** [comment]
There's nothing that snscrape can do about that. You probably won't be able to get any more results.

**Comment by JustAnotherArchivist** [comment]
The default value of 20 is quite arbitrary, but because multiple empty pages appear to be rare, results after 20 of them should be extremely unlikely. There's no actual data basis for this value, but it's large enough to be safe without wasting too many requests. Increasing it beyond 20 is unlikely to ever be useful. (But if you do find a case where it works, please file an issue about that!)

**Comment by stu247** [comment]
I would like to be able to handle this situation via an exception.  Is it possible for snscrape to raise an exception?

**Comment by JustAnotherArchivist** [comment]
@stu247 Every search ends like this (unless you stop looping before it happens), so an exception is not appropriate.

**Comment by Reimao** [comment]
> @stu247 Every search ends like this (unless you stop looping before it happens), so an exception is not appropriate.

How can I stop looping before it happens? Is there a way to know the current number of empty pages searched in each iteration?

**Comment by JustAnotherArchivist** [comment]
There is not. By 'stop looping before it happens', I meant if you e.g. have a limit on the number of results and exceed that before hitting the empty pages.

**Comment by jlkk971** [comment]
I am trying to download 6 months of tweets using the TwitterSearchScraper method and 'bitcoin' as keyword, maxEmptyPages=20. I get the 'stopping after 20 pages' after a few thousands of tweets pulled and I currently don't know how to go on. @JustAnotherArchivist do you have any suggestion?

**Comment by JustAnotherArchivist** [comment]
You will probably have to change your search query. You can try adding an `until` filter for example. It may require some experimentation to find something that works. This is squarely on Twitter's side.
