### ISSUE TITLE
Scraping twitter in parallel

### ISSUE THREAD

**Issue by bilgd** [JustAnotherArchivist/snscrape#890]
Hi, I was wondering if there's any guidance on parallelization since the update to the GraphQL API. I saw previous guidance in #307 and #385, and wanted to know if this still holds.

**Comment by JustAnotherArchivist** [comment]
Nothing has changed in this regard. Use the CLI for best results as it has better token management.

**Comment by bilgd** [comment]
Thank you very much for the quick reply and your hard work in maintaining the package.
