### ISSUE TITLE
Nothing is returned for some users that have tweets

### ISSUE THREAD

**Issue by awchen** [JustAnotherArchivist/snscrape#891]
### Describe the bug

Like #888 and #889, I am trying to retrieve the tweets of a specific user. However, for some users with recent tweets, I am not able to retrieve any data, despite 

### How to reproduce

```python
import snscrape.modules.twitter as sntwitter

for tweet in sntwitter.TwitterUserScraper("<username>", maxEmptyPages=1000).get_items():
    print(tweet)
```

### Expected behaviour

For many users, the scraper works perfectly.

For some other users, there are no results, even with an extremely large parameter for `maxEmptyPages`. It appears that these tend to be users with few followers (say, less than 100).

Logs say `Stopping after 1000 empty pages`

### Operating system

macOS 12.6.1

### Python version: output of `python3 --version`

3.11.3

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev13+g786815d

### Scraper

twitter-user

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Additional context

Happy to help with a fix for this but would need a quick run-down of the observed behavior for the new Twitter API. 

Is there any intuition for why the graphql result is empty for some users?

Given that most of the failure cases are smaller users with fewer followers, I won't be adding any failure case usernames here. But happy to share/correspond privately — let me know if there's a development Discord or something of the sort.

**Comment by JustAnotherArchivist** [comment]
This is essentially a new flavour of #4. I have no idea yet when/how it breaks on the new API exactly, but basically, their search has always had this problem.

**Comment by withkelvin** [comment]
So, searching for tweets is technically still not stable for now right?

**Comment by muenze8** [comment]
I am facing the same issue with the following code:

```
for q in query:
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(q + f' since:{date}').get_items()):
        if i>maxTweets:
            break
        allTweets.append([
            tweet.user.displayname, 
            tweet.user.username,  
            tweet.rawContent,
            tweet.date,
            tweet.url,
            tweet.id
            ])
```

**Comment by JustAnotherArchivist** [comment]
It works as well as Twitter permits. Their entire software stack is falling apart more and more by the day, so this is hardly surprising.

**Comment by muenze8** [comment]
> It works as well as Twitter permits. Their entire software stack is falling apart more and more by the day, so this is hardly surprising.

Did you check Tweepy's package latest changes?
I am not sure how they managed to overcome the latest Twitter changes, because it also got affected by the changes. However, I am now testing their paginator functionality, and it brings me tweets for up to 1 week. The only issue is that (since it uses Twitter API) it has the 1 week limit.

```
for q in query[1:]:
        paginator = tweepy.Paginator(client.search_recent_tweets, query=q,
                                  tweet_fields=['context_annotations', 'created_at','author_id'],
                                  expansions=['author_id'],
                                  max_results=100)
```

**Comment by JustAnotherArchivist** [comment]
@muenze8 snscrape does not use the official/public API, so comparisons with Tweepy are largely moot.

**Comment by withkelvin** [comment]
> It works as well as Twitter permits. Their entire software stack is falling apart more and more by the day, so this is hardly surprising.

I presume this behaviour is not just when retrieving the tweets of a specific user but also when retrieving tweets using a keyword?

**Comment by JustAnotherArchivist** [comment]
@withkelvin Yes, most likely.
