### ISSUE TITLE
snscrape twitter python  non-200 status code

### ISSUE THREAD

**Issue by DK2212** [JustAnotherArchivist/snscrape#896]
### Describe the bug

Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%23opportunity&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%23opportunity&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

### How to reproduce

import snscrape.modules.twitter as sntwitter
import pandas as pd

tweets = []

for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query = "#opportunity").get_items()):
    if i>100:
        break
    tweets.append([tweet.user.username, tweet.date, tweet.likeCount, tweet.retweetCount, tweet.replyCount, tweet.lang,
                   tweet.sourceLabel, tweet.content])

### Expected behaviour

non-200 status code

### Operating system

window 11

### Python version: output of `python3 --version`

Python 3.9.10

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev13+g786815d

### Scraper

sntwitter.TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
> snscrape 0.6.2.20230321.dev13+g786815d

is not what you are using given that error. Cf. #884

**Comment by DK2212** [comment]
![image](https://github.com/JustAnotherArchivist/snscrape/assets/53008952/be18e2fa-9ab6-41b6-b5ee-edc858249d13)

**Comment by DK2212** [comment]
resolved. Thanks @JustAnotherArchivist
