### ISSUE TITLE
Twitter responded with an error: DependencyError: Dependency: Unspecified

### ISSUE THREAD

**Issue by steevenakintilo** [JustAnotherArchivist/snscrape#897]
### Describe the bug

Hello I'm using sncrape to lookup for a lot of tweet and old one but since GraphAPI when I try to lookup for tweet it work well like 80% of the time and 20% of the time I got this error I don't know why (see on backtrace)

### How to reproduce

The bug can happen with this

```python3
def search_tweet(text):
            for i,tweet in enumerate(sntwitter.TwitterSearchScraper(text).get_items()):
                  print(tweet.id)
```

### Expected behaviour

The code should print the id of the tweets but it doesn't

### Operating system

Fedora 36

### Python version: output of `python3 --version`

Python 3.11.0

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev13+g786815d

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Backtrace

```
Error Twitter responded with an error: DependencyError: Dependency: Unspecified
Traceback (most recent call last):
  File "/home/asteeven/Python/CacaTwitter/get_tweet.py", line 242, in search_giveaway
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(text).get_items()):
  File "/home/asteeven/.asdf/installs/python/3.11.0/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 1704, in get_items
    for obj in self._iter_api_data('https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline', _TwitterAPIType.GRAPHQL, params, paginationParams, cursor = self._cursor, instructionsPath = ['data', 'search_by_raw_query', 'search_timeline', 'timeline', 'instructions']):
  File "/home/asteeven/.asdf/installs/python/3.11.0/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 812, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams, instructionsPath = instructionsPath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asteeven/.asdf/installs/python/3.11.0/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 781, in _get_api_data
    raise snscrape.base.ScraperException(msg)
snscrape.base.ScraperException: Twitter responded with an error: DependencyError: Dependency: Unspecified
```

**Comment by TheTechRobo** [comment]
What search query? Searches work fine on my end.

**Comment by steevenakintilo** [comment]
I do search like that:
for search_word in d.word_to_search:
            text = search_word + ' lang:fr'
            for i,tweet in enumerate(sntwitter.TwitterSearchScraper(text).get_items()):
d.word_to_search is a list of search query but it's random word

**Comment by JustAnotherArchivist** [comment]
I've seen that error as well. This is a bug on Twitter's side. The only way to avoid it is to use a different search query.

**Comment by steevenakintilo** [comment]
Ok thanks but the "funny" things is that I've tried the exact keywoard on my rasberry pi and windows pc and it seem to work but as you said it may work when "twitter wants to work" thanks anyway for the answer.
