### ISSUE TITLE
Twitter top search warning: Skipping unrecognised entry ID: 'toptabsrpusermodule-1659138277787041792'

### ISSUE THREAD

**Issue by toptierprojections** [JustAnotherArchivist/snscrape#904]
### Describe the bug

When a try to scrape some data from twitter it appears this error in the console and the search never stops:
Skipping unrecognised entry ID: 'toptabsrpusermodule-1659138277787041792'

I also notice that when it worked the returned tweets are something like the 5% of the total.

I attach my simple code in case there is an error from my side

### How to reproduce

```
import snscrape.modules.twitter as sntwitter
import pandas as pd 

mode_param = sntwitter.TwitterSearchScraperMode.TOP


query = "(#a random hashtag) until:2023-10-01 since:2023-01-01"
limit = 20
tweets = [];
for tweet in sntwitter.TwitterSearchScraper(query, mode = mode_param, maxEmptyPages=1000).get_items():
        
       #if len (tweets) == limit:
       #     break
       #else:
       
           tw={}
           tw['username']= tweet.user.username
     
       
           tweets.append(tw)
        
pd.DataFrame(tweets).to_csv('Test.csv') 
```

### Expected behaviour

A csv which contains all the extracted tweets

### Operating system

Windows10

### Python version: output of `python3 --version`

Python 3.10

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev13+g786815d

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
The top search has always only returned a small number of results, even before the API change. After all, only a small number of all matching tweets are 'top' tweets (by whatever measures Twitter uses for ranking).
And the scrape will eventually finish; you just chose to increase the number of empty pages to a ridiculously large number, so it will take a very long time.

This leaves the warning about the `toptabsrpusermodule` entry. Apparently Twitter has started returning some users on timeline searches. The warning is harmless, but I'll suppress it.

**Comment by toptierprojections** [comment]
Thank you for the clear explanation!
My bad for the high number of empty pages but  if TwitterSearchScraper returns small number of tweets, which one should I use for that kind of query? 

Thank you

**Comment by chein01** [comment]
Sorry, I have a question: 
I crawl tweets of random account for 30 days. Use this format: f"({key}) until:{until} since:{since}".
But now I can get only data newest 1 day. 
Example: I query until 22/5/2023 - 21/4/2023. But the result is only 22/5 and return message "Stopping after 20 empty pages". it doesn't work like before.
Is there any problem with my code with the new update snscrape?
How can I fix that? Thank you so much.

**Comment by JustAnotherArchivist** [comment]
Use the latest search, not the top search, if you want to get all results. It's the default if you don't specify a `mode`.

**Comment by toptierprojections** [comment]
Thank you @JustAnotherArchivist  for the answer.
Unfortunately it does not work. It returns only 6 tweets if I put a range of 3 months for example. I don't know how to fix it. Before the API change, I always had a lot of tweets

**Comment by chein01** [comment]
> Use the latest search, not the top search, if you want to get all results. It's the default if you don't specify a `mode`.

I see 3 statuses: LIVE, TOP, USER. When I try to use LIVE, its return result from since to until, but it's only 30 tweets while TOP returns 130 tweets in only 1 day. 
I think I got the same problem with this thread.
