### ISSUE TITLE
pip3.10 installs snscrape incorrectly from git

### ISSUE THREAD

**Issue by FlyingWolFox** [JustAnotherArchivist/snscrape#905]
### Describe the bug

When trying to install snscrape from git with pip3.10, the package name is UNKNOWN and sncrape is nowhere to be found:
```
$ pip3.10 install git+https://github.com/JustAnotherArchivist/snscrape.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to /tmp/pip-req-build-fu0bprmn
  Running command git clone --filter=blob:none --quiet https://github.com/JustAnotherArchivist/snscrape.git /tmp/pip-req-build-fu0bprmn
  Resolved https://github.com/JustAnotherArchivist/snscrape.git to commit 786815dd05681e2421cd03aa9acf5ab5c773bce9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.6.2.20230321.dev13+g786815d-py3-none-any.whl size=13561 sha256=2c4207b1e4077a30b76c2a489b3b2ca81223f5b48586b24c4b6d04d8d2b91814
  Stored in directory: /tmp/pip-ephem-wheel-cache-toscz8ls/wheels/05/e9/f7/57056e7c7e44b1feed932fa49fdec9d706c4f563e37160ab74
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.6.2.20230321.dev13+g786815d

$ snscrape
snscrape: command not found

$python3.10 -c 'import snscrape'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'snscrape'

```

It works fine with installation from Pypi or in another python version:
```
$ pip3.10 install snscrape
Defaulting to user installation because normal site-packages is not writeable
Collecting snscrape
  Using cached snscrape-0.6.2.20230320-py3-none-any.whl (71 kB)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from snscrape) (4.10.0)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from snscrape) (4.8.0)
Requirement already satisfied: filelock in /usr/lib/python3/dist-packages (from snscrape) (3.6.0)
Requirement already satisfied: requests[socks] in /usr/lib/python3/dist-packages (from snscrape) (2.25.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/lib/python3/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.6.2.20230320

$ snscrape
usage: snscrape [-h] [--version] [--citation] [-v] [--dump-locals] [--retry N] [-n N] [-f FORMAT | --jsonl] [--with-entity] [--since DATETIME] [--progress] SCRAPER ...
snscrape: error: the following arguments are required: SCRAPER
```

```
$ pip3.9 install git+https://github.com/JustAnotherArchivist/snscrape.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to /tmp/pip-req-build-vgzl4urf
  Running command git clone --filter=blob:none --quiet https://github.com/JustAnotherArchivist/snscrape.git /tmp/pip-req-build-vgzl4urf
  Resolved https://github.com/JustAnotherArchivist/snscrape.git to commit 786815dd05681e2421cd03aa9acf5ab5c773bce9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests[socks] in /usr/lib/python3/dist-packages (from snscrape==0.6.2.20230321.dev13+g786815d) (2.25.1)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from snscrape==0.6.2.20230321.dev13+g786815d) (4.8.0)
Requirement already satisfied: beautifulsoup4 in /home/flyingwolfox/.local/lib/python3.9/site-packages (from snscrape==0.6.2.20230321.dev13+g786815d) (4.11.1)
Requirement already satisfied: filelock in /home/flyingwolfox/.local/lib/python3.9/site-packages (from snscrape==0.6.2.20230321.dev13+g786815d) (3.7.1)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->snscrape==0.6.2.20230321.dev13+g786815d) (2.3.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/lib/python3/dist-packages (from requests[socks]->snscrape==0.6.2.20230321.dev13+g786815d) (1.7.1)
Building wheels for collected packages: snscrape
  Building wheel for snscrape (pyproject.toml) ... done
  Created wheel for snscrape: filename=snscrape-0.6.2.20230321.dev13+g786815d-py3-none-any.whl size=73302 sha256=a9612105bc30df48f90ed5407e6b8f8e98684d975c0e8c2aebdab658153f17cd
  Stored in directory: /tmp/pip-ephem-wheel-cache-ujvx7fba/wheels/1a/ba/e2/39fa3a11802c4a622f2efc8be3f5ff854481051d0b4c95c1fd
Successfully built snscrape
Installing collected packages: snscrape
Successfully installed snscrape-0.6.2.20230321.dev13+g786815d

$ snscrape
usage: snscrape [-h] [--version] [--citation] [-v] [--dump-locals] [--retry N] [-n N] [-f FORMAT | --jsonl] [--with-entity] [--since DATETIME] [--progress] SCRAPER ...
snscrape: error: the following arguments are required: SCRAPER
```

### How to reproduce

Install snscrape from git with pip3.10 (or `python3.10 -m pip`):
`$ pip3.10 install git+https://github.com/JustAnotherArchivist/snscrape.git`

### Expected behaviour

Install like with python 3.9/3.8, with being able to call snscrape from terminal or import as a module

### Operating system

Linux Mint 21.1

### Python version: output of `python3 --version`

Python 3.10.6

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev13+g786815d (installed with python3.9)

### Scraper

<not applicable>

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

### Additional context

Files on site-packages (~/.local/lib/python3.10/site-packages/UNKNOWN-0.6.2.20230321.dev13+g786815d.dist-info):
[UNKNOWN-0.6.2.20230321.dev13+g786815d.dist-info.tar.gz](https://github.com/JustAnotherArchivist/snscrape/files/11511695/UNKNOWN-0.6.2.20230321.dev13%2Bg786815d.dist-info.tar.gz)

**Comment by eriAliBaba** [comment]
i also run problem when trying to install snscrape dev version on ubuntu vps, but solved with upgrading pip and install wheel

```
pip3 install --upgrade pip
pip3 install wheel
```
next install snscrape dev version

maybe you can try that

**Comment by FlyingWolFox** [comment]
That fixed it. It's installing correctly now. Recent system upgrade installed an old pip with the new python3.10 package. Thank you @eriAliBaba 

So it was a pip problem, sorry for that. I'll be closing the issue

**Comment by JustAnotherArchivist** [comment]
This isn't entirely surprising since snscrape uses the latest packaging methods. I'm still curious which pip version you had which couldn't handle it though.

**Comment by FlyingWolFox** [comment]
It was 22.0.2 iirc, the default with python3.10 when Linux Mint updated to 21.1 (based on Jammy)

python 3.8 and 3.9's pip were up to date, as these python versions were the only ones available on Linux Mint 20.3 (Focal)

**Comment by JustAnotherArchivist** [comment]
Huh, that's odd. I know it works fine with various pip 21.x versions, and 22.x had no backwards-incompatible changes, so it should work there. Sounds like either a regression or something in a distro patch gone wrong. (A lot of distributions patch pip in a variety of ways, sometimes introducing new bugs.)

**Comment by FlyingWolFox** [comment]
Searched it up a little, it looks like a problem with jammy setuptools, not pip

https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/2018288 (reported 2023-05-02):
>Note how the package ends up called "unknown". This is a known problem with older setuptools versions

https://github.com/pypa/setuptools/issues/3269 (reported 2022-04-15)
>This issue is occurring on Jammy because pip is unable to get an accurate list of system package directories to remove from its temporary build environment's sys.path. As a result, when the temporary build env's site/sitecustomize.py script runs /usr/lib/python3/dist-packages is left at the end of sys.path, before the overlay and normal paths are appended, thus placing it before those dirs in the search path. This means Jammy's debian packaged setuptools (at version 59) is found and loaded ahead of whatever version the pyproject.toml requested. That version does not support PEP621 and is unable to extract name and version metadata, resulting in UNKNOWN-0.0.0.

>This means this is a distro configuration/packaging issue, but I'm posting this comment on a closed bug because this bug report comes up as the top result when googling for this issue.

There's a whole repo to show this problem: https://github.com/nschloe/setuptools-UNKNOWN-bug

**Comment by JustAnotherArchivist** [comment]
Ah, interesting, and yeah, that seems to be exactly what's going on here. If I understand it correctly, it is an issue with pip though, not setuptools; snscrape's package metadata already specifies that setuptools 61 or higher is required (due to PEP 621), but an older version gets loaded from the system packages instead. Upgrading to pip 22.3 or higher appears to be the fix (https://github.com/pypa/pip/pull/11466).

**Comment by FlyingWolFox** [comment]
Yeah, it's pip. It's on the setuptools issue too, I focused on the ubuntu bug report and missed it:
>This issue is occurring on Jammy because pip is unable to get an accurate list of system package directories to remove from its temporary build environment's sys.path

Exactly like what you said
