### ISSUE TITLE
Get Parent Tweet Contents

### ISSUE THREAD

**Issue by inferno46n2** [JustAnotherArchivist/snscrape#906]
### Describe the feature

Would it be possible to implement a way to get the content of a parent tweet in which an account is mentioned? Example: @UserA tweets "hello world". @UserB mentions @UserC in a reply. Retrieve the contents of @userA's tweet. 'enhancement'

### Did you consider other alternatives?

The only alternative I know of is the Twitter API which is a paid endpoint.

**Comment by JustAnotherArchivist** [comment]
There are several options for this:

* Each tweet object has an `inReplyToTweetId` field. You can feed it to the `TwitterTweetScraper` to retrieve the parent tweet directly.
* You can use the tweet scraper in scroll mode with userb's tweet ID. This yields all ancestors and some of the replies. The field above lets you determine which is the parent.
* Every tweet also has a `conversationId`, which happens to be the ID of the initial tweet in the thread; you can use that with either tweet or search scraper to retrieve the full thread if desired. For large threads, with the tweet scraper, you might need recursive mode (slow), and the search may be unreliable.

**Comment by inferno46n2** [comment]
Thank you!
