### ISSUE TITLE
twitter is scraping tweet links instead of the actual tweets

### ISSUE THREAD

**Issue by arceuss** [JustAnotherArchivist/snscrape#91]
im trying to scrape someones tweets for ai but its just giving me links

**Comment by hkim2636** [comment]
Did you tried out --jsonl option? it will give you content of tweets.
`snscrape --jsonl --max-results 100 twitter-hashtag archiveteam`

**Comment by arceuss** [comment]
does it do tweets of a specific user

**Comment by arceuss** [comment]
also i tried but it just says its not a valid arguement

**Comment by JustAnotherArchivist** [comment]
`--jsonl` only exists in the current development version. You can also use `--format '{content}'` on the release version (or the dev one), but be aware that tweets can contain line breaks, so one line in the output will not necessarily be one tweet.

And yes, those options are independent of the scraper, so you can use them with `twitter-user` as well. (The available fields for `--format` do depend on the social network though.)

**Comment by mvitha** [comment]
got it to run - 

installed the development version using: pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git

ran from command line:
snscrape --jsonl --max-results 10 twitter-user textfiles > text_files_test_10.json

then in py script or jupyter notebook script 

import json
import pandas

table = []
with open('text_files_test_10.json', 'r') as f:
    for line in f:
        table.append(json.loads(line))

pd.DataFrame.from_records(table).to_csv('text_files_test_10.csv')

thanks this is awesome!

**Comment by arceuss** [comment]
![image](https://user-images.githubusercontent.com/28229451/94486226-535c0e80-019c-11eb-9dc8-13962b9767df.png)
everything looks like this tho
i dont know how to train this with ai lol

**Comment by arceuss** [comment]
![image](https://user-images.githubusercontent.com/28229451/94486407-9e762180-019c-11eb-8ad6-5deaa5f8186d.png)
oh

**Comment by sunyoid** [comment]
> got it to run -
> 
> installed the development version using: pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git
> 
> ran from command line:
> snscrape --jsonl --max-results 10 twitter-user textfiles > text_files_test_10.json
> 
> then in py script or jupyter notebook script
> 
> import json
> import pandas
> 
> table = []
> with open('text_files_test_10.json', 'r') as f:
> for line in f:
> table.append(json.loads(line))
> 
> pd.DataFrame.from_records(table).to_csv('text_files_test_10.csv')
> 
> thanks this is awesome!

for those having an error like `name pd is not defined`  use `import pandas as pd`
