### ISSUE TITLE
TwitterSearchScraper not working with conversation_id 

### ISSUE THREAD

**Issue by UmarDabhoiwala** [JustAnotherArchivist/snscrape#912]
### Describe the bug

I see a ScraperException: Twitter responded with an error: BadRequestError: BadRequest: SearchQueryParsingException(ERROR_NONCLOSE_FORM), when trying to get tweets by conversation id using TwitterSearchScraper. Was working just yesterday don't know what changed

### How to reproduce

```python3
def get_list_of_tweets(tweet_id, limit=20):
    list_of_tweets = []

    for i, tweet in enumerate(
        sntwitter.TwitterSearchScraper(
            f"conversation_id:{tweet_id} (filter:safe OR -filter:safe)", maxEmptyPages=3
        ).get_items()
    ):
        # Have limit so that we don't spend too long
        if i > limit:
            break

        tweet_dict = get_tweet_from_id(tweet.id)
        list_of_tweets.append(tweet_dict)

    return list_of_tweets
```

### Expected behaviour

Return a list of tweets which have the specified conversation id 

### Operating system

Fedora Linux 37

### Python version: output of `python3 --version`

3.11.3

### snscrape version: output of `snscrape --version`

0.6.2.20230321

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Log output

```
ScraperException                          Traceback (most recent call last)
Cell In[42], line 17
     13         list_of_tweets.append(tweet_dict)
     15     return list_of_tweets
---> 17 get_list_of_tweets(1660902664262266881)

Cell In[42], line 5, in get_list_of_tweets(tweet_id, limit)
      2 def get_list_of_tweets(tweet_id, limit=20):
      3     list_of_tweets = []
----> 5     for i, tweet in enumerate(
      6         sntwitter.TwitterSearchScraper(f"conversation_id:{tweet_id} (filter:safe OR -filter:safe)", maxEmptyPages=1, top = True).get_items()
      7     ):
      8         # Have limit so that we don't spend too long
      9         if i > limit:
     10             break

File [~/.local/lib/python3.11/site-packages/snscrape/modules/twitter.py:1704](https://file+.vscode-resource.vscode-cdn.net/home/u/Documents/twitterThing/~/.local/lib/python3.11/site-packages/snscrape/modules/twitter.py:1704), in TwitterSearchScraper.get_items(self)
   1701 params = {'variables': variables, 'features': features}
   1702 paginationParams = {'variables': paginationVariables, 'features': features}
-> 1704 for obj in self._iter_api_data('https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline', _TwitterAPIType.GRAPHQL, params, paginationParams, cursor = self._cursor, instructionsPath = ['data', 'search_by_raw_query', 'search_timeline', 'timeline', 'instructions']):
   1705 	yield from self._graphql_timeline_instructions_to_tweets(obj['data']['search_by_raw_query']['search_timeline']['timeline']['instructions'])

File [~/.local/lib/python3.11/site-packages/snscrape/modules/twitter.py:812](https://file+.vscode-resource.vscode-cdn.net/home/uDocuments/twitterThing/~/.local/lib/python3.11/site-packages/snscrape/modules/twitter.py:812), in _TwitterAPIScraper._iter_api_data(self, endpoint, apiType, params, paginationParams, cursor, direction, instructionsPath)
    810 while True:
    811 	_logger.info(f'Retrieving scroll page {cursor}')
--> 812 	obj = self._get_api_data(endpoint, apiType, reqParams, instructionsPath = instructionsPath)
    813 	yield obj
    815 	# No data format test, just a hard and loud crash if anything's wrong :-)

File [~/.local/lib/python3.11/site-packages/snscrape/modules/twitter.py:781](https://file+.vscode-resource.vscode-cdn.net/home/u/Documents/twitterThing/~/.local/lib/python3.11/site-packages/snscrape/modules/twitter.py:781), in _TwitterAPIScraper._get_api_data(self, endpoint, apiType, params, instructionsPath)
    779 		_logger.warning(msg)
    780 	else:
--> 781 		raise snscrape.base.ScraperException(msg)
    782 return obj

ScraperException: Twitter responded with an error: BadRequestError: BadRequest: SearchQueryParsingException(ERROR_NONCLOSE_FORM)
```

**Comment by distbit0** [comment]
I am receiving the same error. My code is 
```
def get_replies(tweet_id):
    replies_dict = {}
    # Set the conversation_id search parameter to the tweet ID
    scraper = sntwitter.TwitterSearchScraper(
        "conversation_id:" + tweet_id + " -filter:unsafe (filter:safe OR -filter:safe)"
    )
    mainTweet = sntwitter.TwitterTweetScraper(
        tweet_id, mode=sntwitter.TwitterTweetScraperMode.RECURSE
    ).get_items()
    tweets = [tweet for tweet in scraper.get_items()]
```

and the error I am receiving is 
```
  File "/home/pimania/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1704, in get_items
    for obj in self._iter_api_data('https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline', _TwitterAPIType.GRAPHQL, params, paginationParams, cursor = self._cursor, instructionsPath = ['data', 'search_by_raw_query', 'search_timeline', 'timeline', 'instructions']):
  File "/home/pimania/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 812, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams, instructionsPath = instructionsPath)
  File "/home/pimania/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 781, in _get_api_data
    raise snscrape.base.ScraperException(msg)
snscrape.base.ScraperException: Twitter responded with an error: BadRequestError: BadRequest: SearchQueryParsingException(ERROR_NONCLOSE_FORM)
```

**Comment by ihabpalamino** [comment]
hello guys i am trying to scrape number of retweet by tweet.retweet but it gives le the value null!! any idea how scrap number of retweet?

**Comment by jannat5134** [comment]
same error

**Comment by JustAnotherArchivist** [comment]
It appears that the `conversation_id` filter no longer works, yeah. It'd be up to Twitter to reverse/fix that; there's nothing snscrape can do about it.

**Comment by distbit0** [comment]
Very sad that twitter decided to do this :(

**Comment by hypnoti13** [comment]
Is there currently another way to get replies to a tweet (knowing the tweetID)?

**Comment by UmarDabhoiwala** [comment]
I came up with a hacky workaround. Use the twitter search scraper and in the query do “to:(twitter user) since:(date of tweet post) until:(2 or 3 days after tweet post)”. Then I looped through all the results and then checked the inReplyToTweetId parameter against the tweet id. It is a bit slower than searching by conversation id but not terrible. Biggest drawback is for the largest twitter accounts as the search takes a while but even then it’s workable

> Is there currently another way to get replies to a tweet (knowing the tweetID)?

**Comment by distbit0** [comment]
How does nitter get replies to a tweet if not via using the conversation_id filer? Doesn't the fact that they are still able to retrieve a tweet's conversation imply that they have a fix to this? @JustAnotherArchivist :) many thx

**Comment by JustAnotherArchivist** [comment]
@distbit0 Nitter uses the same endpoint as the `twitter-tweet` scraper, probably in a fashion similar to the scrolling mode in snscrape (which is equivalent to what you see on the Twitter web interface when loading a tweet). This issue is purely about no longer being able to retrieve the full conversation tree easily via the search; instead, you have to use that hacky workaround or slow recursive tweet scraping.

**Comment by distbit0** [comment]
> I came up with a hacky workaround. Use the twitter search scraper and in the query do “to:(twitter user) since:(date of tweet post) until:(2 or 3 days after tweet post)”. Then I looped through all the results and then checked the inReplyToTweetId parameter against the tweet id. It is a bit slower than searching by conversation id but not terrible. Biggest drawback is for the largest twitter accounts as the search takes a while but even then it’s workable
> 
> > Is there currently another way to get replies to a tweet (knowing the tweetID)?

This would not get replies of replies, right? many thx :)

**Comment by distbit0** [comment]
@UmarDabhoiwala 

> I came up with a hacky workaround. Use the twitter search scraper and in the query do “to:(twitter user) since:(date of tweet post) until:(2 or 3 days after tweet post)”. Then I looped through all the results and then checked the inReplyToTweetId parameter against the tweet id. It is a bit slower than searching by conversation id but not terrible. Biggest drawback is for the largest twitter accounts as the search takes a while but even then it’s workable
> 
> > Is there currently another way to get replies to a tweet (knowing the tweetID)?

This would not get replies of replies, right? many thx :)

**Comment by UmarDabhoiwala** [comment]
To get replies of replies I just recursed on comments that have a reply count greater than zero. You can just grab the id of the comment when you search and then do a separate call to twitterTweetScraper to get the main content of the comment. Then do the same thing where you search for all replies to that comment user. 

tbh it is a pretty stupid way of doing it and it is definitely really slow but it works alright for my purposes, just make sure to have sensible limits on the depth of your recursion otherwise for instance elons tweets can take an hour to scrape

**Comment by distbit0** [comment]
Ah nice yeah that makes sense. @UmarDabhoiwala 

Are there any obvious optimisations which could be made to the below implementation of this strategy:

```
def getReplies(tweet_id):
    print(tweet_id)
    rawReplies = []

    # Get the date of the tweet
    mainTweet = next(sntwitter.TwitterTweetScraper(tweet_id).get_items())
    tweet_date = mainTweet.date

    # Calculate the date range for the search (2 or 3 days after the tweet post)
    start_date = tweet_date.strftime("%Y-%m-%d")
    end_date = (tweet_date + timedelta(days=3)).strftime("%Y-%m-%d")

    # Use the TwitterSearchScraper with the new query format
    scraper = sntwitter.TwitterSearchScraper(
        f"to:{mainTweet.user.username} since:{start_date} until:{end_date}",
        maxEmptyPages=5,
    )
    # Get all tweets from the search
    tweets = [tweet for tweet in scraper.get_items()]
    tweets.append(mainTweet)

    # Iterate through the tweets and check if the inReplyToTweetId matches the original tweet ID
    for reply in tweets:
        if reply.id == mainTweet.id:
            rawReplies.append(reply)
            continue
        if reply.inReplyToTweetId != mainTweet.id:
            continue
        print("down")
        rawReplies.extend(getReplies(reply.id))

    print("up")
    return rawReplies
```

Much appreciated.

**Comment by distbit0** [comment]
Ah great thx for that @UmarDabhoiwala. I decided to forgo the depth limit, as my purpose is for reading the conversations myself and often long convos are very worthwhile. May add a limit if this becomes an issues though. For anyone else interested in this strategy, here is the improved code:

```
def getReplies(tweet_id):
    print(tweet_id)
    rawReplies = []

    # Get the date of the tweet
    mainTweet = next(sntwitter.TwitterTweetScraper(tweet_id).get_items())
    tweet_date = mainTweet.date

    # Calculate the date range for the search (2 or 3 days after the tweet post)
    start_date = tweet_date.strftime("%Y-%m-%d")
    end_date = (tweet_date + timedelta(days=3)).strftime("%Y-%m-%d")

    # Use the TwitterSearchScraper with the new query format
    scraper = sntwitter.TwitterSearchScraper(
        f"to:{mainTweet.user.username} since:{start_date} until:{end_date}",
        maxEmptyPages=5,
    )
    # Get all tweets from the search
    tweets = [tweet for tweet in scraper.get_items()]
    tweets.append(mainTweet)

    # Iterate through the tweets and check if the inReplyToTweetId matches the original tweet ID
    for reply in tweets:
        if reply.id == mainTweet.id or reply.replyCount == 0:
            rawReplies.append(reply)
            continue
        if reply.inReplyToTweetId != mainTweet.id:
            continue
        print("down")
        rawReplies.extend(getReplies(reply.id))
        print("up")

    return rawReplies
```

**Comment by JustAnotherArchivist** [comment]
You're manually reimplementing the recursive tweet scraper here. Why not just use that instead? Again, this issue is about not being able to use the search scraper, but that's not the only option snscrape has for conversation scraping; it was just the fastest one because it returned all relevant tweets in a single search query rather than having to spider through all tweets individually.

Also, filtering by the reply count being zero is unreliable. Twitter sometimes returns a reply count of zero even though there are replies.
