### ISSUE TITLE
Twitter profile scrapes with `--since` return no results

### ISSUE THREAD

**Issue by jamescoleuk** [JustAnotherArchivist/snscrape#915]
### Describe the bug

A Twitter profile scrape with `--since` returns no results.

### How to reproduce

Running the following returns no results:
```shell
snscrape --jsonl --since 2023-01-01 twitter-profile JillScottJS8
```

There should be results for [that profile](https://twitter.com/JillScottJS8). Running without `--since` returns results since 2023-01-01.

```shell
snscrape --jsonl twitter-profile JillScottJS8
```

### Expected behaviour

Tweets since 2023-01-01.

### Operating system

macOS 13.3.1 (a)

### Python version: output of `python3 --version`

Python 3.11.3

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev3+g3dd9c28

### Scraper

twitter-profile

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by JustAnotherArchivist** [comment]
This is caused by the pinned tweet: #784
