### ISSUE TITLE
Contact with JustAnotherArchivist

### ISSUE THREAD

**Issue by kaushalkrishna2000** [JustAnotherArchivist/snscrape#919]
Hi,

@JustAnotherArchivist 

Can you send your contact method ?aside from opening pull request.

Also how did you get hold of GraphQL Endpoint for twitter ?

Thanks

**Comment by JustAnotherArchivist** [comment]
You can reach me on IRC; I'm JAA on hackint, Libera, OFTC, and EFnet. I'm also /u/JustAnotherArchivist on Reddit.

The endpoint was suggested in an issue by the developer of Nitter.
