### ISSUE TITLE
Emote Twitter Scrapper

### ISSUE THREAD

**Issue by KevinEstud** [JustAnotherArchivist/snscrape#936]
### Describe the bug

Hello, 
as you can see on the screenshot below : 
https://prnt.sc/6PyYlSePK4Yb

now the "emotes" are not anymore correctly displayed, I mean theyre in black and white, not anymore in color, since the update you made

### How to reproduce

By scrapping from Hashtag

### Expected behaviour

Having emotes in color

### Screenshots and recordings

https://prnt.sc/6PyYlSePK4Yb

### Operating system

Ubuntu 20.04.4 LTS

### Python version: output of `python3 --version`

Python 3.8.10

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev17+ge4c7644

### Scraper

TwitterHashtag

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
This sounds like an issue with the font you use for displaying. snscrape simply returns whatever Twitter sends, which includes Unicode emoji codepoints.

```
$ snscrape -n 1 --format '{renderedContent}' twitter-search 💩
Han tenido que pasar 4 años y 7 meses, muchos trabajos de 💩, trabajar horas y cobrar menos del mínimo, hoy por fin me han tomado las huellas para el NIE.

Gracias a mi yo del pasado por no rendirse.
```

**Comment by KevinEstud** [comment]
how sould I modify it in this python code ? 

```
import snscrape.modules.twitter as twitterScrapper
import json
import sys
import datetime

scraper = twitterScrapper.TwitterHashtagScraper(sys.argv[1])

tweets = []
for i,tweet in enumerate(scraper.get_items()):
    tweets.append({"id": str(tweet.id), "date": int(datetime.datetime.fromisoformat(str(tweet.date)).timestamp()), "profileImage": tweet.user.profileImageUrl, "username": tweet.user.username ,"content": tweet.renderedContent ,"hashtag": sys.argv[1] })
    if i == 30:
        break

json_data = json.dumps(tweets, default=str)

print(json_data)
```

I'm retreiving the tweet infos directly from a js file like that : 

```
const snscrapeCommand = `python3.8 scan.py ${event?.hashtag}`;
    exec(snscrapeCommand, async (error, stdout, stderr) => {
console.log(stdout)
//stdout is my json array of tweets

})
```

**Comment by KevinEstud** [comment]
thank you I figured it out, it was my version of chrome :)
