### ISSUE TITLE
Twitter profile scraper never terminates on some profiles

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#938]
Since sometime in the past few hours (cf. #937), some Twitter profiles result in an infinite loop. It is not yet clear whether or not these two issues are directly connected, but they both showed up very recently.

**Comment by JustAnotherArchivist** [comment]
Some example profiles exhibiting this behaviour: RdpSnitch gameanglia JAMESWT_MHT PocketTrap

**Comment by AntoinePaix** [comment]
I have a slightly different problem on my side, I manage to scrape the last 3 accounts mentioned correctly but I realized that I had no results for 'RdpSnitch'. The problem is that in twitter entries, the `entryId` type does not start with `tweet` but with `profile-conversation.`

**Comment by JustAnotherArchivist** [comment]
Lo and behold, this isn't an snscrape bug: that looping is what Twitter's API actually returns. You can see it in a browser as well, e.g. on <https://twitter.com/EmotetB/with_replies>, though you have to repeatedly scroll up and down again to trigger another page load, and the duplicate tweets do not actually get rendered. In that particular case, the server returns an empty page with a new cursor, and the next request returns tweets again. On other profiles, I see multiple empty responses before it returns (duplicate) tweets again.
