### ISSUE TITLE
tweet.retweetCount, tweet.replyCount, where?

### ISSUE THREAD

**Issue by anakein** [JustAnotherArchivist/snscrape#939]
i updated snscrape to dev (pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git)
i can extract tweet fine.
```
for i,tweetsept in enumerate(sntwitter.TwitterSearchScraper(texto, maxEmptyPages=100).get_items()):
        if i>limit:
            break
        Tweets_dfsept.append(tweetsept)
```
columns retweetedTweet, quotedTweet don´t exists.

why?

thanks

solved

**Comment by JustAnotherArchivist** [comment]
> solved

So I guess you figured it out. They're attributes on the `Tweet` object returned by the scraper's `get_items` iterator, e.g. `tweetsept.retweetedTweet` in your example.
