### ISSUE TITLE
how using in google colab?

### ISSUE THREAD

**Issue by topliftarm** [JustAnotherArchivist/snscrape#94]
how using latest version in google colab? after upgrade with 
 " pip install --upgrade git+https://github.com/JustAnotherArchivist/snscrape@master " 
return error for python version :
 " ERROR: Package 'snscrape' requires a different Python: 3.6.9 not in '~=3.8' "
and we know in colab we cant upgrade python ....

**Comment by JustAnotherArchivist** [comment]
I cannot provide support for specific environments. That said, check out the link in #79.
