### ISSUE TITLE
TwitterSearchScraper Stops before crawling specified number of tweets

### ISSUE THREAD

**Issue by aydogduwu** [JustAnotherArchivist/snscrape#945]
### Describe the bug

TwitterSearchScraper Stops before crawling specified number of tweets. I want it to scrape 9000 tweets, but it finishes before it is done.

### How to reproduce

```
search_string = 'nba'

a = 9000

start_time = time.time()
# Using TwitterSearchScraper to scrape data and append tweets to lista = sntwitter.TwitterTweetScraper(1643214223776858112).get_items()
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(search_string).get_items()):
    if i > a:
        break
    tmp_dict[tweet.id] = tweet.user.username
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
```

### Expected behaviour

It should return 9000 tweets

### Screenshots and recordings

![image](https://github.com/JustAnotherArchivist/snscrape/assets/85997704/401a94c5-74f3-4b41-9cef-22f5580dc2c1)

### Operating system

Ubuntu 22.04

### Python version: output of `python3 --version`

3.10.6

### snscrape version: output of `snscrape --version`

0.6.2.20230321.dev32+gb76f485

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
Yeah, Twitter's search is unreliable: #886
