### ISSUE TITLE
Specify time range in hour using TwitterSearchScraper

### ISSUE THREAD

**Issue by cjing1** [JustAnotherArchivist/snscrape#947]
### Describe the feature

Thank you for the great package. I know we can specify a time range in days in TwitterSearchScraper using the following: 
since:2022-01-01 until:2022-01-03

However, I am wondering whether we can specify a more detailed time range in hours like the following? 
until:2022-01-03-17:30:00

If yes, what is the correct format? 
I tried '2022-01-03-17:30:00' and '2022-01-03 17:30:00', but both do not work. 

Thank you for any help.

**Comment by JustAnotherArchivist** [comment]
#259

**Comment by cjing1** [comment]
> #259

Thank you so much
