### ISSUE TITLE
Error retrieving tweets ( blocked 403 ) 

### ISSUE THREAD

**Issue by avisekksarma** [JustAnotherArchivist/snscrape#950]
### Describe the bug

Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Ajack&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: blocked (403)

 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Ajack&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.

Errors: blocked (403), blocked (403), blocked (403), blocked (403)

### How to reproduce

I am on linux machine. 
I followed [this](https://medium.com/scalereal/million-tweets-and-counting-how-snscrape-can-help-you-scrape-big-data-on-twitter-5c0240cab4f3#:~:text=snscrape%20%2D%2Djsonl%20%2D%2Dprogress%20%2D%2Dmax%2Dresults%20100%20twitter%2Dsearch%20%22from%3Ajack%22%20%3E%20user%2Dtweets.json)  blog.
When I reached following line:
snscrape --jsonl --progress --max-results 100 twitter-search "from:jack" > user-tweets.json

The error of above was shown , i.e. i am not being able to retrieve any tweets.
Is this the issue with new version of twitter API or is this just in my case?

### Expected behaviour

Expected = getting 100 tweets from user : jack

### The same issue occurred when I tried in jupyter notebook too.

![Screenshot from 2023-06-05 22-03-33](https://github.com/JustAnotherArchivist/snscrape/assets/56149664/9ab12b4a-af0d-4c04-847b-065759034226)

### Operating system

Pop!_OS 22.04 LTS x86_64   [ ubuntu based ]

### Python version: output of `python3 --version`

Python 3.10.6

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230320

### Scraper

TwitterSearchScraper

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by freudisapothead** [comment]
I have the same problem with text search. It is working fine with "from:"

**Comment by JustAnotherArchivist** [comment]
#846
