### ISSUE TITLE
Possible to scrape view count of tweets?

### ISSUE THREAD

**Issue by robookwus** [JustAnotherArchivist/snscrape#961]
### Describe the feature

Hello, firstly thanks @JustAnotherArchivist for maintaining this awesome package!
I want to do some analysis of public opinion on climate protests, using Tweets as a source. 
In order to weight the tweets I can use likes and retweet count, but on the website twitter.com you will see a View count (relatively recently implemented) that would be a great way for me to see how much traction a particular Tweet got. 

I might be overseeing something, but I have not found an option to scrape the view count of particular tweets? If an option exists to scrape it with snscrape how do I do it? If it does not exist, I would love to see it implemented, given that like and retweet count are already there it would probably be an easy add-on.
Thank you,
robookwus

### Would this fix a problem you're experiencing? If so, specify.

not being able to see views

**Comment by JustAnotherArchivist** [comment]
#749

**Comment by robookwus** [comment]
thanks, sorry apparently i am blind. checked the tweet class more than once but somehow overlooked viewCount. Thank you so much! really awesome to be able to scrape tweets these days.
