### ISSUE TITLE
TwitterSearchScraper gets very low number of tweets

### ISSUE THREAD

**Issue by DaniRojas7** [JustAnotherArchivist/snscrape#965]
### Describe the bug

Thank you for your work. TwitterSearchScraper fetches a very low number of tweets, and each time the code is run, it fetches a different number of tweets. I never get more than 100 tweets, despite using a very common keyword in the query. 

I have tried varying the maximum limit of tweets to obtain, the type of query, the date limit, and the information to obtain, without success.

### How to reproduce

Code:

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "(apple) -filter:replies"
tweets = []
limit = 1000

for tweet in sntwitter.TwitterSearchScraper(query).get_items():

    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.user.username, tweet.rawContent])

df = pd.DataFrame(tweets, columns=['Date', 'User', 'tweets'])
```

### Expected behaviour

Obtain a sufficient number of tweets, as on previous occasions.

### Operating system

Windows 11

### Python version: output of `python3 --version`

3.11.1

### snscrape version: output of `snscrape --version`

0.6.2.20230321.dev30+gfdbd741

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
#886
