### ISSUE TITLE
Fetching a tweet by tweetID only

### ISSUE THREAD

**Issue by khorg0sh** [JustAnotherArchivist/snscrape#966]
What I require is the parent of each tweet collected. The entire thread cannot be fetched as I have already read in the previous questions/issues, which however is the requirement. Kindly suggest a valid way of doing it (fetching the parent tweet at least). Thanks

I have tried bs4, but it requires logging in through selenium which adds to the lines of code. A better approach through snscrape would be appreciated

**Comment by JustAnotherArchivist** [comment]
#906

**Comment by khorg0sh** [comment]
Thanks
