### ISSUE TITLE
"Skipping unrecognised entry ID: 'profile-conversation-" -> getting this message while using profile scrapper of snscrape, snscrape version is -> snscrape==0.6.2.20230320

### ISSUE THREAD

**Issue by vatsal-kavida** [JustAnotherArchivist/snscrape#968]
### Describe the bug

So , when running the snscrape profile scrapper , for few handles e.g. Lowes, it returns this error while taking out tweets from the profile 

### How to reproduce

Just run the profile scrapper, with any of the handles, it would give this error for some or the other tweets, and also, few more errors like user not identified, and many more 

### Expected behaviour

The snscrape should be able to scrape tweets without any problem from the profile 

### Operating system

Ubuntu 22.04

### Python version: output of `python3 --version`

3.10

### snscrape version: output of `snscrape --version`

0.6.2.20230320

### Scraper

twitter-scrapper(profile)

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
#937
