### ISSUE TITLE
Any risk of throttling due to continuous usage?

### ISSUE THREAD

**Issue by pleblira** [JustAnotherArchivist/snscrape#970]
First of all, thanks so much, JustAnotherArchivist, for the excellent work with snscrape.

Now that the Twitter API has stopped offering the stream functionality for good (unless you want to pay $5k/mo for enterprise), I'm working on converting my tweet streaming bot to use snscrape by running it periodically via APScheduler on python.

My question would be if you have a sense of how frequently it's advisable to run snscrape and if there are risks of throttling, blacklisting. 

I'm setting it to run every 30 seconds, think that would raise any flags? Ideally, running it every 5 seconds would make the bot's response snappier.

Thanks in advance!

**Comment by manueltonneau** [comment]
I tried collecting timelines continuously and I am running into many 429 errors which either mean that I'm requesting too many tokens or that my IP was limited by Twitter. See related issue here: https://github.com/JustAnotherArchivist/snscrape/issues/754

**Comment by pleblira** [comment]
Got a reply from manueltonneau with a related topic. Appreciate the help.

Basically, keep usage low and hope for the best. Switch IP address if issues arise. 

 #754
