### ISSUE TITLE
Can I search using a list or is that not a feature?

### ISSUE THREAD

**Issue by MazenTayseer** [JustAnotherArchivist/snscrape#971]
If I have a list of ['Cristiano', 'Messi', 'Dybala'], and I provided that as keyword.

Does it search for each one individually?
And is there's such a thing as searching for multiple keywords at once?

**Comment by JustAnotherArchivist** [comment]
For a Twitter search, you can do something like `snscrape twitter-search 'Cristiano OR Messi OR Dybala'`. Don't use too many keywords combined like this at once; Twitter's search becomes even less reliable with that than it already is anyway.

**Comment by MazenTayseer** [comment]
@JustAnotherArchivist 
Do you suggest using the OR keyword or searching each keyword individually?

**Comment by JustAnotherArchivist** [comment]
I would recommend individual searches since it's less likely to break on Twitter's side.

**Comment by MazenTayseer** [comment]
Thank You!
