### ISSUE TITLE
Is there a way to contact you?

### ISSUE THREAD

**Issue by couldbejake** [JustAnotherArchivist/snscrape#975]
I have noticed that the iOS version of the Twitter app allows you to query Twitter without being logged in, we could possibly reverse engineer this functionality.

**Comment by JustAnotherArchivist** [comment]
That could be interesting if it differs from the current endpoint.
See #919 for some ways to get in touch. I can also contact you via email if you prefer that, seeing as your address is public.

**Comment by couldbejake** [comment]
Hi, feel free to send me an email. Alternate address: jake@couldbejake.io
