### ISSUE TITLE
"TwitterSearchScraper" function very unstable on scraping top trends

### ISSUE THREAD

**Issue by 4yR1l1k** [JustAnotherArchivist/snscrape#978]
I've been scraping tweets based on top trends, however some of them are receiving the exact number of tweets that I've addressed inside my code, and also some trends are giving me only 10 or 200 something tweets. 
As these trends are actually the real trends, there should be much more tweets my code can get for each trend.
Do you know why such different numbers are being gathered for top trends?
Is there a better way to scrape top trends, such as scraping just like another keyword phrase?
Thank you.

**Comment by JustAnotherArchivist** [comment]
I'm not entirely sure what you're doing exactly. If you're using top tweet search, then that's always been a bit weird (returning only a couple hundred results). In general, the new search endpoint is less reliable and doesn't always return all matches, cf. #886 #891 etc. But that's an issue on Twitter's side.
