### ISSUE TITLE
AttributeError: 'Tombstone' object has no attribute 'rawContent'

### ISSUE THREAD

**Issue by khorg0sh** [JustAnotherArchivist/snscrape#980]
trying to fetch content of the tweet collected using TweetScraper.

**Comment by JustAnotherArchivist** [comment]
The Twitter scrapers return not only `Tweet` objects but also `Tombstone` and `TweetRef`, which only have a couple fields. Use `isinstance` to distinguish them or `hasattr` to check whether a field is present.
