### ISSUE TITLE
Is this library python poetry compatible?

### ISSUE THREAD

**Issue by rbrooks95** [JustAnotherArchivist/snscrape#985]

**Comment by JustAnotherArchivist** [comment]
What does 'poetry-compatible' mean? It's a regular Python package.

**Comment by rbrooks95** [comment]
Like would I be able to use this package on poetry? Because something's don't work as good on poetry.

**Comment by JustAnotherArchivist** [comment]
Have you ... just tried it?

If you encounter any bugs due to snscrape's packaging, I'm happy to fix them given complete bug reports.

**Comment by Elan456** [comment]
Yes, it works on Poetry. `poetry add snscrape` should add the non-dev version.
