### ISSUE TITLE
Using snscrape for academic research

### ISSUE THREAD

**Issue by Jeyb08** [JustAnotherArchivist/snscrape#986]
I am planning to create an academic paper and I need to scrape data from Twitter. However, I am unsure of the authenticity of the data gathered through snscrape and can't afford to pay Twitter API. Is snscrape a valid data-gathering method?

**Comment by JustAnotherArchivist** [comment]
People have done it before. Whether it lives up to your study's requirements is up to you and whoever else is involved (coauthors, supervisors, institutional guidelines, etc.). snscrape tries to extract data as faithfully as it can, but bugs happen, and there are many problems on Twitter's side, most of which you can [find here in the closed issues](https://github.com/JustAnotherArchivist/snscrape/issues?q=is%3Aissue+label%3Amodule%3Atwitter+label%3Aupstream).

Or in short, to quote the GPL blob:

> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

**Comment by Jeyb08** [comment]
Thank you for your response! This is very helpful.
