### ISSUE TITLE
Scrape tweets by tweet ID

### ISSUE THREAD

**Issue by sushiselite** [JustAnotherArchivist/snscrape#987]
Hey! Ive been playing around with snscrape a bit and trying to find a way to scrape tweets by their IDs... but have had no luck. I was wondering if this library has a way for me to do that...

I have tried the following implementations: 

tweet = os.popen(f'snscrape --jsonl --max-results 1 twitter-status {tweet_id}').read() - this gives me a usage error

 tweet = os.popen(f'snscrape --jsonl --max-results 1 twitter-search "since_id:{tweet_id}"').read() - this gives me a 403 bad request

**Comment by JustAnotherArchivist** [comment]
https://github.com/JustAnotherArchivist/snscrape/issues/137#issuecomment-1035710984
