### ISSUE TITLE
Missing tweets

### ISSUE THREAD

**Issue by jingwenshi-dev** [JustAnotherArchivist/snscrape#989]
### Describe the bug

I was using Twitter's official academic account API and have scraped all tweets from "@UofT" it has 19750 tweets, but snscrape only returns me 12134 tweets.

### How to reproduce

You cannot unless you get the Twitter Enterprise API

### Expected behaviour

Should scrape more tweets. 19750 vs 12134 is a huge difference.

### Operating system

Windows 10

### Python version: output of `python3 --version`

3.11

### snscrape version: output of `snscrape --version`

0.7.0.20230622

### Scraper

TwitterUserScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
Interesting numbers, thank you! The problem isn't new at all. Twitter's search is ... suboptimal. See #4 #468 #574 #886 #891 and plenty more. Unfortunately, this is impossible to fix as far as I'm aware.
