### ISSUE TITLE
Requested data tweet 10000 but only get 95

### ISSUE THREAD

**Issue by fahdmuchammad** [JustAnotherArchivist/snscrape#993]
### Describe the bug

when im try to scrape the tweet with limit of data is 10000, but only get 95 data, that so far. i need this data for my thesis

### How to reproduce

Skipping unrecognised entry ID: 'promoted-tweet-1671423456376659969-62b9fefe46061b8'
Skipping unrecognised entry ID: 'promoted-tweet-1673171727008817154-62b22270c6bb800'
Skipping unrecognised entry ID: 'promoted-tweet-1671423456376659969-62bb0aaff2ab4b0'
Skipping unrecognised entry ID: 'promoted-tweet-1663201714403418114-62be7c70e6357c6'
Skipping unrecognised entry ID: 'promoted-tweet-1673171727008817154-62b07655a1cfc13'
Skipping unrecognised entry ID: 'promoted-tweet-1671423456376659969-62b88e1e2f324a1'
Skipping unrecognised entry ID: 'promoted-tweet-1673186825962135553-62b1f2301b69110'
Skipping unrecognised entry ID: 'promoted-tweet-1666150461756555264-62b153e3e774513'
Skipping unrecognised entry ID: 'promoted-tweet-1673171727008817154-62bd9b1fb621753'
Skipping unrecognised entry ID: 'promoted-tweet-1673171727008817154-62b5aaf5a60c075'
Skipping unrecognised entry ID: 'promoted-tweet-1673171727008817154-62bb7ea6a2ca808'
Skipping unrecognised entry ID: 'promoted-tweet-1671423456376659969-62b41df6917676e'
Skipping unrecognised entry ID: 'promoted-tweet-1673171727008817154-62b807f464ea5d2'
Skipping unrecognised entry ID: 'promoted-tweet-1673171727008817154-62b1b654663dec8'
Skipping unrecognised entry ID: 'promoted-tweet-1666150461756555264-62bed6c0a18293a'
Skipping unrecognised entry ID: 'promoted-tweet-1673171727008817154-62b940581a71331'
Skipping unrecognised entry ID: 'promoted-tweet-1671423456376659969-62be63ba769a653'
Skipping unrecognised entry ID: 'promoted-tweet-1671732498685112330-62b271abecffb08'
Skipping unrecognised entry ID: 'promoted-tweet-1671423456376659969-62bb27657bd89b2'
Stopping after 20 empty pages

### Expected behaviour

i get 10000 data

### Operating system

Mac os

### Python version: output of `python3 --version`

python 3.9

### snscrape version: output of `snscrape --version`

snscrape developer

### Scraper

TwitterSearchScrapper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment]
#886 #891 etc.
