### ISSUE TITLE
Twitter now requires login to view content

### ISSUE THREAD

**Issue by Maniktherana** [JustAnotherArchivist/snscrape#994]
Will this affect snscrape? I’m new to scraping so not sure if this affects scrapers.

**Comment by elleobrien** [comment]
(not maintainer, just a user) I expect it will. Some scraping processes use libraries like `selenium` to pass account credentials through a login interface, but not sure how to integrate this best with `snscrape`.

**Comment by Maniktherana** [comment]
Makes sense. Meanwhile my current workflow for scraping Twitter isn’t working anymore.

**Comment by JustAnotherArchivist** [comment]
Chances are it eventually will if they don't reverse course. But in any case, speculation isn't useful, and my crystal ball broke last week. For now, snscrape's Twitter scrapers still work. Use them while you can.

**Comment by TheTechRobo** [comment]
@elleobrien Auth won't be supported: #270

**Comment by Maniktherana** [comment]
I get that this topic’s closed but 

https://twitter.com/elonmusk/status/1675187969420828672?s=46
