### ISSUE TITLE
Twitter: UserByScreenName api fails

### ISSUE THREAD

**Issue by 0bmay** [JustAnotherArchivist/snscrape#995]
### Describe the bug

error getting user id by screen name:

snscrape.base.ScraperException: 4 requests to https://twitter.com/i/api/graphql/pVrmNaXcxPjisIvKtLDMEA/UserByScreenName?variables=%7B%22screen_name%22%3A%22<handle>%22%2C%22withSafetyModeUserFields%22%3Atrue%7D&features=%7B%22blue_business_profile_image_shape_enabled%22%3Atrue%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22highlights_tweets_tab_ui_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%7D failed, giving up.

### How to reproduce

search any profile

### Expected behaviour

not an error. :) return data

### Operating system

Ubuntu 22.04.2 LTS

### Python version: output of `python3 --version`

Python 3.10.6

### snscrape version: output of `snscrape --version`

snscrape 0.7.0.20230622

### Scraper

TwitterProfileScraper

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by 0bmay** [comment]
looks like twitter is completely destroying the ability to get tweets while logged out

**Comment by JustAnotherArchivist** [comment]
Closing this in favour of the more general #996; all endpoints are affected.
