### ISSUE TITLE
Errors: blocked (404), blocked (404), blocked (404), blocked (404)

### ISSUE THREAD

**Issue by ChowSings** [JustAnotherArchivist/snscrape#998]
我使用这个项目很长时间了，每次他都能迎刃而解。期待你的下次更新！暂时用不了了

**Comment by SpiderVice** [comment]
#996  already is talking about this. Hopefully all these completely haphazard Twitter changes aren't the end of great libs like this. They seem to be backtracking a little but...

**Comment by ihabpalamino** [comment]
any updates or solution about this?
