### ISSUE TITLE
Is there any way to extract the following of a user? I need your @username of each followed. help.

### ISSUE THREAD

**Issue by dadiaz1424** [JustAnotherArchivist/snscrape#999]
Is there any way to extract the following of a user? I need your @username of each followed. help.

**Comment by MazenTayseer** [comment]
@dadiaz1424 in which scraper?
Twitter Instagram etc?

**Comment by dadiaz1424** [comment]
> @dadiaz1424 in which scraper? Twitter Instagram etc?

only from twitter

**Comment by dadiaz1424** [comment]
@MazenTayseer only from twitter

**Comment by JustAnotherArchivist** [comment]
#200
